// Code generated by gpp from fsplit.gpp. DO NOT EDIT.
//gpp:v v0.11.0

package store

import "goforge.dev/rune/v3/core"

// The face-split builtin group (§F / R-BOX / A3): the eliminator of a cofibration
// disjunction `holds (for φ ψ)`. It is the dispatch primitive the Kan rules build
// systems from — a system `[φ ↦ u; ψ ↦ v]` becomes `λh. fsplit A φ ψ u v h`, a
// genuine `holds (for φ ψ) -> El A` function that SELECTS the branch by which
// face holds. Plain `holds φ -> El A` functions cannot dispatch (there is no
// `holds` eliminator), which is exactly what blocked proper-face transp/comp over
// pathF (A3). A separate group on its own hash space (like sigma/equiv/glue),
// built against fibrant + face + system, so their hashes — and ch09–ch24 — stay
// stable.
//
//	fsplit : (A : UF) -> (φ : F) -> (ψ : F)
//	           -> (u : holds φ -> El A) -> (v : holds ψ -> El A)
//	           -> holds (for φ ψ) -> El A
//
// fsplit COMPUTES by face-ι (core.FsplitInfo / the evaluator's tryFsplitIota):
//
//	fsplit A φ ψ u v h  ~>  u htop   when φ ≡ ⊤
//	fsplit A φ ψ u v h  ~>  v htop   when ψ ≡ ⊤
//
// stuck when both faces are proper. Overlap (both ⊤) takes the φ-branch; agreement
// on the overlap is the caller's obligation (vacuous for disjoint faces). No
// hash-format bump (no new core constructor). See ref_docs/wootz/RBOX-DESIGN.md.

var fsplitNames = [1]string{"fsplit"}

type fsplitEntry struct {
	hashes [1]core.Hash
}

// AddFsplit registers the face-split group against the already-registered fibrant,
// face, and system groups, binding its name and returning the member hash.
func (s *Store) AddFsplit(fib [10]core.Hash, face [7]core.Hash, sys [5]core.Hash) [1]core.Hash {
	tys := fsplitTypes(fib, face, sys)

	g := newHasher()
	g.Write([]byte{defFormatVersion, 'Y'})
	for _, ty := range tys {
		th := core.HashTerm(ty)
		g.Write(th[:])
	}
	var group core.Hash
	copy(group[:], g.Sum(nil))

	var hs [1]core.Hash
	for i := range hs {
		h := newHasher()
		h.Write([]byte{defFormatVersion, 'y'})
		h.Write(group[:])
		writeUint(h, uint64(i))
		copy(hs[i][:], h.Sum(nil))
	}
	for i, ty := range tys {
		s.defs[hs[i]] = Def{Type: ty}
		s.names[fsplitNames[i]] = hs[i]
	}
	s.fs = &fsplitEntry{hashes: hs}
	return hs
}

// FsplitRoleOf implements core.FsplitInfo.
func (s *Store) FsplitRoleOf(h core.Hash) core.FsplitRole {
	if s.fs == nil {
		return core.SRoleNoneF
	}
	if h == s.fs.hashes[0] {
		return core.SRoleSplit
	}
	return core.SRoleNoneF
}

// FsplitHash implements core.FsplitInfo: the member hash, for the Kan rules to
// CONSTRUCT fsplit systems.
func (s *Store) FsplitHash() (core.Hash, bool) {
	if s.fs == nil {
		return core.Hash{}, false
	}
	return s.fs.hashes[0], true
}

// FsplitHashes returns the registered group's hashes (and whether it exists).
func (s *Store) FsplitHashes() ([1]core.Hash, bool) {
	if s.fs == nil {
		return [1]core.Hash{}, false
	}
	return s.fs.hashes, true
}

// FsplitNames returns the surface names of the group members.
func FsplitNames() [1]string { return fsplitNames }

// fsplitTypes builds the one member type, referencing the fibrant group (UF =
// fib[0], El = fib[1]), the face former (F = face[0]) and disjunction (for =
// face[4]), and holds (sys[0]).
func fsplitTypes(fib [10]core.Hash, face [7]core.Hash, sys [5]core.Hash) [1]core.Tm {
	v := func(i int) core.Tm { return core.Var{Idx: i} }
	pi := func(name string, dom core.Tm, cod core.Tm) core.Tm {
		return core.Pi{Dom: dom, Cod: core.Scope{Name: name, Body: cod}}
	}
	app := func(f core.Tm, xs ...core.Tm) core.Tm {
		for _, x := range xs {
			f = core.App{Fn: f, Arg: x, Icit: core.Expl}
		}
		return f
	}
	uf := core.Tm(core.Ref{Hash: fib[0]})
	el := func(x core.Tm) core.Tm { return app(core.Ref{Hash: fib[1]}, x) }
	fTy := core.Tm(core.Ref{Hash: face[0]})
	holds := func(x core.Tm) core.Tm { return app(core.Ref{Hash: sys[0]}, x) }
	forC := func(x, y core.Tm) core.Tm { return app(core.Ref{Hash: face[4]}, x, y) }

	// fsplit : (A : UF) -> (φ : F) -> (ψ : F)
	//            -> (u : holds φ -> El A) -> (v : holds ψ -> El A)
	//            -> holds (for φ ψ) -> El A
	fsplitTy := pi("A", uf, //                                  [A]: A=0
		pi("phi", fTy, //                                       [φ,A]: φ=0,A=1
			pi("psi", fTy, //                                   [ψ,φ,A]: ψ=0,φ=1,A=2
				pi("u", pi("_", holds(v(1)), el(v(3))), //      u: holds φ -> El A
					pi("v", pi("_", holds(v(1)), el(v(4))), //  v: holds ψ -> El A
						pi("h", holds(forC(v(3), v(2))), //     h: holds (for φ ψ)
							el(v(5)))))))) //                    -> El A

	return [1]core.Tm{fsplitTy}
}
