// Code generated by goplus from io.gp. DO NOT EDIT.
//goplus:v v0.15.0

package store

import "goforge.dev/rune/v3/core"

// The IO / effects builtin group (R-EFFECT / C3): a monadic-IO base shipped as a
// bodiless content-addressed group on its own hash space (like the cubical
// groups), built against nothing but the outer core. Effects are CONTAINED: the
// core stays pure; IO is an abstract type former whose programs sequence with
// pureIO/bindIO.
//
//	World  : U                                            the (abstract) world token
//	IO     : U -> U                                       a computation yielding A
//	pureIO : (A : U) -> A -> IO A                         lift a pure value
//	bindIO : (A B : U) -> IO A -> (A -> IO B) -> IO B     sequence two computations
//
// This increment ships the TYPES: IO programs elaborate and type-check (the monad
// interface is usable), exactly as §F phase 1 shipped the interval as types
// before its computation rules. The members are permanently neutral (bodiless) —
// pureIO/bindIO do not reduce yet. The runtime meaning (a codegen IForeign node +
// the World-threading lowering so IO programs RUN) is the labelled C3 follow-up.
// No hash-format bump; own hash space.

var ioNames = [4]string{"World", "IO", "pureIO", "bindIO"}

type ioEntry struct {
	hashes [4]core.Hash
}

// AddIO registers the IO/effects group, binding its names and returning the
// member hashes in ioNames order.
func (s *Store) AddIO() [4]core.Hash {
	tys := ioTypes()

	g := newHasher()
	g.Write([]byte{defFormatVersion, 'O'})
	for _, ty := range tys {
		th := core.HashTerm(ty)
		g.Write(th[:])
	}
	var group core.Hash
	copy(group[:], g.Sum(nil))

	var hs [4]core.Hash
	for i := range hs {
		h := newHasher()
		h.Write([]byte{defFormatVersion, 'o'})
		h.Write(group[:])
		writeUint(h, uint64(i))
		copy(hs[i][:], h.Sum(nil))
	}
	subst := func(t core.Tm) core.Tm {
		for i := range hs {
			t = replaceRef(t, Placeholder(i), hs[i])
		}
		return t
	}
	for i, ty := range tys {
		s.defs[hs[i]] = Def{Type: subst(ty)}
		s.names[ioNames[i]] = hs[i]
	}
	s.io = &ioEntry{hashes: hs}
	return hs
}

// IOHashes returns the registered group's hashes (and whether it exists).
func (s *Store) IOHashes() ([4]core.Hash, bool) {
	if s.io == nil {
		return [4]core.Hash{}, false
	}
	return s.io.hashes, true
}

// IONames returns the surface names of the group members, in hash order.
func IONames() [4]string { return ioNames }

// ioTypes builds the four member types. IO refers to itself as Placeholder(1).
func ioTypes() [4]core.Tm {
	v := func(i int) core.Tm { return core.Var{Idx: i} }
	pi := func(name string, dom core.Tm, cod core.Tm) core.Tm {
		return core.Pi{Dom: dom, Cod: core.Scope{Name: name, Body: cod}}
	}
	app := func(f core.Tm, xs ...core.Tm) core.Tm {
		for _, x := range xs {
			f = core.App{Fn: f, Arg: x, Icit: core.Expl}
		}
		return f
	}
	u := core.Tm(core.Univ{})
	ioH := core.Ref{Hash: Placeholder(1)}
	io := func(a core.Tm) core.Tm { return app(ioH, a) }

	// World : U
	worldTy := u
	// IO : U -> U
	ioTy := pi("A", u, u)
	// pureIO : (A : U) -> A -> IO A
	pureTy := pi("A", u, pi("a", v(0), io(v(1))))
	// bindIO : (A : U) -> (B : U) -> IO A -> (A -> IO B) -> IO B
	bindTy := pi("A", u, pi("B", u,
		pi("m", io(v(1)), // [B,A]: A = 1
			pi("k", pi("a", v(2), io(v(2))), // [m,B,A]: A=2 ; under a: B=2
				io(v(2)))))) // [k,m,B,A]: B = 2

	return [4]core.Tm{worldTy, ioTy, pureTy, bindTy}
}
