// Code generated by goplus from quotind.gp. DO NOT EDIT.
//goplus:v v0.15.0

package store

import "goforge.dev/rune/v3/core"

// The fibrant quotient's DEPENDENT eliminator (§F / R-HIT / A9): the induction
// principle `quotInd`, a separate one-member group (tag B/b) so the quotient
// group's hashes stay byte-stable. Eliminates into a dependent motive
// `P : El (Quotient A R) -> UF`; the relation method is a dependent path (pathP)
// over the line λi. P (qrel@i):
//
//	quotInd : (A : UF) -> (R : El A -> El A -> UF) -> (P : El (Quotient A R) -> UF)
//	            -> (f : (a : El A) -> El (P (qinc A R a)))
//	            -> (rel : (a b : El A) -> (r : El (R a b))
//	                  -> El (pathP (λi. P (papp (Quotient A R) (qinc A R a) (qinc A R b) (qrel A R a b r) i)) (f a) (f b)))
//	            -> (x : El (Quotient A R)) -> El (P x)
//
// Computes (core.QuotIndInfo / tryQuotIndIota): `quotInd … (qinc a) ~> f a`, along
// a relation path `… (qrel a b r @ i) ~> pappP (λi. P (qrel@i)) (f a) (f b)
// (rel a b r) i`. The proof-respecting induction the strict Quot cannot give. No
// hash-format bump.

var quotIndName = "quotInd"

type quotIndEntry struct {
	hash core.Hash
}

// AddQuotInd registers the dependent fibrant-quotient eliminator.
func (s *Store) AddQuotInd(quot [4]core.Hash, path [2]core.Hash, pathp [3]core.Hash, fib [10]core.Hash) core.Hash {
	ty := quotIndType(quot, path, pathp, fib)

	g := newHasher()
	g.Write([]byte{defFormatVersion, 'B'})
	th := core.HashTerm(ty)
	g.Write(th[:])
	var group core.Hash
	copy(group[:], g.Sum(nil))

	h := newHasher()
	h.Write([]byte{defFormatVersion, 'b'})
	h.Write(group[:])
	writeUint(h, 0)
	var hash core.Hash
	copy(hash[:], h.Sum(nil))

	s.qui = &quotIndEntry{hash: hash}
	s.defs[hash] = Def{Type: ty}
	s.names[quotIndName] = hash
	return hash
}

// IsQuotInd implements core.QuotIndInfo.
func (s *Store) IsQuotInd(h core.Hash) bool {
	return s.qui != nil && s.qui.hash == h
}

// QuotIndHash implements core.QuotIndInfo.
func (s *Store) QuotIndHash() (core.Hash, bool) {
	if s.qui == nil {
		return core.Hash{}, false
	}
	return s.qui.hash, true
}

// QuotIndName returns the surface name of the member.
func QuotIndName() string { return quotIndName }

func quotIndType(quot [4]core.Hash, path [2]core.Hash, pathp [3]core.Hash, fib [10]core.Hash) core.Tm {
	v := func(i int) core.Tm { return core.Var{Idx: i} }
	pi := func(name string, dom core.Tm, cod core.Tm) core.Tm {
		return core.Pi{Dom: dom, Cod: core.Scope{Name: name, Body: cod}}
	}
	app := func(f core.Tm, xs ...core.Tm) core.Tm {
		for _, x := range xs {
			f = core.App{Fn: f, Arg: x, Icit: core.Expl}
		}
		return f
	}
	uf := core.Tm(core.Ref{Hash: fib[0]})
	el := func(x core.Tm) core.Tm { return app(core.Ref{Hash: fib[1]}, x) }
	quotRef := core.Ref{Hash: quot[0]}
	qincRef := core.Ref{Hash: quot[1]}
	qrelRef := core.Ref{Hash: quot[2]}
	pappRef := core.Ref{Hash: path[1]}
	pathPRef := core.Ref{Hash: pathp[0]}
	quotOf := func(a, r core.Tm) core.Tm { return app(quotRef, a, r) }
	relTy := func(aIdx int) core.Tm { return pi("x", el(v(aIdx)), pi("y", el(v(aIdx+1)), uf)) }

	// rel's cod line, built under [r,b,a,f,P,R,A] (r=0,b=1,a=2,f=3,P=4,R=5,A=6).
	// Under λi: i=0,r=1,b=2,a=3,f=4,P=5,R=6,A=7.
	line := core.Lam{Body: core.Scope{Name: "i", Body: app(v(5),
		app(pappRef, quotOf(v(7), v(6)),
			app(qincRef, v(7), v(6), v(3)),             // qinc A R a
			app(qincRef, v(7), v(6), v(2)),             // qinc A R b
			app(qrelRef, v(7), v(6), v(3), v(2), v(1)), // qrel A R a b r
			v(0)))}}

	return pi("A", uf, pi("R", relTy(0),
		// P : El (Quotient A R) -> UF — under [R,A]: A=v1,R=v0
		pi("P", pi("z", el(quotOf(v(1), v(0))), uf),
			// f : (a : El A) -> El (P (qinc A R a)) — dom under [P,R,A]: A=v2;
			//   cod under [a,P,R,A]: P=v1,A=v3,R=v2
			pi("f", pi("a", el(v(2)), el(app(v(1), app(qincRef, v(3), v(2), v(0))))),
				// rel : (a b : El A) -> (r : El (R a b)) -> El (pathP line (f a) (f b))
				pi("rel", pi("a", el(v(3)), // A under [f,P,R,A]=v3
					pi("b", el(v(4)), // A under [a,f,P,R,A]=v4
						// r : El (R a b) under [b,a,f,P,R,A]: R=v4,a=v1,b=v0
						pi("r", el(app(v(4), v(1), v(0))),
							// result under [r,b,a,f,P,R,A]: f=v3,a=v2,b=v1
							el(app(pathPRef, line, app(v(3), v(2)), app(v(3), v(1))))))),
					// x : El (Quotient A R) under [rel,f,P,R,A]: A=v4,R=v3
					pi("x", el(quotOf(v(4), v(3))),
						// result El (P x) under [x,rel,f,P,R,A]: P=v3,x=v0
						el(app(v(3), v(0)))))))))
}
