package codegen

import (
	"fmt"
	"sort"
	"strings"

	"goforge.dev/rune/v3/core"
)

// C is the FIRST NATIVE backend (telos-2 / M4): it emits portable C over the
// CLOSURE-CONVERTED IR (codegen/closure.go) and a tiny embedded closure runtime,
// compiled to real machine code by the system `cc`. Unlike the six SOURCE
// emitters (js/py/go/rust/jvm/beam), which lean on a host runtime's closures and
// GC, the C backend realizes the native ABI of R-NATIVE itself:
//
//   - a uniform tagged-word `Value` (immediate ints for builtin-nat, a pointer to
//     a boxed object for closures/constructors/pairs);
//   - `alloc` — a garbage-collected heap (a mark-sweep collector, see GC below);
//   - `apply(clo, arg)` — unpack a closure's {code, env} and indirect-call;
//   - constructor objects (tag + fields), pairs, and `$show` over the header tag,
//     producing byte-identical observable output to the other backends.
//
// Every `ILam` is lifted to a top-level `Value code_N(Value arg, Value* env)` by
// ClosureConvert; `MkClosure` allocates a {code, env...} object; `AppClosure`
// applies; `CCase`/`CField` are a tag switch / field load. Each top-level
// definition (and each datatype eliminator + constructor) becomes a MEMOIZED
// thunk `Value def_<name>(void)` so (mutually) recursive definitions and the
// eliminators — whose bodies reference themselves by global name — terminate the
// C initialization the way the Go backend's thunks do.
//
// SUPPORTED FRAGMENT (the conformance subset this iteration runs byte-identical
// to the other backends): builtin-nat arithmetic (zero/succ/NatElim + the accel
// add/mul/monus), constructors + eliminators (ICase/IField over ListElim/NatElim/
// any datatype), curried closures + application, dependent pairs (Σ erases to a
// 2-slot pair), quotients (carrier-erased), and the IO monad (deferred-thunk
// erasure), plus `partial` recursion (a top-level def whose body refers to itself
// — the memoized thunk + closure machinery already make this run). The native
// host LITERAL FFI (LitInt/LitStr/LitPtr) and IForeign are emitted but a foreign
// program needs a host-linked accessor, exactly as on the other backends.
//
// GC: this iteration ships a CONSERVATIVE-ROOTS / PRECISE-SLOTS NON-MOVING
// MARK-SWEEP collector (`gc_alloc`/`gc_collect`). It unblocks long-running /
// unbounded-allocation programs (a bump allocator only worked because the
// conformance corpus is finite). Mark-sweep (not the R-NATIVE-recommended
// semispace copying) is the sound choice HERE because the runtime memoizes
// definitions in `static Value cache` slots that do not live on the C stack: a
// non-moving collector only needs those slots MARKED (each is registered as a
// root via gc_add_root), where a copying collector would have to rewrite them.
// Roots = registered static caches (precise) ∪ a conservative C-stack scan
// (setjmp spills registers, scan SP..stack-bottom); object slots are traced
// PRECISELY from the header kind+count. See the runtime's gc section for the
// full rationale. NEXT: precise stack maps / a copying collector / perf (the
// O(live) heap-membership test is the obvious first speedup).
type C struct{}

func (C) Target() string { return "c" }

// Emit closure-converts the program and emits a self-contained C translation
// unit: the runtime header, every lifted code block, the constructor/eliminator/
// definition thunks, and a `main` that evaluates the entry and `$show`s it.
func (C) Emit(p Program) (TargetSource, error) {
	cp := ClosureConvert(p)
	em := &cEmitter{}
	if p.Nat != nil {
		em.natElim = p.Nat.ElimName
		em.accel = p.Nat.Ops
	}
	em.blocks = make(map[string]CodeBlock, len(cp.Blocks))
	for _, blk := range cp.Blocks {
		em.blocks[blk.Name] = blk
	}

	var b strings.Builder
	b.WriteString("/* Generated by rune emit (c backend) — the erased shadow, native via cc. Do not edit. */\n")
	b.WriteString(cRuntime)
	if usesQuot(p) {
		b.WriteString(cQuotRuntime)
	}
	if usesIO(p) {
		b.WriteString(cIORuntime)
	}
	// D3 / R-FFI: bake the machine-float (f64) host bodies + the OpenBLAS dot kernel
	// when referenced (defined before the program code blocks that call them).
	emitFloatPrimsC(&b, p)

	// Forward declarations: every code block and every thunk, so the bodies may
	// reference one another (and themselves) regardless of definition order.
	for _, blk := range cp.Blocks {
		fmt.Fprintf(&b, "static Value %s(Value arg, Value* env);\n", cCodeName(blk.Name))
	}
	thunks := em.collectThunks(cp)
	for _, name := range thunks {
		fmt.Fprintf(&b, "static Value %s(void);\n", cThunkName(name))
	}
	// The constructor code blocks (one per argument) reference one another in a
	// chain; forward-declare them all so the chain links regardless of order.
	for _, d := range cp.Datas {
		if cp.Nat != nil && d.ElimName == cp.Nat.ElimName {
			continue
		}
		for _, c := range d.Ctors {
			base := "ctorfn_" + cName(c.Name)
			for i := 0; i < c.Arity; i++ {
				fmt.Fprintf(&b, "static Value %s_%d(Value arg, Value* env);\n", base, i)
			}
		}
	}
	b.WriteString("\n")

	// Constructor + eliminator thunks. A constructor of arity k is a curried
	// closure built from k generated code blocks (each capturing the prefix of
	// arguments), terminating in the {tag, fields...} object. The nat group emits
	// its native zero/succ/eliminator instead.
	for _, d := range cp.Datas {
		if cp.Nat != nil && d.ElimName == cp.Nat.ElimName {
			em.emitNatC(&b, *cp.Nat)
			continue
		}
		for _, c := range d.Ctors {
			em.emitCtorC(&b, c)
		}
	}
	// The lifted code blocks (definitions' and eliminators' bodies).
	for _, blk := range cp.Blocks {
		em.emitBlock(&b, blk)
	}
	// Definition thunks (eliminators converted as CDefSpec, then user defs).
	for _, def := range cp.Defs {
		em.emitDefThunk(&b, def.Name, def.Body)
	}

	// main: evaluate the entry thunk and show it. An IO main is a deferred world
	// thunk (unit -> A), forced by applying $unit.
	b.WriteString("int main(void) {\n")
	// Capture the C stack bottom for the conservative GC root scan: every live
	// Value used by the evaluation lives in a frame above this point, so the
	// collector scans from the current SP up to here.
	b.WriteString("  void* gc_anchor = 0; gc_stack_bottom = (void*)&gc_anchor;\n")
	b.WriteString("  UNIT = mkunit();\n")
	// UNIT is a static global (a boxed singleton); register it as a GC root so a
	// collection never frees it and show()'s `v == UNIT` comparison stays valid.
	b.WriteString("  gc_add_root(&UNIT);\n")
	if p.Main != "" {
		mainExpr := cThunkName(p.Main) + "()"
		if p.IOMain {
			mainExpr = fmt.Sprintf("apply(%s, UNIT)", mainExpr)
		}
		fmt.Fprintf(&b, "  show(%s);\n", mainExpr)
		b.WriteString("  putchar('\\n');\n")
	}
	// Optional GC stats (compile with -DRUNE_GC_STATS) — lets a test confirm the
	// collector actually fired during the run, on stderr so stdout stays clean.
	b.WriteString("#ifdef RUNE_GC_STATS\n")
	b.WriteString("  fprintf(stderr, \"rune-c: gc collections=%ld\\n\", gc_n_collections);\n")
	b.WriteString("#endif\n")
	b.WriteString("  return 0;\n}\n")
	return TargetSource(b.String()), nil
}

// cEmitter renders CIr terms to C expressions. Like the other backends it knows
// the nat eliminator's name + the accel table so it can emit native arithmetic.
type cEmitter struct {
	natElim string
	accel   map[string]core.NatOp
	blocks  map[string]CodeBlock // code-block lookup for the IH-ignoring nat dispatch
	tmp     int                  // fresh-temporary counter for the rare statement-form (CCase)
}

// collectThunks returns every top-level name that gets a thunk: each datatype's
// constructors + eliminator (the nat group's zero/succ/elim too) and each
// converted definition. Sorted-stable for deterministic forward decls.
func (em *cEmitter) collectThunks(cp ClosureProgram) []string {
	seen := map[string]bool{}
	var out []string
	add := func(n string) {
		if !seen[n] {
			seen[n] = true
			out = append(out, n)
		}
	}
	for _, d := range cp.Datas {
		if cp.Nat != nil && d.ElimName == cp.Nat.ElimName {
			add(cp.Nat.Zero)
			add(cp.Nat.Succ)
			add(cp.Nat.ElimName)
			continue
		}
		for _, c := range d.Ctors {
			add(c.Name)
		}
	}
	for _, def := range cp.Defs {
		add(def.Name)
	}
	sort.Strings(out)
	return out
}

// emitDefThunk emits a memoized thunk for a top-level definition: the first call
// computes the body and caches it, so recursion (and the eliminators' self-
// reference) terminates and is not recomputed.
func (em *cEmitter) emitDefThunk(b *strings.Builder, name string, body CIr) {
	fmt.Fprintf(b, "static Value %s(void) {\n", cThunkName(name))
	b.WriteString("  static int done = 0; static Value cache = 0;\n")
	b.WriteString("  if (done) return cache;\n")
	b.WriteString("  done = 1;\n")
	// Register the cache slot as a GC root BEFORE computing the body: the cache
	// is a static (non-stack) live root the conservative stack scan cannot find,
	// and it is initialized to 0 so a collection during body evaluation scans a
	// safe (null) slot. Non-moving GC means the cached pointer stays valid.
	b.WriteString("  gc_add_root(&cache);\n")
	fmt.Fprintf(b, "  cache = %s;\n", em.expr(body))
	b.WriteString("  return cache;\n}\n")
}

// emitBlock emits one lifted code block as a native function. The body refers to
// its argument as CVar{0} (`arg`, shifted by inner CLet binders) and to captured
// variables via CEnv{slot} (`env[slot]`).
func (em *cEmitter) emitBlock(b *strings.Builder, blk CodeBlock) {
	fmt.Fprintf(b, "static Value %s(Value arg, Value* env) {\n", cCodeName(blk.Name))
	b.WriteString("  (void)arg; (void)env;\n")
	fmt.Fprintf(b, "  return %s;\n}\n", em.exprIn(blk.Body, []string{"arg"}))
}

// emitCtorC emits a constructor as a curried closure. A nullary constructor is the
// {tag} object directly; an arity-k constructor builds k generated code blocks,
// each consuming one argument and capturing the prefix, terminating in the
// {tag, field0 … field_{k-1}} object. The fields keep ALL arguments (datatype
// parameters included) so an eliminator's IField indexing matches the source
// backends ($show skips unit fields exactly as they do).
func (em *cEmitter) emitCtorC(b *strings.Builder, c CtorSpec) {
	if c.Arity == 0 {
		fmt.Fprintf(b, "static Value %s(void) {\n", cThunkName(c.Name))
		b.WriteString("  static int done = 0; static Value cache = 0;\n")
		b.WriteString("  if (done) return cache;\n  done = 1;\n")
		// The memoized cache is a static (non-stack) GC root: register it so a
		// collection never frees this cached constructor object.
		b.WriteString("  gc_add_root(&cache);\n")
		fmt.Fprintf(b, "  cache = mkcon(%d, %q, 0);\n", c.Tag, c.Name)
		b.WriteString("  return cache;\n}\n")
		return
	}
	// Generate one code block per argument. Block i (0-based) takes argument i and
	// has an env of the i previously-captured arguments; the LAST block builds the
	// object, earlier blocks build the next closure capturing arg + its env.
	base := "ctorfn_" + cName(c.Name)
	for i := 0; i < c.Arity; i++ {
		fmt.Fprintf(b, "static Value %s_%d(Value arg, Value* env) {\n", base, i)
		b.WriteString("  (void)arg; (void)env;\n")
		if i == c.Arity-1 {
			// Innermost: build the constructor object. Fields are env[0..i-1] then arg.
			fmt.Fprintf(b, "  Value o = mkcon(%d, %q, %d);\n", c.Tag, c.Name, c.Arity)
			for k := 0; k < i; k++ {
				fmt.Fprintf(b, "  con_set(o, %d, env[%d]);\n", k, k)
			}
			fmt.Fprintf(b, "  con_set(o, %d, arg);\n", i)
			b.WriteString("  return o;\n}\n")
		} else {
			// Allocate the next closure capturing env[0..i-1] ++ arg (i+1 slots).
			fmt.Fprintf(b, "  Value c = mkclo(&%s_%d, %d);\n", base, i+1, i+1)
			for k := 0; k < i; k++ {
				fmt.Fprintf(b, "  clo_set(c, %d, env[%d]);\n", k, k)
			}
			fmt.Fprintf(b, "  clo_set(c, %d, arg);\n", i)
			b.WriteString("  return c;\n}\n")
		}
	}
	// The thunk returns the arity-0 entry closure (empty env).
	fmt.Fprintf(b, "static Value %s(void) {\n", cThunkName(c.Name))
	b.WriteString("  static int done = 0; static Value cache = 0;\n")
	b.WriteString("  if (done) return cache;\n  done = 1;\n")
	// The memoized cache is a static (non-stack) GC root: register it so a
	// collection never frees this cached constructor entry closure.
	b.WriteString("  gc_add_root(&cache);\n")
	fmt.Fprintf(b, "  cache = mkclo(&%s_0, 0);\n", base)
	b.WriteString("  return cache;\n}\n")
}

// emitNatC emits the builtin-nat group natively: zero is the immediate 0, succ a
// closure incrementing its argument, the eliminator a fold loop — exactly the
// rep the other backends give nat (so the conformance output is byte-identical).
func (em *cEmitter) emitNatC(b *strings.Builder, n NatSpec) {
	// zero: the empty bignum.
	fmt.Fprintf(b, "static Value %s(void) { return big_from_long(0); }\n", cThunkName(n.Zero))
	// succ: x -> x+1 (bignum increment).
	fmt.Fprintf(b, "static Value %s_code(Value arg, Value* env) { (void)env; return big_succ(arg); }\n", cName(n.Succ))
	fmt.Fprintf(b, "static Value %s(void) { return mkclo(&%s_code, 0); }\n", cThunkName(n.Succ), cName(n.Succ))
	// eliminator: m -> c0 -> c1 -> x -> fold (m erased/ignored)
	base := cName(n.ElimName)
	// 4 curried code blocks capturing m, c0, c1; the last folds c1 over 0..x-1
	// with a BIGNUM counter (arg = x is a bignum, possibly past i64). O(x) by
	// construction — the same cost the succ-chain elimination always had.
	fmt.Fprintf(b, "static Value %s_b3(Value arg, Value* env) {\n", base)
	b.WriteString("  /* arg = x (bignum); env = {m, c0, c1} */\n")
	b.WriteString("  Value acc = env[1];\n")
	b.WriteString("  for (Value k = big_from_long(0); big_cmp(k, arg) < 0; k = big_succ(k))\n")
	b.WriteString("    acc = apply(apply(env[2], k), acc);\n")
	b.WriteString("  return acc;\n}\n")
	fmt.Fprintf(b, "static Value %s_b2(Value arg, Value* env) {\n", base)
	fmt.Fprintf(b, "  Value c = mkclo(&%s_b3, 3); clo_set(c,0,env[0]); clo_set(c,1,env[1]); clo_set(c,2,arg); return c;\n}\n", base)
	fmt.Fprintf(b, "static Value %s_b1(Value arg, Value* env) {\n", base)
	fmt.Fprintf(b, "  Value c = mkclo(&%s_b2, 2); clo_set(c,0,env[0]); clo_set(c,1,arg); return c;\n}\n", base)
	fmt.Fprintf(b, "static Value %s_b0(Value arg, Value* env) {\n", base)
	fmt.Fprintf(b, "  (void)env; Value c = mkclo(&%s_b1, 1); clo_set(c,0,arg); return c;\n}\n", base)
	fmt.Fprintf(b, "static Value %s(void) { return mkclo(&%s_b0, 0); }\n", cThunkName(n.ElimName), base)
	// One-peel CASE form for an eliminator whose step ignores its IH (see
	// StepIgnoresIH): zero -> c0, succ k -> c1 k unit. The emitter calls this
	// instead of the b3 fold when it can prove the step is IH-independent, turning
	// the super-exponential `beqNat`-shape into linear (the b3 fold evaluates the
	// step at every index 0..x-1, which compounds multiplicatively under nesting).
	fmt.Fprintf(b, "static Value %s_case(Value c0, Value c1, Value x) {\n", base)
	b.WriteString("  if (big_cmp(x, big_from_long(0)) == 0) return c0;\n")
	b.WriteString("  return apply(apply(c1, big_monus(x, big_from_long(1))), UNIT);\n}\n")
}

// natDispatch emits the constant-time one-peel CASE for a saturated `NatElim m c0
// c1 x [extra...]` whose successor step c1 provably ignores its IH, mirroring the
// source backends' $natD optimization (js.go). Without it the native b3 fold is
// super-exponential on the decidable-equality shape (nested IH-ignoring elims).
func (em *cEmitter) natDispatch(app AppClosure, locals []string) (string, bool) {
	args, ok := NatElimSpine(em.natElim, app)
	if !ok || !StepIgnoresIH(em.blocks, args[2]) {
		return "", false
	}
	out := fmt.Sprintf("%s_case(%s, %s, %s)", cName(em.natElim),
		em.exprIn(args[1], locals), em.exprIn(args[2], locals), em.exprIn(args[3], locals))
	for _, extra := range args[4:] {
		out = fmt.Sprintf("apply(%s, %s)", out, em.exprIn(extra, locals))
	}
	return out, true
}

// expr renders a CIr term to a C expression, in a code-block-free context (the
// def-thunk top level): there is no `arg` here, so any CVar is a CLet-bound local.
func (em *cEmitter) expr(t CIr) string { return em.exprIn(t, nil) }

// exprIn renders a CIr in a context of `locals` — the names of binders visible by
// de Bruijn index (innermost = index 0). A code block seeds locals with its
// argument (`arg`); CLet pushes a fresh name. CEnv reads the enclosing block's
// env (always `env[slot]`, valid only inside a code block — which is the only
// place CEnv occurs).
func (em *cEmitter) exprIn(t CIr, locals []string) string {
	switch x := t.(type) {
	case CVar:
		if x.Idx < len(locals) {
			return locals[x.Idx]
		}
		// Should not happen for a closed program; emit a defined-but-unreachable
		// marker so the C still compiles rather than referencing an unknown name.
		return "UNIT"
	case CEnv:
		return fmt.Sprintf("env[%d]", x.Idx)
	case CGlobal:
		return cThunkName(x.Name) + "()"
	case CForeign:
		// Host-linked accessor: the host defines `Value <name>(void)`.
		return cName(x.Name) + "()"
	case CUnit:
		return "UNIT"
	case CLit:
		switch x.Kind {
		case LitNat:
			// A compressed numeral deploys as a bignum parsed from its decimal
			// magnitude — arbitrary precision, interchangeable with a succ-chain
			// (zero/succ are the same bignum rep). No i64 cap.
			return fmt.Sprintf("big_parse(%s)", cstr(x.Nat))
		case LitStr:
			return fmt.Sprintf("mkstr(%s)", cstr(x.Str))
		case LitPtr:
			// Opaque host pointer: boxed so it never aliases an int; $show renders
			// it as a fixed marker.
			return fmt.Sprintf("mkptr(%d)", x.Int)
		default: // LitInt
			return fmt.Sprintf("mkint(%d)", x.Int)
		}
	case MkClosure:
		return em.mkClosure(x, locals)
	case AppClosure:
		if out, ok := em.natDispatch(x, locals); ok {
			return out
		}
		if out, ok := em.accelDispatch(x, locals); ok {
			return out
		}
		return fmt.Sprintf("apply(%s, %s)", em.exprIn(x.Clo, locals), em.exprIn(x.Arg, locals))
	case CLet:
		// A let binds a fresh value visible at index 0 in the body. Emit as an
		// immediately-applied closure-free statement expression via a helper call
		// pattern: GCC/Clang statement expressions keep it an expression so the
		// whole emitter stays expression-oriented.
		n := em.fresh()
		bound := em.exprIn(x.Val, locals)
		inner := em.exprIn(x.Body, prepend(n, locals))
		return fmt.Sprintf("({ Value %s = %s; %s; })", n, bound, inner)
	case CPair:
		return fmt.Sprintf("mkpair(%s, %s)", em.exprIn(x.A, locals), em.exprIn(x.B, locals))
	case CFst:
		return fmt.Sprintf("pair_fst(%s)", em.exprIn(x.P, locals))
	case CSnd:
		return fmt.Sprintf("pair_snd(%s)", em.exprIn(x.P, locals))
	case CField:
		return fmt.Sprintf("con_get(%s, %d)", em.exprIn(x.Scrut, locals), x.Index)
	case CCase:
		return em.caseExpr(x, locals)
	default:
		panic(fmt.Sprintf("codegen(c): unknown CIr node %T", t))
	}
}

// mkClosure emits a closure allocation: `mkclo(&code_N, n)` then fills the env
// slots with the captured terms (evaluated in the enclosing context). Uses a
// statement expression so it is a plain C expression.
func (em *cEmitter) mkClosure(x MkClosure, locals []string) string {
	if len(x.Env) == 0 {
		return fmt.Sprintf("mkclo(&%s, 0)", cCodeName(x.Code))
	}
	n := em.fresh()
	var b strings.Builder
	fmt.Fprintf(&b, "({ Value %s = mkclo(&%s, %d); ", n, cCodeName(x.Code), len(x.Env))
	for i, e := range x.Env {
		fmt.Fprintf(&b, "clo_set(%s, %d, %s); ", n, i, em.exprIn(e, locals))
	}
	fmt.Fprintf(&b, "%s; })", n)
	return b.String()
}

// caseExpr emits an eliminator's tag dispatch as a statement-expression switch
// over the scrutinee's constructor tag, each arm an arm body. Coverage is by
// construction, so an unmatched tag is a runtime abort.
func (em *cEmitter) caseExpr(x CCase, locals []string) string {
	s := em.fresh()
	r := em.fresh()
	var b strings.Builder
	fmt.Fprintf(&b, "({ Value %s = %s; Value %s; switch (con_tag(%s)) {", s, em.exprIn(x.Scrut, locals), r, s)
	for _, arm := range x.Arms {
		// Re-evaluate the scrutinee binding inside each arm by substituting the
		// scrutinee temp for any CField — but arms reference the scrutinee through
		// CField directly, so we render the arm body with the scrutinee already in
		// `locals`? No: CField carries its own Scrut term. We render the arm body
		// directly; it re-evaluates Scrut, which for a thunk/var is cheap and pure.
		fmt.Fprintf(&b, " case %d: %s = %s; break;", arm.Tag, r, em.exprIn(arm.Body, locals))
	}
	fmt.Fprintf(&b, " default: rt_abort(); }; %s; })", r)
	return b.String()
}

// accelDispatch emits a registered accel-op def on two args as native integer
// arithmetic (C7 / R-NUM Decision 4): add/mul are the C operators, monus is the
// saturating Peano monus (floors at 0). The int rep is the SAME NatSpec gives
// nat, so the result is interchangeable with the eliminator loop, O(1).
func (em *cEmitter) accelDispatch(app AppClosure, locals []string) (string, bool) {
	op, a, b, ok := accelMatchC(app, em.accel)
	if !ok {
		return "", false
	}
	ea, eb := em.exprIn(a, locals), em.exprIn(b, locals)
	switch op {
	case core.NatOpAdd:
		return fmt.Sprintf("nat_add(%s, %s)", ea, eb), true
	case core.NatOpMul:
		return fmt.Sprintf("nat_mul(%s, %s)", ea, eb), true
	case core.NatOpMonus:
		return fmt.Sprintf("nat_monus(%s, %s)", ea, eb), true
	}
	return "", false
}

// accelMatchC recognizes a saturated 2-argument application of a registered
// accel-op def on the closure-converted IR: AppClosure(AppClosure(CGlobal name,
// a), b) with `name` in the accel table. Mirrors accelMatch (which is over Ir).
func accelMatchC(app AppClosure, accel map[string]core.NatOp) (op core.NatOp, a, b CIr, ok bool) {
	if len(accel) == 0 {
		return core.NatOpNone, nil, nil, false
	}
	var args []CIr
	t := CIr(app)
	for {
		ap, isApp := t.(AppClosure)
		if !isApp {
			break
		}
		args = append([]CIr{ap.Arg}, args...)
		t = ap.Clo
	}
	g, isGlobal := t.(CGlobal)
	if !isGlobal || len(args) != 2 {
		return core.NatOpNone, nil, nil, false
	}
	kind, registered := accel[g.Name]
	if !registered || kind == core.NatOpNone {
		return core.NatOpNone, nil, nil, false
	}
	return kind, args[0], args[1], true
}

func (em *cEmitter) fresh() string {
	em.tmp++
	return fmt.Sprintf("_t%d", em.tmp)
}

// cName sanitizes a rune identifier into a C identifier (letters, digits, _).
func cName(n string) string {
	if m, ok := jsOpNames[n]; ok {
		return m[1:] // drop the leading $; we add our own prefixes
	}
	if i := strings.IndexByte(n, '$'); i > 0 {
		if m, ok := jsOpNames[n[:i]]; ok {
			n = m[1:] + n[i:]
		}
	}
	var b strings.Builder
	for _, r := range n {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	s := b.String()
	if s == "" {
		s = "x"
	}
	if c := s[0]; c >= '0' && c <= '9' {
		s = "_" + s
	}
	return s
}

// cThunkName / cCodeName namespace the two kinds of emitted symbol so they never
// collide (a def "code1" and a code block "$code1" are distinct).
func cThunkName(n string) string { return "def_" + cName(n) }
func cCodeName(n string) string  { return "code_" + cName(n) }

// cstr renders a Go string as a C string literal.
func cstr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range []byte(s) {
		switch r {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\t':
			b.WriteString("\\t")
		case '\r':
			b.WriteString("\\r")
		default:
			if r < 0x20 || r >= 0x7f {
				fmt.Fprintf(&b, "\\x%02x", r)
			} else {
				b.WriteByte(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

// emitFloatPrimsC bakes the D3 machine-float (f64) host bodies + the OpenBLAS dot
// kernel into the C translation unit (R-FFI assume-tier accessors, gated by use).
// Each is a curried closure over K_FLOAT boxes; a comparison returns a builtin-nat
// (1/0) the Rune side cases into Bool; `dot2` calls cblas_ddot (link -lopenblas).
// `Float` is a foreign TYPE surviving erasure as ok/err's type arg — a unit body.
func emitFloatPrimsC(b *strings.Builder, p Program) {
	// printNat (Nat -> IO Nat): the C backend's baked console-out (the source
	// backends bake it in their Emit; the native backends did not until D3's float
	// demos needed an observable). Prints the nat decimal, returns it.
	if usesForeign(p, "printNat") {
		b.WriteString("static Value printNat_c2(Value w, Value* env) { (void)w; Value n = env[0]; if (IS_INT(n)) printf(\"%ld\\n\", INT_VAL(n)); else { big_print(n); putchar('\\n'); } return n; }\n")
		b.WriteString("static Value printNat_c1(Value n, Value* env) { (void)env; Value c = mkclo(&printNat_c2, 1); clo_set(c, 0, n); return c; }\n")
		b.WriteString("static Value printNat(void) { return mkclo(&printNat_c1, 0); }\n")
	}
	// D4 / R-INTEROP: a MINIMAL CPython EMBED on the native C backend — not a subprocess
	// or the py emitter, but libpython linked INTO the binary (Py_Initialize once, lazily).
	// pyPow a b runs Python's own `pow(a,b)` in the embedded interpreter and marshals the
	// result back to a Rune nat. The proof-of-concept for the "embed/port CPython host model"
	// D4 item: the native runtime can call real CPython. Nats marshal via long (the host
	// model's full Array-dt-sh handle is the heavier remaining design). Link: python3-config
	// --includes --ldflags --embed.
	if usesForeign(p, "pyPow") || usesForeign(p, "pySqrt") || usesForeign(p, "pyFactorial") || usesForeign(p, "pyNpSum") || usesForeign(p, "pyNpScale") || usesForeign(p, "pyNpMatVec") {
		b.WriteString("#include <Python.h>\n")
		b.WriteString("static int rune_py_inited = 0;\n")
		b.WriteString("static void rune_py_ensure(void) { if (!rune_py_inited) { Py_Initialize(); rune_py_inited = 1; } }\n")
	}
	// pyFactorial n = Python's math.factorial(n) — ARBITRARY PRECISION: the nat marshals to a
	// DECIMAL STRING (big_to_decstr), Python computes the (possibly huge) factorial as a bignum,
	// and the result returns as a decimal string parsed back into a Rune bignum (big_from_decstr).
	// So Python's arbitrary-precision ints and Rune's builtin-nat bignums interoperate directly —
	// factorial(25) = 15511210043330985984000000, far beyond a machine long.
	if usesForeign(p, "pyFactorial") {
		b.WriteString("static void big_to_decstr(Value v, char* out, int outsz) { int n = big_nlimbs(v); if (n == 0) { snprintf(out, outsz, \"0\"); return; } int off = snprintf(out, outsz, \"%ld\", big_limb(v, n - 1)); for (int i = n - 2; i >= 0 && off < outsz; i--) off += snprintf(out + off, outsz - off, \"%09ld\", big_limb(v, i)); }\n")
		b.WriteString("static Value big_from_decstr(const char* s) { Value n = mkbig(0); Value ten = big_from_long(10); for (; *s; s++) { if (*s < '0' || *s > '9') continue; n = big_add(big_mul(n, ten), big_from_long(*s - '0')); } return n; }\n")
		b.WriteString("static Value pyFactorial_c(Value aa, Value* env) { (void)env; char inbuf[512]; if (IS_INT(aa)) snprintf(inbuf, sizeof inbuf, \"%ld\", INT_VAL(aa)); else big_to_decstr(aa, inbuf, sizeof inbuf); rune_py_ensure(); char buf[600]; snprintf(buf, sizeof buf, \"str(__import__('math').factorial(%s))\", inbuf); PyObject* m = PyImport_AddModule(\"__main__\"); PyObject* g = PyModule_GetDict(m); PyObject* r = PyRun_String(buf, Py_eval_input, g, g); Value res = big_from_long(0); if (r) { const char* s = PyUnicode_AsUTF8(r); if (s) res = big_from_decstr(s); Py_XDECREF(r); } else { PyErr_Clear(); } return res; }\n")
		b.WriteString("static Value pyFactorial(void) { return mkclo(&pyFactorial_c, 0); }\n")
	}
	if usesForeign(p, "pyPow") {
		b.WriteString("static Value pyPow_c2(Value bb, Value* env) { Value aa = env[0]; long a = IS_INT(aa) ? INT_VAL(aa) : (long)big_to_double(aa); long b = IS_INT(bb) ? INT_VAL(bb) : (long)big_to_double(bb); rune_py_ensure(); char buf[80]; snprintf(buf, sizeof buf, \"pow(%ld,%ld)\", a, b); PyObject* m = PyImport_AddModule(\"__main__\"); PyObject* g = PyModule_GetDict(m); PyObject* r = PyRun_String(buf, Py_eval_input, g, g); long res = 0; if (r) { res = PyLong_AsLong(r); Py_XDECREF(r); } else { PyErr_Clear(); } return big_from_long(res); }\n")
		b.WriteString("static Value pyPow_c1(Value a, Value* env) { (void)env; Value c = mkclo(&pyPow_c2, 1); clo_set(c, 0, a); return c; }\n")
		b.WriteString("static Value pyPow(void) { return mkclo(&pyPow_c1, 0); }\n")
	}
	// pySqrt n = Python's math.sqrt(n) in the embedded interpreter — a FLOAT return (and a
	// stdlib import via __import__), so the embed marshals both directions: nat in, f64 out.
	if usesForeign(p, "pySqrt") {
		b.WriteString("static Value pySqrt_c(Value aa, Value* env) { (void)env; long a = IS_INT(aa) ? INT_VAL(aa) : (long)big_to_double(aa); rune_py_ensure(); char buf[80]; snprintf(buf, sizeof buf, \"__import__('math').sqrt(%ld)\", a); PyObject* m = PyImport_AddModule(\"__main__\"); PyObject* g = PyModule_GetDict(m); PyObject* r = PyRun_String(buf, Py_eval_input, g, g); double d = 0.0; if (r) { d = PyFloat_AsDouble(r); Py_XDECREF(r); } else { PyErr_Clear(); } return mkfloat(d); }\n")
		b.WriteString("static Value pySqrt(void) { return mkclo(&pySqrt_c, 0); }\n")
	}
	if usesForeign(p, "Float") {
		b.WriteString("static Value Float(void) { return UNIT; }\n")
	}
	if usesForeign(p, "fromNat") {
		b.WriteString("static Value fromNat_c(Value a, Value* env) { (void)env; return mkfloat(big_to_double(a)); }\n")
		b.WriteString("static Value fromNat(void) { return mkclo(&fromNat_c, 0); }\n")
	}
	if usesForeign(p, "floatToNat") {
		b.WriteString("static Value floatToNat_c(Value x, Value* env) { (void)env; return big_from_long((long)float_val(x)); }\n")
		b.WriteString("static Value floatToNat(void) { return mkclo(&floatToNat_c, 0); }\n")
	}
	bin := func(name, op string) {
		if usesForeign(p, name) {
			fmt.Fprintf(b, "static Value %s_c2(Value y, Value* env) { return mkfloat(float_val(env[0]) %s float_val(y)); }\n", name, op)
			fmt.Fprintf(b, "static Value %s_c1(Value x, Value* env) { (void)env; Value c = mkclo(&%s_c2, 1); clo_set(c, 0, x); return c; }\n", name, name)
			fmt.Fprintf(b, "static Value %s(void) { return mkclo(&%s_c1, 0); }\n", name, name)
		}
	}
	bin("fadd", "+")
	bin("fsub", "-")
	bin("fmul", "*")
	bin("fdiv", "/")
	if usesForeign(p, "fleqN") {
		b.WriteString("static Value fleqN_c2(Value y, Value* env) { return float_val(env[0]) <= float_val(y) ? big_from_long(1) : big_from_long(0); }\n")
		b.WriteString("static Value fleqN_c1(Value x, Value* env) { (void)env; Value c = mkclo(&fleqN_c2, 1); clo_set(c, 0, x); return c; }\n")
		b.WriteString("static Value fleqN(void) { return mkclo(&fleqN_c1, 0); }\n")
	}
	if usesForeign(p, "fsqrt") {
		b.WriteString("#include <math.h>\n")
		b.WriteString("static Value fsqrt_c(Value x, Value* env) { (void)env; return mkfloat(sqrt(float_val(x))); }\n")
		b.WriteString("static Value fsqrt(void) { return mkclo(&fsqrt_c, 0); }\n")
	}
	if usesForeign(p, "fpow") {
		if !usesForeign(p, "fsqrt") {
			b.WriteString("#include <math.h>\n")
		}
		b.WriteString("static Value fpow_c2(Value e, Value* env) { return mkfloat(pow(float_val(env[0]), float_val(e))); }\n")
		b.WriteString("static Value fpow_c1(Value bs, Value* env) { (void)env; Value c = mkclo(&fpow_c2, 1); clo_set(c, 0, bs); return c; }\n")
		b.WriteString("static Value fpow(void) { return mkclo(&fpow_c1, 0); }\n")
	}
	if usesForeign(p, "fabsP") {
		b.WriteString("static Value fabsP_c(Value x, Value* env) { (void)env; double d = float_val(x); return mkfloat(d < 0 ? -d : d); }\n")
		b.WriteString("static Value fabsP(void) { return mkclo(&fabsP_c, 0); }\n")
	}
	// the OpenBLAS swap: the dot/matrix product(s) run through cblas_*, not a hand loop.
	if usesForeign(p, "dot2") || usesForeign(p, "dotList") || usesForeign(p, "gemmSum") || usesForeign(p, "npDot") || usesForeign(p, "npMatSum") {
		b.WriteString("#include <cblas.h>\n")
	}
	// shared FList marshaller: walk a Rune FList (fcons tag 1, head slot 0, tail slot 1)
	// into a C double[]. Used by dotList/npDot (vectors) and gemmSum/npMatSum (matrices).
	if usesForeign(p, "dotList") || usesForeign(p, "gemmSum") || usesForeign(p, "npDot") || usesForeign(p, "npMatSum") || usesForeign(p, "pyNpSum") || usesForeign(p, "pyNpScale") || usesForeign(p, "pyNpMatVec") {
		b.WriteString("static void fl_fill(Value lst, double* a) { int i = 0; while (!IS_INT(lst) && obj(lst)->kind == K_CON && obj(lst)->tag == 1) { a[i++] = float_val(obj(lst)->slots[0]); lst = obj(lst)->slots[1]; } }\n")
	}
	if usesForeign(p, "dotList") || usesForeign(p, "npDot") || usesForeign(p, "pyNpSum") || usesForeign(p, "pyNpScale") || usesForeign(p, "pyNpMatVec") {
		b.WriteString("static int fl_len(Value lst) { int n = 0; while (!IS_INT(lst) && obj(lst)->kind == K_CON && obj(lst)->tag == 1) { n++; lst = obj(lst)->slots[1]; } return n; }\n")
	}
	// pyNpSum xs = numpy.array(xs).sum() in the EMBEDDED interpreter — the structured-value
	// reach of the host model: a Rune FList marshals to a Python list (PyList of PyFloats), real
	// numpy reduces it, the scalar comes back. So the native binary runs actual numpy on a Rune
	// list, not just builtins/stdlib. (fl_fill/fl_len + rune_py_ensure defined above.)
	if usesForeign(p, "pyNpSum") {
		b.WriteString("static Value pyNpSum_c(Value xs, Value* env) { (void)env; int n = fl_len(xs); double* X = (double*)malloc(sizeof(double) * (n > 0 ? n : 1)); fl_fill(xs, X); rune_py_ensure(); PyObject* lst = PyList_New(n); for (int i = 0; i < n; i++) PyList_SetItem(lst, i, PyFloat_FromDouble(X[i])); free(X); PyObject* m = PyImport_AddModule(\"__main__\"); PyObject* g = PyModule_GetDict(m); PyObject* np = PyImport_ImportModule(\"numpy\"); double d = 0.0; if (np) { PyDict_SetItemString(g, \"np\", np); PyDict_SetItemString(g, \"xs\", lst); PyObject* r = PyRun_String(\"float(np.array(xs).sum())\", Py_eval_input, g, g); if (r) { d = PyFloat_AsDouble(r); Py_XDECREF(r); } else { PyErr_Clear(); } Py_XDECREF(np); } else { PyErr_Clear(); } Py_XDECREF(lst); return mkfloat(d); }\n")
		b.WriteString("static Value pyNpSum(void) { return mkclo(&pyNpSum_c, 0); }\n")
	}
	// pyNpScale xs k = (numpy.array(xs) * k).tolist() — the REVERSE structured-marshalling
	// direction: numpy returns an ARRAY, and the Python list is walked back into a Rune FList
	// (mkcon fcons/fnil, built tail-first). With pyNpSum this closes the bidirectional
	// structured-value bridge: Rune list -> numpy -> Rune list. [1,2,3,4]*3 = [3,6,9,12].
	if usesForeign(p, "pyNpScale") {
		b.WriteString("static Value pyNpScale_c2(Value kk, Value* env) { Value xs = env[0]; long k = IS_INT(kk) ? INT_VAL(kk) : (long)big_to_double(kk); int n = fl_len(xs); double* X = (double*)malloc(sizeof(double) * (n > 0 ? n : 1)); fl_fill(xs, X); rune_py_ensure(); PyObject* lst = PyList_New(n); for (int i = 0; i < n; i++) PyList_SetItem(lst, i, PyFloat_FromDouble(X[i])); free(X); PyObject* m = PyImport_AddModule(\"__main__\"); PyObject* g = PyModule_GetDict(m); PyObject* np = PyImport_ImportModule(\"numpy\"); Value res = mkcon(0, \"fnil\", 0); if (np) { PyDict_SetItemString(g, \"np\", np); PyDict_SetItemString(g, \"xs\", lst); char buf[80]; snprintf(buf, sizeof buf, \"(np.array(xs) * %ld).tolist()\", k); PyObject* r = PyRun_String(buf, Py_eval_input, g, g); if (r) { int rn = (int)PyList_Size(r); Value acc = mkcon(0, \"fnil\", 0); for (int i = rn - 1; i >= 0; i--) { double d = PyFloat_AsDouble(PyList_GetItem(r, i)); Value c = mkcon(1, \"fcons\", 2); con_set(c, 0, mkfloat(d)); con_set(c, 1, acc); acc = c; } res = acc; Py_XDECREF(r); } else { PyErr_Clear(); } Py_XDECREF(np); } else { PyErr_Clear(); } Py_XDECREF(lst); return res; }\n")
		b.WriteString("static Value pyNpScale_c1(Value xs, Value* env) { (void)env; Value c = mkclo(&pyNpScale_c2, 1); clo_set(c, 0, xs); return c; }\n")
		b.WriteString("static Value pyNpScale(void) { return mkclo(&pyNpScale_c1, 0); }\n")
	}
	// pyNpMatVec A m k v = the 2-D rung: a flat row-major (m x k) matrix and a length-k vector
	// marshal to Python lists, numpy reshapes A to (m,k) and computes A @ v, and the length-m
	// result returns as a Rune FList. So the embed handles SHAPED 2-D operands, not just 1-D —
	// a step toward the general Array-dt-sh handle. [[1,2],[3,4]] @ [5,6] = [17,39].
	if usesForeign(p, "pyNpMatVec") {
		b.WriteString("static Value pyNpMatVec_c4(Value v, Value* env) { Value A = env[0]; long m = IS_INT(env[1]) ? INT_VAL(env[1]) : (long)big_to_double(env[1]); long k = IS_INT(env[2]) ? INT_VAL(env[2]) : (long)big_to_double(env[2]); int an = fl_len(A), vn = fl_len(v); double* AA = (double*)malloc(sizeof(double) * (an > 0 ? an : 1)); fl_fill(A, AA); double* VV = (double*)malloc(sizeof(double) * (vn > 0 ? vn : 1)); fl_fill(v, VV); rune_py_ensure(); PyObject* pa = PyList_New(an); for (int i = 0; i < an; i++) PyList_SetItem(pa, i, PyFloat_FromDouble(AA[i])); PyObject* pv = PyList_New(vn); for (int i = 0; i < vn; i++) PyList_SetItem(pv, i, PyFloat_FromDouble(VV[i])); free(AA); free(VV); PyObject* mm = PyImport_AddModule(\"__main__\"); PyObject* g = PyModule_GetDict(mm); PyObject* np = PyImport_ImportModule(\"numpy\"); Value res = mkcon(0, \"fnil\", 0); if (np) { PyDict_SetItemString(g, \"np\", np); PyDict_SetItemString(g, \"A\", pa); PyDict_SetItemString(g, \"v\", pv); char buf[120]; snprintf(buf, sizeof buf, \"(np.array(A).reshape(%ld,%ld) @ np.array(v)).tolist()\", m, k); PyObject* r = PyRun_String(buf, Py_eval_input, g, g); if (r) { int rn = (int)PyList_Size(r); Value acc = mkcon(0, \"fnil\", 0); for (int i = rn - 1; i >= 0; i--) { double d = PyFloat_AsDouble(PyList_GetItem(r, i)); Value c = mkcon(1, \"fcons\", 2); con_set(c, 0, mkfloat(d)); con_set(c, 1, acc); acc = c; } res = acc; Py_XDECREF(r); } else { PyErr_Clear(); } Py_XDECREF(np); } else { PyErr_Clear(); } Py_XDECREF(pa); Py_XDECREF(pv); return res; }\n")
		b.WriteString("static Value pyNpMatVec_c3(Value k, Value* env) { Value c = mkclo(&pyNpMatVec_c4, 3); clo_set(c, 0, env[0]); clo_set(c, 1, env[1]); clo_set(c, 2, k); return c; }\n")
		b.WriteString("static Value pyNpMatVec_c2(Value m, Value* env) { Value c = mkclo(&pyNpMatVec_c3, 2); clo_set(c, 0, env[0]); clo_set(c, 1, m); return c; }\n")
		b.WriteString("static Value pyNpMatVec_c1(Value A, Value* env) { (void)env; Value c = mkclo(&pyNpMatVec_c2, 1); clo_set(c, 0, A); return c; }\n")
		b.WriteString("static Value pyNpMatVec(void) { return mkclo(&pyNpMatVec_c1, 0); }\n")
	}
	if usesForeign(p, "dot2") {
		b.WriteString("static Value dot2_c4(Value b1, Value* env) { double X[2] = { float_val(env[0]), float_val(env[1]) }; double Y[2] = { float_val(env[2]), float_val(b1) }; return mkfloat(cblas_ddot(2, X, 1, Y, 1)); }\n")
		b.WriteString("static Value dot2_c3(Value b0, Value* env) { Value c = mkclo(&dot2_c4, 3); clo_set(c, 0, env[0]); clo_set(c, 1, env[1]); clo_set(c, 2, b0); return c; }\n")
		b.WriteString("static Value dot2_c2(Value a1, Value* env) { Value c = mkclo(&dot2_c3, 2); clo_set(c, 0, env[0]); clo_set(c, 1, a1); return c; }\n")
		b.WriteString("static Value dot2_c1(Value a0, Value* env) { (void)env; Value c = mkclo(&dot2_c2, 1); clo_set(c, 0, a0); return c; }\n")
		b.WriteString("static Value dot2(void) { return mkclo(&dot2_c1, 0); }\n")
	}
	// ARBITRARY-LENGTH ddot: MARSHAL a Rune `FList` (fnil tag 0 | fcons tag 1, the
	// Float head in slot 0, the tail in slot 1) into a C double[], then cblas_ddot
	// over the common prefix. This is the array-marshalling boundary D4 numerics need.
	if usesForeign(p, "dotList") {
		b.WriteString("static Value dotList_c2(Value ys, Value* env) { Value xs = env[0]; int n = fl_len(xs), m = fl_len(ys); int k = n < m ? n : m; double* X = (double*)malloc(sizeof(double) * (k > 0 ? k : 1)); double* Y = (double*)malloc(sizeof(double) * (k > 0 ? k : 1)); fl_fill(xs, X); fl_fill(ys, Y); double r = cblas_ddot(k, X, 1, Y, 1); free(X); free(Y); return mkfloat(r); }\n")
		b.WriteString("static Value dotList_c1(Value xs, Value* env) { (void)env; Value c = mkclo(&dotList_c2, 1); clo_set(c, 0, xs); return c; }\n")
		b.WriteString("static Value dotList(void) { return mkclo(&dotList_c1, 0); }\n")
	}
	// D4 interop: npDot on the native backends is the OpenBLAS gift (cblas_ddot over the
	// marshalled FLists) — the same uniform capability the py backend serves with NumPy.
	if usesForeign(p, "npDot") {
		b.WriteString("static Value npDot_c2(Value ys, Value* env) { Value xs = env[0]; int n = fl_len(xs), m = fl_len(ys); int k = n < m ? n : m; double* X = (double*)malloc(sizeof(double) * (k > 0 ? k : 1)); double* Y = (double*)malloc(sizeof(double) * (k > 0 ? k : 1)); fl_fill(xs, X); fl_fill(ys, Y); double r = cblas_ddot(k, X, 1, Y, 1); free(X); free(Y); return mkfloat(r); }\n")
		b.WriteString("static Value npDot_c1(Value xs, Value* env) { (void)env; Value c = mkclo(&npDot_c2, 1); clo_set(c, 0, xs); return c; }\n")
		b.WriteString("static Value npDot(void) { return mkclo(&npDot_c1, 0); }\n")
	}
	// D4 interop: npMean — hand sum/count (no BLAS); py serves real numpy.mean.
	if usesForeign(p, "npMean") {
		b.WriteString("static Value npMean_c(Value xs, Value* env) { (void)env; double s = 0; int n = 0; while (!IS_INT(xs) && obj(xs)->kind == K_CON && obj(xs)->tag == 1) { s += float_val(obj(xs)->slots[0]); n++; xs = obj(xs)->slots[1]; } return mkfloat(n > 0 ? s / n : 0); }\n")
		b.WriteString("static Value npMean(void) { return mkclo(&npMean_c, 0); }\n")
	}
	// D4 interop: npVar — 2-pass hand body (no BLAS); py serves real numpy.var.
	if usesForeign(p, "npVar") {
		b.WriteString("static Value npVar_c(Value xs, Value* env) { (void)env; double s = 0; int n = 0; Value t = xs; while (!IS_INT(t) && obj(t)->kind == K_CON && obj(t)->tag == 1) { s += float_val(obj(t)->slots[0]); n++; t = obj(t)->slots[1]; } double m = n > 0 ? s / n : 0; double v = 0; Value u = xs; while (!IS_INT(u) && obj(u)->kind == K_CON && obj(u)->tag == 1) { double d = float_val(obj(u)->slots[0]) - m; v += d * d; u = obj(u)->slots[1]; } return mkfloat(n > 0 ? v / n : 0); }\n")
		b.WriteString("static Value npVar(void) { return mkclo(&npVar_c, 0); }\n")
	}
	// D4 interop: npMax — fold-max hand body (no BLAS); py serves real numpy.max.
	if usesForeign(p, "npMax") {
		b.WriteString("static Value npMax_c(Value xs, Value* env) { (void)env; double m = 0; int first = 1; while (!IS_INT(xs) && obj(xs)->kind == K_CON && obj(xs)->tag == 1) { double x = float_val(obj(xs)->slots[0]); if (first || x > m) { m = x; first = 0; } xs = obj(xs)->slots[1]; } return mkfloat(m); }\n")
		b.WriteString("static Value npMax(void) { return mkclo(&npMax_c, 0); }\n")
	}
	// D4 interop: npNorm — sqrt(sum of squares) hand body (math.h, -lm); py serves numpy.linalg.norm.
	if usesForeign(p, "npNorm") {
		if !usesForeign(p, "fsqrt") {
			b.WriteString("#include <math.h>\n")
		}
		b.WriteString("static Value npNorm_c(Value xs, Value* env) { (void)env; double s = 0; while (!IS_INT(xs) && obj(xs)->kind == K_CON && obj(xs)->tag == 1) { double x = float_val(obj(xs)->slots[0]); s += x * x; xs = obj(xs)->slots[1]; } return mkfloat(sqrt(s)); }\n")
		b.WriteString("static Value npNorm(void) { return mkclo(&npNorm_c, 0); }\n")
	}
	// MATRIX BLAS: gemmSum m k n A B marshals two flat row-major Rune FLists into C
	// double[]s, runs cblas_dgemm (C = A·B, A is m×k, B is k×n), and returns the SUM of
	// all entries of the product as a scalar — a real dgemm + 2-D marshalling without
	// host→Rune matrix construction (the observable stays a Float). The dims arrive as
	// builtin-nats (big_to_double → int).
	if usesForeign(p, "gemmSum") {
		b.WriteString("static Value gemmSum_c5(Value Bm, Value* env) { int m = (int)big_to_double(env[0]), k = (int)big_to_double(env[1]), n = (int)big_to_double(env[2]); Value A = env[3]; int al = m*k, bl = k*n, cl = m*n; double* AA = (double*)malloc(sizeof(double)*(al>0?al:1)); double* BB = (double*)malloc(sizeof(double)*(bl>0?bl:1)); double* CC = (double*)malloc(sizeof(double)*(cl>0?cl:1)); fl_fill(A, AA); fl_fill(Bm, BB); cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, m, n, k, 1.0, AA, k, BB, n, 0.0, CC, n); double s = 0; for (int i = 0; i < cl; i++) s += CC[i]; free(AA); free(BB); free(CC); return mkfloat(s); }\n")
		b.WriteString("static Value gemmSum_c4(Value A, Value* env) { Value c = mkclo(&gemmSum_c5, 4); clo_set(c, 0, env[0]); clo_set(c, 1, env[1]); clo_set(c, 2, env[2]); clo_set(c, 3, A); return c; }\n")
		b.WriteString("static Value gemmSum_c3(Value n, Value* env) { Value c = mkclo(&gemmSum_c4, 3); clo_set(c, 0, env[0]); clo_set(c, 1, env[1]); clo_set(c, 2, n); return c; }\n")
		b.WriteString("static Value gemmSum_c2(Value k, Value* env) { Value c = mkclo(&gemmSum_c3, 2); clo_set(c, 0, env[0]); clo_set(c, 1, k); return c; }\n")
		b.WriteString("static Value gemmSum_c1(Value m, Value* env) { (void)env; Value c = mkclo(&gemmSum_c2, 1); clo_set(c, 0, m); return c; }\n")
		b.WriteString("static Value gemmSum(void) { return mkclo(&gemmSum_c1, 0); }\n")
	}
	// D4 interop: npMatSum on the native backends is the OpenBLAS gift (cblas_dgemm),
	// the same uniform 2-D capability the py backend serves with numpy matmul.
	if usesForeign(p, "npMatSum") {
		b.WriteString("static Value npMatSum_c5(Value Bm, Value* env) { int m = (int)big_to_double(env[0]), k = (int)big_to_double(env[1]), n = (int)big_to_double(env[2]); Value A = env[3]; int al = m*k, bl = k*n, cl = m*n; double* AA = (double*)malloc(sizeof(double)*(al>0?al:1)); double* BB = (double*)malloc(sizeof(double)*(bl>0?bl:1)); double* CC = (double*)malloc(sizeof(double)*(cl>0?cl:1)); fl_fill(A, AA); fl_fill(Bm, BB); cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, m, n, k, 1.0, AA, k, BB, n, 0.0, CC, n); double s = 0; for (int i = 0; i < cl; i++) s += CC[i]; free(AA); free(BB); free(CC); return mkfloat(s); }\n")
		b.WriteString("static Value npMatSum_c4(Value A, Value* env) { Value c = mkclo(&npMatSum_c5, 4); clo_set(c, 0, env[0]); clo_set(c, 1, env[1]); clo_set(c, 2, env[2]); clo_set(c, 3, A); return c; }\n")
		b.WriteString("static Value npMatSum_c3(Value n, Value* env) { Value c = mkclo(&npMatSum_c4, 3); clo_set(c, 0, env[0]); clo_set(c, 1, env[1]); clo_set(c, 2, n); return c; }\n")
		b.WriteString("static Value npMatSum_c2(Value k, Value* env) { Value c = mkclo(&npMatSum_c3, 2); clo_set(c, 0, env[0]); clo_set(c, 1, k); return c; }\n")
		b.WriteString("static Value npMatSum_c1(Value m, Value* env) { (void)env; Value c = mkclo(&npMatSum_c2, 1); clo_set(c, 0, m); return c; }\n")
		b.WriteString("static Value npMatSum(void) { return mkclo(&npMatSum_c1, 0); }\n")
	}
}

// cRuntime is the embedded native closure runtime (R-NATIVE ABI piece 1+2+3 at
// the simplest correct point). A `Value` is a tagged word: an immediate int (low
// bit 1) or a pointer to a boxed Obj (low bit 0). Allocation is garbage-collected
// by a conservative-roots / precise-slots non-moving MARK-SWEEP collector
// (`gc_alloc`/`gc_collect`), so unbounded-allocation programs run. `apply`
// unpacks a closure's {code, env} and indirect-calls; `show` renders a value
// matching the other backends' observable output.
const cRuntime = `#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

typedef intptr_t Value;

/* Object kinds. K_BIG is a naive arbitrary-precision integer (builtin-nat): see
   the bignum section. */
enum { K_CLO = 0, K_CON = 1, K_PAIR = 2, K_STR = 3, K_PTR = 4, K_UNIT = 5, K_BIG = 6, K_FLOAT = 7 };

typedef struct Obj {
  int kind;
  /* GC: a forward-linked list of every live object + a mark bit. The collector
     is a CONSERVATIVE (roots) / PRECISE (slots) NON-MOVING MARK-SWEEP — see the
     gc section below. Non-moving keeps the static thunk caches valid. */
  struct Obj* gc_next;
  int gc_mark;
  /* closure */
  Value (*code)(Value, Value*);
  int nenv;
  /* constructor */
  int tag;
  const char* name;
  int nfield;
  /* string / opaque ptr */
  const char* str;
  long handle;
  /* D3 machine float (f64): a boxed IEEE-754 double, kind K_FLOAT. Traces no slots
     (the double is not a heap pointer), so the GC mark/size defaults cover it. */
  double dval;
  /* trailing slots: env (closure) or fields (constructor) */
  Value slots[1];
} Obj;

/* Immediate int tagging: shift left 1, set low bit. A pointer is even-aligned. */
#define INT_TAG(n)  (((Value)(n) << 1) | 1)
#define IS_INT(v)   ((v) & 1)
#define INT_VAL(v)  ((long)((v) >> 1))

/* ===========================================================================
   GARBAGE COLLECTOR — a conservative-roots / precise-slots NON-MOVING MARK-SWEEP.

   R-NATIVE's first cut for long-running native programs. Mark-sweep (not the
   recommended semispace copying) is the SOUND choice for THIS runtime because:

   - The runtime memoizes every top-level definition in a 'static Value cache'
     (emitDefThunk) and builds the quotient/IO builtins as 'static' closures.
     Those caches are live roots that DO NOT live on the C stack, so a stack-only
     scan cannot find them. A COPYING collector would also have to rewrite them
     in place. A non-moving collector only needs them MARKED, and we register
     each cache slot's address with the GC (gc_add_root) the first time a thunk
     runs — so the static caches are exact roots, never freed, never corrupted.
   - Non-moving = no forwarding pointers, no slot rewriting. A mistraced slot
     can never silently relocate a live object to a stale address. Worse-is-
     better, per R-NATIVE: a correct mark-sweep beats a buggy copying collector.

   ROOTS = the registered static cache slots (precise) UNION a CONSERVATIVE scan
   of the C stack between a saved stack bottom (captured in main) and the current
   SP (setjmp spills callee-saved registers first). Any word-aligned stack word
   whose low bit is 0 and which points at the start of a tracked heap object is
   treated as a root (a false positive merely keeps an object alive — safe).

   SLOT TRACING is PRECISE: the header kind + count says exactly which words are
   'Value' slots (env for K_CLO, fields for K_CON, the two K_PAIR words); the
   'code' function pointer, 'str', and 'handle' are NEVER traced. Each Value slot
   is itself checked low-bit (immediate int) vs. Obj* before recursing.
   =========================================================================== */

/* Every live object is on this singly-linked list (newest first), threaded
   through Obj.gc_next; gc_live_bytes tracks the working-set size. */
static Obj* gc_objs = 0;
static size_t gc_live_bytes = 0;
static size_t gc_threshold = 0;
/* Default initial GC threshold (bytes of live working set before a collection
   is triggered). Overridable at compile time with -DRUNE_GC_THRESHOLD=N to force
   collections under a tiny heap for stress testing. */
#ifndef RUNE_GC_THRESHOLD
#define RUNE_GC_THRESHOLD (8u * 1024u * 1024u)
#endif

/* Static (non-stack) roots: the addresses of thunk/builtin cache slots. */
#define GC_MAX_STATIC_ROOTS 4096
static Value* gc_static_roots[GC_MAX_STATIC_ROOTS];
static int gc_n_static_roots = 0;
static void gc_add_root(Value* slot) {
  /* Dropping a static root would let the collector free a still-reachable cached
     value (a soundness bug), so abort rather than silently lose one. Raise
     GC_MAX_STATIC_ROOTS if a program legitimately has more memoized definitions. */
  if (gc_n_static_roots >= GC_MAX_STATIC_ROOTS) {
    fprintf(stderr, "rune-c: too many GC static roots (raise GC_MAX_STATIC_ROOTS)\n"); exit(1);
  }
  gc_static_roots[gc_n_static_roots++] = slot;
}

/* The C stack bottom, captured in main before evaluation begins. The scan walks
   from the current SP up to this address. 'volatile' so the scan is not elided. */
static void* volatile gc_stack_bottom = 0;

#include <setjmp.h>

static void gc_collect(void);

static void* gc_alloc(size_t n) {
  /* align to pointer size so the int low-bit tag is never set on a real pointer */
  size_t a = sizeof(void*);
  n = (n + a - 1) & ~(a - 1);
  if (gc_threshold == 0) gc_threshold = RUNE_GC_THRESHOLD;
  if (gc_live_bytes + n > gc_threshold && gc_stack_bottom != 0) {
    gc_collect();
    /* If still over the threshold after collecting, the live set genuinely grew;
       raise the bar (a doubling heuristic) so we do not collect on every alloc. */
    while (gc_live_bytes + n > gc_threshold) gc_threshold *= 2;
  }
  /* ZERO the whole object: the emitted code allocates an object then fills its
     slots one at a time, and each fill EXPRESSION may itself allocate (triggering
     a collection) while the object is only PARTIALLY built. Zeroed slots read as
     null (ignored by tracing), and a zeroed header has kind K_CLO + nenv 0 so a
     half-built object traces no slots — never a wild pointer through a garbage
     slot. The caller overwrites kind/counts/slots synchronously, with no alloc in
     between, before any further allocation. */
  Obj* o = (Obj*)calloc(1, n);
  if (!o) { fprintf(stderr, "rune-c: out of memory\n"); exit(1); }
  o->gc_next = gc_objs; o->gc_mark = 0;
  gc_objs = o; gc_live_bytes += n;
  /* The sweep recomputes each object's byte-size from its header (gc_obj_size),
     so no per-object size word is stored. */
  return o;
}

/* Object byte-size from its header (kind + slot count). Mirrors the mk* sizes. */
static size_t gc_obj_size(Obj* o) {
  size_t base = sizeof(Obj);
  int extra = 0;
  switch (o->kind) {
    case K_CLO:  extra = o->nenv   > 0 ? o->nenv   - 1 : 0; break;
    case K_CON:  extra = o->nfield > 0 ? o->nfield - 1 : 0; break;
    case K_PAIR: extra = 1; break; /* mkpair allocates sizeof(Obj)+sizeof(Value) => slots[0..1] */
    /* K_BIG sizes off nenv = the ALLOCATED limb capacity (nfield is the LOGICAL
       limb count, which big_norm may shrink — so capacity, not nfield, bounds the
       object). The limbs are raw words, never traced (default in gc_mark_obj). */
    case K_BIG:  extra = o->nenv   > 0 ? o->nenv   - 1 : 0; break;
    default:     extra = 0; break; /* K_STR, K_PTR, K_UNIT: just the header */
  }
  size_t sz = base + (size_t)extra * sizeof(Value);
  size_t a = sizeof(void*);
  return (sz + a - 1) & ~(a - 1);
}

/* If v points anywhere WITHIN a tracked heap object, return that object; else 0.
   INTERIOR pointers must count: 'apply' calls a code block with env = &clo->slots
   (a pointer PAST the closure header, not to its start), and that interior env
   pointer may be the only live reference to the closure on the stack. Treating
   only object-start pointers as roots would free a closure still in use — the
   "apply of non-closure" crash. Conservative membership test, O(live) per
   candidate word (a sorted-bounds / bitmap speedup is a later perf item). */
static Obj* gc_find_obj(Value v) {
  if (v == 0 || (v & 1)) return 0;               /* null or immediate int */
  if ((v & (Value)(sizeof(void*) - 1)) != 0) return 0; /* not word-aligned */
  char* q = (char*)v;
  for (Obj* o = gc_objs; o; o = o->gc_next) {
    char* lo = (char*)o;
    char* hi = lo + gc_obj_size(o);
    if (q >= lo && q < hi) return o;
  }
  return 0;
}

/* PRECISE slot tracing: mark v if it is a heap object, then recurse into its
   Value slots (only the slots the header declares; never code/str/handle). */
static void gc_mark_value(Value v);
static void gc_mark_obj(Obj* o) {
  if (o->gc_mark) return;
  o->gc_mark = 1;
  switch (o->kind) {
    case K_CLO:  for (int i = 0; i < o->nenv;   i++) gc_mark_value(o->slots[i]); break;
    case K_CON:  for (int i = 0; i < o->nfield; i++) gc_mark_value(o->slots[i]); break;
    case K_PAIR: gc_mark_value(o->slots[0]); gc_mark_value(o->slots[1]); break;
    default: break; /* K_STR, K_PTR, K_UNIT carry no heap pointers */
  }
}
static void gc_mark_value(Value v) {
  if (v == 0 || (v & 1)) return;                 /* null or immediate int */
  gc_mark_obj((Obj*)v);
}

/* Conservatively scan a word-range [lo, hi) for anything that looks like a
   pointer to a tracked object, and mark it (with full precise sub-tracing). */
static void gc_scan_range(char* lo, char* hi) {
  if (lo > hi) { char* t = lo; lo = hi; hi = t; }
  /* advance lo to a word boundary */
  while (((uintptr_t)lo % sizeof(void*)) != 0) lo++;
  for (char* p = lo; p + sizeof(Value) <= hi; p += sizeof(void*)) {
    Value v = *(Value*)p;
    Obj* o = gc_find_obj(v);
    if (o) gc_mark_obj(o);
  }
}

/* Collection counter, exposed for tests: a program compiled with -DRUNE_GC_STATS
   prints "rune-c: gc collections=N" to stderr at exit so a test can confirm that
   collection actually fired during the run. */
static long gc_n_collections = 0;

static void gc_collect(void) {
  gc_n_collections++;
  /* spill callee-saved registers onto the stack so the scan sees them */
  jmp_buf regs;
  if (setjmp(regs)) return; /* never longjmp'd; just forces the spill */
  (void)regs;

  /* 1. precise static roots (thunk/builtin caches) */
  for (int i = 0; i < gc_n_static_roots; i++) gc_mark_value(*gc_static_roots[i]);

  /* 2. conservative stack scan (current SP .. saved bottom) + the jmp_buf */
  char* sp = (char*)__builtin_frame_address(0);
  char* bottom = (char*)gc_stack_bottom;
  gc_scan_range(sp, bottom);
  gc_scan_range((char*)&regs, (char*)&regs + sizeof(regs));

  /* 3. sweep: free unmarked, unlink them, clear marks on survivors */
  Obj** link = &gc_objs;
  while (*link) {
    Obj* o = *link;
    if (o->gc_mark) {
      o->gc_mark = 0;
      link = &o->gc_next;
    } else {
      *link = o->gc_next;
      gc_live_bytes -= gc_obj_size(o);
      free(o);
    }
  }
}

static Value UNIT;

static Obj* obj(Value v) { return (Obj*)v; }

static Value mkint(long n) { return INT_TAG(n); }
static long as_int(Value v) {
  if (IS_INT(v)) return INT_VAL(v);
  fprintf(stderr, "rune-c: as_int on non-int\n"); exit(1);
}

static Value mkclo(Value (*code)(Value, Value*), int nenv) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj) + (nenv > 0 ? (nenv - 1) : 0) * sizeof(Value));
  o->kind = K_CLO; o->code = code; o->nenv = nenv;
  return (Value)o;
}
static void clo_set(Value c, int i, Value x) { obj(c)->slots[i] = x; }

static Value mkcon(int tag, const char* name, int nfield) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj) + (nfield > 0 ? (nfield - 1) : 0) * sizeof(Value));
  o->kind = K_CON; o->tag = tag; o->name = name; o->nfield = nfield;
  return (Value)o;
}
static void con_set(Value c, int i, Value x) { obj(c)->slots[i] = x; }
static Value con_get(Value c, int i) { return obj(c)->slots[i]; }
static int con_tag(Value c) { return obj(c)->tag; }

static Value mkpair(Value a, Value b) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj) + sizeof(Value));
  o->kind = K_PAIR; o->slots[0] = a; o->slots[1] = b;
  return (Value)o;
}
static Value pair_fst(Value p) { return obj(p)->slots[0]; }
static Value pair_snd(Value p) { return obj(p)->slots[1]; }

static Value mkstr(const char* s) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj));
  o->kind = K_STR; o->str = s;
  return (Value)o;
}
static Value mkptr(long h) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj));
  o->kind = K_PTR; o->handle = h;
  return (Value)o;
}
/* D3 machine float: box/unbox an IEEE-754 double (kind K_FLOAT). */
static Value mkfloat(double d) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj));
  o->kind = K_FLOAT; o->dval = d;
  return (Value)o;
}
static double float_val(Value v) { return obj(v)->dval; }
static Value mkunit(void) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj));
  o->kind = K_UNIT;
  return (Value)o;
}

/* apply: unpack {code, env} and indirect-call. The fast path is the only path
   this iteration (no eval/apply saturation — currying is nested closures). */
static Value apply(Value clo, Value arg) {
  if (IS_INT(clo) || obj(clo)->kind != K_CLO) {
    fprintf(stderr, "rune-c: apply of non-closure\n"); exit(1);
  }
  Obj* o = obj(clo);
  return o->code(arg, o->slots);
}

/* ===========================================================================
   NAIVE ARBITRARY-PRECISION INTEGERS (R-NATIVE bignum) — the builtin-nat rep.

   A nat/whole is a K_BIG object: a sign (tag; 0 = nonneg — nat is always
   nonneg, the field is kept for the eventual signed Int) and a magnitude as
   base-1e9 limbs (little-endian, each in [0,1e9)). nfield = the LOGICAL limb
   count (big_norm strips leading zeros); nenv = the ALLOCATED capacity (sizes
   the object for the GC). Zero is the empty bignum (nfield 0).

   This is the NAIVE cut (schoolbook add/mul, saturating magnitude monus): every
   nat is boxed, no immediate-int fast path for small values — that optimization
   lands later. The native FFI LitInt keeps the IS_INT immediate rep; only
   builtin-nat is bignum, so the two coexist. The limbs are raw words, never heap
   pointers, so K_BIG traces no slots (default in gc_mark_obj). =============== */
#define BIG_BASE 1000000000L

static Value mkbig(int nlimbs) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj) + (nlimbs > 0 ? (nlimbs - 1) : 0) * sizeof(Value));
  o->kind = K_BIG; o->tag = 0; o->nfield = nlimbs; o->nenv = nlimbs;
  return (Value)o;
}
static int  big_nlimbs(Value v) { return obj(v)->nfield; }
static long big_limb(Value v, int i) { return (long)obj(v)->slots[i]; }
static void big_setlimb(Value v, int i, long x) { obj(v)->slots[i] = (Value)x; }

/* canonicalize: drop leading-zero limbs (logical nfield only; capacity stays). */
static Value big_norm(Value v) {
  Obj* o = obj(v);
  while (o->nfield > 0 && o->slots[o->nfield - 1] == 0) o->nfield--;
  return v;
}

static Value big_from_long(long n) {
  if (n <= 0) return mkbig(0);
  int k = 0; long t = n;
  while (t > 0) { k++; t /= BIG_BASE; }
  Value v = mkbig(k);
  for (int i = 0; i < k; i++) { big_setlimb(v, i, n % BIG_BASE); n /= BIG_BASE; }
  return v;
}

/* parse a decimal magnitude string (the LitNat payload) into a bignum. */
static Value big_parse(const char* s) {
  int len = (int)strlen(s);
  int k = (len + 8) / 9;            /* ceil(len/9) base-1e9 limbs */
  Value v = mkbig(k);
  int idx = 0, end = len;
  while (end > 0) {
    int start = end - 9; if (start < 0) start = 0;
    long limb = 0;
    for (int i = start; i < end; i++) limb = limb * 10 + (s[i] - '0');
    big_setlimb(v, idx++, limb);
    end = start;
  }
  return big_norm(v);
}

static int big_cmp(Value a, Value b) {     /* compare magnitudes: -1, 0, 1 */
  int na = big_nlimbs(a), nb = big_nlimbs(b);
  if (na != nb) return na < nb ? -1 : 1;
  for (int i = na - 1; i >= 0; i--) {
    long x = big_limb(a, i), y = big_limb(b, i);
    if (x != y) return x < y ? -1 : 1;
  }
  return 0;
}

static Value big_add(Value a, Value b) {
  int na = big_nlimbs(a), nb = big_nlimbs(b);
  int n = (na > nb ? na : nb) + 1;
  Value r = mkbig(n);
  long carry = 0;
  for (int i = 0; i < n; i++) {
    long s = carry;
    if (i < na) s += big_limb(a, i);
    if (i < nb) s += big_limb(b, i);
    big_setlimb(r, i, s % BIG_BASE);
    carry = s / BIG_BASE;
  }
  return big_norm(r);
}

static Value big_mul(Value a, Value b) {
  int na = big_nlimbs(a), nb = big_nlimbs(b);
  if (na == 0 || nb == 0) return mkbig(0);
  Value r = mkbig(na + nb);                 /* gc_alloc zeroes the limbs */
  for (int i = 0; i < na; i++) {
    long carry = 0, ai = big_limb(a, i);
    for (int j = 0; j < nb; j++) {
      long cur = big_limb(r, i + j) + ai * big_limb(b, j) + carry;
      big_setlimb(r, i + j, cur % BIG_BASE);
      carry = cur / BIG_BASE;
    }
    big_setlimb(r, i + nb, big_limb(r, i + nb) + carry);
  }
  return big_norm(r);
}

/* saturating magnitude subtraction (Peano monus): a - b, floored at 0. */
static Value big_monus(Value a, Value b) {
  if (big_cmp(a, b) <= 0) return mkbig(0);
  int na = big_nlimbs(a), nb = big_nlimbs(b);
  Value r = mkbig(na);
  long borrow = 0;
  for (int i = 0; i < na; i++) {
    long d = big_limb(a, i) - borrow - (i < nb ? big_limb(b, i) : 0);
    if (d < 0) { d += BIG_BASE; borrow = 1; } else borrow = 0;
    big_setlimb(r, i, d);
  }
  return big_norm(r);
}

static Value big_succ(Value a) { return big_add(a, big_from_long(1)); }

/* print a bignum as a decimal magnitude (top limb plain, the rest 0-padded). */
static void big_print(Value v) {
  int n = big_nlimbs(v);
  if (n == 0) { putchar('0'); return; }
  printf("%ld", big_limb(v, n - 1));
  for (int i = n - 2; i >= 0; i--) printf("%09ld", big_limb(v, i));
}

/* D3: a builtin-nat magnitude as a double (for fromNat: Nat -> Float). */
static double big_to_double(Value v) {
  double d = 0.0;
  for (int i = big_nlimbs(v) - 1; i >= 0; i--) d = d * (double)BIG_BASE + (double)big_limb(v, i);
  return d;
}

/* nat accel ops, now on the bignum rep (saturating Peano monus). */
static Value nat_add(Value a, Value b) { return big_add(a, b); }
static Value nat_mul(Value a, Value b) { return big_mul(a, b); }
static Value nat_monus(Value a, Value b) { return big_monus(a, b); }

static void rt_abort(void) { fprintf(stderr, "rune-c: impossible (unmatched constructor tag)\n"); exit(1); }

/* show: render a value in surface style, byte-identical to the other backends.
   () for unit, the digit for an int, the constructor name + show'd non-unit
   fields (parenthesised when they contain a space), <ptr> for an opaque handle. */
static void show(Value v);
static void show_paren(Value v) {
  /* a field is parenthesised iff its rendering contains a space */
  if (!IS_INT(v) && obj(v)->kind == K_CON && obj(v)->nfield > 0) {
    /* count non-unit fields to decide if a space can appear */
    Obj* o = obj(v); int shown = 0;
    for (int i = 0; i < o->nfield; i++) if (o->slots[i] != UNIT) shown++;
    if (shown > 0) { putchar('('); show(v); putchar(')'); return; }
  }
  show(v);
}
static void show(Value v) {
  if (v == UNIT) { printf("()"); return; }
  if (IS_INT(v)) { printf("%ld", INT_VAL(v)); return; }
  Obj* o = obj(v);
  switch (o->kind) {
    case K_BIG: big_print(v); return;
    case K_FLOAT: printf("%g", o->dval); return;
    case K_CLO: printf("<function>"); return;
    case K_PTR: printf("<ptr>"); return;
    case K_STR: printf("%s", o->str); return;
    case K_PAIR: {
      putchar('('); show(o->slots[0]); printf(", "); show(o->slots[1]); putchar(')');
      return;
    }
    case K_CON: {
      printf("%s", o->name);
      for (int i = 0; i < o->nfield; i++) {
        if (o->slots[i] == UNIT) continue;
        putchar(' ');
        show_paren(o->slots[i]);
      }
      return;
    }
    default: printf("()"); return;
  }
}
`

// cQuotRuntime is the erased quotient builtin group (v2): a quotient compiles to
// its carrier, so qin is the identity on its point and qlift applies the lifted
// function directly; the proof-valued members (qsound, qind) are unit-producers.
// Type/proof arguments arrive as units (no arity surgery), matching js.go's
// quotRuntime so the observable output is identical. Each is a curried closure.
const cQuotRuntime = `
/* qin A R a = a */
static Value quot_qin2(Value arg, Value* env) { (void)env; return arg; }
static Value quot_qin1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qin2, 0); }
static Value quot_qin0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qin1, 0); }
static Value def_qin(void) { return mkclo(&quot_qin0, 0); }
/* qlift A R B f resp q = f q  (captures f, then applies to q) */
static Value quot_qlift5(Value arg, Value* env) { return apply(env[0], arg); }
static Value quot_qlift4(Value arg, Value* env) { (void)arg; Value c = mkclo(&quot_qlift5, 1); clo_set(c, 0, env[0]); return c; }
static Value quot_qlift3(Value arg, Value* env) { (void)env; Value c = mkclo(&quot_qlift4, 1); clo_set(c, 0, arg); return c; }
static Value quot_qlift2(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qlift3, 0); }
static Value quot_qlift1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qlift2, 0); }
static Value quot_qlift0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qlift1, 0); }
static Value def_qlift(void) { return mkclo(&quot_qlift0, 0); }
/* qsound A R a b r = () ; qind A R P h q = () (proofs are units) */
static Value quot_unit5(Value arg, Value* env) { (void)arg; (void)env; return UNIT; }
static Value quot_qsound4(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_unit5, 0); }
static Value quot_qsound3(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qsound4, 0); }
static Value quot_qsound2(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qsound3, 0); }
static Value quot_qsound1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qsound2, 0); }
static Value quot_qsound0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qsound1, 0); }
static Value def_qsound(void) { return mkclo(&quot_qsound0, 0); }
static Value quot_qind4(Value arg, Value* env) { (void)arg; (void)env; return UNIT; }
static Value quot_qind3(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qind4, 0); }
static Value quot_qind2(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qind3, 0); }
static Value quot_qind1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qind2, 0); }
static Value quot_qind0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qind1, 0); }
static Value def_qind(void) { return mkclo(&quot_qind0, 0); }
`

// cIORuntime is the erased IO monad (R-EFFECT / C3): IO A is a deferred thunk
// (a unit-argument closure); pureIO returns a constant thunk; bindIO sequences —
// run m (apply to UNIT), feed its result to k, run that. Type arguments arrive
// as units. Mirrors js.go's ioRuntime for byte-identical observable output.
const cIORuntime = `
/* pureIO A a u = a  (a constant world thunk capturing a) */
static Value io_pure2(Value arg, Value* env) { (void)arg; return env[0]; }
static Value io_pure1(Value arg, Value* env) { (void)env; Value c = mkclo(&io_pure2, 1); clo_set(c, 0, arg); return c; }
static Value io_pure0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&io_pure1, 0); }
static Value def_pureIO(void) { return mkclo(&io_pure0, 0); }
/* bindIO A B m k u = k (m ()) ()   (captures m then k, sequences on force) */
static Value io_bind4(Value arg, Value* env) { (void)arg; /* env = {m, k} */ return apply(apply(env[1], apply(env[0], UNIT)), UNIT); }
static Value io_bind3(Value arg, Value* env) { /* env = {m} */ Value c = mkclo(&io_bind4, 2); clo_set(c, 0, env[0]); clo_set(c, 1, arg); return c; }
static Value io_bind2(Value arg, Value* env) { (void)env; Value c = mkclo(&io_bind3, 1); clo_set(c, 0, arg); return c; }
static Value io_bind1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&io_bind2, 0); }
static Value io_bind0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&io_bind1, 0); }
static Value def_bindIO(void) { return mkclo(&io_bind0, 0); }
`
