package codegen

import (
	"fmt"
	"sort"
	"strings"

	"goforge.dev/rune/v3/core"
)

// C is the FIRST NATIVE backend (telos-2 / M4): it emits portable C over the
// CLOSURE-CONVERTED IR (codegen/closure.go) and a tiny embedded closure runtime,
// compiled to real machine code by the system `cc`. Unlike the six SOURCE
// emitters (js/py/go/rust/jvm/beam), which lean on a host runtime's closures and
// GC, the C backend realizes the native ABI of R-NATIVE itself:
//
//   - a uniform tagged-word `Value` (immediate ints for builtin-nat, a pointer to
//     a boxed object for closures/constructors/pairs);
//   - `alloc` — a garbage-collected heap (a mark-sweep collector, see GC below);
//   - `apply(clo, arg)` — unpack a closure's {code, env} and indirect-call;
//   - constructor objects (tag + fields), pairs, and `$show` over the header tag,
//     producing byte-identical observable output to the other backends.
//
// Every `ILam` is lifted to a top-level `Value code_N(Value arg, Value* env)` by
// ClosureConvert; `MkClosure` allocates a {code, env...} object; `AppClosure`
// applies; `CCase`/`CField` are a tag switch / field load. Each top-level
// definition (and each datatype eliminator + constructor) becomes a MEMOIZED
// thunk `Value def_<name>(void)` so (mutually) recursive definitions and the
// eliminators — whose bodies reference themselves by global name — terminate the
// C initialization the way the Go backend's thunks do.
//
// SUPPORTED FRAGMENT (the conformance subset this iteration runs byte-identical
// to the other backends): builtin-nat arithmetic (zero/succ/NatElim + the accel
// add/mul/monus), constructors + eliminators (ICase/IField over ListElim/NatElim/
// any datatype), curried closures + application, dependent pairs (Σ erases to a
// 2-slot pair), quotients (carrier-erased), and the IO monad (deferred-thunk
// erasure), plus `partial` recursion (a top-level def whose body refers to itself
// — the memoized thunk + closure machinery already make this run). The native
// host LITERAL FFI (LitInt/LitStr/LitPtr) and IForeign are emitted but a foreign
// program needs a host-linked accessor, exactly as on the other backends.
//
// GC: this iteration ships a CONSERVATIVE-ROOTS / PRECISE-SLOTS NON-MOVING
// MARK-SWEEP collector (`gc_alloc`/`gc_collect`). It unblocks long-running /
// unbounded-allocation programs (a bump allocator only worked because the
// conformance corpus is finite). Mark-sweep (not the R-NATIVE-recommended
// semispace copying) is the sound choice HERE because the runtime memoizes
// definitions in `static Value cache` slots that do not live on the C stack: a
// non-moving collector only needs those slots MARKED (each is registered as a
// root via gc_add_root), where a copying collector would have to rewrite them.
// Roots = registered static caches (precise) ∪ a conservative C-stack scan
// (setjmp spills registers, scan SP..stack-bottom); object slots are traced
// PRECISELY from the header kind+count. See the runtime's gc section for the
// full rationale. NEXT: precise stack maps / a copying collector / perf (the
// O(live) heap-membership test is the obvious first speedup).
type C struct{}

func (C) Target() string { return "c" }

// Emit closure-converts the program and emits a self-contained C translation
// unit: the runtime header, every lifted code block, the constructor/eliminator/
// definition thunks, and a `main` that evaluates the entry and `$show`s it.
func (C) Emit(p Program) (TargetSource, error) {
	cp := ClosureConvert(p)
	em := &cEmitter{}
	if p.Nat != nil {
		em.natElim = p.Nat.ElimName
		em.accel = p.Nat.Ops
	}

	var b strings.Builder
	b.WriteString("/* Generated by rune emit (c backend) — the erased shadow, native via cc. Do not edit. */\n")
	b.WriteString(cRuntime)
	if usesQuot(p) {
		b.WriteString(cQuotRuntime)
	}
	if usesIO(p) {
		b.WriteString(cIORuntime)
	}

	// Forward declarations: every code block and every thunk, so the bodies may
	// reference one another (and themselves) regardless of definition order.
	for _, blk := range cp.Blocks {
		fmt.Fprintf(&b, "static Value %s(Value arg, Value* env);\n", cCodeName(blk.Name))
	}
	thunks := em.collectThunks(cp)
	for _, name := range thunks {
		fmt.Fprintf(&b, "static Value %s(void);\n", cThunkName(name))
	}
	// The constructor code blocks (one per argument) reference one another in a
	// chain; forward-declare them all so the chain links regardless of order.
	for _, d := range cp.Datas {
		if cp.Nat != nil && d.ElimName == cp.Nat.ElimName {
			continue
		}
		for _, c := range d.Ctors {
			base := "ctorfn_" + cName(c.Name)
			for i := 0; i < c.Arity; i++ {
				fmt.Fprintf(&b, "static Value %s_%d(Value arg, Value* env);\n", base, i)
			}
		}
	}
	b.WriteString("\n")

	// Constructor + eliminator thunks. A constructor of arity k is a curried
	// closure built from k generated code blocks (each capturing the prefix of
	// arguments), terminating in the {tag, fields...} object. The nat group emits
	// its native zero/succ/eliminator instead.
	for _, d := range cp.Datas {
		if cp.Nat != nil && d.ElimName == cp.Nat.ElimName {
			em.emitNatC(&b, *cp.Nat)
			continue
		}
		for _, c := range d.Ctors {
			em.emitCtorC(&b, c)
		}
	}
	// The lifted code blocks (definitions' and eliminators' bodies).
	for _, blk := range cp.Blocks {
		em.emitBlock(&b, blk)
	}
	// Definition thunks (eliminators converted as CDefSpec, then user defs).
	for _, def := range cp.Defs {
		em.emitDefThunk(&b, def.Name, def.Body)
	}

	// main: evaluate the entry thunk and show it. An IO main is a deferred world
	// thunk (unit -> A), forced by applying $unit.
	b.WriteString("int main(void) {\n")
	// Capture the C stack bottom for the conservative GC root scan: every live
	// Value used by the evaluation lives in a frame above this point, so the
	// collector scans from the current SP up to here.
	b.WriteString("  void* gc_anchor = 0; gc_stack_bottom = (void*)&gc_anchor;\n")
	b.WriteString("  UNIT = mkunit();\n")
	// UNIT is a static global (a boxed singleton); register it as a GC root so a
	// collection never frees it and show()'s `v == UNIT` comparison stays valid.
	b.WriteString("  gc_add_root(&UNIT);\n")
	if p.Main != "" {
		mainExpr := cThunkName(p.Main) + "()"
		if p.IOMain {
			mainExpr = fmt.Sprintf("apply(%s, UNIT)", mainExpr)
		}
		fmt.Fprintf(&b, "  show(%s);\n", mainExpr)
		b.WriteString("  putchar('\\n');\n")
	}
	// Optional GC stats (compile with -DRUNE_GC_STATS) — lets a test confirm the
	// collector actually fired during the run, on stderr so stdout stays clean.
	b.WriteString("#ifdef RUNE_GC_STATS\n")
	b.WriteString("  fprintf(stderr, \"rune-c: gc collections=%ld\\n\", gc_n_collections);\n")
	b.WriteString("#endif\n")
	b.WriteString("  return 0;\n}\n")
	return TargetSource(b.String()), nil
}

// cEmitter renders CIr terms to C expressions. Like the other backends it knows
// the nat eliminator's name + the accel table so it can emit native arithmetic.
type cEmitter struct {
	natElim string
	accel   map[string]core.NatOp
	tmp     int // fresh-temporary counter for the rare statement-form (CCase)
}

// collectThunks returns every top-level name that gets a thunk: each datatype's
// constructors + eliminator (the nat group's zero/succ/elim too) and each
// converted definition. Sorted-stable for deterministic forward decls.
func (em *cEmitter) collectThunks(cp ClosureProgram) []string {
	seen := map[string]bool{}
	var out []string
	add := func(n string) {
		if !seen[n] {
			seen[n] = true
			out = append(out, n)
		}
	}
	for _, d := range cp.Datas {
		if cp.Nat != nil && d.ElimName == cp.Nat.ElimName {
			add(cp.Nat.Zero)
			add(cp.Nat.Succ)
			add(cp.Nat.ElimName)
			continue
		}
		for _, c := range d.Ctors {
			add(c.Name)
		}
	}
	for _, def := range cp.Defs {
		add(def.Name)
	}
	sort.Strings(out)
	return out
}

// emitDefThunk emits a memoized thunk for a top-level definition: the first call
// computes the body and caches it, so recursion (and the eliminators' self-
// reference) terminates and is not recomputed.
func (em *cEmitter) emitDefThunk(b *strings.Builder, name string, body CIr) {
	fmt.Fprintf(b, "static Value %s(void) {\n", cThunkName(name))
	b.WriteString("  static int done = 0; static Value cache = 0;\n")
	b.WriteString("  if (done) return cache;\n")
	b.WriteString("  done = 1;\n")
	// Register the cache slot as a GC root BEFORE computing the body: the cache
	// is a static (non-stack) live root the conservative stack scan cannot find,
	// and it is initialized to 0 so a collection during body evaluation scans a
	// safe (null) slot. Non-moving GC means the cached pointer stays valid.
	b.WriteString("  gc_add_root(&cache);\n")
	fmt.Fprintf(b, "  cache = %s;\n", em.expr(body))
	b.WriteString("  return cache;\n}\n")
}

// emitBlock emits one lifted code block as a native function. The body refers to
// its argument as CVar{0} (`arg`, shifted by inner CLet binders) and to captured
// variables via CEnv{slot} (`env[slot]`).
func (em *cEmitter) emitBlock(b *strings.Builder, blk CodeBlock) {
	fmt.Fprintf(b, "static Value %s(Value arg, Value* env) {\n", cCodeName(blk.Name))
	b.WriteString("  (void)arg; (void)env;\n")
	fmt.Fprintf(b, "  return %s;\n}\n", em.exprIn(blk.Body, []string{"arg"}))
}

// emitCtorC emits a constructor as a curried closure. A nullary constructor is the
// {tag} object directly; an arity-k constructor builds k generated code blocks,
// each consuming one argument and capturing the prefix, terminating in the
// {tag, field0 … field_{k-1}} object. The fields keep ALL arguments (datatype
// parameters included) so an eliminator's IField indexing matches the source
// backends ($show skips unit fields exactly as they do).
func (em *cEmitter) emitCtorC(b *strings.Builder, c CtorSpec) {
	if c.Arity == 0 {
		fmt.Fprintf(b, "static Value %s(void) {\n", cThunkName(c.Name))
		b.WriteString("  static int done = 0; static Value cache = 0;\n")
		b.WriteString("  if (done) return cache;\n  done = 1;\n")
		// The memoized cache is a static (non-stack) GC root: register it so a
		// collection never frees this cached constructor object.
		b.WriteString("  gc_add_root(&cache);\n")
		fmt.Fprintf(b, "  cache = mkcon(%d, %q, 0);\n", c.Tag, c.Name)
		b.WriteString("  return cache;\n}\n")
		return
	}
	// Generate one code block per argument. Block i (0-based) takes argument i and
	// has an env of the i previously-captured arguments; the LAST block builds the
	// object, earlier blocks build the next closure capturing arg + its env.
	base := "ctorfn_" + cName(c.Name)
	for i := 0; i < c.Arity; i++ {
		fmt.Fprintf(b, "static Value %s_%d(Value arg, Value* env) {\n", base, i)
		b.WriteString("  (void)arg; (void)env;\n")
		if i == c.Arity-1 {
			// Innermost: build the constructor object. Fields are env[0..i-1] then arg.
			fmt.Fprintf(b, "  Value o = mkcon(%d, %q, %d);\n", c.Tag, c.Name, c.Arity)
			for k := 0; k < i; k++ {
				fmt.Fprintf(b, "  con_set(o, %d, env[%d]);\n", k, k)
			}
			fmt.Fprintf(b, "  con_set(o, %d, arg);\n", i)
			b.WriteString("  return o;\n}\n")
		} else {
			// Allocate the next closure capturing env[0..i-1] ++ arg (i+1 slots).
			fmt.Fprintf(b, "  Value c = mkclo(&%s_%d, %d);\n", base, i+1, i+1)
			for k := 0; k < i; k++ {
				fmt.Fprintf(b, "  clo_set(c, %d, env[%d]);\n", k, k)
			}
			fmt.Fprintf(b, "  clo_set(c, %d, arg);\n", i)
			b.WriteString("  return c;\n}\n")
		}
	}
	// The thunk returns the arity-0 entry closure (empty env).
	fmt.Fprintf(b, "static Value %s(void) {\n", cThunkName(c.Name))
	b.WriteString("  static int done = 0; static Value cache = 0;\n")
	b.WriteString("  if (done) return cache;\n  done = 1;\n")
	// The memoized cache is a static (non-stack) GC root: register it so a
	// collection never frees this cached constructor entry closure.
	b.WriteString("  gc_add_root(&cache);\n")
	fmt.Fprintf(b, "  cache = mkclo(&%s_0, 0);\n", base)
	b.WriteString("  return cache;\n}\n")
}

// emitNatC emits the builtin-nat group natively: zero is the immediate 0, succ a
// closure incrementing its argument, the eliminator a fold loop — exactly the
// rep the other backends give nat (so the conformance output is byte-identical).
func (em *cEmitter) emitNatC(b *strings.Builder, n NatSpec) {
	// zero
	fmt.Fprintf(b, "static Value %s(void) { return mkint(0); }\n", cThunkName(n.Zero))
	// succ: x -> x+1
	fmt.Fprintf(b, "static Value %s_code(Value arg, Value* env) { (void)env; return mkint(as_int(arg) + 1); }\n", cName(n.Succ))
	fmt.Fprintf(b, "static Value %s(void) { return mkclo(&%s_code, 0); }\n", cThunkName(n.Succ), cName(n.Succ))
	// eliminator: m -> c0 -> c1 -> x -> fold (m erased/ignored)
	base := cName(n.ElimName)
	// 4 curried code blocks capturing m, c0, c1; the last folds.
	fmt.Fprintf(b, "static Value %s_b3(Value arg, Value* env) {\n", base)
	b.WriteString("  /* arg = x; env = {m, c0, c1} */\n")
	b.WriteString("  long x = as_int(arg); Value acc = env[1];\n")
	b.WriteString("  for (long k = 0; k < x; k++) acc = apply(apply(env[2], mkint(k)), acc);\n")
	b.WriteString("  return acc;\n}\n")
	fmt.Fprintf(b, "static Value %s_b2(Value arg, Value* env) {\n", base)
	fmt.Fprintf(b, "  Value c = mkclo(&%s_b3, 3); clo_set(c,0,env[0]); clo_set(c,1,env[1]); clo_set(c,2,arg); return c;\n}\n", base)
	fmt.Fprintf(b, "static Value %s_b1(Value arg, Value* env) {\n", base)
	fmt.Fprintf(b, "  Value c = mkclo(&%s_b2, 2); clo_set(c,0,env[0]); clo_set(c,1,arg); return c;\n}\n", base)
	fmt.Fprintf(b, "static Value %s_b0(Value arg, Value* env) {\n", base)
	fmt.Fprintf(b, "  (void)env; Value c = mkclo(&%s_b1, 1); clo_set(c,0,arg); return c;\n}\n", base)
	fmt.Fprintf(b, "static Value %s(void) { return mkclo(&%s_b0, 0); }\n", cThunkName(n.ElimName), base)
}

// expr renders a CIr term to a C expression, in a code-block-free context (the
// def-thunk top level): there is no `arg` here, so any CVar is a CLet-bound local.
func (em *cEmitter) expr(t CIr) string { return em.exprIn(t, nil) }

// exprIn renders a CIr in a context of `locals` — the names of binders visible by
// de Bruijn index (innermost = index 0). A code block seeds locals with its
// argument (`arg`); CLet pushes a fresh name. CEnv reads the enclosing block's
// env (always `env[slot]`, valid only inside a code block — which is the only
// place CEnv occurs).
func (em *cEmitter) exprIn(t CIr, locals []string) string {
	switch x := t.(type) {
	case CVar:
		if x.Idx < len(locals) {
			return locals[x.Idx]
		}
		// Should not happen for a closed program; emit a defined-but-unreachable
		// marker so the C still compiles rather than referencing an unknown name.
		return "UNIT"
	case CEnv:
		return fmt.Sprintf("env[%d]", x.Idx)
	case CGlobal:
		return cThunkName(x.Name) + "()"
	case CForeign:
		// Host-linked accessor: the host defines `Value <name>(void)`.
		return cName(x.Name) + "()"
	case CUnit:
		return "UNIT"
	case CLit:
		switch x.Kind {
		case LitNat:
			// A compressed numeral deploys as the native immediate int — the SAME
			// rep NatSpec gives nat, so it is interchangeable with a succ-chain.
			return fmt.Sprintf("mkint(%s)", x.Nat)
		case LitStr:
			return fmt.Sprintf("mkstr(%s)", cstr(x.Str))
		case LitPtr:
			// Opaque host pointer: boxed so it never aliases an int; $show renders
			// it as a fixed marker.
			return fmt.Sprintf("mkptr(%d)", x.Int)
		default: // LitInt
			return fmt.Sprintf("mkint(%d)", x.Int)
		}
	case MkClosure:
		return em.mkClosure(x, locals)
	case AppClosure:
		if out, ok := em.accelDispatch(x, locals); ok {
			return out
		}
		return fmt.Sprintf("apply(%s, %s)", em.exprIn(x.Clo, locals), em.exprIn(x.Arg, locals))
	case CLet:
		// A let binds a fresh value visible at index 0 in the body. Emit as an
		// immediately-applied closure-free statement expression via a helper call
		// pattern: GCC/Clang statement expressions keep it an expression so the
		// whole emitter stays expression-oriented.
		n := em.fresh()
		bound := em.exprIn(x.Val, locals)
		inner := em.exprIn(x.Body, prepend(n, locals))
		return fmt.Sprintf("({ Value %s = %s; %s; })", n, bound, inner)
	case CPair:
		return fmt.Sprintf("mkpair(%s, %s)", em.exprIn(x.A, locals), em.exprIn(x.B, locals))
	case CFst:
		return fmt.Sprintf("pair_fst(%s)", em.exprIn(x.P, locals))
	case CSnd:
		return fmt.Sprintf("pair_snd(%s)", em.exprIn(x.P, locals))
	case CField:
		return fmt.Sprintf("con_get(%s, %d)", em.exprIn(x.Scrut, locals), x.Index)
	case CCase:
		return em.caseExpr(x, locals)
	default:
		panic(fmt.Sprintf("codegen(c): unknown CIr node %T", t))
	}
}

// mkClosure emits a closure allocation: `mkclo(&code_N, n)` then fills the env
// slots with the captured terms (evaluated in the enclosing context). Uses a
// statement expression so it is a plain C expression.
func (em *cEmitter) mkClosure(x MkClosure, locals []string) string {
	if len(x.Env) == 0 {
		return fmt.Sprintf("mkclo(&%s, 0)", cCodeName(x.Code))
	}
	n := em.fresh()
	var b strings.Builder
	fmt.Fprintf(&b, "({ Value %s = mkclo(&%s, %d); ", n, cCodeName(x.Code), len(x.Env))
	for i, e := range x.Env {
		fmt.Fprintf(&b, "clo_set(%s, %d, %s); ", n, i, em.exprIn(e, locals))
	}
	fmt.Fprintf(&b, "%s; })", n)
	return b.String()
}

// caseExpr emits an eliminator's tag dispatch as a statement-expression switch
// over the scrutinee's constructor tag, each arm an arm body. Coverage is by
// construction, so an unmatched tag is a runtime abort.
func (em *cEmitter) caseExpr(x CCase, locals []string) string {
	s := em.fresh()
	r := em.fresh()
	var b strings.Builder
	fmt.Fprintf(&b, "({ Value %s = %s; Value %s; switch (con_tag(%s)) {", s, em.exprIn(x.Scrut, locals), r, s)
	for _, arm := range x.Arms {
		// Re-evaluate the scrutinee binding inside each arm by substituting the
		// scrutinee temp for any CField — but arms reference the scrutinee through
		// CField directly, so we render the arm body with the scrutinee already in
		// `locals`? No: CField carries its own Scrut term. We render the arm body
		// directly; it re-evaluates Scrut, which for a thunk/var is cheap and pure.
		fmt.Fprintf(&b, " case %d: %s = %s; break;", arm.Tag, r, em.exprIn(arm.Body, locals))
	}
	fmt.Fprintf(&b, " default: rt_abort(); }; %s; })", r)
	return b.String()
}

// accelDispatch emits a registered accel-op def on two args as native integer
// arithmetic (C7 / R-NUM Decision 4): add/mul are the C operators, monus is the
// saturating Peano monus (floors at 0). The int rep is the SAME NatSpec gives
// nat, so the result is interchangeable with the eliminator loop, O(1).
func (em *cEmitter) accelDispatch(app AppClosure, locals []string) (string, bool) {
	op, a, b, ok := accelMatchC(app, em.accel)
	if !ok {
		return "", false
	}
	ea, eb := em.exprIn(a, locals), em.exprIn(b, locals)
	switch op {
	case core.NatOpAdd:
		return fmt.Sprintf("nat_add(%s, %s)", ea, eb), true
	case core.NatOpMul:
		return fmt.Sprintf("nat_mul(%s, %s)", ea, eb), true
	case core.NatOpMonus:
		return fmt.Sprintf("nat_monus(%s, %s)", ea, eb), true
	}
	return "", false
}

// accelMatchC recognizes a saturated 2-argument application of a registered
// accel-op def on the closure-converted IR: AppClosure(AppClosure(CGlobal name,
// a), b) with `name` in the accel table. Mirrors accelMatch (which is over Ir).
func accelMatchC(app AppClosure, accel map[string]core.NatOp) (op core.NatOp, a, b CIr, ok bool) {
	if len(accel) == 0 {
		return core.NatOpNone, nil, nil, false
	}
	var args []CIr
	t := CIr(app)
	for {
		ap, isApp := t.(AppClosure)
		if !isApp {
			break
		}
		args = append([]CIr{ap.Arg}, args...)
		t = ap.Clo
	}
	g, isGlobal := t.(CGlobal)
	if !isGlobal || len(args) != 2 {
		return core.NatOpNone, nil, nil, false
	}
	kind, registered := accel[g.Name]
	if !registered || kind == core.NatOpNone {
		return core.NatOpNone, nil, nil, false
	}
	return kind, args[0], args[1], true
}

func (em *cEmitter) fresh() string {
	em.tmp++
	return fmt.Sprintf("_t%d", em.tmp)
}

// cName sanitizes a rune identifier into a C identifier (letters, digits, _).
func cName(n string) string {
	if m, ok := jsOpNames[n]; ok {
		return m[1:] // drop the leading $; we add our own prefixes
	}
	if i := strings.IndexByte(n, '$'); i > 0 {
		if m, ok := jsOpNames[n[:i]]; ok {
			n = m[1:] + n[i:]
		}
	}
	var b strings.Builder
	for _, r := range n {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	s := b.String()
	if s == "" {
		s = "x"
	}
	if c := s[0]; c >= '0' && c <= '9' {
		s = "_" + s
	}
	return s
}

// cThunkName / cCodeName namespace the two kinds of emitted symbol so they never
// collide (a def "code1" and a code block "$code1" are distinct).
func cThunkName(n string) string { return "def_" + cName(n) }
func cCodeName(n string) string  { return "code_" + cName(n) }

// cstr renders a Go string as a C string literal.
func cstr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range []byte(s) {
		switch r {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\t':
			b.WriteString("\\t")
		case '\r':
			b.WriteString("\\r")
		default:
			if r < 0x20 || r >= 0x7f {
				fmt.Fprintf(&b, "\\x%02x", r)
			} else {
				b.WriteByte(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

// cRuntime is the embedded native closure runtime (R-NATIVE ABI piece 1+2+3 at
// the simplest correct point). A `Value` is a tagged word: an immediate int (low
// bit 1) or a pointer to a boxed Obj (low bit 0). Allocation is garbage-collected
// by a conservative-roots / precise-slots non-moving MARK-SWEEP collector
// (`gc_alloc`/`gc_collect`), so unbounded-allocation programs run. `apply`
// unpacks a closure's {code, env} and indirect-calls; `show` renders a value
// matching the other backends' observable output.
const cRuntime = `#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

typedef intptr_t Value;

/* Object kinds. */
enum { K_CLO = 0, K_CON = 1, K_PAIR = 2, K_STR = 3, K_PTR = 4, K_UNIT = 5 };

typedef struct Obj {
  int kind;
  /* GC: a forward-linked list of every live object + a mark bit. The collector
     is a CONSERVATIVE (roots) / PRECISE (slots) NON-MOVING MARK-SWEEP — see the
     gc section below. Non-moving keeps the static thunk caches valid. */
  struct Obj* gc_next;
  int gc_mark;
  /* closure */
  Value (*code)(Value, Value*);
  int nenv;
  /* constructor */
  int tag;
  const char* name;
  int nfield;
  /* string / opaque ptr */
  const char* str;
  long handle;
  /* trailing slots: env (closure) or fields (constructor) */
  Value slots[1];
} Obj;

/* Immediate int tagging: shift left 1, set low bit. A pointer is even-aligned. */
#define INT_TAG(n)  (((Value)(n) << 1) | 1)
#define IS_INT(v)   ((v) & 1)
#define INT_VAL(v)  ((long)((v) >> 1))

/* ===========================================================================
   GARBAGE COLLECTOR — a conservative-roots / precise-slots NON-MOVING MARK-SWEEP.

   R-NATIVE's first cut for long-running native programs. Mark-sweep (not the
   recommended semispace copying) is the SOUND choice for THIS runtime because:

   - The runtime memoizes every top-level definition in a 'static Value cache'
     (emitDefThunk) and builds the quotient/IO builtins as 'static' closures.
     Those caches are live roots that DO NOT live on the C stack, so a stack-only
     scan cannot find them. A COPYING collector would also have to rewrite them
     in place. A non-moving collector only needs them MARKED, and we register
     each cache slot's address with the GC (gc_add_root) the first time a thunk
     runs — so the static caches are exact roots, never freed, never corrupted.
   - Non-moving = no forwarding pointers, no slot rewriting. A mistraced slot
     can never silently relocate a live object to a stale address. Worse-is-
     better, per R-NATIVE: a correct mark-sweep beats a buggy copying collector.

   ROOTS = the registered static cache slots (precise) UNION a CONSERVATIVE scan
   of the C stack between a saved stack bottom (captured in main) and the current
   SP (setjmp spills callee-saved registers first). Any word-aligned stack word
   whose low bit is 0 and which points at the start of a tracked heap object is
   treated as a root (a false positive merely keeps an object alive — safe).

   SLOT TRACING is PRECISE: the header kind + count says exactly which words are
   'Value' slots (env for K_CLO, fields for K_CON, the two K_PAIR words); the
   'code' function pointer, 'str', and 'handle' are NEVER traced. Each Value slot
   is itself checked low-bit (immediate int) vs. Obj* before recursing.
   =========================================================================== */

/* Every live object is on this singly-linked list (newest first), threaded
   through Obj.gc_next; gc_live_bytes tracks the working-set size. */
static Obj* gc_objs = 0;
static size_t gc_live_bytes = 0;
static size_t gc_threshold = 0;
/* Default initial GC threshold (bytes of live working set before a collection
   is triggered). Overridable at compile time with -DRUNE_GC_THRESHOLD=N to force
   collections under a tiny heap for stress testing. */
#ifndef RUNE_GC_THRESHOLD
#define RUNE_GC_THRESHOLD (8u * 1024u * 1024u)
#endif

/* Static (non-stack) roots: the addresses of thunk/builtin cache slots. */
#define GC_MAX_STATIC_ROOTS 4096
static Value* gc_static_roots[GC_MAX_STATIC_ROOTS];
static int gc_n_static_roots = 0;
static void gc_add_root(Value* slot) {
  /* Dropping a static root would let the collector free a still-reachable cached
     value (a soundness bug), so abort rather than silently lose one. Raise
     GC_MAX_STATIC_ROOTS if a program legitimately has more memoized definitions. */
  if (gc_n_static_roots >= GC_MAX_STATIC_ROOTS) {
    fprintf(stderr, "rune-c: too many GC static roots (raise GC_MAX_STATIC_ROOTS)\n"); exit(1);
  }
  gc_static_roots[gc_n_static_roots++] = slot;
}

/* The C stack bottom, captured in main before evaluation begins. The scan walks
   from the current SP up to this address. 'volatile' so the scan is not elided. */
static void* volatile gc_stack_bottom = 0;

#include <setjmp.h>

static void gc_collect(void);

static void* gc_alloc(size_t n) {
  /* align to pointer size so the int low-bit tag is never set on a real pointer */
  size_t a = sizeof(void*);
  n = (n + a - 1) & ~(a - 1);
  if (gc_threshold == 0) gc_threshold = RUNE_GC_THRESHOLD;
  if (gc_live_bytes + n > gc_threshold && gc_stack_bottom != 0) {
    gc_collect();
    /* If still over the threshold after collecting, the live set genuinely grew;
       raise the bar (a doubling heuristic) so we do not collect on every alloc. */
    while (gc_live_bytes + n > gc_threshold) gc_threshold *= 2;
  }
  /* ZERO the whole object: the emitted code allocates an object then fills its
     slots one at a time, and each fill EXPRESSION may itself allocate (triggering
     a collection) while the object is only PARTIALLY built. Zeroed slots read as
     null (ignored by tracing), and a zeroed header has kind K_CLO + nenv 0 so a
     half-built object traces no slots — never a wild pointer through a garbage
     slot. The caller overwrites kind/counts/slots synchronously, with no alloc in
     between, before any further allocation. */
  Obj* o = (Obj*)calloc(1, n);
  if (!o) { fprintf(stderr, "rune-c: out of memory\n"); exit(1); }
  o->gc_next = gc_objs; o->gc_mark = 0;
  gc_objs = o; gc_live_bytes += n;
  /* The sweep recomputes each object's byte-size from its header (gc_obj_size),
     so no per-object size word is stored. */
  return o;
}

/* Object byte-size from its header (kind + slot count). Mirrors the mk* sizes. */
static size_t gc_obj_size(Obj* o) {
  size_t base = sizeof(Obj);
  int extra = 0;
  switch (o->kind) {
    case K_CLO:  extra = o->nenv   > 0 ? o->nenv   - 1 : 0; break;
    case K_CON:  extra = o->nfield > 0 ? o->nfield - 1 : 0; break;
    case K_PAIR: extra = 1; break; /* mkpair allocates sizeof(Obj)+sizeof(Value) => slots[0..1] */
    default:     extra = 0; break; /* K_STR, K_PTR, K_UNIT: just the header */
  }
  size_t sz = base + (size_t)extra * sizeof(Value);
  size_t a = sizeof(void*);
  return (sz + a - 1) & ~(a - 1);
}

/* If v points anywhere WITHIN a tracked heap object, return that object; else 0.
   INTERIOR pointers must count: 'apply' calls a code block with env = &clo->slots
   (a pointer PAST the closure header, not to its start), and that interior env
   pointer may be the only live reference to the closure on the stack. Treating
   only object-start pointers as roots would free a closure still in use — the
   "apply of non-closure" crash. Conservative membership test, O(live) per
   candidate word (a sorted-bounds / bitmap speedup is a later perf item). */
static Obj* gc_find_obj(Value v) {
  if (v == 0 || (v & 1)) return 0;               /* null or immediate int */
  if ((v & (Value)(sizeof(void*) - 1)) != 0) return 0; /* not word-aligned */
  char* q = (char*)v;
  for (Obj* o = gc_objs; o; o = o->gc_next) {
    char* lo = (char*)o;
    char* hi = lo + gc_obj_size(o);
    if (q >= lo && q < hi) return o;
  }
  return 0;
}

/* PRECISE slot tracing: mark v if it is a heap object, then recurse into its
   Value slots (only the slots the header declares; never code/str/handle). */
static void gc_mark_value(Value v);
static void gc_mark_obj(Obj* o) {
  if (o->gc_mark) return;
  o->gc_mark = 1;
  switch (o->kind) {
    case K_CLO:  for (int i = 0; i < o->nenv;   i++) gc_mark_value(o->slots[i]); break;
    case K_CON:  for (int i = 0; i < o->nfield; i++) gc_mark_value(o->slots[i]); break;
    case K_PAIR: gc_mark_value(o->slots[0]); gc_mark_value(o->slots[1]); break;
    default: break; /* K_STR, K_PTR, K_UNIT carry no heap pointers */
  }
}
static void gc_mark_value(Value v) {
  if (v == 0 || (v & 1)) return;                 /* null or immediate int */
  gc_mark_obj((Obj*)v);
}

/* Conservatively scan a word-range [lo, hi) for anything that looks like a
   pointer to a tracked object, and mark it (with full precise sub-tracing). */
static void gc_scan_range(char* lo, char* hi) {
  if (lo > hi) { char* t = lo; lo = hi; hi = t; }
  /* advance lo to a word boundary */
  while (((uintptr_t)lo % sizeof(void*)) != 0) lo++;
  for (char* p = lo; p + sizeof(Value) <= hi; p += sizeof(void*)) {
    Value v = *(Value*)p;
    Obj* o = gc_find_obj(v);
    if (o) gc_mark_obj(o);
  }
}

/* Collection counter, exposed for tests: a program compiled with -DRUNE_GC_STATS
   prints "rune-c: gc collections=N" to stderr at exit so a test can confirm that
   collection actually fired during the run. */
static long gc_n_collections = 0;

static void gc_collect(void) {
  gc_n_collections++;
  /* spill callee-saved registers onto the stack so the scan sees them */
  jmp_buf regs;
  if (setjmp(regs)) return; /* never longjmp'd; just forces the spill */
  (void)regs;

  /* 1. precise static roots (thunk/builtin caches) */
  for (int i = 0; i < gc_n_static_roots; i++) gc_mark_value(*gc_static_roots[i]);

  /* 2. conservative stack scan (current SP .. saved bottom) + the jmp_buf */
  char* sp = (char*)__builtin_frame_address(0);
  char* bottom = (char*)gc_stack_bottom;
  gc_scan_range(sp, bottom);
  gc_scan_range((char*)&regs, (char*)&regs + sizeof(regs));

  /* 3. sweep: free unmarked, unlink them, clear marks on survivors */
  Obj** link = &gc_objs;
  while (*link) {
    Obj* o = *link;
    if (o->gc_mark) {
      o->gc_mark = 0;
      link = &o->gc_next;
    } else {
      *link = o->gc_next;
      gc_live_bytes -= gc_obj_size(o);
      free(o);
    }
  }
}

static Value UNIT;

static Obj* obj(Value v) { return (Obj*)v; }

static Value mkint(long n) { return INT_TAG(n); }
static long as_int(Value v) {
  if (IS_INT(v)) return INT_VAL(v);
  fprintf(stderr, "rune-c: as_int on non-int\n"); exit(1);
}

static Value mkclo(Value (*code)(Value, Value*), int nenv) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj) + (nenv > 0 ? (nenv - 1) : 0) * sizeof(Value));
  o->kind = K_CLO; o->code = code; o->nenv = nenv;
  return (Value)o;
}
static void clo_set(Value c, int i, Value x) { obj(c)->slots[i] = x; }

static Value mkcon(int tag, const char* name, int nfield) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj) + (nfield > 0 ? (nfield - 1) : 0) * sizeof(Value));
  o->kind = K_CON; o->tag = tag; o->name = name; o->nfield = nfield;
  return (Value)o;
}
static void con_set(Value c, int i, Value x) { obj(c)->slots[i] = x; }
static Value con_get(Value c, int i) { return obj(c)->slots[i]; }
static int con_tag(Value c) { return obj(c)->tag; }

static Value mkpair(Value a, Value b) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj) + sizeof(Value));
  o->kind = K_PAIR; o->slots[0] = a; o->slots[1] = b;
  return (Value)o;
}
static Value pair_fst(Value p) { return obj(p)->slots[0]; }
static Value pair_snd(Value p) { return obj(p)->slots[1]; }

static Value mkstr(const char* s) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj));
  o->kind = K_STR; o->str = s;
  return (Value)o;
}
static Value mkptr(long h) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj));
  o->kind = K_PTR; o->handle = h;
  return (Value)o;
}
static Value mkunit(void) {
  Obj* o = (Obj*)gc_alloc(sizeof(Obj));
  o->kind = K_UNIT;
  return (Value)o;
}

/* apply: unpack {code, env} and indirect-call. The fast path is the only path
   this iteration (no eval/apply saturation — currying is nested closures). */
static Value apply(Value clo, Value arg) {
  if (IS_INT(clo) || obj(clo)->kind != K_CLO) {
    fprintf(stderr, "rune-c: apply of non-closure\n"); exit(1);
  }
  Obj* o = obj(clo);
  return o->code(arg, o->slots);
}

/* nat accel ops on the native int rep (saturating Peano monus). */
static Value nat_add(Value a, Value b) { return mkint(as_int(a) + as_int(b)); }
static Value nat_mul(Value a, Value b) { return mkint(as_int(a) * as_int(b)); }
static Value nat_monus(Value a, Value b) {
  long x = as_int(a), y = as_int(b);
  return mkint(x > y ? x - y : 0);
}

static void rt_abort(void) { fprintf(stderr, "rune-c: impossible (unmatched constructor tag)\n"); exit(1); }

/* show: render a value in surface style, byte-identical to the other backends.
   () for unit, the digit for an int, the constructor name + show'd non-unit
   fields (parenthesised when they contain a space), <ptr> for an opaque handle. */
static void show(Value v);
static void show_paren(Value v) {
  /* a field is parenthesised iff its rendering contains a space */
  if (!IS_INT(v) && obj(v)->kind == K_CON && obj(v)->nfield > 0) {
    /* count non-unit fields to decide if a space can appear */
    Obj* o = obj(v); int shown = 0;
    for (int i = 0; i < o->nfield; i++) if (o->slots[i] != UNIT) shown++;
    if (shown > 0) { putchar('('); show(v); putchar(')'); return; }
  }
  show(v);
}
static void show(Value v) {
  if (v == UNIT) { printf("()"); return; }
  if (IS_INT(v)) { printf("%ld", INT_VAL(v)); return; }
  Obj* o = obj(v);
  switch (o->kind) {
    case K_CLO: printf("<function>"); return;
    case K_PTR: printf("<ptr>"); return;
    case K_STR: printf("%s", o->str); return;
    case K_PAIR: {
      putchar('('); show(o->slots[0]); printf(", "); show(o->slots[1]); putchar(')');
      return;
    }
    case K_CON: {
      printf("%s", o->name);
      for (int i = 0; i < o->nfield; i++) {
        if (o->slots[i] == UNIT) continue;
        putchar(' ');
        show_paren(o->slots[i]);
      }
      return;
    }
    default: printf("()"); return;
  }
}
`

// cQuotRuntime is the erased quotient builtin group (v2): a quotient compiles to
// its carrier, so qin is the identity on its point and qlift applies the lifted
// function directly; the proof-valued members (qsound, qind) are unit-producers.
// Type/proof arguments arrive as units (no arity surgery), matching js.go's
// quotRuntime so the observable output is identical. Each is a curried closure.
const cQuotRuntime = `
/* qin A R a = a */
static Value quot_qin2(Value arg, Value* env) { (void)env; return arg; }
static Value quot_qin1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qin2, 0); }
static Value quot_qin0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qin1, 0); }
static Value def_qin(void) { return mkclo(&quot_qin0, 0); }
/* qlift A R B f resp q = f q  (captures f, then applies to q) */
static Value quot_qlift5(Value arg, Value* env) { return apply(env[0], arg); }
static Value quot_qlift4(Value arg, Value* env) { (void)arg; Value c = mkclo(&quot_qlift5, 1); clo_set(c, 0, env[0]); return c; }
static Value quot_qlift3(Value arg, Value* env) { (void)env; Value c = mkclo(&quot_qlift4, 1); clo_set(c, 0, arg); return c; }
static Value quot_qlift2(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qlift3, 0); }
static Value quot_qlift1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qlift2, 0); }
static Value quot_qlift0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qlift1, 0); }
static Value def_qlift(void) { return mkclo(&quot_qlift0, 0); }
/* qsound A R a b r = () ; qind A R P h q = () (proofs are units) */
static Value quot_unit5(Value arg, Value* env) { (void)arg; (void)env; return UNIT; }
static Value quot_qsound4(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_unit5, 0); }
static Value quot_qsound3(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qsound4, 0); }
static Value quot_qsound2(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qsound3, 0); }
static Value quot_qsound1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qsound2, 0); }
static Value quot_qsound0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qsound1, 0); }
static Value def_qsound(void) { return mkclo(&quot_qsound0, 0); }
static Value quot_qind4(Value arg, Value* env) { (void)arg; (void)env; return UNIT; }
static Value quot_qind3(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qind4, 0); }
static Value quot_qind2(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qind3, 0); }
static Value quot_qind1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qind2, 0); }
static Value quot_qind0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&quot_qind1, 0); }
static Value def_qind(void) { return mkclo(&quot_qind0, 0); }
`

// cIORuntime is the erased IO monad (R-EFFECT / C3): IO A is a deferred thunk
// (a unit-argument closure); pureIO returns a constant thunk; bindIO sequences —
// run m (apply to UNIT), feed its result to k, run that. Type arguments arrive
// as units. Mirrors js.go's ioRuntime for byte-identical observable output.
const cIORuntime = `
/* pureIO A a u = a  (a constant world thunk capturing a) */
static Value io_pure2(Value arg, Value* env) { (void)arg; return env[0]; }
static Value io_pure1(Value arg, Value* env) { (void)env; Value c = mkclo(&io_pure2, 1); clo_set(c, 0, arg); return c; }
static Value io_pure0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&io_pure1, 0); }
static Value def_pureIO(void) { return mkclo(&io_pure0, 0); }
/* bindIO A B m k u = k (m ()) ()   (captures m then k, sequences on force) */
static Value io_bind4(Value arg, Value* env) { (void)arg; /* env = {m, k} */ return apply(apply(env[1], apply(env[0], UNIT)), UNIT); }
static Value io_bind3(Value arg, Value* env) { /* env = {m} */ Value c = mkclo(&io_bind4, 2); clo_set(c, 0, env[0]); clo_set(c, 1, arg); return c; }
static Value io_bind2(Value arg, Value* env) { (void)env; Value c = mkclo(&io_bind3, 1); clo_set(c, 0, arg); return c; }
static Value io_bind1(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&io_bind2, 0); }
static Value io_bind0(Value arg, Value* env) { (void)arg; (void)env; return mkclo(&io_bind1, 0); }
static Value def_bindIO(void) { return mkclo(&io_bind0, 0); }
`
