package codegen

import (
	"fmt"
	"strings"

	"goforge.dev/rune/v3/core"
)

// Go is a third backend (B-track / multi-backend): plain Go over the SAME erased
// IR as JS/Python. Every value is `any`; a closure is `func(any) any`, applied
// through the `ap` helper (so the emit needs no inline type assertions);
// constructors build map records; eliminators are funcs with statement-body tag
// dispatch; nat is int; the unit token is nil. Each top-level definition becomes
// a thunk `name_() any` and references call it — this sidesteps Go's package-var
// initialization cycles for (mutually) recursive definitions and eliminators.
// Shadow-rule safe: a backend bug is wrong runtime output, never an unsound proof.
type Go struct{}

func (Go) Target() string { return "go" }

// Emit lowers a program to a self-contained Go source file (go run-able).
func (Go) Emit(p Program) (TargetSource, error) {
	em := &goEmitter{}
	if p.Nat != nil {
		em.natElim = p.Nat.ElimName
		em.accel = p.Nat.Ops
	}
	var b strings.Builder
	b.WriteString("// Generated by rune emit (go backend) — the erased shadow. Do not edit.\n")
	imports := "\t\"fmt\"\n\t\"math/big\"\n\t\"strings\"\n"
	if usesForeign(p, "timeNanos") {
		imports += "\t\"time\"\n"
	}
	if usesOS(p) {
		imports += "\t\"os\"\n"
	}
	if usesForeign(p, "fsqrt") || usesForeign(p, "npNorm") || usesForeign(p, "fpow") {
		imports += "\t\"math\"\n"
	}
	b.WriteString("package main\n\nimport (\n" + imports + ")\n\n")
	b.WriteString(goRuntime)
	if usesQuot(p) {
		b.WriteString(goQuotRuntime)
	}
	if usesIO(p) {
		b.WriteString(goIORuntime)
	}
	// D6 / R-EFFECT: bake the standard OS/IO host bodies when referenced.
	if usesForeign(p, "printNat") {
		b.WriteString("func printNat() any { return func(n any) any { return func(_u any) any { fmt.Println(n); return n } } }\n")
	}
	if usesForeign(p, "getNat") {
		b.WriteString("func getNat() any { return func(_u any) any { var x int64; fmt.Scan(&x); return big.NewInt(x) } }\n")
	}
	if usesForeign(p, "timeNanos") {
		b.WriteString("func timeNanos() any { return func(_u any) any { return big.NewInt(time.Now().UnixNano()) } }\n")
	}
	if usesForeign(p, "readLineCode") {
		b.WriteString("func readLineCode() any { return func(_u any) any { var s string; fmt.Scan(&s); n := big.NewInt(1); for i := len(s) - 1; i >= 0; i-- { n.Mul(n, big.NewInt(256)); n.Add(n, big.NewInt(int64(s[i]))) }; return n } }\n")
	}
	// D6 net/fs: the packed-String codec + env/file host bodies, over bare Nat codes.
	if usesFileEnv(p) {
		b.WriteString("func __s2h(v any) string { b := new(big.Int).Set(v.(*big.Int)); one := big.NewInt(1); m := big.NewInt(256); var sb []byte; for b.Cmp(one) > 0 { r := new(big.Int); b.DivMod(b, m, r); sb = append(sb, byte(r.Int64())) }; return string(sb) }\n")
		b.WriteString("func __h2s(v string) any { n := big.NewInt(1); m := big.NewInt(256); for i := len(v) - 1; i >= 0; i-- { n.Mul(n, m); n.Add(n, big.NewInt(int64(v[i]))) }; return n }\n")
	}
	if usesForeign(p, "getEnvCode") {
		b.WriteString("func getEnvCode() any { return func(c any) any { return func(_u any) any { return __h2s(os.Getenv(__s2h(c))) } } }\n")
	}
	if usesForeign(p, "readFileCode") {
		b.WriteString("func readFileCode() any { return func(c any) any { return func(_u any) any { d, err := os.ReadFile(__s2h(c)); if err != nil { return big.NewInt(1) }; return __h2s(string(d)) } } }\n")
	}
	if usesForeign(p, "writeFileCode") {
		b.WriteString("func writeFileCode() any { return func(p any) any { return func(c any) any { return func(_u any) any { os.WriteFile(__s2h(p), []byte(__s2h(c)), 0644); return c } } } }\n")
	}
	if usesForeign(p, "printStrCode") {
		b.WriteString("func printStrCode() any { return func(c any) any { return func(_u any) any { fmt.Println(__s2h(c)); return c } } }\n")
	}
	// D6 argv + process.
	if usesForeign(p, "argCountCode") {
		b.WriteString("func argCountCode() any { return func(_u any) any { return big.NewInt(int64(len(os.Args) - 1)) } }\n")
	}
	if usesForeign(p, "argAtCode") {
		b.WriteString("func argAtCode() any { return func(i any) any { return func(_u any) any { idx := int(i.(*big.Int).Int64()) + 1; if idx < len(os.Args) { return __h2s(os.Args[idx]) }; return big.NewInt(1) } } }\n")
	}
	if usesForeign(p, "exitWith") {
		b.WriteString("func exitWith() any { return func(n any) any { return func(_u any) any { os.Exit(int(n.(*big.Int).Int64())); return nil } } }\n")
	}
	// D3 machine floats (f64) + the BLAS dot kernel — a Float is a boxed float64.
	// `Float` is a foreign type surviving erasure as ok/err's type arg (runtime-irrelevant).
	if usesForeign(p, "Float") {
		b.WriteString("func Float() any { return nil }\n")
	}
	if usesForeign(p, "fromNat") {
		b.WriteString("func fromNat() any { return func(n any) any { f, _ := new(big.Float).SetInt(n.(*big.Int)).Float64(); return f } }\n")
	}
	if usesForeign(p, "fadd") {
		b.WriteString("func fadd() any { return func(a any) any { return func(b any) any { return a.(float64) + b.(float64) } } }\n")
	}
	if usesForeign(p, "fsub") {
		b.WriteString("func fsub() any { return func(a any) any { return func(b any) any { return a.(float64) - b.(float64) } } }\n")
	}
	if usesForeign(p, "fmul") {
		b.WriteString("func fmul() any { return func(a any) any { return func(b any) any { return a.(float64) * b.(float64) } } }\n")
	}
	if usesForeign(p, "fdiv") {
		b.WriteString("func fdiv() any { return func(a any) any { return func(b any) any { return a.(float64) / b.(float64) } } }\n")
	}
	if usesForeign(p, "fabsP") {
		b.WriteString("func fabsP() any { return func(x any) any { v := x.(float64); if v < 0 { return -v }; return v } }\n")
	}
	if usesForeign(p, "floatToNat") {
		b.WriteString("func floatToNat() any { return func(x any) any { return big.NewInt(int64(x.(float64))) } }\n")
	}
	if usesForeign(p, "fleqN") {
		b.WriteString("func fleqN() any { return func(a any) any { return func(b any) any { if a.(float64) <= b.(float64) { return big.NewInt(1) }; return big.NewInt(0) } } }\n")
	}
	if usesForeign(p, "fsqrt") {
		b.WriteString("func fsqrt() any { return func(x any) any { return math.Sqrt(x.(float64)) } }\n")
	}
	if usesForeign(p, "fpow") {
		b.WriteString("func fpow() any { return func(b any) any { return func(e any) any { return math.Pow(b.(float64), e.(float64)) } } }\n")
	}
	if usesForeign(p, "dot2") {
		b.WriteString("func dot2() any { return func(a0 any) any { return func(a1 any) any { return func(b0 any) any { return func(b1 any) any { return a0.(float64)*b0.(float64) + a1.(float64)*b1.(float64) } } } } }\n")
	}
	// Arbitrary-length dot: walk two Rune FLists (fcons = tag 1, head args[0], tail
	// args[1]) summing products — the portable reference (native backends use cblas).
	if usesForeign(p, "dotList") {
		b.WriteString("func dotList() any { return func(xs any) any { return func(ys any) any { s := 0.0; for xs.(map[string]any)[\"tag\"] == 1 && ys.(map[string]any)[\"tag\"] == 1 { mx := xs.(map[string]any); my := ys.(map[string]any); s += mx[\"args\"].([]any)[0].(float64) * my[\"args\"].([]any)[0].(float64); xs = mx[\"args\"].([]any)[1]; ys = my[\"args\"].([]any)[1] }; return s } } }\n")
	}
	// D4 interop: npDot is the uniform dot CAPABILITY (NumPy on py, OpenBLAS on C/LLVM);
	// on the other source backends it is the portable reference floor.
	if usesForeign(p, "npDot") {
		b.WriteString("func npDot() any { return func(xs any) any { return func(ys any) any { s := 0.0; for xs.(map[string]any)[\"tag\"] == 1 && ys.(map[string]any)[\"tag\"] == 1 { mx := xs.(map[string]any); my := ys.(map[string]any); s += mx[\"args\"].([]any)[0].(float64) * my[\"args\"].([]any)[0].(float64); xs = mx[\"args\"].([]any)[1]; ys = my[\"args\"].([]any)[1] }; return s } } }\n")
	}
	// D4 interop: npMean — the reference floor (hand sum/count); py serves real numpy.mean.
	if usesForeign(p, "npMean") {
		b.WriteString("func npMean() any { return func(xs any) any { s := 0.0; n := 0; for xs.(map[string]any)[\"tag\"] == 1 { mx := xs.(map[string]any); s += mx[\"args\"].([]any)[0].(float64); n++; xs = mx[\"args\"].([]any)[1] }; if n > 0 { return s / float64(n) }; return 0.0 } }\n")
	}
	// Matrix product sum: flat row-major A (m×k), B (k×n); sum all entries of A·B — the
	// portable triple-loop reference (native backends use cblas_dgemm).
	if usesForeign(p, "gemmSum") {
		b.WriteString("func gemmSum() any { return func(m any) any { return func(k any) any { return func(n any) any { return func(A any) any { return func(B any) any { var a, b2 []float64; for t := A; t.(map[string]any)[\"tag\"] == 1; { mt := t.(map[string]any); a = append(a, mt[\"args\"].([]any)[0].(float64)); t = mt[\"args\"].([]any)[1] }; for t := B; t.(map[string]any)[\"tag\"] == 1; { mt := t.(map[string]any); b2 = append(b2, mt[\"args\"].([]any)[0].(float64)); t = mt[\"args\"].([]any)[1] }; M := int(m.(*big.Int).Int64()); K := int(k.(*big.Int).Int64()); N := int(n.(*big.Int).Int64()); s := 0.0; for i := 0; i < M; i++ { for j := 0; j < N; j++ { for l := 0; l < K; l++ { s += a[i*K+l] * b2[l*N+j] } } }; return s } } } } } }\n")
	}
	// D4 interop: npNorm — the sqrt(sum of squares) floor; py serves numpy.linalg.norm.
	if usesForeign(p, "npNorm") {
		b.WriteString("func npNorm() any { return func(xs any) any { s := 0.0; for t := xs; t.(map[string]any)[\"tag\"] == 1; { mt := t.(map[string]any); x := mt[\"args\"].([]any)[0].(float64); s += x * x; t = mt[\"args\"].([]any)[1] }; return math.Sqrt(s) } }\n")
	}
	// D4 interop: npMax — the fold-max reference floor (base 0); py serves real numpy.max.
	if usesForeign(p, "npMax") {
		b.WriteString("func npMax() any { return func(xs any) any { m := 0.0; first := true; for t := xs; t.(map[string]any)[\"tag\"] == 1; { mt := t.(map[string]any); x := mt[\"args\"].([]any)[0].(float64); if first || x > m { m = x; first = false }; t = mt[\"args\"].([]any)[1] }; return m } }\n")
	}
	// D4 interop: npVar — the 2-pass reference floor (mean, then mean of sq deviations).
	if usesForeign(p, "npVar") {
		b.WriteString("func npVar() any { return func(xs any) any { s := 0.0; n := 0; for t := xs; t.(map[string]any)[\"tag\"] == 1; { mt := t.(map[string]any); s += mt[\"args\"].([]any)[0].(float64); n++; t = mt[\"args\"].([]any)[1] }; m := 0.0; if n > 0 { m = s / float64(n) }; v := 0.0; for u := xs; u.(map[string]any)[\"tag\"] == 1; { mu := u.(map[string]any); d := mu[\"args\"].([]any)[0].(float64) - m; v += d * d; u = mu[\"args\"].([]any)[1] }; if n > 0 { return v / float64(n) }; return 0.0 } }\n")
	}
	// D4 interop: npMatSum — the triple-loop reference floor; py serves real numpy matmul.
	if usesForeign(p, "npMatSum") {
		b.WriteString("func npMatSum() any { return func(m any) any { return func(k any) any { return func(n any) any { return func(A any) any { return func(B any) any { var a, b2 []float64; for t := A; t.(map[string]any)[\"tag\"] == 1; { mt := t.(map[string]any); a = append(a, mt[\"args\"].([]any)[0].(float64)); t = mt[\"args\"].([]any)[1] }; for t := B; t.(map[string]any)[\"tag\"] == 1; { mt := t.(map[string]any); b2 = append(b2, mt[\"args\"].([]any)[0].(float64)); t = mt[\"args\"].([]any)[1] }; M := int(m.(*big.Int).Int64()); K := int(k.(*big.Int).Int64()); N := int(n.(*big.Int).Int64()); s := 0.0; for i := 0; i < M; i++ { for j := 0; j < N; j++ { for l := 0; l < K; l++ { s += a[i*K+l] * b2[l*N+j] } } }; return s } } } } } }\n")
	}
	for _, d := range p.Datas {
		if p.Nat != nil && d.ElimName == p.Nat.ElimName {
			emitNatGo(&b, *p.Nat)
			continue
		}
		for _, c := range d.Ctors {
			emitCtorGo(&b, c)
		}
		// B2 / R-IR: the eliminator is lowered to the shared IR once (LowerElim)
		// and emitted as an ordinary thunk — no eliminator-specific backend code.
		fmt.Fprintf(&b, "func %s() any { return %s }\n", goThunk(d.ElimName), em.expr(LowerElim(d), nil))
	}
	for _, def := range p.Defs {
		fmt.Fprintf(&b, "func %s() any { return %s }\n", goThunk(def.Name), em.expr(def.Body, nil))
	}
	b.WriteString("func main() {\n")
	if p.Main != "" {
		mainExpr := goThunk(p.Main) + "()"
		if p.IOMain {
			// An IO main is a deferred world thunk (unit -> A): force by applying nil.
			mainExpr = fmt.Sprintf("ap(%s, nil)", mainExpr)
		}
		fmt.Fprintf(&b, "\tfmt.Println(_show(%s))\n", mainExpr)
	}
	b.WriteString("}\n")
	return TargetSource(b.String()), nil
}

func emitCtorGo(b *strings.Builder, c CtorSpec) {
	fmt.Fprintf(b, "func %s() any { return ", goThunk(c.Name))
	for i := 0; i < c.Arity; i++ {
		fmt.Fprintf(b, "func(a%d any) any { return ", i)
	}
	args := make([]string, c.Arity)
	for i := range args {
		args[i] = fmt.Sprintf("a%d", i)
	}
	fmt.Fprintf(b, "map[string]any{\"tag\": %d, \"name\": %q, \"args\": []any{%s}}", c.Tag, c.Name, strings.Join(args, ", "))
	b.WriteString(strings.Repeat(" }", c.Arity))
	b.WriteString(" }\n")
}

func emitNatGo(b *strings.Builder, n NatSpec) {
	fmt.Fprintf(b, "func %s() any { return big.NewInt(0) }\n", goThunk(n.Zero))
	fmt.Fprintf(b, "func %s() any { return func(x any) any { return new(big.Int).Add(x.(*big.Int), big.NewInt(1)) } }\n", goThunk(n.Succ))
	fmt.Fprintf(b, "func %s() any { return func(m any) any { return func(c0 any) any { return func(c1 any) any { return func(x any) any { return _natElim(c0, c1, x) } } } } }\n", goThunk(n.ElimName))
}

type goEmitter struct {
	natElim string
	accel   map[string]core.NatOp
}

func (em *goEmitter) expr(t Ir, env []string) string {
	switch x := t.(type) {
	case IVar:
		if x.Idx < len(env) {
			return env[x.Idx]
		}
		return fmt.Sprintf("_v%d", x.Idx)
	case IGlobal:
		return goThunk(x.Name) + "()"
	case IForeign:
		// Host-linked accessor: the host defines `func <name>() any { return … }`.
		// A plain name (no _d suffix) keeps the FFI ABI distinct from def thunks.
		return goLocal(x.Name) + "()"
	case IUnit:
		return "nil"
	case ILit:
		// Native host literal marshalled at the FFI boundary (B4): a Go int or
		// string literal (both flow as `any`).
		if x.Kind == LitNat {
			// C7 / R-NUM: a compressed numeral deploys as a native *big.Int (boxed
			// in `any`) — the SAME representation NatSpec gives nat (`big.NewInt(0)`,
			// `+1`), arbitrary precision, O(1) source instead of a succ-chain.
			return fmt.Sprintf("any(_bigFromDec(%q))", x.Nat)
		}
		if x.Kind == LitStr {
			return fmt.Sprintf("any(%q)", x.Str)
		}
		if x.Kind == LitPtr {
			// Opaque host pointer: a distinct named type so it never aliases an
			// int, and _show renders it as a fixed marker rather than its handle.
			return fmt.Sprintf("any(_ptr(%d))", x.Int)
		}
		return fmt.Sprintf("any(%d)", x.Int)
	case ILam:
		n := freshGo(x.Name, env)
		return fmt.Sprintf("func(%s any) any { return %s }", n, em.expr(x.Body, prepend(n, env)))
	case IApp:
		if out, ok := em.accelDispatch(x, env); ok {
			return out
		}
		if out, ok := em.natDispatch(x, env); ok {
			return out
		}
		return fmt.Sprintf("ap(%s, %s)", em.expr(x.Fn, env), em.expr(x.Arg, env))
	case ILet:
		n := freshGo(x.Name, env)
		return fmt.Sprintf("func(%s any) any { return %s }(%s)", n, em.expr(x.Body, prepend(n, env)), em.expr(x.Val, env))
	case IPair:
		return fmt.Sprintf("[]any{%s, %s}", em.expr(x.A, env), em.expr(x.B, env))
	case IFst:
		return fmt.Sprintf("(%s).([]any)[0]", em.expr(x.P, env))
	case ISnd:
		return fmt.Sprintf("(%s).([]any)[1]", em.expr(x.P, env))
	case IField:
		return fmt.Sprintf("(%s).(map[string]any)[\"args\"].([]any)[%d]", em.expr(x.Scrut, env), x.Index)
	case ICase:
		// IIFE over a statement switch on the scrutinee tag.
		scrut := em.expr(x.Scrut, env)
		var b strings.Builder
		fmt.Fprintf(&b, "func() any { switch (%s).(map[string]any)[\"tag\"].(int) {", scrut)
		for _, arm := range x.Arms {
			fmt.Fprintf(&b, " case %d: return %s;", arm.Tag, em.expr(arm.Body, env))
		}
		b.WriteString(" }; return _impossible() }()")
		return b.String()
	default:
		panic("codegen(go): unknown IR node")
	}
}

// accelDispatch emits a registered accel-op def on two args as native int
// arithmetic (C7 / R-NUM Decision 4) through the `_natAdd`/`_natMul`/`_natMonus`
// runtime helpers (which unbox the `any`-wrapped ints, compute, and rebox).
// Monus is the saturating Peano monus (floors at 0). The int representation is
// the SAME NatSpec gives nat (`0`, `x.(int)+1`), so the result is interchangeable.
func (em *goEmitter) accelDispatch(app IApp, env []string) (string, bool) {
	op, a, b, ok := accelMatch(app, em.accel)
	if !ok {
		return "", false
	}
	ea, eb := em.expr(a, env), em.expr(b, env)
	switch op {
	case core.NatOpAdd:
		return fmt.Sprintf("_natAdd(%s, %s)", ea, eb), true
	case core.NatOpMul:
		return fmt.Sprintf("_natMul(%s, %s)", ea, eb), true
	case core.NatOpMonus:
		return fmt.Sprintf("_natMonus(%s, %s)", ea, eb), true
	case core.NatOpDiv:
		return fmt.Sprintf("_natDiv(%s, %s)", ea, eb), true
	case core.NatOpMod:
		return fmt.Sprintf("_natMod(%s, %s)", ea, eb), true
	}
	return "", false
}

func (em *goEmitter) natDispatch(app IApp, env []string) (string, bool) {
	if em.natElim == "" {
		return "", false
	}
	var args []Ir
	t := Ir(app)
	for {
		a, ok := t.(IApp)
		if !ok {
			break
		}
		args = append([]Ir{a.Arg}, args...)
		t = a.Fn
	}
	g, ok := t.(IGlobal)
	if !ok || g.Name != em.natElim || len(args) < 4 {
		return "", false
	}
	c1lam, ok := args[2].(ILam)
	if !ok {
		return "", false
	}
	inner, ok := c1lam.Body.(ILam)
	if !ok || usesVar(inner.Body, 0) {
		return "", false
	}
	out := fmt.Sprintf("_natD(%s, %s, %s)",
		em.expr(args[1], env), em.expr(args[2], env), em.expr(args[3], env))
	for _, extra := range args[4:] {
		out = fmt.Sprintf("ap(%s, %s)", out, em.expr(extra, env))
	}
	return out, true
}

func freshGo(hint string, env []string) string {
	n := goLocal(hint)
	for {
		clash := false
		for _, e := range env {
			if e == n {
				clash = true
				break
			}
		}
		if !clash {
			return n
		}
		n += "_"
	}
}

// goThunk is the package-level thunk name for a definition (suffix _ avoids
// clashing with Go keywords/builtins and the runtime helpers).
func goThunk(n string) string { return goLocal(n) + "_d" }

func goLocal(n string) string {
	if m, ok := jsOpNames[n]; ok {
		return m
	}
	if i := strings.IndexByte(n, '$'); i > 0 {
		if m, ok := jsOpNames[n[:i]]; ok {
			n = m + n[i:]
		}
	}
	n = strings.ReplaceAll(n, "'", "_")
	n = strings.ReplaceAll(n, "$", "_")
	n = strings.ReplaceAll(n, ".", "_")
	if n == "" {
		n = "_x"
	}
	// leading digit or empty → prefix.
	if c := n[0]; c >= '0' && c <= '9' {
		n = "_" + n
	}
	return n
}

const goRuntime = `type _ptr int64 // opaque host pointer (B4): never shown structurally
func ap(f, x any) any { return f.(func(any) any)(x) }
// builtin-nat is an arbitrary-precision *big.Int (naive: no small-int fast path).
func _bigFromDec(s string) *big.Int { z, _ := new(big.Int).SetString(s, 10); return z }
func _natElim(c0, c1, x any) any {
	acc := c0
	n := x.(*big.Int)
	for k := new(big.Int); k.Cmp(n) < 0; k.Add(k, big.NewInt(1)) {
		acc = ap(ap(c1, new(big.Int).Set(k)), acc)
	}
	return acc
}
func _natD(c0, c1, x any) any {
	n := x.(*big.Int)
	if n.Sign() == 0 {
		return c0
	}
	return ap(ap(c1, new(big.Int).Sub(n, big.NewInt(1))), nil)
}
func _natAdd(a, b any) any { return new(big.Int).Add(a.(*big.Int), b.(*big.Int)) }
func _natMul(a, b any) any { return new(big.Int).Mul(a.(*big.Int), b.(*big.Int)) }
func _natMonus(a, b any) any {
	x, y := a.(*big.Int), b.(*big.Int)
	if x.Cmp(y) > 0 {
		return new(big.Int).Sub(x, y)
	}
	return big.NewInt(0)
}
func _natDiv(a, b any) any {
	y := b.(*big.Int)
	if y.Sign() == 0 {
		return big.NewInt(0)
	}
	return new(big.Int).Quo(a.(*big.Int), y)
}
func _natMod(a, b any) any {
	y := b.(*big.Int)
	if y.Sign() == 0 {
		return new(big.Int).Set(a.(*big.Int))
	}
	return new(big.Int).Rem(a.(*big.Int), y)
}
func _impossible() any { panic("impossible: unmatched constructor tag") }
func _show(v any) string {
	switch t := v.(type) {
	case nil:
		return "()"
	case _ptr:
		return "<ptr>"
	case *big.Int:
		return t.String()
	case int:
		return fmt.Sprintf("%d", t)
	case string:
		return t
	case bool:
		if t {
			return "true"
		}
		return "false"
	case []any:
		parts := make([]string, len(t))
		for i, a := range t {
			parts[i] = _show(a)
		}
		return "(" + strings.Join(parts, ", ") + ")"
	case map[string]any:
		s := t["name"].(string)
		for _, a := range t["args"].([]any) {
			if a == nil {
				continue
			}
			r := _show(a)
			if strings.Contains(r, " ") {
				r = "(" + r + ")"
			}
			s += " " + r
		}
		return s
	default:
		return fmt.Sprintf("%v", t)
	}
}
`

// goIORuntime is the erased IO monad (R-EFFECT / C3): IO A is a deferred thunk
// encoded as a unit-argument closure, so `ap` forces it by applying nil; pureIO
// returns a constant thunk, bindIO sequences. Type arguments arrive as units.
const goIORuntime = `func pureIO_d() any { return func(_A any) any { return func(a any) any { return func(_u any) any { return a } } } }
func bindIO_d() any { return func(_A any) any { return func(_B any) any { return func(m any) any { return func(k any) any { return func(_u any) any { return ap(ap(k, ap(m, nil)), nil) } } } } } }
`

const goQuotRuntime = `func qin_d() any { return func(a any) any { return func(r any) any { return func(x any) any { return x } } } }
func qsound_d() any { return func(a any) any { return func(r any) any { return func(x any) any { return func(y any) any { return func(p any) any { return nil } } } } } }
func qlift_d() any { return func(a any) any { return func(r any) any { return func(b any) any { return func(f any) any { return func(resp any) any { return func(q any) any { return ap(f, q) } } } } } } }
func qind_d() any { return func(a any) any { return func(r any) any { return func(p any) any { return func(h any) any { return func(q any) any { return nil } } } } } }
`
