package codegen

import (
	"fmt"
	"strings"
)

// EmitLibrary lowers a Rune program to an importable Go package. The first ABI is
// intentionally raw: exported wrappers accept curried runtime values as any. Typed
// wrappers can be layered once Furnace fixes the host boundary types.
func (Go) EmitLibrary(p Program, spec BuildSpec) (ArtifactSet, error) {
	if len(spec.Exports) == 0 {
		return ArtifactSet{}, fmt.Errorf("go library build needs at least one export")
	}
	defs := map[string]DefSpec{}
	for _, d := range p.Defs {
		defs[d.Name] = d
	}
	for _, ex := range spec.Exports {
		if _, ok := defs[ex.RuneName]; !ok {
			return ArtifactSet{}, fmt.Errorf("go library export %q is not an emitted definition", ex.RuneName)
		}
	}

	lp := p
	lp.Main = ""
	lp.IOMain = false
	src, err := (Go{}).Emit(lp)
	if err != nil {
		return ArtifactSet{}, err
	}
	pkg := goPackageFromModule(spec.Module)
	text := string(src)
	text = strings.Replace(text, "Generated by rune emit (go backend)", "Generated by rune build (go backend, library)", 1)
	text = strings.Replace(text, "package main\n\n", "package "+pkg+"\n\n", 1)
	text = strings.TrimSuffix(text, "func main() {\n}\n")
	var b strings.Builder
	b.WriteString(text)
	b.WriteString("\n")
	b.WriteString("// Show renders a raw Rune runtime value using the backend's canonical show.\n")
	b.WriteString("func Show(v any) string { return _show(v) }\n")
	for _, ex := range spec.Exports {
		host := goExportName(ex)
		thunk := goThunk(ex.RuneName)
		fmt.Fprintf(&b, "\nfunc %s(args ...any) any {\n", host)
		fmt.Fprintf(&b, "\tv := %s()\n", thunk)
		b.WriteString("\tfor _, a := range args {\n")
		b.WriteString("\t\tv = ap(v, a)\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn v\n")
		b.WriteString("}\n")
	}
	file := pkg + ".go"
	return ArtifactSet{
		Target: "go",
		Kind:   BuildLibrary,
		Artifacts: []Artifact{{
			Path: file,
			Role: ArtifactSource,
			Data: []byte(b.String()),
		}},
		Link: &LinkHint{Args: []string{"go", "test", "./..."}},
	}, nil
}

func goPackageFromModule(module string) string {
	if module == "" {
		return "rune"
	}
	module = strings.TrimSuffix(module, "/")
	if i := strings.LastIndex(module, "/"); i >= 0 {
		module = module[i+1:]
	}
	return goIdent(module, false)
}

func goExportName(ex Export) string {
	name := ex.HostName
	if name == "" {
		name = ex.RuneName
		if i := strings.LastIndexAny(name, ".-/"); i >= 0 {
			name = name[i+1:]
		}
	}
	return goIdent(name, true)
}

func goIdent(name string, exported bool) string {
	var b strings.Builder
	for i := 0; i < len(name); i++ {
		ch := name[i]
		if ch >= 'a' && ch <= 'z' || ch >= 'A' && ch <= 'Z' || ch >= '0' && ch <= '9' || ch == '_' {
			b.WriteByte(ch)
		} else {
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" {
		out = "rune"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	if exported && out[0] >= 'a' && out[0] <= 'z' {
		out = string(out[0]-'a'+'A') + out[1:]
	}
	if !exported && out[0] >= 'A' && out[0] <= 'Z' {
		out = string(out[0]-'A'+'a') + out[1:]
	}
	return out
}
