package codegen

import (
	"fmt"
	"strings"
)

// JS is the v1 backend: boring JavaScript. Everything is curried one-argument
// arrow functions; constructors build {tag, args} records; eliminators are
// switch-dispatch with recursive calls for the inductive hypotheses; the
// erased token is null. The output runs under node with no dependencies.
type JS struct{}

func (JS) Target() string { return "js" }

// Emit lowers a program to a self-contained JavaScript source file.
func (JS) Emit(p Program) (TargetSource, error) {
	var b strings.Builder
	b.WriteString("// Generated by rune emit — the erased shadow of checked core. Do not edit.\n")
	b.WriteString("'use strict';\n")
	b.WriteString("const $unit = null;\n")

	if usesQuot(p) {
		b.WriteString(quotRuntime)
	}
	for _, d := range p.Datas {
		if p.Nat != nil && d.ElimName == p.Nat.ElimName {
			emitNat(&b, *p.Nat)
			continue
		}
		for _, c := range d.Ctors {
			emitCtor(&b, c)
		}
		emitElim(&b, d)
	}
	for _, def := range p.Defs {
		fmt.Fprintf(&b, "const %s = %s;\n", jsName(def.Name), jsExpr(def.Body, nil))
	}
	if p.Main != "" {
		b.WriteString(showRuntime)
		fmt.Fprintf(&b, "console.log($show(%s));\n", jsName(p.Main))
	}
	return TargetSource(b.String()), nil
}

// emitCtor writes a curried constructor: parameters (erased) and arguments
// are all collected; the record keeps every argument so the eliminator can
// slice off the parameter prefix uniformly.
func emitCtor(b *strings.Builder, c CtorSpec) {
	fmt.Fprintf(b, "const %s = ", jsName(c.Name))
	for i := 0; i < c.Arity; i++ {
		fmt.Fprintf(b, "a%d => ", i)
	}
	args := make([]string, c.Arity)
	for i := range args {
		args[i] = fmt.Sprintf("a%d", i)
	}
	fmt.Fprintf(b, "({tag: %d, name: %q, args: [%s]});\n", c.Tag, c.Name, strings.Join(args, ", "))
}

// emitNat writes the builtin-nat group as BigInt arithmetic (rung 6): zero is
// 0n, succ adds one, and the eliminator is a loop — acc starts at the zero
// case and folds the succ case k times, exactly the iota-rule unrolled. The
// motive is erased and ignored.
func emitNat(b *strings.Builder, n NatSpec) {
	fmt.Fprintf(b, "const %s = 0n;\n", jsName(n.Zero))
	fmt.Fprintf(b, "const %s = x => x + 1n;\n", jsName(n.Succ))
	fmt.Fprintf(b, "const %s = m => c0 => c1 => x => {\n", jsName(n.ElimName))
	b.WriteString("  let acc = c0;\n")
	b.WriteString("  for (let k = 0n; k < x; k++) acc = c1(k)(acc);\n")
	b.WriteString("  return acc;\n")
	b.WriteString("};\n")
}

// emitElim writes the eliminator: params, motive, one case per constructor,
// scrutinee; dispatch on tag, apply the case to the constructor's own
// arguments and then to the recursive eliminations.
func emitElim(b *strings.Builder, d DataSpec) {
	fmt.Fprintf(b, "const %s = ", jsName(d.ElimName))
	n := len(d.Ctors)
	var params []string
	for i := 0; i < d.NumParams; i++ {
		p := fmt.Sprintf("p%d", i)
		params = append(params, p)
		fmt.Fprintf(b, "%s => ", p)
	}
	b.WriteString("m => ")
	for i := 0; i < n; i++ {
		fmt.Fprintf(b, "c%d => ", i)
	}
	b.WriteString("x => {\n  switch (x.tag) {\n")
	for i, c := range d.Ctors {
		fmt.Fprintf(b, "  case %d: return ", i)
		// The constructor record holds params + own args; own args start at
		// NumParams.
		expr := fmt.Sprintf("c%d", i)
		own := c.Arity - d.NumParams
		for j := 0; j < own; j++ {
			expr = fmt.Sprintf("%s(x.args[%d])", expr, d.NumParams+j)
		}
		for j := 0; j < own; j++ {
			if d.Rec[i][j] {
				rec := jsName(d.ElimName)
				for _, p := range params {
					rec = fmt.Sprintf("%s(%s)", rec, p)
				}
				rec = fmt.Sprintf("%s(m)", rec)
				for k := 0; k < n; k++ {
					rec = fmt.Sprintf("%s(c%d)", rec, k)
				}
				expr = fmt.Sprintf("%s(%s(x.args[%d]))", expr, rec, d.NumParams+j)
			}
		}
		fmt.Fprintf(b, "%s;\n", expr)
	}
	b.WriteString("  }\n  throw new Error('impossible: unmatched constructor tag ' + x.tag);\n};\n")
}

// jsExpr renders an IR term; env carries binder names innermost-first.
func jsExpr(t Ir, env []string) string {
	switch x := t.(type) {
	case IVar:
		if x.Idx < len(env) {
			return env[x.Idx]
		}
		return fmt.Sprintf("$v%d", x.Idx)
	case IGlobal:
		return jsName(x.Name)
	case IUnit:
		return "$unit"
	case ILam:
		n := freshJS(x.Name, env)
		return fmt.Sprintf("(%s => %s)", n, jsExpr(x.Body, prepend(n, env)))
	case IApp:
		return fmt.Sprintf("%s(%s)", jsExpr(x.Fn, env), jsExpr(x.Arg, env))
	case ILet:
		n := freshJS(x.Name, env)
		return fmt.Sprintf("((%s) => %s)(%s)", n, jsExpr(x.Body, prepend(n, env)), jsExpr(x.Val, env))
	default:
		panic("codegen: unknown IR node")
	}
}

func prepend(n string, env []string) []string {
	out := make([]string, 0, len(env)+1)
	out = append(out, n)
	return append(out, env...)
}

// jsOpNames maps the operator definition names of GRAMMAR §3 (symbolic
// identifiers, invalid in JS) to mangled JS identifiers.
var jsOpNames = map[string]string{
	"+": "$add",
	"-": "$sub",
	"*": "$mul",
	"/": "$div",
	"%": "$mod",
}

// jsName sanitizes a rune identifier into a JS one. Alphabetic rune identifiers
// are already close (letters, digits, _, '); primes become $. Operator names
// mangle through jsOpNames.
func jsName(n string) string {
	if m, ok := jsOpNames[n]; ok {
		return m
	}
	n = strings.ReplaceAll(n, "'", "$")
	if n == "" {
		n = "$x"
	}
	if jsReserved[n] {
		return "$" + n
	}
	return n
}

func freshJS(hint string, env []string) string {
	n := jsName(hint)
	if n == "" || n == "_" {
		n = "$x"
	}
	for {
		clash := false
		for _, e := range env {
			if e == n {
				clash = true
				break
			}
		}
		if !clash {
			return n
		}
		n += "$"
	}
}

var jsReserved = map[string]bool{
	"await": true, "break": true, "case": true, "catch": true, "class": true,
	"const": true, "continue": true, "debugger": true, "default": true,
	"delete": true, "do": true, "else": true, "enum": true, "export": true,
	"extends": true, "false": true, "finally": true, "for": true,
	"function": true, "if": true, "import": true, "in": true,
	"instanceof": true, "new": true, "null": true, "return": true,
	"super": true, "switch": true, "this": true, "throw": true, "true": true,
	"try": true, "typeof": true, "var": true, "void": true, "while": true,
	"with": true, "yield": true, "let": true, "static": true,
}

// quotRuntime is the erased quotient builtin group (v2): a quotient compiles
// to its carrier, so qin is the identity on its point, qlift applies the
// lifted function directly, and the proof-valued members (qsound, qind) are
// unit-producers. Type and proof arguments arrive as units (no arity surgery).
const quotRuntime = `const qin = A => R => a => a;
const qsound = A => R => a => b => r => $unit;
const qlift = A => R => B => f => resp => q => f(q);
const qind = A => R => P => h => q => $unit;
`

// usesQuot reports whether any emitted definition references a quotient
// builtin by name, so the runtime is included only when needed.
func usesQuot(p Program) bool {
	names := map[string]bool{"qin": true, "qsound": true, "qlift": true, "qind": true}
	var walk func(Ir) bool
	walk = func(t Ir) bool {
		switch x := t.(type) {
		case IGlobal:
			return names[x.Name]
		case ILam:
			return walk(x.Body)
		case IApp:
			return walk(x.Fn) || walk(x.Arg)
		case ILet:
			return walk(x.Val) || walk(x.Body)
		default:
			return false
		}
	}
	for _, d := range p.Defs {
		if walk(d.Body) {
			return true
		}
	}
	return false
}

// showRuntime renders constructor values back in surface style for the
// program's printed result.
const showRuntime = `function $show(v) {
  if (v === null) return "()";
  if (typeof v === "function") return "<function>";
  if (typeof v === "bigint") return v.toString();
  if (v && typeof v === "object" && "tag" in v) {
    let s = v.name;
    for (const a of v.args) {
      if (a === null) continue;
      const r = $show(a);
      s += " " + (r.includes(" ") ? "(" + r + ")" : r);
    }
    return s;
  }
  return String(v);
}
`
