package codegen

import (
	"fmt"
	"sort"
	"strings"

	"goforge.dev/rune/v3/core"
)

// LL is the SECOND NATIVE backend (telos-2 / M4, the B3+ "fan out"): it emits
// LLVM IR TEXT over the CLOSURE-CONVERTED IR (codegen/closure.go), compiled and
// run via `clang program.ll runtime.c -o exe`. Where the C backend (codegen/c.go,
// the ORACLE) emits portable C that `cc` lowers, this backend emits the program
// LOGIC as genuine LLVM IR — each CodeBlock is an LLVM `define`, MkClosure is an
// alloc + stores, AppClosure loads a code pointer and indirect-calls, CCase is an
// LLVM `switch`, CField is a runtime field load, CLit{LitNat} is an immediate.
//
// RUNTIME STRATEGY (pragmatic, low-risk — R-NATIVE stage 2): the LLVM backend
// REUSES the C runtime. Re-implementing the tagged-word Value rep, the mark-sweep
// GC, and `$show` by hand in LLVM IR would be enormous and unforgiving; instead
// the generated CODE is real LLVM IR that CALLS into a small linked C runtime
// (`llRuntimeC`, the external-linkage twin of cRuntime). This is a legitimate LLVM
// backend: the codegen target IS LLVM IR; the runtime is a linked C shim exactly
// as the source backends lean on a runtime blob. `EmitRuntime()` exposes the C
// the harness links alongside the emitted `.ll`.
//
// SUPPORTED FRAGMENT (byte-identical to the C/other backends on this subset):
// builtin-nat arithmetic (zero/succ/NatElim + accel add/mul/monus), constructors +
// eliminators (CCase/CField over ListElim/NatElim/any datatype), curried closures +
// application, dependent pairs (CPair/CFst/CSnd), the erased token (CUnit), and
// native literals (CLit). Quotient/IO builtins are emitted via the shared runtime
// when present. `partial` recursion runs through the memoized thunks, as in C.
//
// VALUE REP: a `Value` is `intptr_t` (R-NATIVE piece 1). In LLVM IR every Rune
// value is an `i64`; the runtime functions take/return `i64`, env is `i64*`, and a
// code pointer is `i64 (i64, i64*)*`. The emitter never inspects the tag itself —
// it defers to the runtime helpers (mkint/mkclo/apply/con_get/…), so the rep stays
// owned by ONE place (cRuntime, shared) and the two native backends cannot drift.
type LL struct{}

func (LL) Target() string { return "ll" }

// Emit closure-converts the program and emits an LLVM IR translation unit: a
// declare of every runtime helper, every lifted code block as an LLVM define, the
// constructor/eliminator/definition thunks, and `rune_main` (called by the linked
// runtime's C main) that evaluates the entry and `$show`s it. The accompanying C
// runtime is EmitRuntime(); compile with `clang program.ll runtime.c -o exe`.
func (LL) Emit(p Program) (TargetSource, error) {
	cp := ClosureConvert(p)
	em := &llEmitter{}
	if p.Nat != nil {
		em.natElim = p.Nat.ElimName
		em.accel = p.Nat.Ops
	}

	// The function bodies are written to `body` first so the string-constant
	// globals they reference (collected into em.strs) can be flushed to module
	// scope BEFORE them — LLVM requires a string global be a module-scope
	// definition, not an inline constant.
	var body strings.Builder

	// Constructor + eliminator code blocks and thunks.
	for _, d := range cp.Datas {
		if cp.Nat != nil && d.ElimName == cp.Nat.ElimName {
			em.emitNatLL(&body, *cp.Nat)
			continue
		}
		for _, c := range d.Ctors {
			em.emitCtorLL(&body, c)
		}
	}
	// The lifted code blocks (definitions' and eliminators' bodies).
	for _, blk := range cp.Blocks {
		em.emitBlock(&body, blk)
	}
	// Definition thunks (eliminators converted as CDefSpec, then user defs).
	for _, def := range cp.Defs {
		em.emitDefThunk(&body, def.Name, def.Body)
	}

	// rune_main: evaluate the entry thunk and show it. Called by the runtime's C
	// `main` (which captures the GC stack bottom and seeds UNIT first). An IO main
	// is a deferred world thunk (unit -> A), forced by applying $unit.
	body.WriteString("define void @rune_main() {\nentry:\n")
	if p.Main != "" {
		f := &llFunc{em: em}
		mainV := f.emit(&body, CGlobal{Name: p.Main}, nil)
		if p.IOMain {
			unit := f.fresh()
			fmt.Fprintf(&body, "  %s = load i64, i64* @UNIT\n", unit)
			r := f.fresh()
			fmt.Fprintf(&body, "  %s = call i64 @rt_apply(i64 %s, i64 %s)\n", r, mainV, unit)
			mainV = r
		}
		fmt.Fprintf(&body, "  call void @rt_show_line(i64 %s)\n", mainV)
	}
	body.WriteString("  ret void\n}\n")

	// Assemble the module: header, preamble, runtime declares, string globals, then
	// the function bodies.
	var b strings.Builder
	b.WriteString("; Generated by rune emit (llvm backend) — the erased shadow, native via clang. Do not edit.\n")
	b.WriteString("; Link with the C runtime from LL{}.EmitRuntime(): clang program.ll runtime.c -o exe\n\n")
	b.WriteString(llPreamble)
	b.WriteString(llDeclares)
	if usesQuot(p) {
		b.WriteString(llQuotDeclares)
	}
	if usesIO(p) {
		b.WriteString(llIODeclares)
	}
	// Host-linked foreign accessors (R-FFI / B4): an `IForeign` lowers to a call to
	// the zero-arg `@<name>()` the host supplies at link time. LLVM IR requires the
	// callee be declared in the module, so emit a `declare` for each foreign symbol
	// the program references (the source backends need no analogue — their callee is
	// resolved by name at the host's runtime). The definition lives in the linked
	// runtime.c the host provides; here we only promise its signature.
	if fns := foreignNames(p); len(fns) > 0 {
		b.WriteString("; Host-linked foreign accessors (R-FFI; defined in the linked host runtime).\n")
		for _, fn := range fns {
			fmt.Fprintf(&b, "declare i64 @%s()\n", llName(fn))
		}
	}
	b.WriteString("\n")
	// String-constant globals (constructor names + string literals), in stable
	// first-seen order for deterministic output.
	for _, s := range em.strOrder {
		bytes, n := llStrBytes(s)
		fmt.Fprintf(&b, "%s = private unnamed_addr constant [%d x i8] c\"%s\"\n", em.strs[s], n, bytes)
	}
	b.WriteString("\n")
	b.WriteString(body.String())
	return TargetSource(b.String()), nil
}

// foreignNames returns the distinct host-linked foreign symbols the program
// references (R-FFI / B4), in stable first-seen order. The LLVM backend needs
// each one `declare`d in the module so the emitted `call @<name>()` verifies; the
// host supplies the definition in the linked runtime.c. Mirrors usesIO/usesQuot's
// walk but over every IR node kind so a foreign nested in a case arm or pair is
// found.
func foreignNames(p Program) []string {
	seen := map[string]bool{}
	var out []string
	var walk func(Ir)
	walk = func(t Ir) {
		switch x := t.(type) {
		case IForeign:
			if !seen[x.Name] {
				seen[x.Name] = true
				out = append(out, x.Name)
			}
		case ILam:
			walk(x.Body)
		case IApp:
			walk(x.Fn)
			walk(x.Arg)
		case ILet:
			walk(x.Val)
			walk(x.Body)
		case IPair:
			walk(x.A)
			walk(x.B)
		case IFst:
			walk(x.P)
		case ISnd:
			walk(x.P)
		case IField:
			walk(x.Scrut)
		case ICase:
			walk(x.Scrut)
			for _, arm := range x.Arms {
				walk(arm.Body)
			}
		}
	}
	for _, d := range p.Defs {
		walk(d.Body)
	}
	return out
}

// EmitRuntime returns the C runtime the emitted LLVM IR links against (external-
// linkage twin of cRuntime + the C `main` that captures the GC stack bottom, seeds
// UNIT, and calls `rune_main`). The harness writes this beside the `.ll` and
// compiles both with clang. The quotient/IO groups are always included here (they
// are tiny and harmless when the `.ll` never references them).
func (LL) EmitRuntime() string {
	var b strings.Builder
	b.WriteString(llRuntimeC)
	b.WriteString(llRuntimeQuot)
	b.WriteString(llRuntimeIO)
	b.WriteString(llRuntimeMain)
	return b.String()
}

// llEmitter renders CIr terms to LLVM IR. Like cEmitter it knows the nat
// eliminator's name + the accel table for native arithmetic. It also accumulates
// the string-constant globals (constructor names + string literals) so they can be
// flushed to module scope before the functions that reference them.
type llEmitter struct {
	natElim  string
	accel    map[string]core.NatOp
	strs     map[string]string // string content -> its global symbol (@.str.N)
	strOrder []string          // first-seen order, for deterministic output
}

// intern returns (and registers, on first sight) the module-scope symbol for a
// string constant. The symbol embeds a counter so distinct strings never collide;
// identical strings share one global.
func (em *llEmitter) intern(s string) string {
	if em.strs == nil {
		em.strs = map[string]string{}
	}
	if sym, ok := em.strs[s]; ok {
		return sym
	}
	sym := fmt.Sprintf("@.str.%d", len(em.strOrder))
	em.strs[s] = sym
	em.strOrder = append(em.strOrder, s)
	return sym
}

// llFunc tracks per-function SSA state: a fresh-register counter and a fresh-label
// counter. LLVM IR is SSA + statement-oriented (unlike the C emitter's expression
// form), so each CIr node lowers to a sequence of instructions written to the
// builder and returns the NAME of the register holding its i64 value.
type llFunc struct {
	em    *llEmitter
	reg   int
	label int
}

func (f *llFunc) fresh() string { f.reg++; return fmt.Sprintf("%%v%d", f.reg) }
func (f *llFunc) freshLabel(s string) string {
	f.label++
	return fmt.Sprintf("%s%d", s, f.label)
}

// emitDefThunk emits a memoized thunk for a top-level definition. The first call
// computes the body and caches it (a private global cache + done flag), so
// recursion + the eliminators' self-reference terminate and run once. The cache is
// registered as a GC root before the body runs (the conservative stack scan cannot
// find a non-stack static), exactly as the C backend does.
func (em *llEmitter) emitDefThunk(b *strings.Builder, name string, body CIr) {
	cache := "@cache_" + llName(name)
	done := "@done_" + llName(name)
	fmt.Fprintf(b, "%s = internal global i64 0\n", cache)
	fmt.Fprintf(b, "%s = internal global i1 0\n", done)
	fmt.Fprintf(b, "define i64 @%s() {\nentry:\n", llThunkName(name))
	f := &llFunc{em: em}
	d := f.fresh()
	fmt.Fprintf(b, "  %s = load i1, i1* %s\n", d, done)
	lret := f.freshLabel("ret")
	lcomp := f.freshLabel("comp")
	fmt.Fprintf(b, "  br i1 %s, label %%%s, label %%%s\n", d, lret, lcomp)
	fmt.Fprintf(b, "%s:\n", lret)
	c0 := f.fresh()
	fmt.Fprintf(b, "  %s = load i64, i64* %s\n", c0, cache)
	fmt.Fprintf(b, "  ret i64 %s\n", c0)
	fmt.Fprintf(b, "%s:\n", lcomp)
	fmt.Fprintf(b, "  store i1 1, i1* %s\n", done)
	fmt.Fprintf(b, "  call void @rt_add_root(i64* %s)\n", cache)
	v := f.emit(b, body, nil)
	fmt.Fprintf(b, "  store i64 %s, i64* %s\n", v, cache)
	fmt.Fprintf(b, "  ret i64 %s\n", v)
	b.WriteString("}\n")
}

// emitBlock emits one lifted code block as an LLVM function. The body refers to
// its argument as CVar{0} (the `%arg` parameter, shifted by inner CLet binders) and
// to captured variables via CEnv{slot} (a GEP+load of `%env`). Locals are tracked
// as a stack of register names (innermost = index 0); the seed is `%arg`.
func (em *llEmitter) emitBlock(b *strings.Builder, blk CodeBlock) {
	fmt.Fprintf(b, "define i64 @%s(i64 %%arg, i64* %%env) {\nentry:\n", llCodeName(blk.Name))
	f := &llFunc{em: em}
	v := f.emitIn(b, blk.Body, []string{"%arg"})
	fmt.Fprintf(b, "  ret i64 %s\n", v)
	b.WriteString("}\n")
}

// emitCtorLL emits a constructor as a curried closure, mirroring emitCtorC: a
// nullary constructor is the {tag} object; an arity-k constructor builds k code
// blocks, each capturing the prefix and the last building the {tag,fields} object.
func (em *llEmitter) emitCtorLL(b *strings.Builder, c CtorSpec) {
	if c.Arity == 0 {
		em.emitCachedThunk(b, c.Name, func(f *llFunc) string {
			r := f.fresh()
			fmt.Fprintf(b, "  %s = call i64 @rt_mkcon(i32 %d, i8* %s, i32 0)\n", r, c.Tag, em.cStr(c.Name))
			return r
		})
		return
	}
	base := "ctorfn_" + llName(c.Name)
	for i := 0; i < c.Arity; i++ {
		fmt.Fprintf(b, "define i64 @%s_%d(i64 %%arg, i64* %%env) {\nentry:\n", base, i)
		f := &llFunc{em: em}
		if i == c.Arity-1 {
			o := f.fresh()
			fmt.Fprintf(b, "  %s = call i64 @rt_mkcon(i32 %d, i8* %s, i32 %d)\n", o, c.Tag, em.cStr(c.Name), c.Arity)
			for k := 0; k < i; k++ {
				ev := f.loadEnv(b, k)
				fmt.Fprintf(b, "  call void @rt_con_set(i64 %s, i32 %d, i64 %s)\n", o, k, ev)
			}
			fmt.Fprintf(b, "  call void @rt_con_set(i64 %s, i32 %d, i64 %%arg)\n", o, i)
			fmt.Fprintf(b, "  ret i64 %s\n}\n", o)
		} else {
			cl := f.fresh()
			fmt.Fprintf(b, "  %s = call i64 @rt_mkclo(i64 (i64, i64*)* @%s_%d, i32 %d)\n", cl, base, i+1, i+1)
			for k := 0; k < i; k++ {
				ev := f.loadEnv(b, k)
				fmt.Fprintf(b, "  call void @rt_clo_set(i64 %s, i32 %d, i64 %s)\n", cl, k, ev)
			}
			fmt.Fprintf(b, "  call void @rt_clo_set(i64 %s, i32 %d, i64 %%arg)\n", cl, i)
			fmt.Fprintf(b, "  ret i64 %s\n}\n", cl)
		}
	}
	em.emitCachedThunk(b, c.Name, func(f *llFunc) string {
		r := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @rt_mkclo(i64 (i64, i64*)* @%s_0, i32 0)\n", r, base)
		return r
	})
}

// emitCachedThunk emits the standard memoized-thunk wrapper around a body that
// produces a Value (a constructor object or its entry closure). Shared by the
// constructor and nat thunks.
func (em *llEmitter) emitCachedThunk(b *strings.Builder, name string, body func(*llFunc) string) {
	cache := "@cache_" + llName(name)
	done := "@done_" + llName(name)
	fmt.Fprintf(b, "%s = internal global i64 0\n", cache)
	fmt.Fprintf(b, "%s = internal global i1 0\n", done)
	fmt.Fprintf(b, "define i64 @%s() {\nentry:\n", llThunkName(name))
	f := &llFunc{em: em}
	d := f.fresh()
	fmt.Fprintf(b, "  %s = load i1, i1* %s\n", d, done)
	lret := f.freshLabel("ret")
	lcomp := f.freshLabel("comp")
	fmt.Fprintf(b, "  br i1 %s, label %%%s, label %%%s\n", d, lret, lcomp)
	fmt.Fprintf(b, "%s:\n", lret)
	c0 := f.fresh()
	fmt.Fprintf(b, "  %s = load i64, i64* %s\n", c0, cache)
	fmt.Fprintf(b, "  ret i64 %s\n", c0)
	fmt.Fprintf(b, "%s:\n", lcomp)
	fmt.Fprintf(b, "  store i1 1, i1* %s\n", done)
	fmt.Fprintf(b, "  call void @rt_add_root(i64* %s)\n", cache)
	v := body(f)
	fmt.Fprintf(b, "  store i64 %s, i64* %s\n", v, cache)
	fmt.Fprintf(b, "  ret i64 %s\n}\n", v)
}

// emitNatLL emits the builtin-nat group natively, mirroring emitNatC: zero is the
// immediate 0, succ a +1 closure, the eliminator a 4-block curried fold loop.
func (em *llEmitter) emitNatLL(b *strings.Builder, n NatSpec) {
	// zero: immediate 0
	em.emitCachedThunk(b, n.Zero, func(f *llFunc) string {
		r := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @rt_mkint(i64 0)\n", r)
		return r
	})
	// succ code: x -> x+1
	sc := llName(n.Succ) + "_code"
	fmt.Fprintf(b, "define i64 @%s(i64 %%arg, i64* %%env) {\nentry:\n", sc)
	f := &llFunc{em: em}
	x := f.fresh()
	fmt.Fprintf(b, "  %s = call i64 @rt_as_int(i64 %%arg)\n", x)
	x1 := f.fresh()
	fmt.Fprintf(b, "  %s = add i64 %s, 1\n", x1, x)
	r := f.fresh()
	fmt.Fprintf(b, "  %s = call i64 @rt_mkint(i64 %s)\n", r, x1)
	fmt.Fprintf(b, "  ret i64 %s\n}\n", r)
	em.emitCachedThunk(b, n.Succ, func(f *llFunc) string {
		rr := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @rt_mkclo(i64 (i64, i64*)* @%s, i32 0)\n", rr, sc)
		return rr
	})
	// eliminator: m -> c0 -> c1 -> x -> fold (m erased/ignored). env order {m,c0,c1}.
	base := llName(n.ElimName)
	// b3: the fold. env = {m, c0, c1}, arg = x.
	fmt.Fprintf(b, "define i64 @%s_b3(i64 %%arg, i64* %%env) {\nentry:\n", base)
	ff := &llFunc{em: em}
	xv := ff.fresh()
	fmt.Fprintf(b, "  %s = call i64 @rt_as_int(i64 %%arg)\n", xv)
	c0 := ff.loadEnv(b, 1)
	c1 := ff.loadEnv(b, 2)
	// loop: acc = c0; for k in 0..x: acc = apply(apply(c1, mkint(k)), acc)
	accSlot := ff.fresh()
	fmt.Fprintf(b, "  %s = alloca i64\n", accSlot)
	fmt.Fprintf(b, "  store i64 %s, i64* %s\n", c0, accSlot)
	kSlot := ff.fresh()
	fmt.Fprintf(b, "  %s = alloca i64\n", kSlot)
	fmt.Fprintf(b, "  store i64 0, i64* %s\n", kSlot)
	lcond := ff.freshLabel("cond")
	lbody := ff.freshLabel("body")
	ldone := ff.freshLabel("done")
	fmt.Fprintf(b, "  br label %%%s\n", lcond)
	fmt.Fprintf(b, "%s:\n", lcond)
	kv := ff.fresh()
	fmt.Fprintf(b, "  %s = load i64, i64* %s\n", kv, kSlot)
	cmp := ff.fresh()
	fmt.Fprintf(b, "  %s = icmp slt i64 %s, %s\n", cmp, kv, xv)
	fmt.Fprintf(b, "  br i1 %s, label %%%s, label %%%s\n", cmp, lbody, ldone)
	fmt.Fprintf(b, "%s:\n", lbody)
	ki := ff.fresh()
	fmt.Fprintf(b, "  %s = call i64 @rt_mkint(i64 %s)\n", ki, kv)
	step := ff.fresh()
	fmt.Fprintf(b, "  %s = call i64 @rt_apply(i64 %s, i64 %s)\n", step, c1, ki)
	accv := ff.fresh()
	fmt.Fprintf(b, "  %s = load i64, i64* %s\n", accv, accSlot)
	nacc := ff.fresh()
	fmt.Fprintf(b, "  %s = call i64 @rt_apply(i64 %s, i64 %s)\n", nacc, step, accv)
	fmt.Fprintf(b, "  store i64 %s, i64* %s\n", nacc, accSlot)
	k1 := ff.fresh()
	fmt.Fprintf(b, "  %s = add i64 %s, 1\n", k1, kv)
	fmt.Fprintf(b, "  store i64 %s, i64* %s\n", k1, kSlot)
	fmt.Fprintf(b, "  br label %%%s\n", lcond)
	fmt.Fprintf(b, "%s:\n", ldone)
	res := ff.fresh()
	fmt.Fprintf(b, "  %s = load i64, i64* %s\n", res, accSlot)
	fmt.Fprintf(b, "  ret i64 %s\n}\n", res)
	// b2: arg=c1, env={m,c0}; build b3 closure capturing {m,c0,c1}.
	em.emitCurryBlock(b, base+"_b2", base+"_b3", 3, []int{0, 1}, 2)
	// b1: arg=c0, env={m}; build b2 closure capturing {m,c0}.
	em.emitCurryBlock(b, base+"_b1", base+"_b2", 2, []int{0}, 1)
	// b0: arg=m, env={}; build b1 closure capturing {m}.
	em.emitCurryBlock(b, base+"_b0", base+"_b1", 1, []int{}, 0)
	em.emitCachedThunk(b, n.ElimName, func(f *llFunc) string {
		rr := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @rt_mkclo(i64 (i64, i64*)* @%s_b0, i32 0)\n", rr, base)
		return rr
	})
}

// emitCurryBlock emits one currying block of a primitive: it builds the next
// closure of `nslots` slots over code `@next`, copying env slots `copyEnv` (by env
// index, into the same target slots) then placing %arg at slot `argSlot`.
func (em *llEmitter) emitCurryBlock(b *strings.Builder, name, next string, nslots int, copyEnv []int, argSlot int) {
	fmt.Fprintf(b, "define i64 @%s(i64 %%arg, i64* %%env) {\nentry:\n", name)
	f := &llFunc{em: em}
	cl := f.fresh()
	fmt.Fprintf(b, "  %s = call i64 @rt_mkclo(i64 (i64, i64*)* @%s, i32 %d)\n", cl, next, nslots)
	for _, k := range copyEnv {
		ev := f.loadEnv(b, k)
		fmt.Fprintf(b, "  call void @rt_clo_set(i64 %s, i32 %d, i64 %s)\n", cl, k, ev)
	}
	fmt.Fprintf(b, "  call void @rt_clo_set(i64 %s, i32 %d, i64 %%arg)\n", cl, argSlot)
	fmt.Fprintf(b, "  ret i64 %s\n}\n", cl)
}

// loadEnv emits a GEP+load reading env slot i, returning the register name.
func (f *llFunc) loadEnv(b *strings.Builder, i int) string {
	p := f.fresh()
	fmt.Fprintf(b, "  %s = getelementptr i64, i64* %%env, i64 %d\n", p, i)
	v := f.fresh()
	fmt.Fprintf(b, "  %s = load i64, i64* %s\n", v, p)
	return v
}

// emit lowers a CIr in the empty-locals context (def-thunk top level).
func (f *llFunc) emit(b *strings.Builder, t CIr, locals []string) string {
	return f.emitIn(b, t, locals)
}

// emitIn lowers a CIr in a context of `locals` (register names of binders visible
// by de Bruijn index, innermost = 0), writing instructions to b and returning the
// register holding the i64 result. CEnv reads the enclosing block's %env.
func (f *llFunc) emitIn(b *strings.Builder, t CIr, locals []string) string {
	switch x := t.(type) {
	case CVar:
		if x.Idx < len(locals) {
			return locals[x.Idx]
		}
		// Closed program invariant: should not happen; emit UNIT as a safe marker.
		r := f.fresh()
		fmt.Fprintf(b, "  %s = load i64, i64* @UNIT\n", r)
		return r
	case CEnv:
		return f.loadEnv(b, x.Idx)
	case CGlobal:
		r := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @%s()\n", r, llThunkName(x.Name))
		return r
	case CForeign:
		r := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @%s()\n", r, llName(x.Name))
		return r
	case CUnit:
		r := f.fresh()
		fmt.Fprintf(b, "  %s = load i64, i64* @UNIT\n", r)
		return r
	case CLit:
		return f.emitLit(b, x)
	case MkClosure:
		return f.emitMkClosure(b, x, locals)
	case AppClosure:
		if out, ok := f.accelDispatch(b, x, locals); ok {
			return out
		}
		clo := f.emitIn(b, x.Clo, locals)
		arg := f.emitIn(b, x.Arg, locals)
		r := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @rt_apply(i64 %s, i64 %s)\n", r, clo, arg)
		return r
	case CLet:
		v := f.emitIn(b, x.Val, locals)
		return f.emitIn(b, x.Body, prepend(v, locals))
	case CPair:
		a := f.emitIn(b, x.A, locals)
		bb := f.emitIn(b, x.B, locals)
		r := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @rt_mkpair(i64 %s, i64 %s)\n", r, a, bb)
		return r
	case CFst:
		p := f.emitIn(b, x.P, locals)
		r := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @rt_pair_fst(i64 %s)\n", r, p)
		return r
	case CSnd:
		p := f.emitIn(b, x.P, locals)
		r := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @rt_pair_snd(i64 %s)\n", r, p)
		return r
	case CField:
		s := f.emitIn(b, x.Scrut, locals)
		r := f.fresh()
		fmt.Fprintf(b, "  %s = call i64 @rt_con_get(i64 %s, i32 %d)\n", r, s, x.Index)
		return r
	case CCase:
		return f.emitCase(b, x, locals)
	default:
		panic(fmt.Sprintf("codegen(ll): unknown CIr node %T", t))
	}
}

// emitLit lowers a native literal, deferring to the runtime constructors.
func (f *llFunc) emitLit(b *strings.Builder, x CLit) string {
	r := f.fresh()
	switch x.Kind {
	case LitNat:
		// A compressed numeral is the native immediate int (the SAME rep NatSpec
		// gives nat, interchangeable with a succ-chain). The magnitude rides a
		// decimal string; emit it as an i64 literal (machine-int bound, matching the
		// Go/Rust/JVM source backends).
		fmt.Fprintf(b, "  %s = call i64 @rt_mkint(i64 %s)\n", r, x.Nat)
	case LitStr:
		fmt.Fprintf(b, "  %s = call i64 @rt_mkstr(i8* %s)\n", r, f.em.cStr(x.Str))
	case LitPtr:
		fmt.Fprintf(b, "  %s = call i64 @rt_mkptr(i64 %d)\n", r, x.Int)
	default: // LitInt
		fmt.Fprintf(b, "  %s = call i64 @rt_mkint(i64 %d)\n", r, x.Int)
	}
	return r
}

// emitMkClosure allocates a closure and fills its env slots (each evaluated in the
// enclosing context).
func (f *llFunc) emitMkClosure(b *strings.Builder, x MkClosure, locals []string) string {
	cl := f.fresh()
	fmt.Fprintf(b, "  %s = call i64 @rt_mkclo(i64 (i64, i64*)* @%s, i32 %d)\n", cl, llCodeName(x.Code), len(x.Env))
	for i, e := range x.Env {
		ev := f.emitIn(b, e, locals)
		fmt.Fprintf(b, "  call void @rt_clo_set(i64 %s, i32 %d, i64 %s)\n", cl, i, ev)
	}
	return cl
}

// emitCase lowers an eliminator's tag dispatch to an LLVM `switch` over the
// scrutinee's constructor tag. Each arm computes its body into a result alloca
// (an alloca avoids hand-rolling phi nodes across arms that may themselves branch),
// then branches to a join block that loads the result. Coverage is by construction;
// an unmatched tag aborts via the runtime.
func (f *llFunc) emitCase(b *strings.Builder, x CCase, locals []string) string {
	s := f.emitIn(b, x.Scrut, locals)
	tag := f.fresh()
	fmt.Fprintf(b, "  %s = call i32 @rt_con_tag(i64 %s)\n", tag, s)
	slot := f.fresh()
	fmt.Fprintf(b, "  %s = alloca i64\n", slot)
	ldef := f.freshLabel("casedefault")
	ljoin := f.freshLabel("casejoin")
	armLabels := make([]string, len(x.Arms))
	for i := range x.Arms {
		armLabels[i] = f.freshLabel("casearm")
	}
	fmt.Fprintf(b, "  switch i32 %s, label %%%s [\n", tag, ldef)
	for i, arm := range x.Arms {
		fmt.Fprintf(b, "    i32 %d, label %%%s\n", arm.Tag, armLabels[i])
	}
	b.WriteString("  ]\n")
	for i, arm := range x.Arms {
		fmt.Fprintf(b, "%s:\n", armLabels[i])
		v := f.emitIn(b, arm.Body, locals)
		fmt.Fprintf(b, "  store i64 %s, i64* %s\n", v, slot)
		fmt.Fprintf(b, "  br label %%%s\n", ljoin)
	}
	fmt.Fprintf(b, "%s:\n", ldef)
	b.WriteString("  call void @rt_abort()\n")
	b.WriteString("  unreachable\n")
	fmt.Fprintf(b, "%s:\n", ljoin)
	r := f.fresh()
	fmt.Fprintf(b, "  %s = load i64, i64* %s\n", r, slot)
	return r
}

// accelDispatch emits a registered accel-op def on two args as native integer
// arithmetic (C7 / R-NUM Decision 4 — the runtime helpers nat_add/nat_mul/
// nat_monus, identical to the C backend's), O(1), interchangeable with the loop.
func (f *llFunc) accelDispatch(b *strings.Builder, app AppClosure, locals []string) (string, bool) {
	op, a, bb, ok := accelMatchC(app, f.em.accel)
	if !ok {
		return "", false
	}
	ea := f.emitIn(b, a, locals)
	eb := f.emitIn(b, bb, locals)
	r := f.fresh()
	switch op {
	case core.NatOpAdd:
		fmt.Fprintf(b, "  %s = call i64 @rt_nat_add(i64 %s, i64 %s)\n", r, ea, eb)
		return r, true
	case core.NatOpMul:
		fmt.Fprintf(b, "  %s = call i64 @rt_nat_mul(i64 %s, i64 %s)\n", r, ea, eb)
		return r, true
	case core.NatOpMonus:
		fmt.Fprintf(b, "  %s = call i64 @rt_nat_monus(i64 %s, i64 %s)\n", r, ea, eb)
		return r, true
	}
	return "", false
}

// llName sanitizes a rune identifier into an LLVM-safe symbol fragment. LLVM
// global names may contain a wide set of characters when quoted, but we keep it to
// [A-Za-z0-9_] (reusing the C sanitizer) so symbols are plain and never need
// quoting; the operator-name table is shared with the C backend.
func llName(n string) string { return cName(n) }

// llThunkName / llCodeName namespace the two kinds of emitted symbol (a def thunk
// vs. a lifted code block), matching the C backend's scheme.
func llThunkName(n string) string { return "def_" + llName(n) }
func llCodeName(n string) string  { return "code_" + llName(n) }

// cStr renders a string constant as an i8* the emitted code can pass to the
// runtime: it interns the string (registering its module-scope global) and returns
// a getelementptr to the first byte of that global. The `[N x i8]*` length must
// match the global's, so it is computed from the same byte count.
func (em *llEmitter) cStr(s string) string {
	sym := em.intern(s)
	n := len(s) + 1 // + NUL terminator
	return fmt.Sprintf("getelementptr inbounds ([%d x i8], [%d x i8]* %s, i64 0, i64 0)", n, n, sym)
}

// llStrBytes renders a Go string as the BODY of an LLVM `c"..."` byte array
// (NUL-terminated, every non-printable/quote/backslash byte as `\HH`), returning
// the escaped text and the total byte count (including the NUL).
func llStrBytes(s string) (string, int) {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '\\':
			b.WriteString("\\5C")
		case c == '"':
			b.WriteString("\\22")
		case c < 0x20 || c >= 0x7f:
			fmt.Fprintf(&b, "\\%02X", c)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteString("\\00")
	return b.String(), len(s) + 1
}

var _ = sort.Strings
