package codegen

import (
	"fmt"
	"strings"

	"goforge.dev/rune/v3/core"
)

// Py is a second backend (B-track / multi-backend): plain Python 3 over the SAME
// erased IR as the JS backend. Everything is curried one-argument lambdas;
// constructors build {"tag","name","args"} dicts; eliminators are Python defs
// with chained-conditional dispatch and recursive calls for the induction
// hypotheses; the erased token is None; nat is int. The output runs under
// python3 with no dependencies. Its purpose is cross-backend conformance: the
// same program must observe equal results on JS and Python (the shadow rule —
// codegen mutates only its own output, never the core).
type Py struct{}

func (Py) Target() string { return "py" }

// Emit lowers a program to a self-contained Python 3 source file.
func (Py) Emit(p Program) (TargetSource, error) {
	em := &pyEmitter{}
	if p.Nat != nil {
		em.natElim = p.Nat.ElimName
		em.accel = p.Nat.Ops
	}
	var b strings.Builder
	b.WriteString("# Generated by rune emit (py backend) — the erased shadow. Do not edit.\n")
	b.WriteString("import sys\nsys.setrecursionlimit(1000000)\n")
	b.WriteString("_unit = None\n")
	b.WriteString(pyNatElimRuntime)
	if usesQuot(p) {
		b.WriteString(pyQuotRuntime)
	}
	if usesIO(p) {
		b.WriteString(pyIORuntime)
	}
	// D6 / R-EFFECT: bake the standard OS/IO host bodies when referenced.
	if usesForeign(p, "printNat") {
		b.WriteString("def printNat():\n    return lambda n: lambda _u: (print(n), n)[1]\n")
	}
	if usesForeign(p, "getNat") {
		b.WriteString("def getNat():\n    import sys\n    return lambda _u: int(sys.stdin.readline())\n")
	}
	if usesForeign(p, "timeNanos") {
		b.WriteString("def timeNanos():\n    import time\n    return lambda _u: time.time_ns()\n")
	}
	if usesForeign(p, "readLineCode") {
		b.WriteString("def readLineCode():\n    import sys\n    def t(_u):\n        s = sys.stdin.readline().rstrip('\\n')\n        n = 1\n        for ch in reversed(s):\n            n = n * 256 + ord(ch)\n        return n\n    return t\n")
	}
	// D6 net/fs: the packed-String codec + env/file host bodies, over bare Nat codes.
	if usesFileEnv(p) {
		b.WriteString("def __s2h(n):\n    s = ''\n    while n > 1:\n        s += chr(n % 256)\n        n //= 256\n    return s\n")
		b.WriteString("def __h2s(v):\n    n = 1\n    for ch in reversed(v):\n        n = n * 256 + ord(ch)\n    return n\n")
	}
	if usesForeign(p, "getEnvCode") {
		b.WriteString("def getEnvCode():\n    import os\n    return lambda c: lambda _u: __h2s(os.environ.get(__s2h(c), ''))\n")
	}
	if usesForeign(p, "readFileCode") {
		b.WriteString("def readFileCode():\n    def f(c):\n        def t(_u):\n            try:\n                with open(__s2h(c), 'r') as h:\n                    return __h2s(h.read())\n            except Exception:\n                return 1\n        return t\n    return f\n")
	}
	if usesForeign(p, "writeFileCode") {
		b.WriteString("def writeFileCode():\n    def f(p2):\n        def g(c):\n            def t(_u):\n                with open(__s2h(p2), 'w') as h:\n                    h.write(__s2h(c))\n                return c\n            return t\n        return g\n    return f\n")
	}
	if usesForeign(p, "printStrCode") {
		b.WriteString("def printStrCode():\n    return lambda c: lambda _u: (print(__s2h(c)), c)[1]\n")
	}
	// D6 argv + process.
	if usesForeign(p, "argCountCode") {
		b.WriteString("def argCountCode():\n    import sys\n    return lambda _u: len(sys.argv) - 1\n")
	}
	if usesForeign(p, "argAtCode") {
		b.WriteString("def argAtCode():\n    import sys\n    return lambda i: lambda _u: (__h2s(sys.argv[i + 1]) if i + 1 < len(sys.argv) else 1)\n")
	}
	if usesForeign(p, "exitWith") {
		b.WriteString("def exitWith():\n    import sys\n    return lambda n: lambda _u: sys.exit(n)\n")
	}
	for _, d := range p.Datas {
		if p.Nat != nil && d.ElimName == p.Nat.ElimName {
			emitNatPy(&b, *p.Nat)
			continue
		}
		for _, c := range d.Ctors {
			emitCtorPy(&b, c)
		}
		// B2 / R-IR: the eliminator is lowered to the shared IR once (LowerElim)
		// and emitted as an ordinary binding — no eliminator-specific backend code.
		fmt.Fprintf(&b, "%s = %s\n", pyName(d.ElimName), em.expr(LowerElim(d), nil))
	}
	for _, def := range p.Defs {
		fmt.Fprintf(&b, "%s = %s\n", pyName(def.Name), em.expr(def.Body, nil))
	}
	if p.Main != "" {
		b.WriteString(pyShowRuntime)
		mainExpr := pyName(p.Main)
		if p.IOMain {
			// An IO main is a deferred world thunk (unit -> A): force it before show.
			mainExpr += "(_unit)"
		}
		fmt.Fprintf(&b, "print(_show(%s))\n", mainExpr)
	}
	return TargetSource(b.String()), nil
}

func emitCtorPy(b *strings.Builder, c CtorSpec) {
	fmt.Fprintf(b, "%s = ", pyName(c.Name))
	for i := 0; i < c.Arity; i++ {
		fmt.Fprintf(b, "lambda a%d: ", i)
	}
	args := make([]string, c.Arity)
	for i := range args {
		args[i] = fmt.Sprintf("a%d", i)
	}
	fmt.Fprintf(b, "{\"tag\": %d, \"name\": %q, \"args\": [%s]}\n", c.Tag, c.Name, strings.Join(args, ", "))
}

func emitNatPy(b *strings.Builder, n NatSpec) {
	fmt.Fprintf(b, "%s = 0\n", pyName(n.Zero))
	fmt.Fprintf(b, "%s = lambda x: x + 1\n", pyName(n.Succ))
	fmt.Fprintf(b, "%s = lambda m: lambda c0: lambda c1: lambda x: _natElim(c0, c1, x)\n", pyName(n.ElimName))
}

type pyEmitter struct {
	natElim string
	accel   map[string]core.NatOp
}

func (em *pyEmitter) expr(t Ir, env []string) string {
	switch x := t.(type) {
	case IVar:
		if x.Idx < len(env) {
			return env[x.Idx]
		}
		return fmt.Sprintf("_v%d", x.Idx)
	case IGlobal:
		return pyName(x.Name)
	case IForeign:
		// Host-linked accessor: the host defines `def <name>(): return …`.
		return pyName(x.Name) + "()"
	case IUnit:
		return "_unit"
	case ILit:
		// Native host literal marshalled at the FFI boundary (B4): a Python int or
		// str literal.
		if x.Kind == LitNat {
			// C7 / R-NUM: a compressed numeral deploys as a native Python int — the
			// SAME representation NatSpec gives nat (`0`/`x + 1`), arbitrary
			// precision, O(1) source instead of a succ-chain.
			return x.Nat
		}
		if x.Kind == LitStr {
			return fmt.Sprintf("%q", x.Str)
		}
		if x.Kind == LitPtr {
			// Opaque host pointer: boxed in a dict so it never aliases an int, and
			// _show renders it as a fixed marker rather than its handle.
			return fmt.Sprintf("{\"ptr\": %d}", x.Int)
		}
		return fmt.Sprintf("%d", x.Int)
	case ILam:
		n := freshPy(x.Name, env)
		return fmt.Sprintf("(lambda %s: %s)", n, em.expr(x.Body, prepend(n, env)))
	case IApp:
		if out, ok := em.accelDispatch(x, env); ok {
			return out
		}
		if out, ok := em.natDispatch(x, env); ok {
			return out
		}
		return fmt.Sprintf("%s(%s)", em.expr(x.Fn, env), em.expr(x.Arg, env))
	case ILet:
		n := freshPy(x.Name, env)
		return fmt.Sprintf("(lambda %s: %s)(%s)", n, em.expr(x.Body, prepend(n, env)), em.expr(x.Val, env))
	case IPair:
		return fmt.Sprintf("(%s, %s)", em.expr(x.A, env), em.expr(x.B, env))
	case IFst:
		return fmt.Sprintf("(%s)[0]", em.expr(x.P, env))
	case ISnd:
		return fmt.Sprintf("(%s)[1]", em.expr(x.P, env))
	case IField:
		return fmt.Sprintf("(%s)[\"args\"][%d]", em.expr(x.Scrut, env), x.Index)
	case ICase:
		// Chained conditional expression on the scrutinee tag (Python has no
		// statement switch in an expression position).
		scrut := em.expr(x.Scrut, env)
		var b strings.Builder
		b.WriteString("(")
		for _, arm := range x.Arms {
			fmt.Fprintf(&b, "%s if (%s)[\"tag\"] == %d else ", em.expr(arm.Body, env), scrut, arm.Tag)
		}
		b.WriteString("_impossible())")
		return b.String()
	default:
		panic("codegen(py): unknown IR node")
	}
}

// accelDispatch emits a registered accel-op def on two args as native Python int
// arithmetic (C7 / R-NUM Decision 4): add → `(a + b)`, mul → `(a * b)`, monus →
// saturating `(a - b if a > b else 0)` (Peano monus floors at 0). Python ints are
// arbitrary precision, the SAME representation NatSpec gives nat.
func (em *pyEmitter) accelDispatch(app IApp, env []string) (string, bool) {
	op, a, b, ok := accelMatch(app, em.accel)
	if !ok {
		return "", false
	}
	ea, eb := em.expr(a, env), em.expr(b, env)
	switch op {
	case core.NatOpAdd:
		return fmt.Sprintf("(%s + %s)", ea, eb), true
	case core.NatOpMul:
		return fmt.Sprintf("(%s * %s)", ea, eb), true
	case core.NatOpMonus:
		return fmt.Sprintf("((%s) - (%s) if (%s) > (%s) else 0)", ea, eb, ea, eb), true
	case core.NatOpDiv:
		return fmt.Sprintf("((%s) // (%s) if (%s) != 0 else 0)", ea, eb, eb), true
	case core.NatOpMod:
		return fmt.Sprintf("((%s) %% (%s) if (%s) != 0 else (%s))", ea, eb, eb, ea), true
	}
	return "", false
}

func (em *pyEmitter) natDispatch(app IApp, env []string) (string, bool) {
	if em.natElim == "" {
		return "", false
	}
	var args []Ir
	t := Ir(app)
	for {
		a, ok := t.(IApp)
		if !ok {
			break
		}
		args = append([]Ir{a.Arg}, args...)
		t = a.Fn
	}
	g, ok := t.(IGlobal)
	if !ok || g.Name != em.natElim || len(args) < 4 {
		return "", false
	}
	c1lam, ok := args[2].(ILam)
	if !ok {
		return "", false
	}
	inner, ok := c1lam.Body.(ILam)
	if !ok || usesVar(inner.Body, 0) {
		return "", false
	}
	out := fmt.Sprintf("_natD(%s, %s, %s)",
		em.expr(args[1], env), em.expr(args[2], env), em.expr(args[3], env))
	for _, extra := range args[4:] {
		out = fmt.Sprintf("%s(%s)", out, em.expr(extra, env))
	}
	return out, true
}

func freshPy(hint string, env []string) string {
	n := pyName(hint)
	if n == "" || n == "_" {
		n = "_x"
	}
	for {
		clash := false
		for _, e := range env {
			if e == n {
				clash = true
				break
			}
		}
		if !clash {
			return n
		}
		n += "_"
	}
}

// pyName sanitizes a rune identifier into a Python one (qualified names with dots
// mangle their dots; operators mangle through jsOpNames; primes become _).
func pyName(n string) string {
	if m, ok := jsOpNames[n]; ok {
		return m
	}
	if i := strings.IndexByte(n, '$'); i > 0 {
		if m, ok := jsOpNames[n[:i]]; ok {
			n = m + n[i:]
		}
	}
	n = strings.ReplaceAll(n, "'", "_")
	n = strings.ReplaceAll(n, "$", "_")
	n = strings.ReplaceAll(n, ".", "_")
	if n == "" {
		n = "_x"
	}
	if pyReserved[n] {
		return "_" + n
	}
	return n
}

var pyReserved = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true,
	"assert": true, "async": true, "await": true, "break": true, "class": true,
	"continue": true, "def": true, "del": true, "elif": true, "else": true,
	"except": true, "finally": true, "for": true, "from": true, "global": true,
	"if": true, "import": true, "in": true, "is": true, "lambda": true,
	"nonlocal": true, "not": true, "or": true, "pass": true, "raise": true,
	"return": true, "try": true, "while": true, "with": true, "yield": true,
}

const pyNatElimRuntime = `def _natElim(c0, c1, x):
    acc = c0
    for k in range(x):
        acc = c1(k)(acc)
    return acc
def _natD(c0, c1, x):
    return c0 if x == 0 else c1(x - 1)(_unit)
def _impossible():
    raise Exception("impossible: unmatched constructor tag")
`

// pyIORuntime is the erased IO monad (R-EFFECT / C3): IO A is a deferred thunk
// encoded as a unit-argument closure (so the existing call machinery forces it by
// applying _unit); pureIO returns a constant thunk; bindIO sequences — run m, feed
// its result to k, run that. Type arguments arrive as units.
const pyIORuntime = `pureIO = lambda _A: lambda a: lambda _u: a
bindIO = lambda _A: lambda _B: lambda m: lambda k: lambda _u: k(m(_unit))(_unit)
`

const pyQuotRuntime = `qin = lambda A: lambda R: lambda a: a
qsound = lambda A: lambda R: lambda a: lambda b: lambda r: _unit
qlift = lambda A: lambda R: lambda B: lambda f: lambda resp: lambda q: f(q)
qind = lambda A: lambda R: lambda P: lambda h: lambda q: _unit
`

const pyShowRuntime = `def _show(v):
    if v is None:
        return "()"
    if callable(v):
        return "<function>"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, tuple):
        return "(" + ", ".join(_show(x) for x in v) + ")"
    if isinstance(v, dict) and "ptr" in v:
        return "<ptr>"
    if isinstance(v, dict) and "tag" in v:
        s = v["name"]
        for a in v["args"]:
            if a is None:
                continue
            r = _show(a)
            s += " " + ("(" + r + ")" if " " in r else r)
        return s
    return str(v)
`
