package codegen

import (
	"fmt"
	"strings"

	"goforge.dev/rune/v3/core"
)

// Rust is a fourth backend (B-track / multi-backend): safe Rust over the SAME
// erased IR as JS/Python/Go. A runtime value is the reference-counted `Rc<V>`
// dynamic enum (unit / machine int / curried closure / tagged constructor /
// pair); a function is `Rc<dyn Fn(Rc<V>) -> Rc<V>>` applied through `ap`, so the
// emit needs no inline type juggling; constructors build `V::Ctor` records;
// eliminators are statement-body tag dispatch; nat is `i64`; the unit token is
// `V::Unit`. Each top-level definition becomes a thunk `name_d() -> Rc<V>` and
// references call it — sidestepping Rust's no-cyclic-statics rule for (mutually)
// recursive definitions and eliminators, exactly as the Go backend does.
//
// Rust moves by default, so every curried closure CLONES the captures it forwards
// inward before constructing the next closure: that keeps each closure `Fn`
// (a closure that moved a capture out would be `FnOnce`, which `vfun` rejects).
// `Rc::clone` is a refcount bump, not a deep copy — the shadow stays cheap.
// Shadow-rule safe: a backend bug is wrong runtime output, never an unsound proof.
type Rust struct{}

func (Rust) Target() string { return "rs" }

// Emit lowers a program to a self-contained Rust source file (rustc-compilable).
func (Rust) Emit(p Program) (TargetSource, error) {
	em := &rustEmitter{}
	if p.Nat != nil {
		em.natElim = p.Nat.ElimName
		em.accel = p.Nat.Ops
	}
	var b strings.Builder
	b.WriteString("// Generated by rune emit (rust backend) — the erased shadow. Do not edit.\n")
	b.WriteString("#![allow(warnings)]\n")
	b.WriteString(rustRuntime)
	if usesQuot(p) {
		b.WriteString(rustQuotRuntime)
	}
	if usesIO(p) {
		b.WriteString(rustIORuntime())
	}
	for _, d := range p.Datas {
		if p.Nat != nil && d.ElimName == p.Nat.ElimName {
			emitNatRust(&b, *p.Nat)
			continue
		}
		for _, c := range d.Ctors {
			emitCtorRust(&b, c)
		}
		// B2 / R-IR: the eliminator is lowered to the shared IR once (LowerElim)
		// and emitted as an ordinary thunk — no eliminator-specific backend code.
		fmt.Fprintf(&b, "fn %s() -> Rc<V> { %s }\n", rustThunk(d.ElimName), em.expr(LowerElim(d), nil))
	}
	for _, def := range p.Defs {
		fmt.Fprintf(&b, "fn %s() -> Rc<V> { %s }\n", rustThunk(def.Name), em.expr(def.Body, nil))
	}
	b.WriteString("fn main() {\n")
	if p.Main != "" {
		// Run the show on a large-stack thread: deep erased recursion (unrolled
		// arithmetic, partial defs) would otherwise overflow the default stack —
		// the analogue of the Python backend's raised recursion limit.
		mainExpr := rustThunk(p.Main) + "()"
		if p.IOMain {
			// An IO main is a deferred world thunk (unit -> A): force by applying unit.
			mainExpr = fmt.Sprintf("ap(%s, unit())", mainExpr)
		}
		fmt.Fprintf(&b, "\tlet h = std::thread::Builder::new().stack_size(512*1024*1024)\n")
		fmt.Fprintf(&b, "\t\t.spawn(|| { println!(\"{}\", _show(&%s)); }).unwrap();\n", mainExpr)
		b.WriteString("\th.join().unwrap();\n")
	}
	b.WriteString("}\n")
	return TargetSource(b.String()), nil
}

// rustCurry nests one-argument closures binding params in order; body is the
// innermost expression with every param in scope. Each closure clones the params
// the deeper closures capture, so no closure moves a capture out (each stays Fn).
func rustCurry(params []string, body string) string {
	inner := body
	for i := len(params) - 1; i >= 0; i-- {
		var cl strings.Builder
		cl.WriteString("{ ")
		for _, s := range params[:i] {
			fmt.Fprintf(&cl, "let %s = %s.clone(); ", s, s)
		}
		fmt.Fprintf(&cl, "vfun(move |%s: Rc<V>| -> Rc<V> { %s }) }", params[i], inner)
		inner = cl.String()
	}
	return inner
}

func emitCtorRust(b *strings.Builder, c CtorSpec) {
	params := make([]string, c.Arity)
	args := make([]string, c.Arity)
	for i := range params {
		params[i] = fmt.Sprintf("a%d", i)
		args[i] = fmt.Sprintf("a%d.clone()", i)
	}
	body := fmt.Sprintf("Rc::new(V::Ctor(%d, %q, vec![%s]))", c.Tag, c.Name, strings.Join(args, ", "))
	fmt.Fprintf(b, "fn %s() -> Rc<V> { %s }\n", rustThunk(c.Name), rustCurry(params, body))
}

func emitNatRust(b *strings.Builder, n NatSpec) {
	fmt.Fprintf(b, "fn %s() -> Rc<V> { Rc::new(V::Int(0)) }\n", rustThunk(n.Zero))
	fmt.Fprintf(b, "fn %s() -> Rc<V> { vfun(move |x: Rc<V>| -> Rc<V> { Rc::new(V::Int(_int(&x) + 1)) }) }\n", rustThunk(n.Succ))
	body := "_nat_elim(c0.clone(), c1.clone(), x.clone())"
	fmt.Fprintf(b, "fn %s() -> Rc<V> { %s }\n", rustThunk(n.ElimName),
		rustCurry([]string{"m", "c0", "c1", "x"}, body))
}

type rustEmitter struct {
	natElim string
	accel   map[string]core.NatOp
}

func (em *rustEmitter) expr(t Ir, env []string) string {
	switch x := t.(type) {
	case IVar:
		if x.Idx < len(env) {
			return env[x.Idx] + ".clone()"
		}
		return fmt.Sprintf("_v%d.clone()", x.Idx)
	case IGlobal:
		return rustThunk(x.Name) + "()"
	case IForeign:
		// Host-linked accessor: the host defines `fn <name>() -> Rc<V> { … }`.
		// A plain name (no _d suffix) keeps the FFI ABI distinct from def thunks.
		return rustName(x.Name) + "()"
	case IUnit:
		return "unit()"
	case ILit:
		// Native host literal marshalled at the FFI boundary (B4): a V::Int scalar
		// or V::Str (a dedicated value-domain case so strings never alias ints).
		if x.Kind == LitNat {
			// C7 / R-NUM: a compressed numeral deploys as a native V::Int — the SAME
			// representation NatSpec gives nat (`V::Int(0)`, `_int(&x) + 1`), O(1)
			// source instead of a succ-chain. Machine-bounded (i64), matching the
			// succ-chain-to-int path it replaces.
			return fmt.Sprintf("Rc::new(V::Int(%s))", x.Nat)
		}
		if x.Kind == LitStr {
			return fmt.Sprintf("Rc::new(V::Str(%q.to_string()))", x.Str)
		}
		if x.Kind == LitPtr {
			// Opaque host pointer (B4): a dedicated V::Ptr case so it never aliases
			// an int, and _show renders it as a fixed marker, not its handle.
			return fmt.Sprintf("Rc::new(V::Ptr(%d))", x.Int)
		}
		return fmt.Sprintf("Rc::new(V::Int(%d))", x.Int)
	case ILam:
		n := freshRust(x.Name, env)
		// Clone the in-scope captures so the move closure stays Fn.
		var pre strings.Builder
		pre.WriteString("{ ")
		for _, e := range env {
			fmt.Fprintf(&pre, "let %s = %s.clone(); ", e, e)
		}
		fmt.Fprintf(&pre, "vfun(move |%s: Rc<V>| -> Rc<V> { %s }) }", n, em.expr(x.Body, prepend(n, env)))
		return pre.String()
	case IApp:
		if out, ok := em.accelDispatch(x, env); ok {
			return out
		}
		if out, ok := em.natDispatch(x, env); ok {
			return out
		}
		return fmt.Sprintf("ap(%s, %s)", em.expr(x.Fn, env), em.expr(x.Arg, env))
	case ILet:
		n := freshRust(x.Name, env)
		return fmt.Sprintf("{ let %s: Rc<V> = %s; %s }", n, em.expr(x.Val, env), em.expr(x.Body, prepend(n, env)))
	case IPair:
		return fmt.Sprintf("Rc::new(V::Pair(%s, %s))", em.expr(x.A, env), em.expr(x.B, env))
	case IFst:
		return fmt.Sprintf("_fst(%s)", em.expr(x.P, env))
	case ISnd:
		return fmt.Sprintf("_snd(%s)", em.expr(x.P, env))
	case IField:
		return fmt.Sprintf("_field(%s, %d)", em.expr(x.Scrut, env), x.Index)
	case ICase:
		scrut := em.expr(x.Scrut, env)
		var b strings.Builder
		fmt.Fprintf(&b, "(match _tag_of(&(%s)) {", scrut)
		for _, arm := range x.Arms {
			fmt.Fprintf(&b, " %d => %s,", arm.Tag, em.expr(arm.Body, env))
		}
		b.WriteString(" _ => _impossible() })")
		return b.String()
	default:
		panic("codegen(rust): unknown IR node")
	}
}

// accelDispatch emits a registered accel-op def on two args as native i64
// arithmetic (C7 / R-NUM Decision 4) through the `_nat_add`/`_nat_mul`/
// `_nat_monus` runtime helpers (unbox V::Int, compute, rebox). Monus is the
// saturating Peano monus (floors at 0). The i64 representation is the SAME
// NatSpec gives nat, so the result is interchangeable with the eliminator loop.
func (em *rustEmitter) accelDispatch(app IApp, env []string) (string, bool) {
	op, a, b, ok := accelMatch(app, em.accel)
	if !ok {
		return "", false
	}
	ea, eb := em.expr(a, env), em.expr(b, env)
	switch op {
	case core.NatOpAdd:
		return fmt.Sprintf("_nat_add(%s, %s)", ea, eb), true
	case core.NatOpMul:
		return fmt.Sprintf("_nat_mul(%s, %s)", ea, eb), true
	case core.NatOpMonus:
		return fmt.Sprintf("_nat_monus(%s, %s)", ea, eb), true
	}
	return "", false
}

func (em *rustEmitter) natDispatch(app IApp, env []string) (string, bool) {
	if em.natElim == "" {
		return "", false
	}
	var args []Ir
	t := Ir(app)
	for {
		a, ok := t.(IApp)
		if !ok {
			break
		}
		args = append([]Ir{a.Arg}, args...)
		t = a.Fn
	}
	g, ok := t.(IGlobal)
	if !ok || g.Name != em.natElim || len(args) < 4 {
		return "", false
	}
	c1lam, ok := args[2].(ILam)
	if !ok {
		return "", false
	}
	inner, ok := c1lam.Body.(ILam)
	if !ok || usesVar(inner.Body, 0) {
		return "", false
	}
	out := fmt.Sprintf("_nat_d(%s, %s, %s)",
		em.expr(args[1], env), em.expr(args[2], env), em.expr(args[3], env))
	for _, extra := range args[4:] {
		out = fmt.Sprintf("ap(%s, %s)", out, em.expr(extra, env))
	}
	return out, true
}

func freshRust(hint string, env []string) string {
	n := rustName(hint)
	if n == "" || n == "_" {
		n = "_x"
	}
	if rustReserved[n] {
		n = "_" + n
	}
	for {
		clash := false
		for _, e := range env {
			if e == n {
				clash = true
				break
			}
		}
		if !clash {
			return n
		}
		n += "_"
	}
}

// rustThunk is the top-level thunk name for a definition (suffix _d avoids
// clashing with the runtime helpers, which carry no suffix).
func rustThunk(n string) string { return rustName(n) + "_d" }

func rustName(n string) string {
	if m, ok := jsOpNames[n]; ok {
		n = m
	} else if i := strings.IndexByte(n, '$'); i > 0 {
		if m, ok := jsOpNames[n[:i]]; ok {
			n = m + n[i:]
		}
	}
	n = strings.ReplaceAll(n, "'", "_")
	n = strings.ReplaceAll(n, "$", "_")
	n = strings.ReplaceAll(n, ".", "_")
	if n == "" {
		n = "_x"
	}
	if c := n[0]; c >= '0' && c <= '9' {
		n = "_" + n
	}
	return n
}

var rustReserved = map[string]bool{
	"as": true, "break": true, "const": true, "continue": true, "crate": true,
	"dyn": true, "else": true, "enum": true, "extern": true, "false": true,
	"fn": true, "for": true, "if": true, "impl": true, "in": true, "let": true,
	"loop": true, "match": true, "mod": true, "move": true, "mut": true,
	"pub": true, "ref": true, "return": true, "self": true, "Self": true,
	"static": true, "struct": true, "super": true, "trait": true, "true": true,
	"type": true, "unsafe": true, "use": true, "where": true, "while": true,
	"async": true, "await": true,
}

// rustRuntime is the dynamic value enum and the shared helpers: application,
// machine-int access, the nat eliminator/destructor, the impossible head, and
// the structural show (erased unit fields are skipped, matching JS/Go).
const rustRuntime = `use std::rc::Rc;
enum V {
    Unit,
    Int(i64),
    Str(String),
    Ptr(i64),
    Fun(Rc<dyn Fn(Rc<V>) -> Rc<V>>),
    Ctor(i64, &'static str, Vec<Rc<V>>),
    Pair(Rc<V>, Rc<V>),
}
fn unit() -> Rc<V> { Rc::new(V::Unit) }
fn vfun<F: Fn(Rc<V>) -> Rc<V> + 'static>(f: F) -> Rc<V> { Rc::new(V::Fun(Rc::new(f))) }
fn ap(f: Rc<V>, x: Rc<V>) -> Rc<V> {
    match &*f { V::Fun(g) => g(x), _ => panic!("rune: applied a non-function") }
}
fn _int(v: &Rc<V>) -> i64 {
    match &**v { V::Int(n) => *n, _ => panic!("rune: expected an int") }
}
fn _fst(p: Rc<V>) -> Rc<V> {
    match &*p { V::Pair(a, _) => a.clone(), _ => panic!("rune: fst of a non-pair") }
}
fn _snd(p: Rc<V>) -> Rc<V> {
    match &*p { V::Pair(_, b) => b.clone(), _ => panic!("rune: snd of a non-pair") }
}
fn _tag_of(v: &Rc<V>) -> i64 {
    match &**v { V::Ctor(t, _, _) => *t, _ => panic!("rune: scrutinee is not a constructor") }
}
fn _field(v: Rc<V>, i: usize) -> Rc<V> {
    match &*v { V::Ctor(_, _, a) => a[i].clone(), _ => panic!("rune: field of a non-constructor") }
}
fn _impossible() -> Rc<V> { panic!("impossible: unmatched constructor tag") }
fn _nat_elim(c0: Rc<V>, c1: Rc<V>, x: Rc<V>) -> Rc<V> {
    let mut acc = c0;
    for k in 0.._int(&x) {
        acc = ap(ap(c1.clone(), Rc::new(V::Int(k))), acc);
    }
    acc
}
fn _nat_d(c0: Rc<V>, c1: Rc<V>, x: Rc<V>) -> Rc<V> {
    let n = _int(&x);
    if n == 0 { c0 } else { ap(ap(c1, Rc::new(V::Int(n - 1))), unit()) }
}
fn _nat_add(a: Rc<V>, b: Rc<V>) -> Rc<V> { Rc::new(V::Int(_int(&a) + _int(&b))) }
fn _nat_mul(a: Rc<V>, b: Rc<V>) -> Rc<V> { Rc::new(V::Int(_int(&a) * _int(&b))) }
fn _nat_monus(a: Rc<V>, b: Rc<V>) -> Rc<V> {
    let (x, y) = (_int(&a), _int(&b));
    Rc::new(V::Int(if x > y { x - y } else { 0 }))
}
fn _show(v: &Rc<V>) -> String {
    match &**v {
        V::Unit => "()".to_string(),
        V::Int(n) => n.to_string(),
        V::Str(s) => s.clone(),
        V::Ptr(_) => "<ptr>".to_string(),
        V::Fun(_) => "<function>".to_string(),
        V::Pair(a, b) => format!("({}, {})", _show(a), _show(b)),
        V::Ctor(_, name, args) => {
            let mut s = name.to_string();
            for a in args {
                if let V::Unit = &**a { continue; }
                let r = _show(a);
                if r.contains(' ') { s.push_str(&format!(" ({})", r)); }
                else { s.push(' '); s.push_str(&r); }
            }
            s
        }
    }
}
`

// rustIORuntime is the erased IO monad (R-EFFECT / C3): IO A is a deferred thunk
// encoded as a unit-argument closure, so `ap` forces it by applying unit; pureIO
// returns a constant thunk, bindIO sequences. Type arguments arrive as units.
func rustIORuntime() string {
	return "fn pureIO_d() -> Rc<V> { " + rustCurry([]string{"_a", "a", "_u"}, "a.clone()") + " }\n" +
		"fn bindIO_d() -> Rc<V> { " + rustCurry([]string{"_a", "_b", "m", "k", "_u"},
		"ap(ap(k.clone(), ap(m.clone(), unit())), unit())") + " }\n"
}

// rustQuotRuntime is the erased quotient builtin group (v2): a quotient compiles
// to its carrier, so qin is the identity on its point, qlift applies the lifted
// function directly, and the proof-valued members (qsound, qind) are
// unit-producers. Type and proof arguments arrive as units (no arity surgery).
var rustQuotRuntime = "fn qin_d() -> Rc<V> { " + rustCurry([]string{"_a", "_r", "x"}, "x.clone()") + " }\n" +
	"fn qsound_d() -> Rc<V> { " + rustCurry([]string{"_a", "_r", "_x", "_y", "_p"}, "unit()") + " }\n" +
	"fn qlift_d() -> Rc<V> { " + rustCurry([]string{"_a", "_r", "_b", "f", "_resp", "q"}, "ap(f.clone(), q.clone())") + " }\n" +
	"fn qind_d() -> Rc<V> { " + rustCurry([]string{"_a", "_r", "_p", "_h", "_q"}, "unit()") + " }\n"
