package codegen

import (
	"fmt"
	"strings"

	"goforge.dev/rune/v3/core"
)

// Rust is a fourth backend (B-track / multi-backend): safe Rust over the SAME
// erased IR as JS/Python/Go. A runtime value is the reference-counted `Rc<V>`
// dynamic enum (unit / machine int / curried closure / tagged constructor /
// pair); a function is `Rc<dyn Fn(Rc<V>) -> Rc<V>>` applied through `ap`, so the
// emit needs no inline type juggling; constructors build `V::Ctor` records;
// eliminators are statement-body tag dispatch; nat is `i64`; the unit token is
// `V::Unit`. Each top-level definition becomes a thunk `name_d() -> Rc<V>` and
// references call it — sidestepping Rust's no-cyclic-statics rule for (mutually)
// recursive definitions and eliminators, exactly as the Go backend does.
//
// Rust moves by default, so every curried closure CLONES the captures it forwards
// inward before constructing the next closure: that keeps each closure `Fn`
// (a closure that moved a capture out would be `FnOnce`, which `vfun` rejects).
// `Rc::clone` is a refcount bump, not a deep copy — the shadow stays cheap.
// Shadow-rule safe: a backend bug is wrong runtime output, never an unsound proof.
type Rust struct{}

func (Rust) Target() string { return "rs" }

// Emit lowers a program to a self-contained Rust source file (rustc-compilable).
func (Rust) Emit(p Program) (TargetSource, error) {
	em := &rustEmitter{}
	if p.Nat != nil {
		em.natElim = p.Nat.ElimName
		em.accel = p.Nat.Ops
	}
	var b strings.Builder
	b.WriteString("// Generated by rune emit (rust backend) — the erased shadow. Do not edit.\n")
	b.WriteString("#![allow(warnings)]\n")
	b.WriteString(rustRuntime)
	if usesQuot(p) {
		b.WriteString(rustQuotRuntime)
	}
	if usesIO(p) {
		b.WriteString(rustIORuntime())
	}
	// D6 / R-EFFECT: bake the standard OS/IO host bodies when referenced.
	if usesForeign(p, "printNat") {
		b.WriteString("fn printNat() -> Rc<V> { vfun(|n: Rc<V>| -> Rc<V> { let s = _show(&n); let n2 = n.clone(); vfun(move |_u: Rc<V>| -> Rc<V> { println!(\"{}\", s); n2.clone() }) }) }\n")
	}
	// Phase 0 — real byte strings (Bin): the value domain gained a V::Bytes(Vec<u8>)
	// variant (in rustRuntime); these are its host ops. Nats are V::Nat limbs.
	if usesBin(p) {
		b.WriteString("fn binEmpty() -> Rc<V> { Rc::new(V::Bytes(Vec::new())) }\n")
		b.WriteString("fn binCons() -> Rc<V> { vfun(|c: Rc<V>| -> Rc<V> { let byte = _natbyte(&c); vfun(move |b: Rc<V>| -> Rc<V> { let mut v = _bytes(&b).clone(); v.insert(0, byte); Rc::new(V::Bytes(v)) }) }) }\n")
		b.WriteString("fn binLen() -> Rc<V> { vfun(|b: Rc<V>| -> Rc<V> { _nat_of_usize(_bytes(&b).len()) }) }\n")
		b.WriteString("fn binAt() -> Rc<V> { vfun(|b: Rc<V>| -> Rc<V> { let v = _bytes(&b).clone(); vfun(move |i: Rc<V>| -> Rc<V> { let k = _natusize(&i); if k < v.len() { _nat_of_usize(v[k] as usize) } else { _nat_of_usize(0) } }) }) }\n")
		b.WriteString("fn printBin() -> Rc<V> { vfun(|b: Rc<V>| -> Rc<V> { let s = _binshow(_bytes(&b)); vfun(move |_u: Rc<V>| -> Rc<V> { println!(\"{}\", s); unit() }) }) }\n")
	}
	// Phase 1 — uniform socket FFI: V cannot box a TcpStream, so handles are i64
	// tokens (V::Nat) into a thread-local table; payloads are Bin (V::Bytes). Blocking.
	if usesNet(p) {
		b.WriteString("thread_local!(static __SOCKS: std::cell::RefCell<std::collections::HashMap<i64, std::net::TcpStream>> = std::cell::RefCell::new(std::collections::HashMap::new()));\n")
		b.WriteString("thread_local!(static __LISTS: std::cell::RefCell<std::collections::HashMap<i64, std::net::TcpListener>> = std::cell::RefCell::new(std::collections::HashMap::new()));\n")
		b.WriteString("thread_local!(static __SOCKID: std::cell::RefCell<i64> = std::cell::RefCell::new(0));\n")
		b.WriteString("fn sockConnect() -> Rc<V> { vfun(|host: Rc<V>| -> Rc<V> { let h = String::from_utf8_lossy(_bytes(&host)).to_string(); vfun(move |port: Rc<V>| -> Rc<V> { let p = _natusize(&port); let h = h.clone(); vfun(move |_u: Rc<V>| -> Rc<V> { match std::net::TcpStream::connect(format!(\"{}:{}\", h, p)) { Ok(s) => { let id = __SOCKID.with(|c| { let mut c = c.borrow_mut(); *c += 1; *c }); __SOCKS.with(|m| { m.borrow_mut().insert(id, s); }); _nat_of_usize(id as usize) } Err(_) => _nat_of_usize(0) } }) }) }) }\n")
		b.WriteString("fn sockWrite() -> Rc<V> { vfun(|c: Rc<V>| -> Rc<V> { let id = _natusize(&c) as i64; vfun(move |data: Rc<V>| -> Rc<V> { let bytes = _bytes(&data).clone(); vfun(move |_u: Rc<V>| -> Rc<V> { use std::io::Write; let n = __SOCKS.with(|m| { let mut m = m.borrow_mut(); match m.get_mut(&id) { Some(s) => s.write(&bytes).unwrap_or(0), None => 0 } }); _nat_of_usize(n) }) }) }) }\n")
		b.WriteString("fn sockRead() -> Rc<V> { vfun(|c: Rc<V>| -> Rc<V> { let id = _natusize(&c) as i64; vfun(move |n: Rc<V>| -> Rc<V> { let k = _natusize(&n); vfun(move |_u: Rc<V>| -> Rc<V> { use std::io::Read; let mut buf = vec![0u8; k]; let got = __SOCKS.with(|m| { let mut m = m.borrow_mut(); match m.get_mut(&id) { Some(s) => s.read(&mut buf).unwrap_or(0), None => 0 } }); buf.truncate(got); Rc::new(V::Bytes(buf)) }) }) }) }\n")
		b.WriteString("fn sockClose() -> Rc<V> { vfun(|c: Rc<V>| -> Rc<V> { let id = _natusize(&c) as i64; vfun(move |_u: Rc<V>| -> Rc<V> { __SOCKS.with(|m| { m.borrow_mut().remove(&id); }); __LISTS.with(|m| { m.borrow_mut().remove(&id); }); unit() }) }) }\n")
		b.WriteString("fn sockListen() -> Rc<V> { vfun(|port: Rc<V>| -> Rc<V> { let p = _natusize(&port); vfun(move |_u: Rc<V>| -> Rc<V> { match std::net::TcpListener::bind(format!(\"127.0.0.1:{}\", p)) { Ok(l) => { let id = __SOCKID.with(|c| { let mut c = c.borrow_mut(); *c += 1; *c }); __LISTS.with(|m| { m.borrow_mut().insert(id, l); }); _nat_of_usize(id as usize) } Err(_) => _nat_of_usize(0) } }) }) }\n")
		b.WriteString("fn sockAccept() -> Rc<V> { vfun(|l: Rc<V>| -> Rc<V> { let id = _natusize(&l) as i64; vfun(move |_u: Rc<V>| -> Rc<V> { let s = __LISTS.with(|m| { let m = m.borrow(); m.get(&id).and_then(|ln| ln.accept().ok().map(|(s, _)| s)) }); match s { Some(s) => { let sid = __SOCKID.with(|c| { let mut c = c.borrow_mut(); *c += 1; *c }); __SOCKS.with(|m| { m.borrow_mut().insert(sid, s); }); _nat_of_usize(sid as usize) } None => _nat_of_usize(0) } }) }) }\n")
	}
	// Phase 1 — expanded OS/filesystem layer (Bin = V::Bytes).
	if usesFS(p) {
		b.WriteString("fn fsWrite() -> Rc<V> { vfun(|path: Rc<V>| -> Rc<V> { let p = String::from_utf8_lossy(_bytes(&path)).to_string(); vfun(move |content: Rc<V>| -> Rc<V> { let c = _bytes(&content).clone(); let p = p.clone(); vfun(move |_u: Rc<V>| -> Rc<V> { match std::fs::write(&p, &c) { Ok(_) => _nat_of_usize(c.len()), Err(_) => _nat_of_usize(0) } }) }) }) }\n")
		b.WriteString("fn fsRead() -> Rc<V> { vfun(|path: Rc<V>| -> Rc<V> { let p = String::from_utf8_lossy(_bytes(&path)).to_string(); vfun(move |_u: Rc<V>| -> Rc<V> { match std::fs::read(&p) { Ok(d) => Rc::new(V::Bytes(d)), Err(_) => Rc::new(V::Bytes(Vec::new())) } }) }) }\n")
		b.WriteString("fn fsExists() -> Rc<V> { vfun(|path: Rc<V>| -> Rc<V> { let p = String::from_utf8_lossy(_bytes(&path)).to_string(); vfun(move |_u: Rc<V>| -> Rc<V> { if std::path::Path::new(&p).exists() { _nat_of_usize(1) } else { _nat_of_usize(0) } }) }) }\n")
		b.WriteString("fn fsRemove() -> Rc<V> { vfun(|path: Rc<V>| -> Rc<V> { let p = String::from_utf8_lossy(_bytes(&path)).to_string(); vfun(move |_u: Rc<V>| -> Rc<V> { if std::fs::remove_file(&p).is_ok() { _nat_of_usize(1) } else { _nat_of_usize(0) } }) }) }\n")
		b.WriteString("fn fsMkdir() -> Rc<V> { vfun(|path: Rc<V>| -> Rc<V> { let p = String::from_utf8_lossy(_bytes(&path)).to_string(); vfun(move |_u: Rc<V>| -> Rc<V> { if std::fs::create_dir_all(&p).is_ok() { _nat_of_usize(1) } else { _nat_of_usize(0) } }) }) }\n")
	}
	// Phase 1 — os/exec: run program with one arg, capture stdout.
	if usesProc(p) {
		b.WriteString("fn procRun() -> Rc<V> { vfun(|prog: Rc<V>| -> Rc<V> { let p = String::from_utf8_lossy(_bytes(&prog)).to_string(); vfun(move |arg: Rc<V>| -> Rc<V> { let a = String::from_utf8_lossy(_bytes(&arg)).to_string(); let p = p.clone(); vfun(move |_u: Rc<V>| -> Rc<V> { match std::process::Command::new(&p).arg(&a).output() { Ok(o) => Rc::new(V::Bytes(o.stdout)), Err(_) => Rc::new(V::Bytes(Vec::new())) } }) }) }) }\n")
	}
	// Phase 3 crypto: real sha256 via the vendored BearSSL static lib (extern "C").
	// The context is an oversized 8-aligned opaque blob (BearSSL's is vtable+buf[64]+
	// count+val[8] ~112B). Gives rust a fast digest; pure-wootz ch514 is the oracle.
	if usesCrypto(p) {
		b.WriteString("#[repr(C, align(8))] struct BrSha256Ctx { _b: [u8; 128] }\n")
		// NB: br_sha256_update is a C MACRO for br_sha224_update (shared 256/224
		// context); the real symbol is br_sha224_update. init/out are real symbols.
		b.WriteString("extern \"C\" { fn br_sha256_init(c: *mut BrSha256Ctx); fn br_sha224_update(c: *mut BrSha256Ctx, d: *const u8, n: usize); fn br_sha256_out(c: *const BrSha256Ctx, o: *mut u8); }\n")
		b.WriteString("fn sha256() -> Rc<V> { vfun(|data: Rc<V>| -> Rc<V> { let b = _bytes(&data).clone(); let mut ctx = BrSha256Ctx { _b: [0u8; 128] }; let mut out = [0u8; 32]; unsafe { br_sha256_init(&mut ctx); br_sha224_update(&mut ctx, b.as_ptr(), b.len()); br_sha256_out(&ctx, out.as_mut_ptr()); } Rc::new(V::Bytes(out.to_vec())) }) }\n")
	}
	// Phase 3 TLS: HTTPS GET via the vendored rune_tls.c shim (BearSSL minimal
	// client + skip-verify), linked alongside libbearssl.a. Rust declares one
	// extern fn and never touches the TLS state machine.
	if usesTLS(p) {
		b.WriteString("extern \"C\" { fn rune_tls_get(host: *const u8, port: i32, path: *const u8, out: *mut *mut u8, outlen: *mut usize) -> i32; fn free(p: *mut core::ffi::c_void); }\n")
		b.WriteString("fn tlsGet() -> Rc<V> { vfun(|host: Rc<V>| -> Rc<V> { let h = _bytes(&host).clone(); vfun(move |port: Rc<V>| -> Rc<V> { let p = _natusize(&port) as i32; let h = h.clone(); vfun(move |path: Rc<V>| -> Rc<V> { let pa = _bytes(&path).clone(); let h = h.clone(); vfun(move |_u: Rc<V>| -> Rc<V> { let mut hc = h.clone(); hc.push(0); let mut pc = pa.clone(); pc.push(0); let mut outp: *mut u8 = core::ptr::null_mut(); let mut on: usize = 0; let rc = unsafe { rune_tls_get(hc.as_ptr(), p, pc.as_ptr(), &mut outp, &mut on) }; if rc != 0 || outp.is_null() { return Rc::new(V::Bytes(Vec::new())); } let body = unsafe { core::slice::from_raw_parts(outp, on) }.to_vec(); unsafe { free(outp as *mut core::ffi::c_void) }; Rc::new(V::Bytes(body)) }) }) }) }) }\n")
	}
	if usesForeign(p, "getNat") {
		b.WriteString("fn getNat() -> Rc<V> { vfun(move |_u: Rc<V>| -> Rc<V> { let mut s = String::new(); std::io::stdin().read_line(&mut s).unwrap(); Rc::new(V::Nat(_big_from_u64(s.trim().parse::<u64>().unwrap()))) }) }\n")
	}
	if usesForeign(p, "timeNanos") {
		b.WriteString("fn timeNanos() -> Rc<V> { vfun(move |_u: Rc<V>| -> Rc<V> { let ns = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos() as u64; Rc::new(V::Nat(_big_from_u64(ns))) }) }\n")
	}
	// D3 machine floats (f64) — pure host bodies (native f64 arithmetic). A Float is
	// a V::Float(f64). `Float` is a foreign TYPE but survives erasure as ok/err's type
	// argument, so it needs a trivial runtime-irrelevant body (like ch205's Pid).
	if usesForeign(p, "Float") {
		b.WriteString("fn Float() -> Rc<V> { unit() }\n")
	}
	if usesForeign(p, "fromNat") {
		b.WriteString("fn fromNat() -> Rc<V> { vfun(|n: Rc<V>| Rc::new(V::Float(_big_to_string(_nat(&n)).parse::<f64>().unwrap()))) }\n")
	}
	if usesForeign(p, "fadd") {
		b.WriteString("fn fadd() -> Rc<V> { vfun(|a: Rc<V>| vfun(move |b: Rc<V>| Rc::new(V::Float(_float(&a) + _float(&b))))) }\n")
	}
	if usesForeign(p, "fsub") {
		b.WriteString("fn fsub() -> Rc<V> { vfun(|a: Rc<V>| vfun(move |b: Rc<V>| Rc::new(V::Float(_float(&a) - _float(&b))))) }\n")
	}
	if usesForeign(p, "fmul") {
		b.WriteString("fn fmul() -> Rc<V> { vfun(|a: Rc<V>| vfun(move |b: Rc<V>| Rc::new(V::Float(_float(&a) * _float(&b))))) }\n")
	}
	if usesForeign(p, "fdiv") {
		b.WriteString("fn fdiv() -> Rc<V> { vfun(|a: Rc<V>| vfun(move |b: Rc<V>| Rc::new(V::Float(_float(&a) / _float(&b))))) }\n")
	}
	if usesForeign(p, "fabsP") {
		b.WriteString("fn fabsP() -> Rc<V> { vfun(|x: Rc<V>| Rc::new(V::Float(_float(&x).abs()))) }\n")
	}
	if usesForeign(p, "floatToNat") {
		b.WriteString("fn floatToNat() -> Rc<V> { vfun(|x: Rc<V>| Rc::new(V::Nat(_big_from_dec(&format!(\"{:.0}\", _float(&x).trunc()))))) }\n")
	}
	if usesForeign(p, "fleqN") {
		b.WriteString("fn fleqN() -> Rc<V> { vfun(|a: Rc<V>| vfun(move |b: Rc<V>| if _float(&a) <= _float(&b) { Rc::new(V::Nat(_big_from_u64(1))) } else { Rc::new(V::Nat(Vec::new())) })) }\n")
	}
	if usesForeign(p, "fsqrt") {
		b.WriteString("fn fsqrt() -> Rc<V> { vfun(|x: Rc<V>| Rc::new(V::Float(_float(&x).sqrt()))) }\n")
	}
	if usesForeign(p, "fpow") {
		b.WriteString("fn fpow() -> Rc<V> { vfun(|b: Rc<V>| vfun(move |e: Rc<V>| Rc::new(V::Float(_float(&b).powf(_float(&e)))))) }\n")
	}
	if usesForeign(p, "dot2") {
		b.WriteString("fn dot2() -> Rc<V> { vfun(|a0: Rc<V>| vfun(move |a1: Rc<V>| { let a0 = a0.clone(); vfun(move |b0: Rc<V>| { let a0 = a0.clone(); let a1 = a1.clone(); vfun(move |b1: Rc<V>| Rc::new(V::Float(_float(&a0) * _float(&b0) + _float(&a1) * _float(&b1)))) }) })) }\n")
	}
	if usesForeign(p, "dotList") {
		b.WriteString("fn dotList() -> Rc<V> { vfun(|xs: Rc<V>| vfun(move |ys: Rc<V>| Rc::new(V::Float(_fldot(xs.clone(), ys.clone()))))) }\n")
	}
	// D5 float IO: parseFloat/getFloat/printFloat with canonical ECMAScript Number::toString
	// dressing. No regex crate — manual validator. Precision-search loop (p=0..=17) finds
	// shortest round-trip digits from format!("{:.*e}", p, x); _s2h decodes packed String.
	if usesForeign(p, "parseFloat") || usesForeign(p, "getFloat") || usesForeign(p, "printFloat") {
		// Validator matches the binding regex ^[+-]?((\d+(\.\d*)?)|(\.\d+))([eE][+-]?\d+)?$
		// exactly: accept iff sawDigitBeforeDot || (sawDot && sawDigitAfterDot).
		// A lone dot (or sign + dot) lacks both, so it is correctly rejected.
		b.WriteString("fn __is_valid_float_str(s: &str) -> bool {\n")
		b.WriteString("    let s = s.as_bytes(); let n = s.len(); if n == 0 { return false; }\n")
		b.WriteString("    let mut i = 0usize;\n")
		b.WriteString("    if i < n && (s[i] == b'+' || s[i] == b'-') { i += 1; }\n")
		b.WriteString("    let d0 = i; while i < n && s[i].is_ascii_digit() { i += 1; }\n")
		b.WriteString("    let saw_before = i > d0;\n")
		b.WriteString("    let saw_dot = i < n && s[i] == b'.';\n")
		b.WriteString("    if saw_dot { i += 1; }\n")
		b.WriteString("    let d1 = i; if saw_dot { while i < n && s[i].is_ascii_digit() { i += 1; } }\n")
		b.WriteString("    let saw_after = saw_dot && i > d1;\n")
		b.WriteString("    if !saw_before && !saw_after { return false; }\n")
		b.WriteString("    if i < n && (s[i] == b'e' || s[i] == b'E') {\n")
		b.WriteString("        i += 1;\n")
		b.WriteString("        if i < n && (s[i] == b'+' || s[i] == b'-') { i += 1; }\n")
		b.WriteString("        let es = i; while i < n && s[i].is_ascii_digit() { i += 1; }\n")
		b.WriteString("        if i == es { return false; } // exponent must have digits\n")
		b.WriteString("    }\n")
		b.WriteString("    i == n\n")
		b.WriteString("}\n")
		b.WriteString("fn __fmtf(x: f64) -> String {\n")
		b.WriteString("    if x.is_nan() { return \"NaN\".to_string(); }\n")
		b.WriteString("    if x.is_infinite() { return (if x > 0.0 { \"Infinity\" } else { \"-Infinity\" }).to_string(); }\n")
		b.WriteString("    if x == 0.0 { return \"0\".to_string(); }\n")
		b.WriteString("    let sign = if x < 0.0 { \"-\" } else { \"\" };\n")
		b.WriteString("    let ax = x.abs();\n")
		b.WriteString("    let s = (0usize..=17).find_map(|p| {\n")
		b.WriteString("        let t = format!(\"{:.*e}\", p, ax);\n")
		b.WriteString("        if t.parse::<f64>().ok() == Some(ax) { Some(t) } else { None }\n")
		b.WriteString("    }).unwrap_or_else(|| format!(\"{:e}\", ax));\n")
		b.WriteString("    let ei = s.find('e').unwrap_or(s.len());\n")
		b.WriteString("    let mant = &s[..ei];\n")
		b.WriteString("    let exp: i32 = s[ei+1..].parse().unwrap_or(0);\n")
		b.WriteString("    let k = exp + 1;\n")
		b.WriteString("    let raw: String = mant.chars().filter(|&c| c != '.').collect();\n")
		b.WriteString("    let d: String = raw.trim_end_matches('0').to_string();\n")
		b.WriteString("    let d = if d.is_empty() { \"0\".to_string() } else { d };\n")
		b.WriteString("    let n = d.len() as i32;\n")
		b.WriteString("    let out = if n <= k && k <= 21 {\n")
		b.WriteString("        format!(\"{}{}\", d, \"0\".repeat((k - n) as usize))\n")
		b.WriteString("    } else if k > 0 && k <= 21 && k < n {\n")
		b.WriteString("        format!(\"{}.{}\", &d[..k as usize], &d[k as usize..])\n")
		b.WriteString("    } else if k > -6 && k <= 0 {\n")
		b.WriteString("        format!(\"0.{}{}\", \"0\".repeat((-k) as usize), d)\n")
		b.WriteString("    } else {\n")
		b.WriteString("        let base = if n > 1 { format!(\"{}.{}\", &d[..1], &d[1..]) } else { d.clone() };\n")
		b.WriteString("        let ek = k - 1;\n")
		b.WriteString("        if ek >= 0 { format!(\"{}e+{}\", base, ek) } else { format!(\"{}e-{}\", base, -ek) }\n")
		b.WriteString("    };\n")
		b.WriteString("    format!(\"{}{}\", sign, out)\n")
		b.WriteString("}\n")
	}
	if usesForeign(p, "parseFloat") {
		b.WriteString("fn parseFloat() -> Rc<V> { vfun(|s: Rc<V>| -> Rc<V> { let v = _s2h(&s); let vs = String::from_utf8_lossy(&v).to_string(); if __is_valid_float_str(&vs) { let f: f64 = vs.parse().unwrap_or(0.0); Rc::new(V::Ctor(1, \"some\", vec![unit(), Rc::new(V::Float(f))])) } else { Rc::new(V::Ctor(0, \"none\", vec![unit()])) } }) }\n")
	}
	if usesForeign(p, "getFloat") {
		b.WriteString("fn getFloat() -> Rc<V> { vfun(move |_u: Rc<V>| -> Rc<V> { let mut s = String::new(); std::io::stdin().read_line(&mut s).unwrap_or(0); let s = s.trim_end_matches(|c| c == '\\n' || c == '\\r').to_string(); if __is_valid_float_str(&s) { Rc::new(V::Float(s.parse().unwrap_or(0.0))) } else { Rc::new(V::Float(0.0)) } }) }\n")
	}
	if usesForeign(p, "printFloat") {
		b.WriteString("fn printFloat() -> Rc<V> { vfun(|x: Rc<V>| -> Rc<V> { let s = __fmtf(_float(&x)); let x2 = x.clone(); vfun(move |_u: Rc<V>| -> Rc<V> { println!(\"{}\", s); x2.clone() }) }) }\n")
	}
	// D4 interop: npDot is the uniform dot CAPABILITY (NumPy on py, OpenBLAS on C/LLVM);
	// on rust it is the portable reference floor.
	if usesForeign(p, "npDot") {
		b.WriteString("fn npDot() -> Rc<V> { vfun(|xs: Rc<V>| vfun(move |ys: Rc<V>| Rc::new(V::Float(_fldot(xs.clone(), ys.clone()))))) }\n")
	}
	// D4 interop: npMean — the reference floor (hand sum/count); py serves real numpy.mean.
	if usesForeign(p, "npMean") {
		b.WriteString("fn npMean() -> Rc<V> { vfun(|xs: Rc<V>| { let v = _flvec(xs.clone()); let n = v.len(); let s: f64 = v.iter().sum(); Rc::new(V::Float(if n > 0 { s / n as f64 } else { 0.0 })) }) }\n")
	}
	if usesForeign(p, "gemmSum") {
		b.WriteString("fn gemmSum() -> Rc<V> { vfun(|m: Rc<V>| vfun(move |k: Rc<V>| { let m = m.clone(); vfun(move |n: Rc<V>| { let m = m.clone(); let k = k.clone(); vfun(move |a: Rc<V>| { let m = m.clone(); let k = k.clone(); let n = n.clone(); vfun(move |bm: Rc<V>| { let mm: usize = _big_to_string(_nat(&m)).parse().unwrap(); let kk: usize = _big_to_string(_nat(&k)).parse().unwrap(); let nn: usize = _big_to_string(_nat(&n)).parse().unwrap(); let av = _flvec(a.clone()); let bv = _flvec(bm.clone()); let mut s = 0.0; for i in 0..mm { for j in 0..nn { for l in 0..kk { s += av[i * kk + l] * bv[l * nn + j]; } } } Rc::new(V::Float(s)) }) }) }) })) }\n")
	}
	// D4 interop: npNorm — the sqrt(sum of squares) floor; py serves numpy.linalg.norm.
	if usesForeign(p, "npNorm") {
		b.WriteString("fn npNorm() -> Rc<V> { vfun(|xs: Rc<V>| { let v = _flvec(xs.clone()); let s: f64 = v.iter().map(|x| x * x).sum(); Rc::new(V::Float(s.sqrt())) }) }\n")
	}
	// D4 interop: npMax — the fold-max reference floor (base 0); py serves real numpy.max.
	if usesForeign(p, "npMax") {
		b.WriteString("fn npMax() -> Rc<V> { vfun(|xs: Rc<V>| { let v = _flvec(xs.clone()); let m = v.iter().cloned().fold(None, |acc: Option<f64>, x| Some(match acc { Some(a) if a >= x => a, _ => x })).unwrap_or(0.0); Rc::new(V::Float(m)) }) }\n")
	}
	// D4 interop: npVar — the 2-pass reference floor (mean, then mean of sq deviations).
	if usesForeign(p, "npVar") {
		b.WriteString("fn npVar() -> Rc<V> { vfun(|xs: Rc<V>| { let v = _flvec(xs.clone()); let n = v.len(); if n == 0 { return Rc::new(V::Float(0.0)); } let m: f64 = v.iter().sum::<f64>() / n as f64; let s: f64 = v.iter().map(|x| (x - m) * (x - m)).sum(); Rc::new(V::Float(s / n as f64)) }) }\n")
	}
	// D4 interop: npMatSum — the triple-loop reference floor; py serves real numpy matmul.
	if usesForeign(p, "npMatSum") {
		b.WriteString("fn npMatSum() -> Rc<V> { vfun(|m: Rc<V>| vfun(move |k: Rc<V>| { let m = m.clone(); vfun(move |n: Rc<V>| { let m = m.clone(); let k = k.clone(); vfun(move |a: Rc<V>| { let m = m.clone(); let k = k.clone(); let n = n.clone(); vfun(move |bm: Rc<V>| { let mm: usize = _big_to_string(_nat(&m)).parse().unwrap(); let kk: usize = _big_to_string(_nat(&k)).parse().unwrap(); let nn: usize = _big_to_string(_nat(&n)).parse().unwrap(); let av = _flvec(a.clone()); let bv = _flvec(bm.clone()); let mut s = 0.0; for i in 0..mm { for j in 0..nn { for l in 0..kk { s += av[i * kk + l] * bv[l * nn + j]; } } } Rc::new(V::Float(s)) }) }) }) })) }\n")
	}
	// E4 / R-INFRA: the LIVE data-plane binding. The same RESP-over-a-raw-socket wire
	// the Go/JVM/JS backends speak, now on Rust (std::net, dep-free) — kv = SET/GET,
	// queue = Valkey LIST LPUSH/RPOP (FIFO). A packed-string V::Nat is marshalled to/from
	// host bytes by _s2h/_h2s (the same base-256 packing the other backends use). This is
	// the fourth source backend's live body, closing the cross-backend live data plane.
	if usesRustStrMarshal(p) {
		b.WriteString(rustStrMarshal)
	}
	// Stream prims: pure ops over the packed-String codec (_s2h/_h2s). No world token.
	if usesForeign(p, "byteLen") {
		b.WriteString("fn byteLen() -> Rc<V> { vfun(|c: Rc<V>| Rc::new(V::Nat(_big_from_u64(_s2h(&c).len() as u64)))) }\n")
	}
	if usesForeign(p, "splitOn") {
		b.WriteString("fn splitOn() -> Rc<V> { vfun(|sep: Rc<V>| { let sb = _natusize(&sep) as u8; vfun(move |c: Rc<V>| { let data = _s2h(&c); let parts: Vec<&[u8]> = data.split(|&z| z == sb).collect(); let mut lst = Rc::new(V::Ctor(0, \"nil\", vec![unit()])); for part in parts.iter().rev() { lst = Rc::new(V::Ctor(1, \"cons\", vec![unit(), _h2s(part), lst])); } lst }) }) }\n")
	}
	if usesForeign(p, "jsonStrField") {
		b.WriteString("fn _find(h: &[u8], n: &[u8]) -> Option<usize> { if n.is_empty() { return Some(0); } if n.len() > h.len() { return None; } for i in 0..=(h.len()-n.len()) { if &h[i..i+n.len()] == n { return Some(i); } } None }\n")
		b.WriteString("fn jsonStrField() -> Rc<V> { vfun(|field: Rc<V>| { let field = field.clone(); vfun(move |doc: Rc<V>| { let fnb = _s2h(&field); let ds = _s2h(&doc); let mut needle = vec![b'\"']; needle.extend_from_slice(&fnb); needle.push(b'\"'); let none = Rc::new(V::Ctor(0, \"none\", vec![unit()])); match _find(&ds, &needle) { None => none, Some(i) => { let mut j = i + needle.len(); while j < ds.len() && (ds[j]==b' '||ds[j]==b'\\t'||ds[j]==b':') { j += 1; } if j < ds.len() && ds[j]==b'\"' { j += 1; let mut k = j; while k < ds.len() && ds[k]!=b'\"' { k += 1; } Rc::new(V::Ctor(1, \"some\", vec![unit(), _h2s(&ds[j..k])])) } else { none } } } }) }) }\n")
	}
	if usesForeign(p, "sqlQuote") {
		b.WriteString("fn sqlQuote() -> Rc<V> { vfun(|s: Rc<V>| { let inp = _s2h(&s); let mut out: Vec<u8> = Vec::new(); out.push(b'\\''); for &z in inp.iter() { if z == b'\\'' { out.push(b'\\''); } out.push(z); } out.push(b'\\''); _h2s(&out) }) }\n")
	}
	// Higher-order stream ops: host loop applying an erased Rune step per line / per file.
	// foldLines reads raw bytes via std::fs::read, splits on b'\n', drops trailing empty.
	// foldDir recursively walks a dir via _foldwalk, sorted, matching the suffix.
	if usesForeign(p, "foldLines") {
		// foldLines: 5 curried args (_s/path/step/s0/unit). The `path` variable is
		// captured by `|step|` from `|path|`'s scope, making it a captured variable in
		// `|step|`. To satisfy the Fn constraint, clone it inside the `|step|` block
		// before the inner `|s0|` closure can capture it by move.
		b.WriteString("fn foldLines() -> Rc<V> { vfun(|_s: Rc<V>| vfun(move |path: Rc<V>| vfun(move |step: Rc<V>| { let path = path.clone(); vfun(move |s0: Rc<V>| { let step = step.clone(); let s0 = s0.clone(); let path = path.clone(); vfun(move |_u: Rc<V>| { let pth = String::from_utf8_lossy(&_s2h(&path)).to_string(); let data = match std::fs::read(&pth) { Ok(d) => d, Err(_) => return s0.clone() }; let mut parts: Vec<&[u8]> = data.split(|&z| z == b'\\n').collect(); if let Some(last) = parts.last() { if last.is_empty() { parts.pop(); } } let mut s = s0.clone(); for ln in parts { s = ap(ap(ap(step.clone(), s.clone()), _h2s(ln)), unit()); } s }) }) }))) }\n")
	}
	if usesForeign(p, "foldDir") {
		// foldDir: 6 curried args (_s/dirc/suf/step/s0/unit). Each captured variable
		// that must reach the innermost closure is cloned at the level where it first
		// becomes a captured var (not a param), so the Fn constraint is satisfied.
		b.WriteString("fn _foldwalk(dir: &std::path::Path, sfx: &[u8], step: &Rc<V>, s: &mut Rc<V>) { let mut ents: Vec<_> = match std::fs::read_dir(dir) { Ok(e) => e.filter_map(|x| x.ok()).collect(), Err(_) => return }; ents.sort_by_key(|e| e.file_name()); for e in ents { let full = e.path(); if full.is_dir() { _foldwalk(&full, sfx, step, s); } else { let name = full.to_string_lossy().into_owned(); if name.as_bytes().ends_with(sfx) { if let Ok(data) = std::fs::read(&full) { *s = ap(ap(ap(step.clone(), s.clone()), _h2s(&data)), unit()); } } } } }\n")
		b.WriteString("fn foldDir() -> Rc<V> { vfun(|_s: Rc<V>| vfun(move |dirc: Rc<V>| vfun(move |suf: Rc<V>| { let dirc = dirc.clone(); vfun(move |step: Rc<V>| { let dirc = dirc.clone(); let suf = suf.clone(); vfun(move |s0: Rc<V>| { let step = step.clone(); let s0 = s0.clone(); let dirc = dirc.clone(); let suf = suf.clone(); vfun(move |_u: Rc<V>| { let d = String::from_utf8_lossy(&_s2h(&dirc)).to_string(); let sfx = _s2h(&suf); let mut s = s0.clone(); _foldwalk(std::path::Path::new(&d), &sfx, &step, &mut s); s }) }) }) }))) }\n")
	}
	// WRITE-STREAM ops: Handle (opaque i64 token into a thread-local File table), openWrite/
	// writeChunk/closeWrite, and sortFile (bytewise external line sort). The token pattern
	// mirrors __SOCKS/__SOCKID for network handles.
	if usesForeign(p, "openWrite") || usesForeign(p, "writeChunk") || usesForeign(p, "closeWrite") {
		b.WriteString("thread_local! { static __WH: std::cell::RefCell<std::collections::HashMap<i64, std::fs::File>> = std::cell::RefCell::new(std::collections::HashMap::new()); static __WHID: std::cell::RefCell<i64> = std::cell::RefCell::new(0); }\n")
	}
	if usesForeign(p, "openWrite") {
		b.WriteString("fn openWrite() -> Rc<V> { vfun(|path: Rc<V>| { let path = path.clone(); vfun(move |_u: Rc<V>| { let pth = String::from_utf8_lossy(&_s2h(&path)).to_string(); match std::fs::File::create(&pth) { Ok(f) => { let id = __WHID.with(|c| { let mut c = c.borrow_mut(); *c += 1; *c }); __WH.with(|m| { m.borrow_mut().insert(id, f); }); _nat_of_usize(id as usize) } Err(_) => _nat_of_usize(0) } }) }) }\n")
	}
	if usesForeign(p, "writeChunk") {
		b.WriteString("fn writeChunk() -> Rc<V> { vfun(|h: Rc<V>| { let h = h.clone(); vfun(move |c: Rc<V>| { let h = h.clone(); vfun(move |_u: Rc<V>| { use std::io::Write; let id = _natusize(&h) as i64; let mut bytes = _s2h(&c); bytes.push(b'\\n'); __WH.with(|m| { if let Some(f) = m.borrow_mut().get_mut(&id) { let _ = f.write_all(&bytes); } }); h.clone() }) }) }) }\n")
	}
	if usesForeign(p, "closeWrite") {
		b.WriteString("fn closeWrite() -> Rc<V> { vfun(|h: Rc<V>| { let h = h.clone(); vfun(move |_u: Rc<V>| { let id = _natusize(&h) as i64; __WH.with(|m| { m.borrow_mut().remove(&id); }); unit() }) }) }\n")
	}
	if usesForeign(p, "sortFile") {
		b.WriteString("fn sortFile() -> Rc<V> { vfun(|inp: Rc<V>| { let inp = inp.clone(); vfun(move |outp: Rc<V>| { let inp = inp.clone(); let outp = outp.clone(); vfun(move |_u: Rc<V>| { let ip = String::from_utf8_lossy(&_s2h(&inp)).to_string(); let op = String::from_utf8_lossy(&_s2h(&outp)).to_string(); let data = match std::fs::read(&ip) { Ok(d) => d, Err(_) => { let _ = std::fs::write(&op, b\"\"); return unit(); } }; let mut lines: Vec<&[u8]> = data.split(|&z| z == b'\\n').collect(); if let Some(last) = lines.last() { if last.is_empty() { lines.pop(); } } lines.sort(); let mut out: Vec<u8> = Vec::new(); for ln in lines { out.extend_from_slice(ln); out.push(b'\\n'); } let _ = std::fs::write(&op, &out); unit() }) }) }) }\n")
	}
	if usesForeign(p, "dbApply") {
		b.WriteString("fn dbApply() -> Rc<V> { vfun(|db: Rc<V>| { let db = db.clone(); vfun(move |sql: Rc<V>| { let db = db.clone(); let sql = sql.clone(); vfun(move |_u: Rc<V>| { let d = String::from_utf8_lossy(&_s2h(&db)).to_string(); let s = String::from_utf8_lossy(&_s2h(&sql)).to_string(); let _ = std::process::Command::new(\"sqlite3\").arg(&d).arg(format!(\".read {}\", s)).output(); unit() }) }) }) }\n")
	}
	if usesForeign(p, "printStrCode") {
		b.WriteString("fn printStrCode() -> Rc<V> { vfun(|c: Rc<V>| { let c = c.clone(); vfun(move |_u: Rc<V>| { println!(\"{}\", String::from_utf8_lossy(&_s2h(&c))); c.clone() }) }) }\n")
	}
	// D6 / R-EFFECT: the standard OS vocabulary on Rust (env / file / argv / process-exit),
	// the cross-backend parity companion to the js/py/go/erl bodies. Strings marshal through
	// the same _s2h/_h2s; the empty-string / error sentinel is the packed bignum 1, matching
	// the other backends. Brings Rust to full D6 conformance so a Rust E4/infra program can
	// read its environment and files like every other source backend.
	if usesForeign(p, "getEnvCode") {
		b.WriteString("fn getEnvCode() -> Rc<V> { vfun(|c: Rc<V>| { let c = c.clone(); vfun(move |_u: Rc<V>| { let key = String::from_utf8_lossy(&_s2h(&c)).to_string(); let val = std::env::var(&key).unwrap_or_default(); _h2s(val.as_bytes()) }) }) }\n")
	}
	if usesForeign(p, "readFileCode") {
		b.WriteString("fn readFileCode() -> Rc<V> { vfun(|c: Rc<V>| { let c = c.clone(); vfun(move |_u: Rc<V>| { let path = String::from_utf8_lossy(&_s2h(&c)).to_string(); match std::fs::read(&path) { Ok(d) => _h2s(&d), Err(_) => Rc::new(V::Nat(_big_from_u64(1))) } }) }) }\n")
	}
	if usesForeign(p, "writeFileCode") {
		b.WriteString("fn writeFileCode() -> Rc<V> { vfun(|p: Rc<V>| vfun(move |c: Rc<V>| { let p = p.clone(); vfun(move |_u: Rc<V>| { let path = String::from_utf8_lossy(&_s2h(&p)).to_string(); let _ = std::fs::write(&path, _s2h(&c)); c.clone() }) })) }\n")
	}
	if usesForeign(p, "argCountCode") {
		b.WriteString("fn argCountCode() -> Rc<V> { vfun(|_u: Rc<V>| { let n = std::env::args().count().saturating_sub(1) as u64; Rc::new(V::Nat(_big_from_u64(n))) }) }\n")
	}
	if usesForeign(p, "argAtCode") {
		b.WriteString("fn argAtCode() -> Rc<V> { vfun(|i: Rc<V>| { let i = i.clone(); vfun(move |_u: Rc<V>| { let idx: usize = _big_to_string(_nat(&i)).parse::<usize>().unwrap_or(0) + 1; let args: Vec<String> = std::env::args().collect(); if idx < args.len() { _h2s(args[idx].as_bytes()) } else { Rc::new(V::Nat(_big_from_u64(1))) } }) }) }\n")
	}
	if usesForeign(p, "exitWith") {
		b.WriteString("fn exitWith() -> Rc<V> { vfun(|n: Rc<V>| { let n = n.clone(); vfun(move |_u: Rc<V>| { let code: i32 = _big_to_string(_nat(&n)).parse::<i32>().unwrap_or(0); std::process::exit(code) }) }) }\n")
	}
	if usesLiveKV(p) {
		b.WriteString(rustRespRuntime)
	}
	if usesForeign(p, "kvSetLive") {
		b.WriteString("fn kvSetLive() -> Rc<V> { vfun(|k: Rc<V>| vfun(move |v: Rc<V>| { let k = k.clone(); vfun(move |_u: Rc<V>| { _resp(&[b\"SET\".to_vec(), _s2h(&k), _s2h(&v)]); v.clone() }) })) }\n")
	}
	if usesForeign(p, "kvGetLive") {
		b.WriteString("fn kvGetLive() -> Rc<V> { vfun(|k: Rc<V>| vfun(move |_u: Rc<V>| _h2s(&_resp(&[b\"GET\".to_vec(), _s2h(&k)])))) }\n")
	}
	if usesForeign(p, "enqueueLive") {
		b.WriteString("fn enqueueLive() -> Rc<V> { vfun(|q: Rc<V>| vfun(move |m: Rc<V>| { let q = q.clone(); vfun(move |_u: Rc<V>| { _resp(&[b\"LPUSH\".to_vec(), _s2h(&q), _s2h(&m)]); m.clone() }) })) }\n")
	}
	if usesForeign(p, "dequeueLive") {
		b.WriteString("fn dequeueLive() -> Rc<V> { vfun(|q: Rc<V>| vfun(move |_u: Rc<V>| _h2s(&_resp(&[b\"RPOP\".to_vec(), _s2h(&q)])))) }\n")
	}
	for _, d := range p.Datas {
		if p.Nat != nil && d.ElimName == p.Nat.ElimName {
			emitNatRust(&b, *p.Nat)
			continue
		}
		for _, c := range d.Ctors {
			emitCtorRust(&b, c)
		}
		// B2 / R-IR: the eliminator is lowered to the shared IR once (LowerElim)
		// and emitted as an ordinary thunk — no eliminator-specific backend code.
		fmt.Fprintf(&b, "fn %s() -> Rc<V> { %s }\n", rustThunk(d.ElimName), em.expr(LowerElim(d), nil))
	}
	for _, def := range p.Defs {
		if p.Partials[def.Name] {
			// T2: a partial emits in two parts so deep tail recursion runs flat —
			//   <name>_step: the body (a marked tail call is a V::Bounce re-entering
			//                _step, no frame nests); <name>: apply _step, _tramp once.
			step := rustThunk(def.Name) + "_step"
			fmt.Fprintf(&b, "fn %s() -> Rc<V> { %s }\n", step, em.expr(def.Body, nil))
			fmt.Fprintf(&b, "fn %s() -> Rc<V> { %s }\n", rustThunk(def.Name), em.exprPartialPublic(def.Body, step, nil))
			continue
		}
		fmt.Fprintf(&b, "fn %s() -> Rc<V> { %s }\n", rustThunk(def.Name), em.expr(def.Body, nil))
	}
	b.WriteString("fn main() {\n")
	if p.Main != "" {
		// Run the show on a large-stack thread: deep erased recursion (unrolled
		// arithmetic, partial defs) would otherwise overflow the default stack —
		// the analogue of the Python backend's raised recursion limit.
		mainExpr := rustThunk(p.Main) + "()"
		if p.IOMain {
			// An IO main is a deferred world thunk (unit -> A): force by applying unit.
			mainExpr = fmt.Sprintf("ap(%s, unit())", mainExpr)
		}
		fmt.Fprintf(&b, "\tlet h = std::thread::Builder::new().stack_size(512*1024*1024)\n")
		fmt.Fprintf(&b, "\t\t.spawn(|| { println!(\"{}\", _show(&%s)); }).unwrap();\n", mainExpr)
		b.WriteString("\th.join().unwrap();\n")
	}
	b.WriteString("}\n")
	return TargetSource(b.String()), nil
}

// rustCurry nests one-argument closures binding params in order; body is the
// innermost expression with every param in scope. Each closure clones the params
// the deeper closures capture, so no closure moves a capture out (each stays Fn).
func rustCurry(params []string, body string) string {
	inner := body
	for i := len(params) - 1; i >= 0; i-- {
		var cl strings.Builder
		cl.WriteString("{ ")
		for _, s := range params[:i] {
			fmt.Fprintf(&cl, "let %s = %s.clone(); ", s, s)
		}
		fmt.Fprintf(&cl, "vfun(move |%s: Rc<V>| -> Rc<V> { %s }) }", params[i], inner)
		inner = cl.String()
	}
	return inner
}

// exprBounce emits a marked tail self/sibling call as a V::Bounce whose thunk
// re-enters the head partial's _step entry, so forcing it advances ONE iteration;
// the public driver (_tramp) loops without nesting. The move closure only clones its
// captures (every IVar emits `.clone()`), so it stays Fn.
func (em *rustEmitter) exprBounce(call Ir, env []string) string {
	var args []Ir
	t := call
	for {
		app, ok := t.(IApp)
		if !ok {
			break
		}
		args = append([]Ir{app.Arg}, args...)
		t = app.Fn
	}
	g, ok := t.(IGlobal)
	if !ok {
		return em.expr(call, env)
	}
	s := rustThunk(g.Name) + "_step()"
	for _, a := range args {
		s = fmt.Sprintf("ap(%s, %s)", s, em.expr(a, env))
	}
	// The inner `move` closure must capture FRESH clones, not the outer Fn closure's
	// own bindings (moving those out of an Fn closure is illegal). Pre-clone every
	// in-scope binder into a same-named local, so `move` moves the clone.
	var pre strings.Builder
	pre.WriteString("{ ")
	for _, e := range env {
		fmt.Fprintf(&pre, "let %s = %s.clone(); ", e, e)
	}
	return pre.String() + "Rc::new(V::Bounce(Rc::new(move || " + s + "))) }"
}

// exprPartialPublic emits a partial def's public entry: peel its parameter lambdas,
// apply the _step thunk to them, and drive (_tramp) the result once.
func (em *rustEmitter) exprPartialPublic(t Ir, step string, env []string) string {
	var params []string
	cur := t
	for {
		lam, ok := cur.(ILam)
		if !ok {
			break
		}
		n := freshRust(lam.Name, env)
		params = append(params, n)
		env = prepend(n, env)
		cur = lam.Body
	}
	app := step + "()"
	for _, pn := range params {
		app = fmt.Sprintf("ap(%s, %s.clone())", app, pn)
	}
	return rustCurry(params, "_tramp("+app+")")
}

func emitCtorRust(b *strings.Builder, c CtorSpec) {
	params := make([]string, c.Arity)
	args := make([]string, c.Arity)
	for i := range params {
		params[i] = fmt.Sprintf("a%d", i)
		args[i] = fmt.Sprintf("a%d.clone()", i)
	}
	body := fmt.Sprintf("Rc::new(V::Ctor(%d, %q, vec![%s]))", c.Tag, c.Name, strings.Join(args, ", "))
	fmt.Fprintf(b, "fn %s() -> Rc<V> { %s }\n", rustThunk(c.Name), rustCurry(params, body))
}

func emitNatRust(b *strings.Builder, n NatSpec) {
	fmt.Fprintf(b, "fn %s() -> Rc<V> { Rc::new(V::Nat(Vec::new())) }\n", rustThunk(n.Zero))
	fmt.Fprintf(b, "fn %s() -> Rc<V> { vfun(move |x: Rc<V>| -> Rc<V> { Rc::new(V::Nat(_big_succ(_nat(&x)))) }) }\n", rustThunk(n.Succ))
	body := "_nat_elim(c0.clone(), c1.clone(), x.clone())"
	fmt.Fprintf(b, "fn %s() -> Rc<V> { %s }\n", rustThunk(n.ElimName),
		rustCurry([]string{"m", "c0", "c1", "x"}, body))
}

type rustEmitter struct {
	natElim string
	accel   map[string]core.NatOp
}

func (em *rustEmitter) expr(t Ir, env []string) string {
	switch x := t.(type) {
	case IVar:
		if x.Idx < len(env) {
			return env[x.Idx] + ".clone()"
		}
		return fmt.Sprintf("_v%d.clone()", x.Idx)
	case IGlobal:
		return rustThunk(x.Name) + "()"
	case IForeign:
		// Host-linked accessor: the host defines `fn <primname>() -> Rc<V> { … }`.
		// A plain name (no _d suffix) keeps the FFI ABI distinct from def thunks.
		return rustName(primName(x.Name)) + "()"
	case IUnit:
		return "unit()"
	case ILit:
		// Native host literal marshalled at the FFI boundary (B4): a V::Int scalar
		// or V::Str (a dedicated value-domain case so strings never alias ints).
		if x.Kind == LitNat {
			// C7 / R-NUM: a compressed numeral deploys as a native V::Nat — the SAME
			// representation NatSpec gives nat (`V::Nat(empty)`, `_big_succ`),
			// arbitrary precision, O(1) source instead of a succ-chain.
			return fmt.Sprintf("Rc::new(V::Nat(_big_from_dec(%q)))", x.Nat)
		}
		if x.Kind == LitStr {
			return fmt.Sprintf("Rc::new(V::Str(%q.to_string()))", x.Str)
		}
		if x.Kind == LitPtr {
			// Opaque host pointer (B4): a dedicated V::Ptr case so it never aliases
			// an int, and _show renders it as a fixed marker, not its handle.
			return fmt.Sprintf("Rc::new(V::Ptr(%d))", x.Int)
		}
		return fmt.Sprintf("Rc::new(V::Int(%d))", x.Int)
	case ILam:
		n := freshRust(x.Name, env)
		// Clone the in-scope captures so the move closure stays Fn.
		var pre strings.Builder
		pre.WriteString("{ ")
		for _, e := range env {
			fmt.Fprintf(&pre, "let %s = %s.clone(); ", e, e)
		}
		fmt.Fprintf(&pre, "vfun(move |%s: Rc<V>| -> Rc<V> { %s }) }", n, em.expr(x.Body, prepend(n, env)))
		return pre.String()
	case IApp:
		if out, ok := em.accelDispatch(x, env); ok {
			return out
		}
		if out, ok := em.natDispatch(x, env); ok {
			return out
		}
		return fmt.Sprintf("ap(%s, %s)", em.expr(x.Fn, env), em.expr(x.Arg, env))
	case ILet:
		n := freshRust(x.Name, env)
		return fmt.Sprintf("{ let %s: Rc<V> = %s; %s }", n, em.expr(x.Val, env), em.expr(x.Body, prepend(n, env)))
	case IPair:
		return fmt.Sprintf("Rc::new(V::Pair(%s, %s))", em.expr(x.A, env), em.expr(x.B, env))
	case IFst:
		return fmt.Sprintf("_fst(%s)", em.expr(x.P, env))
	case ISnd:
		return fmt.Sprintf("_snd(%s)", em.expr(x.P, env))
	case IField:
		return fmt.Sprintf("_field(%s, %d)", em.expr(x.Scrut, env), x.Index)
	case IBounce:
		return em.exprBounce(x.Call, env)
	case ICase:
		scrut := em.expr(x.Scrut, env)
		var b strings.Builder
		fmt.Fprintf(&b, "(match _tag_of(&(%s)) {", scrut)
		for _, arm := range x.Arms {
			fmt.Fprintf(&b, " %d => %s,", arm.Tag, em.expr(arm.Body, env))
		}
		b.WriteString(" _ => _impossible() })")
		return b.String()
	default:
		panic("codegen(rust): unknown IR node")
	}
}

// accelDispatch emits a registered accel-op def on two args as native i64
// arithmetic (C7 / R-NUM Decision 4) through the `_nat_add`/`_nat_mul`/
// `_nat_monus` runtime helpers (unbox V::Int, compute, rebox). Monus is the
// saturating Peano monus (floors at 0). The i64 representation is the SAME
// NatSpec gives nat, so the result is interchangeable with the eliminator loop.
func (em *rustEmitter) accelDispatch(app IApp, env []string) (string, bool) {
	op, a, b, ok := accelMatch(app, em.accel)
	if !ok {
		return "", false
	}
	ea, eb := em.expr(a, env), em.expr(b, env)
	switch op {
	case core.NatOpAdd:
		return fmt.Sprintf("_nat_add(%s, %s)", ea, eb), true
	case core.NatOpMul:
		return fmt.Sprintf("_nat_mul(%s, %s)", ea, eb), true
	case core.NatOpMonus:
		return fmt.Sprintf("_nat_monus(%s, %s)", ea, eb), true
	case core.NatOpDiv:
		return fmt.Sprintf("_nat_div(%s, %s)", ea, eb), true
	case core.NatOpMod:
		return fmt.Sprintf("_nat_mod(%s, %s)", ea, eb), true
	}
	return "", false
}

func (em *rustEmitter) natDispatch(app IApp, env []string) (string, bool) {
	if em.natElim == "" {
		return "", false
	}
	var args []Ir
	t := Ir(app)
	for {
		a, ok := t.(IApp)
		if !ok {
			break
		}
		args = append([]Ir{a.Arg}, args...)
		t = a.Fn
	}
	g, ok := t.(IGlobal)
	if !ok || g.Name != em.natElim || len(args) < 4 {
		return "", false
	}
	c1lam, ok := args[2].(ILam)
	if !ok {
		return "", false
	}
	inner, ok := c1lam.Body.(ILam)
	if !ok || usesVar(inner.Body, 0) {
		return "", false
	}
	out := fmt.Sprintf("_nat_d(%s, %s, %s)",
		em.expr(args[1], env), em.expr(args[2], env), em.expr(args[3], env))
	for _, extra := range args[4:] {
		out = fmt.Sprintf("ap(%s, %s)", out, em.expr(extra, env))
	}
	return out, true
}

func freshRust(hint string, env []string) string {
	n := rustName(hint)
	if n == "" || n == "_" {
		n = "_x"
	}
	if rustReserved[n] {
		n = "_" + n
	}
	for {
		clash := false
		for _, e := range env {
			if e == n {
				clash = true
				break
			}
		}
		if !clash {
			return n
		}
		n += "_"
	}
}

// rustThunk is the top-level thunk name for a definition (suffix _d avoids
// clashing with the runtime helpers, which carry no suffix).
func rustThunk(n string) string { return rustName(n) + "_d" }

func rustName(n string) string {
	if m, ok := jsOpNames[n]; ok {
		n = m
	} else if i := strings.IndexByte(n, '$'); i > 0 {
		if m, ok := jsOpNames[n[:i]]; ok {
			n = m + n[i:]
		}
	}
	n = strings.ReplaceAll(n, "'", "_")
	n = strings.ReplaceAll(n, "$", "_")
	n = strings.ReplaceAll(n, ".", "_")
	if n == "" {
		n = "_x"
	}
	if c := n[0]; c >= '0' && c <= '9' {
		n = "_" + n
	}
	return n
}

var rustReserved = map[string]bool{
	"as": true, "break": true, "const": true, "continue": true, "crate": true,
	"dyn": true, "else": true, "enum": true, "extern": true, "false": true,
	"fn": true, "for": true, "if": true, "impl": true, "in": true, "let": true,
	"loop": true, "match": true, "mod": true, "move": true, "mut": true,
	"pub": true, "ref": true, "return": true, "self": true, "Self": true,
	"static": true, "struct": true, "super": true, "trait": true, "true": true,
	"type": true, "unsafe": true, "use": true, "where": true, "while": true,
	"async": true, "await": true,
}

// rustRuntime is the dynamic value enum and the shared helpers: application,
// machine-int access, the nat eliminator/destructor, the impossible head, and
// the structural show (erased unit fields are skipped, matching JS/Go).
const rustRuntime = `use std::rc::Rc;
enum V {
    Unit,
    Int(i64),                 // host machine int (FFI LitInt)
    Nat(Vec<u32>),            // builtin-nat: arbitrary-precision base-1e9 limbs (little-endian)
    Float(f64),               // D3 machine float (f64): host native double
    Str(String),
    Bytes(Vec<u8>),           // Phase 0 real byte string (Bin): arbitrary bytes
    Ptr(i64),
    Fun(Rc<dyn Fn(Rc<V>) -> Rc<V>>),
    Ctor(i64, &'static str, Vec<Rc<V>>),
    Pair(Rc<V>, Rc<V>),
    Bounce(Rc<dyn Fn() -> Rc<V>>), // T2 trampoline: a deferred tail call, forced by _tramp
}
// _tramp is the T2 driver: force a chain of deferred tail calls (bounces) until a
// real value surfaces. A partial's public entry drives once; a tail self/sibling
// call inside the _step body evaluates to a V::Bounce instead of nesting a frame.
fn _tramp(mut r: Rc<V>) -> Rc<V> {
    loop {
        let next = match &*r { V::Bounce(k) => k(), _ => return r };
        r = next;
    }
}
fn unit() -> Rc<V> { Rc::new(V::Unit) }
fn vfun<F: Fn(Rc<V>) -> Rc<V> + 'static>(f: F) -> Rc<V> { Rc::new(V::Fun(Rc::new(f))) }
fn ap(f: Rc<V>, x: Rc<V>) -> Rc<V> {
    match &*f { V::Fun(g) => g(x), _ => panic!("rune: applied a non-function") }
}
fn _int(v: &Rc<V>) -> i64 {
    match &**v { V::Int(n) => *n, _ => panic!("rune: expected an int") }
}
fn _fst(p: Rc<V>) -> Rc<V> {
    match &*p { V::Pair(a, _) => a.clone(), _ => panic!("rune: fst of a non-pair") }
}
fn _snd(p: Rc<V>) -> Rc<V> {
    match &*p { V::Pair(_, b) => b.clone(), _ => panic!("rune: snd of a non-pair") }
}
fn _tag_of(v: &Rc<V>) -> i64 {
    match &**v { V::Ctor(t, _, _) => *t, _ => panic!("rune: scrutinee is not a constructor") }
}
fn _field(v: Rc<V>, i: usize) -> Rc<V> {
    match &*v { V::Ctor(_, _, a) => a[i].clone(), _ => panic!("rune: field of a non-constructor") }
}
fn _impossible() -> Rc<V> { panic!("impossible: unmatched constructor tag") }
// Phase 0 byte-string (Bin) helpers: a V::Bytes carries arbitrary bytes; nats
// (small here: byte values < 256, lengths/indices < 1e9) cross via single-limb V::Nat.
fn _bytes<'a>(v: &'a Rc<V>) -> &'a Vec<u8> {
    match &**v { V::Bytes(b) => b, _ => panic!("rune: expected bytes") }
}
fn _natusize(v: &Rc<V>) -> usize {
    let l = _nat(v); if l.is_empty() { 0 } else { l[0] as usize }
}
fn _natbyte(v: &Rc<V>) -> u8 { (_natusize(v) % 256) as u8 }
fn _nat_of_usize(n: usize) -> Rc<V> {
    if n == 0 { Rc::new(V::Nat(Vec::new())) } else { Rc::new(V::Nat(vec![n as u32])) }
}
fn _binshow(b: &Vec<u8>) -> String {
    let mut s = String::from("\"");
    for &x in b {
        if x >= 0x20 && x < 0x7f && x != 0x22 && x != 0x5c { s.push(x as char); }
        else { s.push_str(&format!("\\x{:02x}", x)); }
    }
    s.push('"');
    s
}
// ---- naive arbitrary-precision nat: base-1e9 limbs (no std bignum), schoolbook
// ops, mirroring the C/LLVM native runtimes. Empty Vec is zero. ----
const BIG_BASE: u64 = 1_000_000_000;
fn _nat<'a>(v: &'a Rc<V>) -> &'a Vec<u32> {
    match &**v { V::Nat(l) => l, _ => panic!("rune: expected a nat") }
}
fn _float(v: &Rc<V>) -> f64 {
    match &**v { V::Float(x) => *x, _ => panic!("rune: expected a float") }
}
// _fldot: the portable arbitrary-length dot — walk two Rune FLists (fcons = tag 1,
// head in slot 0, tail in slot 1) in lockstep summing products. (Native backends
// route dotList through cblas_ddot; the rust source backend uses this reference.)
fn _fldot(mut xs: Rc<V>, mut ys: Rc<V>) -> f64 {
    let mut s = 0.0;
    loop {
        let xn = match &*xs { V::Ctor(1, _, a) => Some((a[0].clone(), a[1].clone())), _ => None };
        let yn = match &*ys { V::Ctor(1, _, a) => Some((a[0].clone(), a[1].clone())), _ => None };
        match (xn, yn) {
            (Some((xh, xt)), Some((yh, yt))) => { s += _float(&xh) * _float(&yh); xs = xt; ys = yt; }
            _ => break,
        }
    }
    s
}
// _flvec: flatten a Rune FList into a Vec<f64> (for gemmSum's flat row-major matrices).
fn _flvec(mut xs: Rc<V>) -> Vec<f64> {
    let mut v = Vec::new();
    loop {
        let nx = match &*xs { V::Ctor(1, _, a) => Some((_float(&a[0]), a[1].clone())), _ => None };
        match nx { Some((h, t)) => { v.push(h); xs = t; }, None => break }
    }
    v
}
fn _big_norm(mut l: Vec<u32>) -> Vec<u32> { while let Some(&0) = l.last() { l.pop(); } l }
fn _big_from_u64(mut n: u64) -> Vec<u32> {
    let mut l = Vec::new();
    while n > 0 { l.push((n % BIG_BASE) as u32); n /= BIG_BASE; }
    l
}
fn _big_from_dec(s: &str) -> Vec<u32> {
    let b = s.as_bytes();
    let mut l: Vec<u32> = Vec::new();
    let mut end = b.len();
    while end > 0 {
        let start = if end >= 9 { end - 9 } else { 0 };
        let mut limb: u32 = 0;
        for i in start..end { limb = limb * 10 + (b[i] - b'0') as u32; }
        l.push(limb);
        end = start;
    }
    _big_norm(l)
}
fn _big_cmp(a: &Vec<u32>, b: &Vec<u32>) -> i32 {
    if a.len() != b.len() { return if a.len() < b.len() { -1 } else { 1 }; }
    for i in (0..a.len()).rev() { if a[i] != b[i] { return if a[i] < b[i] { -1 } else { 1 }; } }
    0
}
fn _big_add(a: &Vec<u32>, b: &Vec<u32>) -> Vec<u32> {
    let n = a.len().max(b.len());
    let mut r = Vec::with_capacity(n + 1);
    let mut carry: u64 = 0;
    for i in 0..n {
        let mut s = carry;
        if i < a.len() { s += a[i] as u64; }
        if i < b.len() { s += b[i] as u64; }
        r.push((s % BIG_BASE) as u32);
        carry = s / BIG_BASE;
    }
    if carry > 0 { r.push(carry as u32); }
    _big_norm(r)
}
fn _big_mul(a: &Vec<u32>, b: &Vec<u32>) -> Vec<u32> {
    if a.is_empty() || b.is_empty() { return Vec::new(); }
    let mut r = vec![0u64; a.len() + b.len()];
    for i in 0..a.len() {
        let mut carry: u64 = 0;
        let ai = a[i] as u64;
        for j in 0..b.len() {
            let cur = r[i + j] + ai * (b[j] as u64) + carry;
            r[i + j] = cur % BIG_BASE;
            carry = cur / BIG_BASE;
        }
        r[i + b.len()] += carry;
    }
    _big_norm(r.iter().map(|&x| x as u32).collect())
}
fn _big_monus(a: &Vec<u32>, b: &Vec<u32>) -> Vec<u32> {
    if _big_cmp(a, b) <= 0 { return Vec::new(); }
    let mut r = Vec::with_capacity(a.len());
    let mut borrow: i64 = 0;
    for i in 0..a.len() {
        let mut d = a[i] as i64 - borrow - if i < b.len() { b[i] as i64 } else { 0 };
        if d < 0 { d += BIG_BASE as i64; borrow = 1; } else { borrow = 0; }
        r.push(d as u32);
    }
    _big_norm(r)
}
fn _big_succ(a: &Vec<u32>) -> Vec<u32> { _big_add(a, &_big_from_u64(1)) }
fn _big_to_string(l: &Vec<u32>) -> String {
    if l.is_empty() { return "0".to_string(); }
    let mut s = l[l.len() - 1].to_string();
    for i in (0..l.len() - 1).rev() { s.push_str(&format!("{:09}", l[i])); }
    s
}
fn _nat_elim(c0: Rc<V>, c1: Rc<V>, x: Rc<V>) -> Rc<V> {
    let mut acc = c0;
    let n = _nat(&x).clone();
    let mut k: Vec<u32> = Vec::new();
    while _big_cmp(&k, &n) < 0 {
        acc = ap(ap(c1.clone(), Rc::new(V::Nat(k.clone()))), acc);
        k = _big_succ(&k);
    }
    acc
}
fn _nat_d(c0: Rc<V>, c1: Rc<V>, x: Rc<V>) -> Rc<V> {
    let n = _nat(&x);
    if n.is_empty() { c0 } else { ap(ap(c1, Rc::new(V::Nat(_big_monus(n, &_big_from_u64(1))))), unit()) }
}
// schoolbook long division (base-1e9), MS-limb first with per-limb binary search.
// Returns (quotient, remainder). Div by zero: (0, a).
fn _big_divmod(a: &Vec<u32>, b: &Vec<u32>) -> (Vec<u32>, Vec<u32>) {
    if b.is_empty() { return (Vec::new(), a.clone()); }
    if _big_cmp(a, b) < 0 { return (Vec::new(), a.clone()); }
    let n = a.len();
    let mut q = vec![0u32; n];
    let mut r: Vec<u32> = Vec::new();
    let base = _big_from_u64(BIG_BASE);
    for i in (0..n).rev() {
        r = _big_add(&_big_mul(&r, &base), &_big_from_u64(a[i] as u64));
        let (mut lo, mut hi, mut d): (i64, i64, i64) = (0, (BIG_BASE - 1) as i64, 0);
        while lo <= hi {
            let mid = lo + (hi - lo) / 2;
            if _big_cmp(&_big_mul(b, &_big_from_u64(mid as u64)), &r) <= 0 { d = mid; lo = mid + 1; } else { hi = mid - 1; }
        }
        q[i] = d as u32;
        r = _big_monus(&r, &_big_mul(b, &_big_from_u64(d as u64)));
    }
    (_big_norm(q), _big_norm(r))
}
fn _nat_add(a: Rc<V>, b: Rc<V>) -> Rc<V> { Rc::new(V::Nat(_big_add(_nat(&a), _nat(&b)))) }
fn _nat_mul(a: Rc<V>, b: Rc<V>) -> Rc<V> { Rc::new(V::Nat(_big_mul(_nat(&a), _nat(&b)))) }
fn _nat_monus(a: Rc<V>, b: Rc<V>) -> Rc<V> { Rc::new(V::Nat(_big_monus(_nat(&a), _nat(&b)))) }
fn _nat_div(a: Rc<V>, b: Rc<V>) -> Rc<V> { Rc::new(V::Nat(_big_divmod(_nat(&a), _nat(&b)).0)) }
fn _nat_mod(a: Rc<V>, b: Rc<V>) -> Rc<V> { Rc::new(V::Nat(_big_divmod(_nat(&a), _nat(&b)).1)) }
fn _show(v: &Rc<V>) -> String {
    match &**v {
        V::Unit => "()".to_string(),
        V::Int(n) => n.to_string(),
        V::Nat(l) => _big_to_string(l),
        V::Float(x) => format!("{}", x),
        V::Str(s) => s.clone(),
        V::Bytes(b) => _binshow(b),
        V::Ptr(_) => "<ptr>".to_string(),
        V::Fun(_) => "<function>".to_string(),
        V::Bounce(_) => _show(&_tramp(v.clone())), // defensive: drivers resolve first
        V::Pair(a, b) => format!("({}, {})", _show(a), _show(b)),
        V::Ctor(_, name, args) => {
            let mut s = name.to_string();
            for a in args {
                if let V::Unit = &**a { continue; }
                let r = _show(a);
                if r.contains(' ') { s.push_str(&format!(" ({})", r)); }
                else { s.push(' '); s.push_str(&r); }
            }
            s
        }
    }
}
`

// usesRustStrMarshal reports whether any emitted body needs the packed-string <-> host
// marshalling (_s2h/_h2s): the live data-plane ops, the D6 string-valued OS ops, and
// the pure stream ops (byteLen/splitOn/jsonStrField/sqlQuote) which decode/encode the
// packed-string code exactly like the D6 file ops.
func usesRustStrMarshal(p Program) bool {
	return usesLiveKV(p) || usesStream(p) || usesForeign(p, "printStrCode") || usesForeign(p, "getEnvCode") ||
		usesForeign(p, "readFileCode") || usesForeign(p, "writeFileCode") || usesForeign(p, "argAtCode") ||
		usesForeign(p, "parseFloat")
}

// rustStrMarshal is the packed-string <-> host-bytes marshalling shared by the live
// data-plane ops and printStrCode: _s2h decodes a base-256 V::Nat to bytes by repeated
// divmod-by-256; _h2s folds bytes back — both byte-identical to the Go/JVM/JS backends.
var rustStrMarshal = `fn _big_divmod_small(l: &Vec<u32>, d: u64) -> (Vec<u32>, u64) {
    let base: u64 = 1_000_000_000;
    let mut rem: u64 = 0;
    let mut out = vec![0u32; l.len()];
    for i in (0..l.len()).rev() {
        let cur = rem * base + l[i] as u64;
        out[i] = (cur / d) as u32;
        rem = cur % d;
    }
    (_big_norm(out), rem)
}
fn _s2h(v: &Rc<V>) -> Vec<u8> {
    let mut b = _nat(v).clone();
    let one = _big_from_u64(1);
    let mut bytes: Vec<u8> = Vec::new();
    while _big_cmp(&b, &one) > 0 {
        let (q, r) = _big_divmod_small(&b, 256);
        bytes.push(r as u8);
        b = q;
    }
    bytes
}
fn _h2s(s: &[u8]) -> Rc<V> {
    let mut n = _big_from_u64(1);
    let m = _big_from_u64(256);
    for i in (0..s.len()).rev() {
        n = _big_add(&_big_mul(&n, &m), &_big_from_u64(s[i] as u64));
    }
    Rc::new(V::Nat(n))
}
`

// rustRespRuntime is the live-broker plumbing: address resolution + a RESP request/reply
// over a raw TCP socket (no third-party crate — std::net only). Emitted only when a live
// kv/queue op is referenced. Reuses rustStrMarshal's _s2h/_h2s for the payloads.
var rustRespRuntime = `fn _kv_addr() -> String {
    let mut u = std::env::var("WAVELET_KV_URL").unwrap_or_default();
    if let Some(rest) = u.strip_prefix("redis://") { u = rest.to_string(); }
    if u.is_empty() { u = "localhost:6379".to_string(); }
    u
}
fn _resp(args: &[Vec<u8>]) -> Vec<u8> {
    use std::io::{Write, Read, BufRead};
    let mut c = match std::net::TcpStream::connect(_kv_addr()) { Ok(c) => c, Err(_) => return Vec::new() };
    let mut req: Vec<u8> = Vec::new();
    req.extend_from_slice(format!("*{}\r\n", args.len()).as_bytes());
    for a in args {
        req.extend_from_slice(format!("${}\r\n", a.len()).as_bytes());
        req.extend_from_slice(a);
        req.extend_from_slice(b"\r\n");
    }
    if c.write_all(&req).is_err() { return Vec::new(); }
    let mut r = std::io::BufReader::new(c);
    let mut line = String::new();
    if r.read_line(&mut line).is_err() { return Vec::new(); }
    let line = line.trim_end_matches(|ch| ch == '\r' || ch == '\n').to_string();
    if line.is_empty() { return Vec::new(); }
    let lb = line.as_bytes();
    match lb[0] {
        b'+' => line[1..].as_bytes().to_vec(),
        b'$' => {
            let n: i64 = line[1..].parse().unwrap_or(-1);
            if n < 0 { return Vec::new(); }
            let mut buf = vec![0u8; (n as usize) + 2];
            if r.read_exact(&mut buf).is_err() { return Vec::new(); }
            buf.truncate(n as usize);
            buf
        }
        _ => Vec::new(),
    }
}
`

// rustIORuntime is the erased IO monad (R-EFFECT / C3): IO A is a deferred thunk
// encoded as a unit-argument closure, so `ap` forces it by applying unit; pureIO
// returns a constant thunk, bindIO sequences. Type arguments arrive as units.
func rustIORuntime() string {
	return "fn pureIO_d() -> Rc<V> { " + rustCurry([]string{"_a", "a", "_u"}, "a.clone()") + " }\n" +
		"fn bindIO_d() -> Rc<V> { " + rustCurry([]string{"_a", "_b", "m", "k", "_u"},
		"ap(ap(k.clone(), ap(m.clone(), unit())), unit())") + " }\n"
}

// rustQuotRuntime is the erased quotient builtin group (v2): a quotient compiles
// to its carrier, so qin is the identity on its point, qlift applies the lifted
// function directly, and the proof-valued members (qsound, qind) are
// unit-producers. Type and proof arguments arrive as units (no arity surgery).
var rustQuotRuntime = "fn qin_d() -> Rc<V> { " + rustCurry([]string{"_a", "_r", "x"}, "x.clone()") + " }\n" +
	"fn qsound_d() -> Rc<V> { " + rustCurry([]string{"_a", "_r", "_x", "_y", "_p"}, "unit()") + " }\n" +
	"fn qlift_d() -> Rc<V> { " + rustCurry([]string{"_a", "_r", "_b", "f", "_resp", "q"}, "ap(f.clone(), q.clone())") + " }\n" +
	"fn qind_d() -> Rc<V> { " + rustCurry([]string{"_a", "_r", "_p", "_h", "_q"}, "unit()") + " }\n"
