package codegen

import (
	"fmt"
	"sort"
	"strings"

	"goforge.dev/rune/v3/core"
)

// Wasm is the NINTH backend (R-NATIVE Cranelift/WASM node): it emits WebAssembly
// text (WAT) over the CLOSURE-CONVERTED IR (codegen/closure.go), runnable directly
// by `wasmtime run module.wat`. Where the LLVM backend (codegen/ll.go, the closest
// template) emits LLVM IR that links a C runtime, WASM emits a SELF-CONTAINED module:
// the runtime (linear-memory bump allocator, heap records for closures/constructors,
// a function table for `call_indirect`, the naive base-1e9 bignum, and a `$show`
// writer over WASI `fd_write`) is WAT emitted inline (wasmRuntime), because wasmtime
// runs a single `.wat` with no host linkage.
//
// VALUE REP: a Rune value is an i32 — an immediate small int `(n<<1)|1` (FFI LitInt)
// or an even-aligned heap pointer. The emitter never inspects the tag; it defers to
// the `rt_*` runtime helpers, so the rep is owned by ONE place (wasmRuntime).
//
// SUPPORTED FRAGMENT (byte-identical to the C/LLVM backends on this subset): builtin-
// nat arithmetic (zero/succ/NatElim + accel add/mul/monus), constructors + eliminators
// (CCase/CField over ListElim/NatElim/any datatype), curried closures + application,
// dependent pairs (CPair/CFst/CSnd), the erased token (CUnit), native int/nat literals
// (CLit{LitInt,LitNat}). UNSUPPORTED in v1 (the emitter returns a clear error, never
// broken WAT): LitStr/LitBytes/LitPtr, IForeign/CForeign (no host vocabulary in the
// WASI sandbox yet), and IO main. GC: none — a bump allocator only (v1); a program
// that out-allocates the 16 MiB initial memory traps. See the deliverable notes.
type Wasm struct{}

func (Wasm) Target() string { return "wasm" }

// Emit closure-converts the program and emits a self-contained WAT module: the inline
// runtime, every lifted code block + constructor/eliminator code block as a `(func)`,
// the definition thunks (lazy cached, as mutable globals), the function table the
// `call_indirect` apply reads, and `$rune_main` (evaluates the entry and `$show`s it),
// exported as `_start` so `wasmtime run` invokes it.
func (Wasm) Emit(p Program) (TargetSource, error) {
	// Reject the unsupported fragment up front with a clear error (HONESTY: never
	// emit broken WAT for a form we cannot lower).
	if err := wasmCheckSupported(p); err != nil {
		return "", err
	}

	cp := ClosureConvert(p)
	em := &wasmEmitter{codeIdx: map[string]int{}, strs: map[string]int{}}
	if p.Nat != nil {
		em.natElim = p.Nat.ElimName
		em.accel = p.Nat.Ops
	}

	var body strings.Builder

	// Constructor + eliminator code blocks and thunks.
	for _, d := range cp.Datas {
		if cp.Nat != nil && d.ElimName == cp.Nat.ElimName {
			em.emitNat(&body, *cp.Nat)
			continue
		}
		for _, c := range d.Ctors {
			em.emitCtor(&body, c)
		}
	}
	// The lifted code blocks (definitions' and eliminators' bodies).
	for _, blk := range cp.Blocks {
		em.emitBlock(&body, blk)
	}
	// Definition thunks (eliminators converted as CDefSpec, then user defs).
	for _, def := range cp.Defs {
		em.emitDefThunk(&body, def.Name, def.Body)
	}

	// $rune_main: evaluate the entry thunk and show it.
	body.WriteString("  (func $rune_main\n")
	if p.Main != "" {
		f := &wasmFunc{em: em}
		mainV := f.emit(&body, CGlobal{Name: p.Main}, nil)
		fmt.Fprintf(&body, "    (call $rt_show_line %s)\n", mainV)
	}
	body.WriteString("  )\n")

	// Assemble the module: header, the function-table type, the inline runtime, the
	// string-constant data, the program bodies, the table + elem, and the init/export.
	var b strings.Builder
	b.WriteString(";; Generated by rune emit (wasm backend) — the erased shadow, native via wasmtime.\n")
	b.WriteString(";; Run: wasmtime run module.wat  (WAT runs directly; the runtime is inline).\n")
	b.WriteString("(module\n")
	b.WriteString("  (type $codety (func (param i32 i32) (result i32)))\n")
	b.WriteString(wasmRuntime)
	b.WriteString("\n")
	// String-constant data segments (constructor names) + the fixed runtime messages,
	// laid out in the reserved low region [64, 4096). Each cstr is NUL-terminated.
	em.emitData(&b)
	b.WriteString("\n")
	b.WriteString(body.String())
	// The function table + elem: every code block by its assigned index.
	em.emitTable(&b)
	// init: seed UNIT, run main. Exported as _start so wasmtime invokes it.
	b.WriteString("  (func $_start (export \"_start\")\n")
	b.WriteString("    (global.set $UNIT (call $rt_mkcon (i32.const 0) (global.get $unit_name) (i32.const 0)))\n")
	b.WriteString("    (call $rune_main))\n")
	b.WriteString(")\n")
	return TargetSource(b.String()), nil
}

// wasmCheckSupported walks the program's IR and returns a clear error for any form the
// v1 WASM backend cannot lower (rather than emit broken WAT). Mirrors foreignNames'
// walk over every node kind so a nested unsupported form is found.
func wasmCheckSupported(p Program) error {
	var err error
	var walk func(Ir)
	walk = func(t Ir) {
		if err != nil {
			return
		}
		switch x := t.(type) {
		case IForeign:
			err = fmt.Errorf("codegen(wasm): foreign %q is not supported in v1 (no WASI host vocabulary yet)", x.Name)
		case ILit:
			switch x.Kind {
			case LitInt, LitNat:
				// supported
			case LitStr:
				err = fmt.Errorf("codegen(wasm): string literals are not supported in v1")
			case LitPtr:
				err = fmt.Errorf("codegen(wasm): opaque host pointers are not supported in v1")
			}
		case ILam:
			walk(x.Body)
		case IApp:
			walk(x.Fn)
			walk(x.Arg)
		case ILet:
			walk(x.Val)
			walk(x.Body)
		case IPair:
			walk(x.A)
			walk(x.B)
		case IFst:
			walk(x.P)
		case ISnd:
			walk(x.P)
		case IField:
			walk(x.Scrut)
		case ICase:
			walk(x.Scrut)
			for _, arm := range x.Arms {
				walk(arm.Body)
			}
		}
	}
	for _, d := range p.Defs {
		walk(d.Body)
	}
	if err != nil {
		return err
	}
	if p.IOMain {
		return fmt.Errorf("codegen(wasm): IO main is not supported in v1")
	}
	return nil
}

// wasmEmitter renders CIr terms to WAT. Like llEmitter it knows the nat eliminator's
// name + the accel table, accumulates constructor-name string constants (interned into
// the data segment), and assigns each emitted code block a function-table index so
// `call_indirect` can reach it.
type wasmEmitter struct {
	natElim string
	accel   map[string]core.NatOp

	// codeIdx maps a code-block func name (without leading $) to its table index, in
	// first-seen order. The order is also the (elem) order.
	codeIdx   map[string]int
	codeOrder []string

	// strs maps a string constant (constructor name) to its byte offset in the data
	// segment, allocated bump-style from strBase upward.
	strs     map[string]int
	strOrder []string
	strBytes int
}

// codeRef registers (on first sight) a code-block name and returns its table index.
func (em *wasmEmitter) codeRef(name string) int {
	if idx, ok := em.codeIdx[name]; ok {
		return idx
	}
	idx := len(em.codeOrder)
	em.codeIdx[name] = idx
	em.codeOrder = append(em.codeOrder, name)
	return idx
}

// strBase is where constructor-name cstrs live: above the iovec/messages, below the
// show scratch buffer (4096). The runtime's reserved low region is [0,4096): the iovec
// is at [16,24), fixed runtime messages at [32,512), and interned cstrs at [512,4096).

// wasmStrBase is where interned constructor-name / numeral cstrs begin (above the
// fixed runtime messages at [32,512)).
const wasmStrBase = 512

// wasmShowBuf is the show scratch buffer base; interned cstrs must stay below it.
const wasmShowBuf = 4096

// intern registers a string constant and returns its byte offset.
func (em *wasmEmitter) intern(s string) int {
	if off, ok := em.strs[s]; ok {
		return off
	}
	off := wasmStrBase + em.strBytes
	if off+len(s)+1 > wasmShowBuf {
		// Out of reserved cstr space; v1 caps interned constants at ~3.5 KiB. A real
		// program rarely needs this much in names, but be honest about the bound.
		panic("codegen(wasm): interned string constants exceed the reserved region")
	}
	em.strs[s] = off
	em.strOrder = append(em.strOrder, s)
	em.strBytes += len(s) + 1 // + NUL
	return off
}

// emitData writes the data segments: the fixed runtime messages (referenced by the
// runtime via $fn_msg/$abort_msg/$unit_name globals) and the interned constructor-name
// cstrs. The globals are declared here too (offsets are known only after interning).
func (em *wasmEmitter) emitData(b *strings.Builder) {
	// Fixed runtime messages live at [32,512), referenced by the runtime via the
	// $fn_msg/$abort_msg/$unit_name globals (the iovec occupies [16,32)).
	fnMsg := "<function>"
	abortMsg := "rune-wasm: impossible (unmatched constructor tag)\n"
	unitName := "" // the boxed unit's con name is unused by show (UNIT is special-cased)

	fnOff := 32
	abortOff := fnOff + len(fnMsg) + 1
	unitOff := abortOff + len(abortMsg) + 1
	if unitOff+len(unitName)+1 > wasmStrBase {
		panic("codegen(wasm): fixed runtime messages overflow the reserved region")
	}

	fmt.Fprintf(b, "  (global $fn_msg i32 (i32.const %d))\n", fnOff)
	fmt.Fprintf(b, "  (global $abort_msg i32 (i32.const %d))\n", abortOff)
	fmt.Fprintf(b, "  (global $abort_len i32 (i32.const %d))\n", len(abortMsg))
	fmt.Fprintf(b, "  (global $unit_name i32 (i32.const %d))\n", unitOff)
	fmt.Fprintf(b, "  (data (i32.const %d) %s)\n", fnOff, wasmDataStr(fnMsg))
	fmt.Fprintf(b, "  (data (i32.const %d) %s)\n", abortOff, wasmDataStr(abortMsg))
	fmt.Fprintf(b, "  (data (i32.const %d) %s)\n", unitOff, wasmDataStr(unitName))

	for _, s := range em.strOrder {
		fmt.Fprintf(b, "  (data (i32.const %d) %s)\n", em.strs[s], wasmDataStr(s))
	}
}

// emitTable writes the function table sized to hold every registered code block, and
// the (elem) that installs each at its assigned index.
func (em *wasmEmitter) emitTable(b *strings.Builder) {
	n := len(em.codeOrder)
	fmt.Fprintf(b, "  (table %d funcref)\n", n)
	if n > 0 {
		b.WriteString("  (elem (i32.const 0)")
		for _, name := range em.codeOrder {
			fmt.Fprintf(b, " $%s", name)
		}
		b.WriteString(")\n")
	}
}

// wasmFunc tracks per-function emission state. A code block / def thunk body lowers a
// CIr to a SEQUENCE of `(local.set $tN value)` statements and returns the WAT
// expression `(local.get $tN)` naming the result, so nested control flow (CCase) is
// straightforward. Locals are declared lazily and flushed into the func header.
type wasmFunc struct {
	em    *wasmEmitter
	tmp   int
	decls []string // local declarations to splice into the func header
}

// fresh allocates a fresh i32 local and returns its name (e.g. "$t3").
func (f *wasmFunc) fresh() string {
	f.tmp++
	name := fmt.Sprintf("$t%d", f.tmp)
	f.decls = append(f.decls, name)
	return name
}

// localDecls renders the accumulated local declarations for the func header.
func (f *wasmFunc) localDecls() string {
	if len(f.decls) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("   ")
	for _, d := range f.decls {
		fmt.Fprintf(&b, " (local %s i32)", d)
	}
	b.WriteString("\n")
	return b.String()
}

// emitDefThunk emits a memoized thunk for a top-level definition as a lazy cached
// global: a value cache + a done flag; the first call computes and caches, so recursion
// + eliminator self-reference terminate and run once.
func (em *wasmEmitter) emitDefThunk(b *strings.Builder, name string, body CIr) {
	em.emitCachedThunk(b, name, func(f *wasmFunc, bb *strings.Builder) string {
		return f.emit(bb, body, nil)
	})
}

// emitCachedThunk emits the memoized-thunk wrapper around a body producing a Value.
// Shared by definitions, constructors, and the nat thunks. The cache/done live as two
// mutable globals; the func computes body into a temp buffer (so its local decls and
// the cache-check share one func header).
func (em *wasmEmitter) emitCachedThunk(b *strings.Builder, name string, body func(*wasmFunc, *strings.Builder) string) {
	cache := "$cache_" + wasmName(name)
	done := "$done_" + wasmName(name)
	fmt.Fprintf(b, "  (global %s (mut i32) (i32.const 0))\n", cache)
	fmt.Fprintf(b, "  (global %s (mut i32) (i32.const 0))\n", done)
	thunk := wasmThunkName(name)
	f := &wasmFunc{em: em}
	var inner strings.Builder
	v := body(f, &inner)
	fmt.Fprintf(b, "  (func $%s (result i32)\n", thunk)
	b.WriteString(f.localDecls())
	fmt.Fprintf(b, "    (if (global.get %s) (then (return (global.get %s))))\n", done, cache)
	fmt.Fprintf(b, "    (global.set %s (i32.const 1))\n", done)
	b.WriteString(inner.String())
	fmt.Fprintf(b, "    (global.set %s %s)\n", cache, v)
	fmt.Fprintf(b, "    (global.get %s))\n", cache)
}

// emitBlock emits one lifted code block as a WAT func taking (arg, env) -> i32 and
// registers it in the table. The body refers to its argument as CVar{0} and captures
// via CEnv{slot} (an env load). Locals are tracked as a stack of WAT expressions
// (innermost = index 0); the seed is the $arg parameter.
func (em *wasmEmitter) emitBlock(b *strings.Builder, blk CodeBlock) {
	name := wasmCodeName(blk.Name)
	em.codeRef(name)
	f := &wasmFunc{em: em}
	var inner strings.Builder
	v := f.emitIn(&inner, blk.Body, []string{"(local.get $arg)"})
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", name)
	b.WriteString(f.localDecls())
	b.WriteString(inner.String())
	fmt.Fprintf(b, "    %s)\n", v)
}

// emitCtor emits a constructor as a curried closure, mirroring emitCtorLL: a nullary
// constructor is the {tag} object thunk; an arity-k constructor builds k code blocks,
// each capturing the prefix and the last building the {tag,fields} object.
func (em *wasmEmitter) emitCtor(b *strings.Builder, c CtorSpec) {
	nameOff := em.intern(c.Name)
	if c.Arity == 0 {
		em.emitCachedThunk(b, c.Name, func(f *wasmFunc, bb *strings.Builder) string {
			r := f.fresh()
			fmt.Fprintf(bb, "    (local.set %s (call $rt_mkcon (i32.const %d) (i32.const %d) (i32.const 0)))\n", r, c.Tag, nameOff)
			return "(local.get " + r + ")"
		})
		return
	}
	base := "ctorfn_" + wasmName(c.Name)
	for i := 0; i < c.Arity; i++ {
		em.emitCtorBlock(b, fmt.Sprintf("%s_%d", base, i), c, i, nameOff)
	}
	em.emitCachedThunk(b, c.Name, func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, em.codeRef(base+"_0"))
		return "(local.get " + r + ")"
	})
}

// emitCtorBlock emits the i-th currying block of a k-ary constructor. The block i<k-1
// builds the next closure capturing env[0..i-1] + arg; block i==k-1 builds the
// {tag,fields} constructor object.
func (em *wasmEmitter) emitCtorBlock(b *strings.Builder, fname string, c CtorSpec, i, nameOff int) {
	em.codeRef(fname)
	base := "ctorfn_" + wasmName(c.Name)
	var inner strings.Builder
	f := &wasmFunc{em: em}
	var ret string
	if i == c.Arity-1 {
		o := f.fresh()
		fmt.Fprintf(&inner, "    (local.set %s (call $rt_mkcon (i32.const %d) (i32.const %d) (i32.const %d)))\n", o, c.Tag, nameOff, c.Arity)
		for k := 0; k < i; k++ {
			fmt.Fprintf(&inner, "    (call $rt_con_set (local.get %s) (i32.const %d) (call $rt_env (local.get $env) (i32.const %d)))\n", o, k, k)
		}
		fmt.Fprintf(&inner, "    (call $rt_con_set (local.get %s) (i32.const %d) (local.get $arg))\n", o, i)
		ret = "(local.get " + o + ")"
	} else {
		cl := f.fresh()
		fmt.Fprintf(&inner, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const %d)))\n", cl, em.codeRef(fmt.Sprintf("%s_%d", base, i+1)), i+1)
		for k := 0; k < i; k++ {
			fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (call $rt_env (local.get $env) (i32.const %d)))\n", cl, k, k)
		}
		fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (local.get $arg))\n", cl, i)
		ret = "(local.get " + cl + ")"
	}
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", fname)
	b.WriteString(f.localDecls())
	b.WriteString(inner.String())
	fmt.Fprintf(b, "    %s)\n", ret)
}

// emitNat emits the builtin-nat group natively, mirroring emitNatLL: zero is the empty
// bignum, succ a +1 closure, the eliminator a 4-block curried fold loop.
func (em *wasmEmitter) emitNat(b *strings.Builder, n NatSpec) {
	// zero: the empty bignum.
	em.emitCachedThunk(b, n.Zero, func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_big_from_long (i32.const 0)))\n", r)
		return "(local.get " + r + ")"
	})
	// succ code: x -> x+1 (bignum increment).
	sc := wasmName(n.Succ) + "_code"
	em.codeRef(sc)
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", sc)
	b.WriteString("    (call $rt_big_succ (local.get $arg)))\n")
	em.emitCachedThunk(b, n.Succ, func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, em.codeRef(sc))
		return "(local.get " + r + ")"
	})
	// eliminator: m -> c0 -> c1 -> x -> fold. env order {m,c0,c1}, arg = x.
	base := wasmName(n.ElimName)
	// b3: the fold. env = {m,c0,c1}, arg = x (a bignum).
	em.emitNatFold(b, base+"_b3")
	// b2: arg=c1, env={m,c0}; build b3 capturing {m,c0,c1}.
	em.emitCurryBlock(b, base+"_b2", base+"_b3", 3, []int{0, 1}, 2)
	em.emitCurryBlock(b, base+"_b1", base+"_b2", 2, []int{0}, 1)
	em.emitCurryBlock(b, base+"_b0", base+"_b1", 1, []int{}, 0)
	em.emitCachedThunk(b, n.ElimName, func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, em.codeRef(base+"_b0"))
		return "(local.get " + r + ")"
	})
}

// emitNatFold emits the eliminator's inner fold: env = {m, c0, c1}, arg = x. acc starts
// at c0; k counts from 0; while k < x: acc = (c1 k) acc; k = k+1. Returns acc.
func (em *wasmEmitter) emitNatFold(b *strings.Builder, fname string) {
	em.codeRef(fname)
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", fname)
	b.WriteString("    (local $c1 i32) (local $acc i32) (local $k i32) (local $step i32)\n")
	b.WriteString("    (local.set $c1 (call $rt_env (local.get $env) (i32.const 2)))\n")
	b.WriteString("    (local.set $acc (call $rt_env (local.get $env) (i32.const 1)))\n")
	b.WriteString("    (local.set $k (call $rt_big_from_long (i32.const 0)))\n")
	b.WriteString("    (block $done (loop $l\n")
	b.WriteString("      (br_if $done (i32.ge_s (call $rt_big_cmp (local.get $k) (local.get $arg)) (i32.const 0)))\n")
	b.WriteString("      (local.set $step (call $rt_apply (local.get $c1) (local.get $k)))\n")
	b.WriteString("      (local.set $acc (call $rt_apply (local.get $step) (local.get $acc)))\n")
	b.WriteString("      (local.set $k (call $rt_big_succ (local.get $k)))\n")
	b.WriteString("      (br $l)))\n")
	b.WriteString("    (local.get $acc))\n")
}

// emitCurryBlock emits one currying block of a primitive: builds the next closure of
// nslots slots over $next, copying env slots copyEnv (by index, into the same slots)
// then placing $arg at argSlot.
func (em *wasmEmitter) emitCurryBlock(b *strings.Builder, name, next string, nslots int, copyEnv []int, argSlot int) {
	em.codeRef(name)
	f := &wasmFunc{em: em}
	cl := f.fresh()
	var inner strings.Builder
	fmt.Fprintf(&inner, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const %d)))\n", cl, em.codeRef(next), nslots)
	for _, k := range copyEnv {
		fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (call $rt_env (local.get $env) (i32.const %d)))\n", cl, k, k)
	}
	fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (local.get $arg))\n", cl, argSlot)
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", name)
	b.WriteString(f.localDecls())
	b.WriteString(inner.String())
	fmt.Fprintf(b, "    (local.get %s))\n", cl)
}

// emit lowers a CIr in the empty-locals context (def-thunk top level).
func (f *wasmFunc) emit(b *strings.Builder, t CIr, locals []string) string {
	return f.emitIn(b, t, locals)
}

// emitIn lowers a CIr in a context of `locals` (WAT expressions naming each binder
// visible by de Bruijn index, innermost = 0), writing `(local.set ...)` statements to b
// and returning a WAT expression naming the i32 result.
func (f *wasmFunc) emitIn(b *strings.Builder, t CIr, locals []string) string {
	switch x := t.(type) {
	case CVar:
		if x.Idx < len(locals) {
			return locals[x.Idx]
		}
		return "(call $rt_unit)" // closed-program safety marker
	case CEnv:
		return fmt.Sprintf("(call $rt_env (local.get $env) (i32.const %d))", x.Idx)
	case CGlobal:
		return fmt.Sprintf("(call $%s)", wasmThunkName(x.Name))
	case CForeign:
		// Guarded out by wasmCheckSupported; defensive.
		return "(call $rt_unit)"
	case CUnit:
		return "(call $rt_unit)"
	case CLit:
		return f.emitLit(b, x)
	case MkClosure:
		return f.emitMkClosure(b, x, locals)
	case AppClosure:
		if out, ok := f.accelDispatch(b, x, locals); ok {
			return out
		}
		clo := f.emitIn(b, x.Clo, locals)
		arg := f.emitIn(b, x.Arg, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_apply %s %s))\n", r, clo, arg)
		return "(local.get " + r + ")"
	case CLet:
		v := f.emitIn(b, x.Val, locals)
		// Bind v to a fresh local so the body can reference it by name (de Bruijn 0).
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s %s)\n", r, v)
		return f.emitIn(b, x.Body, prependW("(local.get "+r+")", locals))
	case CPair:
		a := f.emitIn(b, x.A, locals)
		bb := f.emitIn(b, x.B, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_mkpair %s %s))\n", r, a, bb)
		return "(local.get " + r + ")"
	case CFst:
		p := f.emitIn(b, x.P, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_pair_fst %s))\n", r, p)
		return "(local.get " + r + ")"
	case CSnd:
		p := f.emitIn(b, x.P, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_pair_snd %s))\n", r, p)
		return "(local.get " + r + ")"
	case CField:
		s := f.emitIn(b, x.Scrut, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_con_get %s (i32.const %d)))\n", r, s, x.Index)
		return "(local.get " + r + ")"
	case CCase:
		return f.emitCase(b, x, locals)
	default:
		panic(fmt.Sprintf("codegen(wasm): unknown CIr node %T", t))
	}
}

// emitLit lowers a native literal. v1 supports LitInt (immediate-tagged i32) and LitNat
// (a parsed bignum); other kinds are rejected by wasmCheckSupported.
func (f *wasmFunc) emitLit(b *strings.Builder, x CLit) string {
	r := f.fresh()
	switch x.Kind {
	case LitNat:
		off := f.em.intern(x.Nat)
		fmt.Fprintf(b, "    (local.set %s (call $rt_big_parse (i32.const %d)))\n", r, off)
	default: // LitInt
		fmt.Fprintf(b, "    (local.set %s (call $rt_mkint (i32.const %d)))\n", r, x.Int)
	}
	return "(local.get " + r + ")"
}

// emitMkClosure allocates a closure and fills its env slots (each evaluated in the
// enclosing context). The env terms are evaluated FIRST (into locals), then the closure
// is built and filled — so a nested AppClosure inside an env slot does not interleave
// with the rt_clo_set calls.
func (f *wasmFunc) emitMkClosure(b *strings.Builder, x MkClosure, locals []string) string {
	idx := f.em.codeRef(wasmCodeName(x.Code))
	envVals := make([]string, len(x.Env))
	for i, e := range x.Env {
		ev := f.emitIn(b, e, locals)
		// Bind into a local so the value is stable across the alloc + sets.
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s %s)\n", r, ev)
		envVals[i] = "(local.get " + r + ")"
	}
	cl := f.fresh()
	fmt.Fprintf(b, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const %d)))\n", cl, idx, len(x.Env))
	for i, ev := range envVals {
		fmt.Fprintf(b, "    (call $rt_clo_set (local.get %s) (i32.const %d) %s)\n", cl, i, ev)
	}
	return "(local.get " + cl + ")"
}

// emitCase lowers an eliminator's tag dispatch. WAT has no n-way switch expression, so
// we read the tag into a local and emit a chain of `(if (i32.eq tag K) (then ...))`,
// each arm storing its result into a shared result local; an unmatched tag aborts.
func (f *wasmFunc) emitCase(b *strings.Builder, x CCase, locals []string) string {
	s := f.emitIn(b, x.Scrut, locals)
	tag := f.fresh()
	fmt.Fprintf(b, "    (local.set %s (call $rt_con_tag %s))\n", tag, s)
	res := f.fresh()
	// Sort arms by tag for deterministic output (matches the LLVM switch's stable
	// iteration; arms are already in declaration order but be explicit).
	arms := append([]CCaseArm(nil), x.Arms...)
	sort.SliceStable(arms, func(i, j int) bool { return arms[i].Tag < arms[j].Tag })
	for _, arm := range arms {
		fmt.Fprintf(b, "    (if (i32.eq (local.get %s) (i32.const %d)) (then\n", tag, arm.Tag)
		v := f.emitIn(b, arm.Body, locals)
		fmt.Fprintf(b, "      (local.set %s %s)\n", res, v)
		b.WriteString("    ))\n")
	}
	return "(local.get " + res + ")"
}

// accelDispatch emits a registered accel-op def on two args as native bignum arithmetic
// (the rt_nat_add/mul/monus helpers), interchangeable with the eliminator loop.
func (f *wasmFunc) accelDispatch(b *strings.Builder, app AppClosure, locals []string) (string, bool) {
	op, a, bb, ok := accelMatchC(app, f.em.accel)
	if !ok {
		return "", false
	}
	ea := f.emitIn(b, a, locals)
	eb := f.emitIn(b, bb, locals)
	r := f.fresh()
	switch op {
	case core.NatOpAdd:
		fmt.Fprintf(b, "    (local.set %s (call $rt_nat_add %s %s))\n", r, ea, eb)
		return "(local.get " + r + ")", true
	case core.NatOpMul:
		fmt.Fprintf(b, "    (local.set %s (call $rt_nat_mul %s %s))\n", r, ea, eb)
		return "(local.get " + r + ")", true
	case core.NatOpMonus:
		fmt.Fprintf(b, "    (local.set %s (call $rt_nat_monus %s %s))\n", r, ea, eb)
		return "(local.get " + r + ")", true
	}
	return "", false
}

// wasmName sanitizes a rune identifier into a WAT-symbol fragment ([A-Za-z0-9_], shared
// with the C/LLVM sanitizer so symbol schemes match).
func wasmName(n string) string { return cName(n) }

// wasmThunkName / wasmCodeName namespace the two emitted symbol kinds, matching the LLVM
// backend's scheme.
func wasmThunkName(n string) string { return "def_" + wasmName(n) }
func wasmCodeName(n string) string  { return "code_" + wasmName(n) }

// prependW pushes a new innermost local (de Bruijn 0) onto the locals stack.
func prependW(v string, locals []string) []string {
	out := make([]string, 0, len(locals)+1)
	out = append(out, v)
	out = append(out, locals...)
	return out
}

// wasmDataStr renders a Go string as a WAT data-segment string literal (each byte as
// \HH for non-printables / quote / backslash), NUL-terminated.
func wasmDataStr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '\\':
			b.WriteString("\\5c")
		case c == '"':
			b.WriteString("\\22")
		case c < 0x20 || c >= 0x7f:
			fmt.Fprintf(&b, "\\%02x", c)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteString("\\00")
	b.WriteByte('"')
	return b.String()
}
