package codegen

import (
	"fmt"
	"sort"
	"strings"

	"goforge.dev/rune/v3/core"
)

// Wasm is the NINTH backend (R-NATIVE Cranelift/WASM node): it emits WebAssembly
// text (WAT) over the CLOSURE-CONVERTED IR (codegen/closure.go), runnable directly
// by `wasmtime run module.wat`. Where the LLVM backend (codegen/ll.go, the closest
// template) emits LLVM IR that links a C runtime, WASM emits a SELF-CONTAINED module:
// the runtime (linear-memory bump allocator, heap records for closures/constructors,
// a function table for `call_indirect`, the naive base-1e9 bignum, and a `$show`
// writer over WASI `fd_write`) is WAT emitted inline (wasmRuntime), because wasmtime
// runs a single `.wat` with no host linkage.
//
// VALUE REP: a Rune value is an i32 — an immediate small int `(n<<1)|1` (FFI LitInt)
// or an even-aligned heap pointer. The emitter never inspects the tag; it defers to
// the `rt_*` runtime helpers, so the rep is owned by ONE place (wasmRuntime).
//
// SUPPORTED FRAGMENT (byte-identical to the C/LLVM backends on this subset): builtin-
// nat arithmetic (zero/succ/NatElim + accel add/mul/monus), constructors + eliminators
// (CCase/CField over ListElim/NatElim/any datatype), curried closures + application,
// dependent pairs (CPair/CFst/CSnd), the erased token (CUnit), native int/nat literals
// (CLit{LitInt,LitNat}). UNSUPPORTED in v1 (the emitter returns a clear error, never
// broken WAT): LitStr/LitBytes/LitPtr, IForeign/CForeign (no host vocabulary in the
// WASI sandbox yet), and IO main. GC: none — a bump allocator only (v1); a program
// that out-allocates the 16 MiB initial memory traps. See the deliverable notes.
type Wasm struct{}

func (Wasm) Target() string { return "wasm" }

// Emit closure-converts the program and emits a self-contained WAT module: the inline
// runtime, every lifted code block + constructor/eliminator code block as a `(func)`,
// the definition thunks (lazy cached, as mutable globals), the function table the
// `call_indirect` apply reads, and `$rune_main` (evaluates the entry and `$show`s it),
// exported as `_start` so `wasmtime run` invokes it.
func (Wasm) Emit(p Program) (TargetSource, error) {
	// Reject the unsupported fragment up front with a clear error (HONESTY: never
	// emit broken WAT for a form we cannot lower).
	if err := wasmCheckSupported(p); err != nil {
		return "", err
	}

	cp := ClosureConvert(p)
	cp = Perceus(cp)
	em := newWasmEmitter(cp)

	var body strings.Builder

	em.emitDefs(&body)
	// Bake the whitelisted foreign IO ops + the IO monad (bindIO/pureIO) into the module.
	// This runs BEFORE emitTable so each op's code blocks are registered (codeRef) and
	// land in the function table; WAT is order-agnostic across function references, so
	// $rune_main below may forward-reference these thunks freely.
	em.emitForeignPrimsWasm(&body, p)

	// $rune_main: evaluate the entry thunk and show it. An IO main (p.IOMain) is a
	// deferred world thunk (unit -> A): mirror C/JS by running the effect chain --
	// apply the entry to the world token ($rt_unit) -- then show the yielded value.
	body.WriteString("  (func $rune_main\n")
	if p.Main != "" {
		f := &wasmFunc{em: em}
		var inner strings.Builder
		mainV := f.emit(&inner, CGlobal{Name: p.Main}, nil)
		if p.IOMain {
			r := f.fresh()
			fmt.Fprintf(&inner, "    (local.set %s (call $rt_apply %s (call $rt_unit)))\n", r, mainV)
			mainV = "(local.get " + r + ")"
		}
		fmt.Fprintf(&inner, "    (call $rt_show_line %s)\n", mainV)
		body.WriteString(f.localDecls())
		body.WriteString(inner.String())
	}
	body.WriteString("  )\n")

	// Assemble the module: header, the function-table type, the inline runtime, the
	// string-constant data, the program bodies, the table + elem, and the init/export.
	var b strings.Builder
	b.WriteString(";; Generated by rune emit (wasm backend) — the erased shadow, native via wasmtime.\n")
	b.WriteString(";; Run: wasmtime run module.wat  (WAT runs directly; the runtime is inline).\n")
	b.WriteString("(module\n")
	b.WriteString("  (type $codety (func (param i32 i32) (result i32)))\n")
	b.WriteString(wasmRuntime)
	b.WriteString("\n")
	// String-constant data segments (constructor names) + the fixed runtime messages,
	// laid out in the reserved low region [64, 4096). Each cstr is NUL-terminated.
	em.emitData(&b)
	b.WriteString("\n")
	b.WriteString(body.String())
	// The function table + elem: every code block by its assigned index.
	em.emitTable(&b)
	// init: seed UNIT, run main. Exported as _start so wasmtime invokes it.
	b.WriteString("  (func $_start (export \"_start\")\n")
	b.WriteString("    (global.set $UNIT (call $rt_mkcon (i32.const 0) (global.get $unit_name) (i32.const 0)))\n")
	b.WriteString("    (call $rune_main))\n")
	b.WriteString(")\n")
	return TargetSource(b.String()), nil
}

// wasmSupportedForeign lists the foreign ops with a WAT body in emitForeignPrimsWasm.
// wasmCheckSupported allows these; any other foreign is still a hard, honest error.
//
// Task 1 (the D6/bible-ops WASM tier foundation) opens this whitelist with the two
// foreign IO ops the ch210 demo exercises: printNat (console-out via fd_write) and
// timeNanos (the OS monotonic clock via WASI clock_time_get). Both are baked in
// emitForeignPrimsWasm as CURRIED IO-closure chains -- the load-bearing template every
// later IO op (getEnvCode/readFileCode/foldLines/...) reuses. Later tasks append names
// here as their WAT bodies land; an unknown foreign STILL hard-errors (the honesty gate).
var wasmSupportedForeign = map[string]bool{
	"printNat":  true,
	"timeNanos": true,
}

// wasmCheckSupported walks the program's IR and returns a clear error for any form the
// v1 WASM backend cannot lower (rather than emit broken WAT). Mirrors foreignNames'
// walk over every node kind so a nested unsupported form is found.
func wasmCheckSupported(p Program) error {
	var err error
	var walk func(Ir)
	walk = func(t Ir) {
		if err != nil {
			return
		}
		switch x := t.(type) {
		case IForeign:
			if !wasmSupportedForeign[x.Name] {
				err = fmt.Errorf("codegen(wasm): foreign %q is not supported (no WASI/WAT body)", x.Name)
				return
			}
			// whitelisted: a WAT body is baked by emitForeignPrimsWasm -- no error.
		case ILit:
			switch x.Kind {
			case LitInt, LitNat:
				// supported
			case LitStr:
				err = fmt.Errorf("codegen(wasm): string literals are not supported in v1")
			case LitPtr:
				err = fmt.Errorf("codegen(wasm): opaque host pointers are not supported in v1")
			}
		case ILam:
			walk(x.Body)
		case IApp:
			walk(x.Fn)
			walk(x.Arg)
		case ILet:
			walk(x.Val)
			walk(x.Body)
		case IPair:
			walk(x.A)
			walk(x.B)
		case IFst:
			walk(x.P)
		case ISnd:
			walk(x.P)
		case IField:
			walk(x.Scrut)
		case ICase:
			walk(x.Scrut)
			for _, arm := range x.Arms {
				walk(arm.Body)
			}
		}
	}
	for _, d := range p.Defs {
		walk(d.Body)
	}
	if err != nil {
		return err
	}
	// IO-main is supported since Task 1 (the effect chain is run at $rune_main by
	// applying the world token, then the final value is shown) -- see Emit().
	return nil
}

// wasmEmitter renders CIr terms to WAT. Like llEmitter it knows the nat eliminator's
// name + the accel table, accumulates constructor-name string constants (interned into
// the data segment), and assigns each emitted code block a function-table index so
// `call_indirect` can reach it.
type wasmEmitter struct {
	cp      ClosureProgram // the program being emitted; set by newWasmEmitter
	natElim string
	accel   map[string]core.NatOp

	// codeIdx maps a code-block func name (without leading $) to its table index, in
	// first-seen order. The order is also the (elem) order.
	codeIdx   map[string]int
	codeOrder []string

	// strs maps a string constant (constructor name) to its byte offset in the data
	// segment, allocated bump-style from strBase upward.
	strs     map[string]int
	strOrder []string
	strBytes int

	// ctorByName maps a non-nat constructor's emitted name to its CtorSpec, so the
	// AppClosure emit path can recognize a SATURATED constructor application (an
	// AppClosure spine headed by a CGlobal naming a constructor, with exactly Arity
	// args) and build the K_CON directly via rt_mkcon (satCtorDispatch), instead of
	// currying through emitCtorBlock and allocating an intermediate partial-application
	// K_CLO. The builtin-nat data group is EXCLUDED (its zero/succ compile to native
	// bignum via emitNat, not K_CON), so a `succ n` spine never matches here.
	ctorByName map[string]CtorSpec
}

// newWasmEmitter constructs a wasmEmitter for the given closure-converted program,
// wiring the nat eliminator name and accel table when a NatSpec is present.
func newWasmEmitter(cp ClosureProgram) *wasmEmitter {
	em := &wasmEmitter{
		cp:         cp,
		codeIdx:    map[string]int{},
		strs:       map[string]int{},
		ctorByName: map[string]CtorSpec{},
	}
	if cp.Nat != nil {
		em.natElim = cp.Nat.ElimName
		em.accel = cp.Nat.Ops
	}
	// Index every non-nat constructor for satCtorDispatch. Skip the builtin-nat data
	// group (zero/succ compile to native bignum via emitNat, not K_CON) so a saturated
	// `succ n` never mis-routes into the rt_mkcon path.
	for _, d := range cp.Datas {
		if cp.Nat != nil && d.ElimName == cp.Nat.ElimName {
			continue
		}
		for _, c := range d.Ctors {
			em.ctorByName[c.Name] = c
		}
	}
	return em
}

// emitDefs emits all constructor/eliminator code blocks + thunks, the lifted lambda
// code blocks, and the top-level definition thunks into b. This is the "program
// bodies" section of the module, factored out of Emit so WasmSteadyModule can reuse
// the same emission path with a custom entry point.
func (em *wasmEmitter) emitDefs(b *strings.Builder) {
	// Constructor + eliminator code blocks and thunks.
	for _, d := range em.cp.Datas {
		if em.cp.Nat != nil && d.ElimName == em.cp.Nat.ElimName {
			em.emitNat(b, *em.cp.Nat)
			continue
		}
		for _, c := range d.Ctors {
			em.emitCtor(b, c)
		}
	}
	// The lifted code blocks (definitions' and eliminators' bodies).
	for _, blk := range em.cp.Blocks {
		em.emitBlock(b, blk)
	}
	// Definition thunks (eliminators converted as CDefSpec, then user defs). A `partial`
	// def is split into a _step body + curried drivers + a public trampoline thunk.
	for _, def := range em.cp.Defs {
		if em.cp.Partials[def.Name] {
			em.emitPartialWasm(b, def.Name, def.Arity, def.Body)
			continue
		}
		em.emitDefThunk(b, def.Name, def.Body)
	}
}

// codeRef registers (on first sight) a code-block name and returns its table index.
func (em *wasmEmitter) codeRef(name string) int {
	if idx, ok := em.codeIdx[name]; ok {
		return idx
	}
	idx := len(em.codeOrder)
	em.codeIdx[name] = idx
	em.codeOrder = append(em.codeOrder, name)
	return idx
}

// strBase is where constructor-name cstrs live: above the iovec/messages, below the
// show scratch buffer (4096). The runtime's reserved low region is [0,4096): the iovec
// is at [16,24), fixed runtime messages at [32,512), and interned cstrs at [512,4096).

// wasmStrBase is where interned constructor-name / numeral cstrs begin (above the
// fixed runtime messages at [32,512)).
const wasmStrBase = 512

// wasmShowBuf is the show scratch buffer base; interned cstrs must stay below it.
const wasmShowBuf = 4096

// intern registers a string constant and returns its byte offset.
func (em *wasmEmitter) intern(s string) int {
	if off, ok := em.strs[s]; ok {
		return off
	}
	off := wasmStrBase + em.strBytes
	if off+len(s)+1 > wasmShowBuf {
		// Out of reserved cstr space; v1 caps interned constants at ~3.5 KiB. A real
		// program rarely needs this much in names, but be honest about the bound.
		panic("codegen(wasm): interned string constants exceed the reserved region")
	}
	em.strs[s] = off
	em.strOrder = append(em.strOrder, s)
	em.strBytes += len(s) + 1 // + NUL
	return off
}

// emitData writes the data segments: the fixed runtime messages (referenced by the
// runtime via $fn_msg/$abort_msg/$unit_name globals) and the interned constructor-name
// cstrs. The globals are declared here too (offsets are known only after interning).
func (em *wasmEmitter) emitData(b *strings.Builder) {
	// Fixed runtime messages live at [32,512), referenced by the runtime via the
	// $fn_msg/$abort_msg/$unit_name globals (the iovec occupies [16,32)).
	fnMsg := "<function>"
	abortMsg := "rune-wasm: impossible (unmatched constructor tag)\n"
	unitName := "" // the boxed unit's con name is unused by show (UNIT is special-cased)

	fnOff := 32
	abortOff := fnOff + len(fnMsg) + 1
	unitOff := abortOff + len(abortMsg) + 1
	if unitOff+len(unitName)+1 > wasmStrBase {
		panic("codegen(wasm): fixed runtime messages overflow the reserved region")
	}

	fmt.Fprintf(b, "  (global $fn_msg i32 (i32.const %d))\n", fnOff)
	fmt.Fprintf(b, "  (global $abort_msg i32 (i32.const %d))\n", abortOff)
	fmt.Fprintf(b, "  (global $abort_len i32 (i32.const %d))\n", len(abortMsg))
	fmt.Fprintf(b, "  (global $unit_name i32 (i32.const %d))\n", unitOff)
	fmt.Fprintf(b, "  (data (i32.const %d) %s)\n", fnOff, wasmDataStr(fnMsg))
	fmt.Fprintf(b, "  (data (i32.const %d) %s)\n", abortOff, wasmDataStr(abortMsg))
	fmt.Fprintf(b, "  (data (i32.const %d) %s)\n", unitOff, wasmDataStr(unitName))

	for _, s := range em.strOrder {
		fmt.Fprintf(b, "  (data (i32.const %d) %s)\n", em.strs[s], wasmDataStr(s))
	}
}

// emitTable writes the function table sized to hold every registered code block, and
// the (elem) that installs each at its assigned index.
func (em *wasmEmitter) emitTable(b *strings.Builder) {
	n := len(em.codeOrder)
	fmt.Fprintf(b, "  (table %d funcref)\n", n)
	if n > 0 {
		b.WriteString("  (elem (i32.const 0)")
		for _, name := range em.codeOrder {
			fmt.Fprintf(b, " $%s", name)
		}
		b.WriteString(")\n")
	}
}

// wasmFunc tracks per-function emission state. A code block / def thunk body lowers a
// CIr to a SEQUENCE of `(local.set $tN value)` statements and returns the WAT
// expression `(local.get $tN)` naming the result, so nested control flow (CCase) is
// straightforward. Locals are declared lazily and flushed into the func header.
type wasmFunc struct {
	em    *wasmEmitter
	tmp   int
	decls []string // local declarations to splice into the func header
}

// fresh allocates a fresh i32 local and returns its name (e.g. "$t3").
func (f *wasmFunc) fresh() string {
	f.tmp++
	name := fmt.Sprintf("$t%d", f.tmp)
	f.decls = append(f.decls, name)
	return name
}

// localDecls renders the accumulated local declarations for the func header.
func (f *wasmFunc) localDecls() string {
	if len(f.decls) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("   ")
	for _, d := range f.decls {
		fmt.Fprintf(&b, " (local %s i32)", d)
	}
	b.WriteString("\n")
	return b.String()
}

// emitDefThunk emits a memoized thunk for a top-level definition as a lazy cached
// global: a value cache + a done flag; the first call computes and caches, so recursion
// + eliminator self-reference terminate and run once.
func (em *wasmEmitter) emitDefThunk(b *strings.Builder, name string, body CIr) {
	em.emitCachedThunk(b, name, func(f *wasmFunc, bb *strings.Builder) string {
		return f.emit(bb, body, nil)
	})
}

// emitCachedThunk emits the memoized-thunk wrapper around a body producing a Value.
// Shared by definitions, constructors, and the nat thunks. The cache/done live as two
// mutable globals; the func computes body into a temp buffer (so its local decls and
// the cache-check share one func header).
func (em *wasmEmitter) emitCachedThunk(b *strings.Builder, name string, body func(*wasmFunc, *strings.Builder) string) {
	cache := "$cache_" + wasmName(name)
	done := "$done_" + wasmName(name)
	fmt.Fprintf(b, "  (global %s (mut i32) (i32.const 0))\n", cache)
	fmt.Fprintf(b, "  (global %s (mut i32) (i32.const 0))\n", done)
	thunk := wasmThunkName(name)
	f := &wasmFunc{em: em}
	var inner strings.Builder
	v := body(f, &inner)
	fmt.Fprintf(b, "  (func $%s (result i32)\n", thunk)
	b.WriteString(f.localDecls())
	fmt.Fprintf(b, "    (if (global.get %s) (then (return (global.get %s))))\n", done, cache)
	fmt.Fprintf(b, "    (global.set %s (i32.const 1))\n", done)
	b.WriteString(inner.String())
	fmt.Fprintf(b, "    (global.set %s %s)\n", cache, v)
	fmt.Fprintf(b, "    (global.get %s))\n", cache)
}

// wasmStepName is the partial's memoized _step thunk func name. It matches the cache
// key name+"_step" passed to emitCachedThunk (cName is a plain sanitizer, so
// "def_"+cName(name)+"_step" == "def_"+cName(name+"_step")).
func wasmStepName(name string) string { return wasmThunkName(name) + "_step" }

// emitPartialWasm lowers a `partial` def to the T2 trampoline split (the WASM dual of
// emitPartialC): a memoized _step thunk (the body, where a CBounce is a K_BOUNCE), then
// `arity` curried driver code blocks that collect args into the closure env, the last of
// which saturates _step and drives the bounce chain via $rt_tramp; and a public thunk
// returning a closure entering driver 0.
func (em *wasmEmitter) emitPartialWasm(b *strings.Builder, name string, arity int, body CIr) {
	// _step: the memoized body (a curried lambda of `arity` args; a tail call inside is
	// a K_BOUNCE). Its func name is wasmStepName(name).
	em.emitCachedThunk(b, name+"_step", func(f *wasmFunc, bb *strings.Builder) string {
		return f.emit(bb, body, nil)
	})
	step := wasmStepName(name)

	if arity == 0 {
		// No args to collect: the public thunk drives the (bounce-free) step once.
		em.emitCachedThunk(b, name, func(f *wasmFunc, bb *strings.Builder) string {
			r := f.fresh()
			fmt.Fprintf(bb, "    (local.set %s (call $rt_tramp (call $%s)))\n", r, step)
			return "(local.get " + r + ")"
		})
		return
	}

	base := "drvfn_" + wasmName(name)
	for i := 0; i < arity; i++ {
		em.emitPartialDriverBlock(b, fmt.Sprintf("%s_%d", base, i), name, arity, i)
	}
	em.emitCachedThunk(b, name, func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, em.codeRef(base+"_0"))
		return "(local.get " + r + ")"
	})
}

// emitPartialDriverBlock emits the i-th curry block of a partial's public driver. For
// i<arity-1 it builds the next driver closure capturing env[0..i-1] + arg (identical to
// emitCtorBlock's collect arm). For i==arity-1 it saturates _step() with env[0..i-1] +
// arg via $rt_apply, then $rt_tramp's the result.
func (em *wasmEmitter) emitPartialDriverBlock(b *strings.Builder, fname, name string, arity, i int) {
	em.codeRef(fname)
	base := "drvfn_" + wasmName(name)
	step := wasmStepName(name)
	f := &wasmFunc{em: em}
	var inner strings.Builder
	var ret string
	if i < arity-1 {
		// Collect block: build the next driver closure capturing env[0..i-1] + arg. Unlike
		// emitCtorBlock (whose constructor spines are recognized + never released), a DRIVER
		// intermediate IS released by the generic apply path, so each forwarded env value
		// must be RETAINED into the child (the child takes its own reference; the parent's
		// later release is then balanced). The fresh $arg is owned by this block, so it MOVES.
		cl := f.fresh()
		fmt.Fprintf(&inner, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const %d)))\n", cl, em.codeRef(fmt.Sprintf("%s_%d", base, i+1)), i+1)
		for k := 0; k < i; k++ {
			fmt.Fprintf(&inner, "    (call $rt_retain (call $rt_env (local.get $env) (i32.const %d)))\n", k)
			fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (call $rt_env (local.get $env) (i32.const %d)))\n", cl, k, k)
		}
		fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (local.get $arg))\n", cl, i)
		ret = "(local.get " + cl + ")"
	} else {
		// Saturating block: build the starting bounce {step(), env[0..i-1], arg} and drive
		// it. The driver closure OWNS its captured env (and is released by the caller after
		// this returns), so each env value is RETAINED into the bounce (the bounce takes its
		// own reference). The fresh $arg is owned by this block, so it MOVES into the bounce.
		// $rt_tramp then drives uniformly.
		bn := f.fresh()
		fmt.Fprintf(&inner, "    (local.set %s (call $rt_mkbounce (call $%s) (i32.const %d)))\n", bn, step, arity)
		for k := 0; k < i; k++ {
			fmt.Fprintf(&inner, "    (call $rt_retain (call $rt_env (local.get $env) (i32.const %d)))\n", k)
			fmt.Fprintf(&inner, "    (call $rt_bounce_set (local.get %s) (i32.const %d) (call $rt_env (local.get $env) (i32.const %d)))\n", bn, k, k)
		}
		fmt.Fprintf(&inner, "    (call $rt_bounce_set (local.get %s) (i32.const %d) (local.get $arg))\n", bn, i)
		rv := f.fresh()
		fmt.Fprintf(&inner, "    (local.set %s (call $rt_tramp (local.get %s)))\n", rv, bn)
		ret = "(local.get " + rv + ")"
	}
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", fname)
	b.WriteString(f.localDecls())
	b.WriteString(inner.String())
	fmt.Fprintf(b, "    %s)\n", ret)
}

// emitBlock emits one lifted code block as a WAT func taking (arg, env) -> i32 and
// registers it in the table. The body refers to its argument as CVar{0} and captures
// via CEnv{slot} (an env load). Locals are tracked as a stack of WAT expressions
// (innermost = index 0); the seed is the $arg parameter.
func (em *wasmEmitter) emitBlock(b *strings.Builder, blk CodeBlock) {
	name := wasmCodeName(blk.Name)
	em.codeRef(name)
	f := &wasmFunc{em: em}
	var inner strings.Builder
	v := f.emitIn(&inner, blk.Body, []string{"(local.get $arg)"})
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", name)
	b.WriteString(f.localDecls())
	b.WriteString(inner.String())
	fmt.Fprintf(b, "    %s)\n", v)
}

// emitCtor emits a constructor as a curried closure, mirroring emitCtorLL: a nullary
// constructor is the {tag} object thunk; an arity-k constructor builds k code blocks,
// each capturing the prefix and the last building the {tag,fields} object.
func (em *wasmEmitter) emitCtor(b *strings.Builder, c CtorSpec) {
	nameOff := em.intern(c.Name)
	if c.Arity == 0 {
		em.emitCachedThunk(b, c.Name, func(f *wasmFunc, bb *strings.Builder) string {
			r := f.fresh()
			fmt.Fprintf(bb, "    (local.set %s (call $rt_mkcon (i32.const %d) (i32.const %d) (i32.const 0)))\n", r, c.Tag, nameOff)
			return "(local.get " + r + ")"
		})
		return
	}
	base := "ctorfn_" + wasmName(c.Name)
	for i := 0; i < c.Arity; i++ {
		em.emitCtorBlock(b, fmt.Sprintf("%s_%d", base, i), c, i, nameOff)
	}
	em.emitCachedThunk(b, c.Name, func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, em.codeRef(base+"_0"))
		return "(local.get " + r + ")"
	})
}

// emitCtorBlock emits the i-th currying block of a k-ary constructor. The block i<k-1
// builds the next closure capturing env[0..i-1] + arg; block i==k-1 builds the
// {tag,fields} constructor object.
func (em *wasmEmitter) emitCtorBlock(b *strings.Builder, fname string, c CtorSpec, i, nameOff int) {
	em.codeRef(fname)
	base := "ctorfn_" + wasmName(c.Name)
	var inner strings.Builder
	f := &wasmFunc{em: em}
	var ret string
	if i == c.Arity-1 {
		o := f.fresh()
		fmt.Fprintf(&inner, "    (local.set %s (call $rt_mkcon (i32.const %d) (i32.const %d) (i32.const %d)))\n", o, c.Tag, nameOff, c.Arity)
		for k := 0; k < i; k++ {
			fmt.Fprintf(&inner, "    (call $rt_con_set (local.get %s) (i32.const %d) (call $rt_env (local.get $env) (i32.const %d)))\n", o, k, k)
		}
		fmt.Fprintf(&inner, "    (call $rt_con_set (local.get %s) (i32.const %d) (local.get $arg))\n", o, i)
		ret = "(local.get " + o + ")"
	} else {
		cl := f.fresh()
		fmt.Fprintf(&inner, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const %d)))\n", cl, em.codeRef(fmt.Sprintf("%s_%d", base, i+1)), i+1)
		for k := 0; k < i; k++ {
			fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (call $rt_env (local.get $env) (i32.const %d)))\n", cl, k, k)
		}
		fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (local.get $arg))\n", cl, i)
		ret = "(local.get " + cl + ")"
	}
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", fname)
	b.WriteString(f.localDecls())
	b.WriteString(inner.String())
	fmt.Fprintf(b, "    %s)\n", ret)
}

// emitNat emits the builtin-nat group natively, mirroring emitNatLL: zero is the empty
// bignum, succ a +1 closure, the eliminator a 4-block curried fold loop.
func (em *wasmEmitter) emitNat(b *strings.Builder, n NatSpec) {
	// zero: the empty bignum.
	em.emitCachedThunk(b, n.Zero, func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_big_from_long (i32.const 0)))\n", r)
		return "(local.get " + r + ")"
	})
	// succ code: x -> x+1 (bignum increment). rt_big_succ BORROW-reads $arg and
	// returns a fresh K_BIG; under PATH B the caller hands the closure an OWNED arg
	// (Perceus dups a borrowed operand at the owning AppClosure position), so succ
	// must FREE its arg like any user closure code block does -- otherwise a
	// succ-chain (succ (succ x)) leaks every intermediate K_BIG each run.
	sc := wasmName(n.Succ) + "_code"
	em.codeRef(sc)
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32) (local $r i32)\n", sc)
	b.WriteString("    (local.set $r (call $rt_big_succ (local.get $arg)))\n")
	b.WriteString("    (call $rt_release (local.get $arg))\n")
	b.WriteString("    (local.get $r))\n")
	em.emitCachedThunk(b, n.Succ, func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, em.codeRef(sc))
		return "(local.get " + r + ")"
	})
	// eliminator: m -> c0 -> c1 -> x -> fold. env order {m,c0,c1}, arg = x.
	base := wasmName(n.ElimName)
	// b3: the fold. env = {m,c0,c1}, arg = x (a bignum).
	em.emitNatFold(b, base+"_b3")
	// b2: arg=c1, env={m,c0}; build b3 capturing {m,c0,c1}.
	em.emitCurryBlock(b, base+"_b2", base+"_b3", 3, []int{0, 1}, 2)
	em.emitCurryBlock(b, base+"_b1", base+"_b2", 2, []int{0}, 1)
	em.emitCurryBlock(b, base+"_b0", base+"_b1", 1, []int{}, 0)
	em.emitCachedThunk(b, n.ElimName, func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, em.codeRef(base+"_b0"))
		return "(local.get " + r + ")"
	})
}

// emitNatFold emits the eliminator's inner fold: env = {m, c0, c1}, arg = x. acc starts
// at c0; k counts from 0; while k < x: acc = (c1 k) acc; k = k+1. Returns acc.
//
// Ownership: $arg (the bound) is BORROWED from the caller -- do NOT release it. $c1
// (env slot 2, the step closure) is BORROWED from the env -- do NOT release it. $acc
// is moved into the step each iteration (the step owns+consumes it). $k is owned by the
// loop: we RETAIN $k before the first apply so the step gets its own reference while the
// loop keeps its own; after the step we RELEASE the old $k, and after the loop we RELEASE
// the final $k (which was never consumed by the step because the loop exited). $step (the
// partially-applied step closure from rt_apply($c1, $k)) is released after the second
// apply -- it is a fresh K_CLO each iteration and nothing else owns it.
func (em *wasmEmitter) emitNatFold(b *strings.Builder, fname string) {
	em.codeRef(fname)
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", fname)
	b.WriteString("    (local $c1 i32) (local $acc i32) (local $k i32) (local $step i32) (local $knext i32)\n")
	b.WriteString("    (local.set $c1 (call $rt_env (local.get $env) (i32.const 2)))\n")
	b.WriteString("    (local.set $acc (call $rt_env (local.get $env) (i32.const 1)))\n")
	// $acc starts as a BORROWED alias of env slot 1 (the base c0). RETAIN it so the loop
	// owns its own reference: each iteration the step CONSUMES (frees) $acc and returns a
	// fresh owned one, and on a 0-iteration fold $acc is returned directly. Without this
	// retain, a caller that RELEASES the eliminator's env (satElimDispatch frees the b3
	// fold closure after the call) would free the same K_BIG the fold returned or the
	// step already freed -- a use-after-free / double-free. The retain makes the returned
	// $acc independent of the env's slot-1 ownership.
	b.WriteString("    (call $rt_retain (local.get $acc))\n")
	b.WriteString("    (local.set $k (call $rt_big_from_long (i32.const 0)))\n")
	b.WriteString("    (block $done (loop $l\n")
	b.WriteString("      (br_if $done (i32.ge_s (call $rt_big_cmp (local.get $k) (local.get $arg)) (i32.const 0)))\n")
	b.WriteString("      ;; retain $k: the step owns its argument copy; the loop keeps its own\n")
	b.WriteString("      (call $rt_retain (local.get $k))\n")
	b.WriteString("      (local.set $step (call $rt_apply (local.get $c1) (local.get $k)))\n")
	b.WriteString("      (local.set $acc (call $rt_apply (local.get $step) (local.get $acc)))\n")
	b.WriteString("      ;; $step is a fresh K_CLO each iteration; release it now\n")
	b.WriteString("      (call $rt_release (local.get $step))\n")
	b.WriteString("      ;; advance $k: compute successor, release old $k, install new\n")
	b.WriteString("      (local.set $knext (call $rt_big_succ (local.get $k)))\n")
	b.WriteString("      (call $rt_release (local.get $k))\n")
	b.WriteString("      (local.set $k (local.get $knext))\n")
	b.WriteString("      (br $l)))\n")
	b.WriteString("    ;; final $k (loop exited because $k >= $arg): release it\n")
	b.WriteString("    (call $rt_release (local.get $k))\n")
	b.WriteString("    (local.get $acc))\n")
}

// emitCurryBlock emits one currying block of a primitive: builds the next closure of
// nslots slots over $next, copying env slots copyEnv (by index, into the same slots)
// then placing $arg at argSlot.
func (em *wasmEmitter) emitCurryBlock(b *strings.Builder, name, next string, nslots int, copyEnv []int, argSlot int) {
	em.codeRef(name)
	f := &wasmFunc{em: em}
	cl := f.fresh()
	var inner strings.Builder
	fmt.Fprintf(&inner, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const %d)))\n", cl, em.codeRef(next), nslots)
	for _, k := range copyEnv {
		fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (call $rt_env (local.get $env) (i32.const %d)))\n", cl, k, k)
	}
	fmt.Fprintf(&inner, "    (call $rt_clo_set (local.get %s) (i32.const %d) (local.get $arg))\n", cl, argSlot)
	fmt.Fprintf(b, "  (func $%s (param $arg i32) (param $env i32) (result i32)\n", name)
	b.WriteString(f.localDecls())
	b.WriteString(inner.String())
	fmt.Fprintf(b, "    (local.get %s))\n", cl)
}

// emit lowers a CIr in the empty-locals context (def-thunk top level).
func (f *wasmFunc) emit(b *strings.Builder, t CIr, locals []string) string {
	return f.emitIn(b, t, locals)
}

// emitIn lowers a CIr in a context of `locals` (WAT expressions naming each binder
// visible by de Bruijn index, innermost = 0), writing `(local.set ...)` statements to b
// and returning a WAT expression naming the i32 result.
func (f *wasmFunc) emitIn(b *strings.Builder, t CIr, locals []string) string {
	switch x := t.(type) {
	case CVar:
		if x.Idx < len(locals) {
			return locals[x.Idx]
		}
		return "(call $rt_unit)" // closed-program safety marker
	case CEnv:
		return fmt.Sprintf("(call $rt_env (local.get $env) (i32.const %d))", x.Idx)
	case CGlobal:
		return fmt.Sprintf("(call $%s)", wasmThunkName(x.Name))
	case CForeign:
		// A whitelisted foreign lowers to its baked accessor thunk (emitForeignPrimsWasm),
		// named identically to a CGlobal thunk. The accessor returns the curried IO-closure
		// chain; wasmCheckSupported has already rejected any non-whitelisted foreign.
		return fmt.Sprintf("(call $%s)", wasmThunkName(x.Name))
	case CUnit:
		return "(call $rt_unit)"
	case CLit:
		return f.emitLit(b, x)
	case MkClosure:
		return f.emitMkClosure(b, x, locals)
	case AppClosure:
		if out, ok := f.satCtorDispatch(b, x, locals); ok {
			return out
		}
		if out, ok := f.satElimDispatch(b, x, locals); ok {
			return out
		}
		if out, ok := f.accelDispatch(b, x, locals); ok {
			return out
		}
		clo := f.emitIn(b, x.Clo, locals)
		arg := f.emitIn(b, x.Arg, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_apply %s %s))\n", r, clo, arg)
		return "(local.get " + r + ")"
	case CLet:
		v := f.emitIn(b, x.Val, locals)
		// Bind v to a fresh local so the body can reference it by name (de Bruijn 0).
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s %s)\n", r, v)
		return f.emitIn(b, x.Body, prependW("(local.get "+r+")", locals))
	case CPair:
		a := f.emitIn(b, x.A, locals)
		bb := f.emitIn(b, x.B, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_mkpair %s %s))\n", r, a, bb)
		return "(local.get " + r + ")"
	case CFst:
		p := f.emitIn(b, x.P, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_pair_fst %s))\n", r, p)
		return "(local.get " + r + ")"
	case CSnd:
		p := f.emitIn(b, x.P, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_pair_snd %s))\n", r, p)
		return "(local.get " + r + ")"
	case CField:
		s := f.emitIn(b, x.Scrut, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s (call $rt_con_get %s (i32.const %d)))\n", r, s, x.Index)
		return "(local.get " + r + ")"
	case CCase:
		return f.emitCase(b, x, locals)
	case CDup:
		// Retain V (a CVar/CEnv -- pure, no side effect) then evaluate K.
		v := f.emitIn(b, x.V, locals)
		fmt.Fprintf(b, "    (call $rt_retain %s)\n", v)
		return f.emitIn(b, x.K, locals)
	case CDrop:
		// Release V (a CVar/CEnv -- pure, no side effect) then evaluate K.
		v := f.emitIn(b, x.V, locals)
		fmt.Fprintf(b, "    (call $rt_release %s)\n", v)
		return f.emitIn(b, x.K, locals)
	case CBounce:
		return f.emitBounce(b, x.Call, locals)
	default:
		panic(fmt.Sprintf("codegen(wasm): unknown CIr node %T", t))
	}
}

// emitBounce lowers a CBounce (a saturated tail call to a partial member) to a K_BOUNCE:
// rt_mkbounce((call $<head>_step), nargs) then store each evaluated arg. The driver loop
// ($rt_tramp) forces the chain. A non-CGlobal head is not a recognizable partial spine,
// so emit the call directly (it runs, just not as a bounce).
func (f *wasmFunc) emitBounce(b *strings.Builder, call CIr, locals []string) string {
	var args []CIr
	t := call
	for {
		app, ok := t.(AppClosure)
		if !ok {
			break
		}
		args = append([]CIr{app.Arg}, args...)
		t = app.Clo
	}
	g, ok := t.(CGlobal)
	if !ok {
		return f.emitIn(b, call, locals)
	}
	o := f.fresh()
	fmt.Fprintf(b, "    (local.set %s (call $rt_mkbounce (call $%s) (i32.const %d)))\n", o, wasmStepName(g.Name), len(args))
	for i, a := range args {
		fmt.Fprintf(b, "    (call $rt_bounce_set (local.get %s) (i32.const %d) %s)\n", o, i, f.emitIn(b, a, locals))
	}
	return "(local.get " + o + ")"
}

// emitLit lowers a native literal. v1 supports LitInt (immediate-tagged i32) and LitNat
// (a parsed bignum); other kinds are rejected by wasmCheckSupported.
func (f *wasmFunc) emitLit(b *strings.Builder, x CLit) string {
	r := f.fresh()
	switch x.Kind {
	case LitNat:
		off := f.em.intern(x.Nat)
		fmt.Fprintf(b, "    (local.set %s (call $rt_big_parse (i32.const %d)))\n", r, off)
	default: // LitInt
		fmt.Fprintf(b, "    (local.set %s (call $rt_mkint (i32.const %d)))\n", r, x.Int)
	}
	return "(local.get " + r + ")"
}

// emitMkClosure allocates a closure and fills its env slots (each evaluated in the
// enclosing context). The env terms are evaluated FIRST (into locals), then the closure
// is built and filled — so a nested AppClosure inside an env slot does not interleave
// with the rt_clo_set calls.
func (f *wasmFunc) emitMkClosure(b *strings.Builder, x MkClosure, locals []string) string {
	idx := f.em.codeRef(wasmCodeName(x.Code))
	envVals := make([]string, len(x.Env))
	for i, e := range x.Env {
		ev := f.emitIn(b, e, locals)
		// Bind into a local so the value is stable across the alloc + sets.
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s %s)\n", r, ev)
		envVals[i] = "(local.get " + r + ")"
	}
	cl := f.fresh()
	fmt.Fprintf(b, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const %d)))\n", cl, idx, len(x.Env))
	for i, ev := range envVals {
		fmt.Fprintf(b, "    (call $rt_clo_set (local.get %s) (i32.const %d) %s)\n", cl, i, ev)
	}
	return "(local.get " + cl + ")"
}

// emitCase lowers an eliminator's tag dispatch. WAT has no n-way switch expression, so
// we read the tag into a local and emit a chain of `(if (i32.eq tag K) (then ...))`,
// each arm storing its result into a shared result local; an unmatched tag aborts.
func (f *wasmFunc) emitCase(b *strings.Builder, x CCase, locals []string) string {
	s := f.emitIn(b, x.Scrut, locals)
	tag := f.fresh()
	fmt.Fprintf(b, "    (local.set %s (call $rt_con_tag %s))\n", tag, s)
	res := f.fresh()
	// Sort arms by tag for deterministic output (matches the LLVM switch's stable
	// iteration; arms are already in declaration order but be explicit).
	arms := append([]CCaseArm(nil), x.Arms...)
	sort.SliceStable(arms, func(i, j int) bool { return arms[i].Tag < arms[j].Tag })
	for _, arm := range arms {
		fmt.Fprintf(b, "    (if (i32.eq (local.get %s) (i32.const %d)) (then\n", tag, arm.Tag)
		v := f.emitIn(b, arm.Body, locals)
		fmt.Fprintf(b, "      (local.set %s %s)\n", res, v)
		b.WriteString("    ))\n")
	}
	return "(local.get " + res + ")"
}

// satCtorDispatch recognizes a SATURATED constructor application -- an AppClosure spine
// headed by a CGlobal naming a (non-nat) constructor, with EXACTLY Arity args -- and emits
// the K_CON DIRECTLY: rt_mkcon(tag, name, arity) + one rt_con_set per arg (each arg value
// evaluated once and MOVED into its field slot). No intermediate partial-application K_CLO
// is ever allocated, so the arity>=2 currying container leak (the +1/run K_CLO_mk1 the
// recognize-then-skip rule could not release without double-freeing the moved field) is
// gone. Returns the result expression + true on a hit; "" + false otherwise.
//
// A PARTIALLY applied constructor (fewer than Arity args) does NOT match (len(args) !=
// c.Arity) and falls through to the generic rt_apply path -- it curries through
// emitCtorBlock as before, building a legitimate partial-application K_CLO the Perceus pass
// owns and drops normally.
//
// OUTPUT-INVARIANCE: the rt_mkcon name offset REUSES em.intern(c.Name), the SAME interning
// emitCtorBlock uses (emitDefs interns every ctor name before any body is emitted, so this
// is an idempotent lookup, not a re-intern), and the tag / field order match emitCtorBlock
// exactly -- the printed K_CON is byte-identical to the curried path.
//
// This is DISTINCT from an accel / nat-eliminator spine: those are headed by a CGlobal
// naming a builtin op / eliminator def, never a constructor in ctorByName (the builtin-nat
// ctors are excluded), so the dispatch order does not shadow accelMatchC / NatElimSpine.
func (f *wasmFunc) satCtorDispatch(b *strings.Builder, app AppClosure, locals []string) (string, bool) {
	// Unwind the application spine into head + args (left-to-right), mirroring
	// accelMatchC. The Perceus pass keeps a recognized ctor spine's BACKBONE bare (only
	// the leaf args carry consumeOwning wrappers), so the Clo chain here is a bare
	// AppClosure chain ending in the head CGlobal.
	var args []CIr
	t := CIr(app)
	for {
		ap, isApp := t.(AppClosure)
		if !isApp {
			break
		}
		args = append([]CIr{ap.Arg}, args...)
		t = ap.Clo
	}
	g, isGlobal := t.(CGlobal)
	if !isGlobal {
		return "", false
	}
	c, isCtor := f.em.ctorByName[g.Name]
	if !isCtor || len(args) != c.Arity {
		return "", false
	}
	nameOff := f.em.intern(c.Name) // idempotent: emitDefs already interned every ctor name
	// Evaluate each arg into a stable local FIRST (so a nested AppClosure inside an arg
	// does not interleave with the rt_con_set fills), then build + fill the con. Mirrors
	// emitMkClosure's evaluate-then-alloc-then-set ordering.
	vals := make([]string, len(args))
	for i, a := range args {
		ev := f.emitIn(b, a, locals)
		r := f.fresh()
		fmt.Fprintf(b, "    (local.set %s %s)\n", r, ev)
		vals[i] = "(local.get " + r + ")"
	}
	o := f.fresh()
	fmt.Fprintf(b, "    (local.set %s (call $rt_mkcon (i32.const %d) (i32.const %d) (i32.const %d)))\n", o, c.Tag, nameOff, c.Arity)
	for i, v := range vals {
		fmt.Fprintf(b, "    (call $rt_con_set (local.get %s) (i32.const %d) %s)\n", o, i, v)
	}
	return "(local.get " + o + ")", true
}

// satElimDispatch recognizes a SATURATED builtin-nat eliminator application -- a
// NatElimSpine `NatElim mot z step n` with EXACTLY 4 args -- and runs the fold
// DIRECTLY: it builds ONLY the b3 fold closure (env {unit, z, step}) and applies it
// to n, instead of currying through the cached eliminator thunk's b0->b1->b2 chain
// (three intermediate partial-application K_CLOs that leak -- the eliminator analogue
// of the satCtorDispatch container leak). This is what makes an inline NatElim fold
// reach steady-flat.
//
// The erased MOTIVE is evaluated (running its consumeOwning side effects) and freed
// immediately -- the fold never reads env slot 0, so the motive is not stored. z and
// step are MOVED into the b3 env (the closure owns them); the b3 closure is RELEASED
// after the call, freeing them. n is borrow-read by the fold and RELEASED here
// afterward. All four spine args arrive OWNED (annotateBareSpine consumeOwning'd each
// leaf), so these releases are balanced; emitNatFold retains its $acc so the base
// survives the b3 release (0-iteration return, and the step's per-iteration consume).
//
// A non-4-arg (partial or over-applied) nat-elim spine returns false and falls through
// to the generic rt_apply path unchanged. The head is the eliminator def CGlobal, never
// a ctor in ctorByName nor an accel op, so the dispatch order does not shadow.
func (f *wasmFunc) satElimDispatch(b *strings.Builder, app AppClosure, locals []string) (string, bool) {
	if f.em.natElim == "" {
		return "", false
	}
	args, ok := NatElimSpine(f.em.natElim, app)
	if !ok || len(args) != 4 {
		return "", false
	}
	mot, z, step, n := args[0], args[1], args[2], args[3]
	// Erased motive: evaluate (for its annotated side effects) and release. Not stored.
	emot := f.emitIn(b, mot, locals)
	fmt.Fprintf(b, "    (call $rt_release %s)\n", emot)
	// z, step, n into stable locals (a nested AppClosure in one must not interleave the
	// closure fills); z and step are moved into the env, n is the fold bound.
	ez := f.emitIn(b, z, locals)
	rz := f.fresh()
	fmt.Fprintf(b, "    (local.set %s %s)\n", rz, ez)
	estep := f.emitIn(b, step, locals)
	rstep := f.fresh()
	fmt.Fprintf(b, "    (local.set %s %s)\n", rstep, estep)
	en := f.emitIn(b, n, locals)
	rn := f.fresh()
	fmt.Fprintf(b, "    (local.set %s %s)\n", rn, en)
	// Build the b3 fold closure {unit, z, step} and run it on n.
	b3idx := f.em.codeRef(wasmName(f.em.natElim) + "_b3")
	cl := f.fresh()
	fmt.Fprintf(b, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 3)))\n", cl, b3idx)
	fmt.Fprintf(b, "    (call $rt_clo_set (local.get %s) (i32.const 0) (call $rt_unit))\n", cl)
	fmt.Fprintf(b, "    (call $rt_clo_set (local.get %s) (i32.const 1) (local.get %s))\n", cl, rz)
	fmt.Fprintf(b, "    (call $rt_clo_set (local.get %s) (i32.const 2) (local.get %s))\n", cl, rstep)
	r := f.fresh()
	fmt.Fprintf(b, "    (local.set %s (call $rt_apply (local.get %s) (local.get %s)))\n", r, cl, rn)
	fmt.Fprintf(b, "    (call $rt_release (local.get %s))\n", cl) // frees env z + step
	fmt.Fprintf(b, "    (call $rt_release (local.get %s))\n", rn) // the bound, dead now
	return "(local.get " + r + ")", true
}

// accelDispatch emits a registered accel-op def on two args as native bignum arithmetic
// (the rt_nat_add/mul/monus helpers), interchangeable with the eliminator loop.
func (f *wasmFunc) accelDispatch(b *strings.Builder, app AppClosure, locals []string) (string, bool) {
	op, a, bb, ok := accelMatchC(app, f.em.accel)
	if !ok {
		return "", false
	}
	ea := f.emitIn(b, a, locals)
	eb := f.emitIn(b, bb, locals)
	r := f.fresh()
	var opName string
	switch op {
	case core.NatOpAdd:
		opName = "rt_nat_add"
	case core.NatOpMul:
		opName = "rt_nat_mul"
	case core.NatOpMonus:
		opName = "rt_nat_monus"
	default:
		return "", false
	}
	fmt.Fprintf(b, "    (local.set %s (call $%s %s %s))\n", r, opName, ea, eb)
	// The accel op BORROW-reads its two operands (rt_nat_* read both inputs and
	// return a fresh K_BIG) and has now read them, so both operands are dead. Every
	// operand reaching here is a PRIVATE OWNED reference: annotateBareSpine routes each
	// accel leaf through consumeOwning (a bare owned CVar stays a single private ref; a
	// borrowed CEnv/CGlobal/projection is dup'd to a fresh owned ref), and a local
	// consumed in both operand sub-spines is dup'd once by annotateBareSpine's
	// shared-owned-local dup, while a local also used outside the spine is dup'd by the
	// enclosing scope. So exactly one live reference reaches the op per operand, and the
	// op must free both -- the accel dual of succ_code freeing its $arg under PATH B.
	// Releasing unconditionally (not just fresh-producing forms) is what closes the
	// owned-CVar / dup'd-borrow operand leak; a borrowed root is never reached bare here
	// because consumeOwning already replaced it with an owned dup.
	fmt.Fprintf(b, "    (call $rt_release %s)\n", ea)
	fmt.Fprintf(b, "    (call $rt_release %s)\n", eb)
	return "(local.get " + r + ")", true
}

// emitForeignPrimsWasm bakes the WAT bodies for the supported foreign IO ops referenced
// by p, plus the IO monad (bindIO/pureIO) when the program uses IO. It mirrors the JS
// ioRuntime + the D6 host-body bake (js.go) and the C cIORuntime + printNat (c.go), but
// over the WASM value rep + ARC. Each op is a CURRIED IO-CLOSURE CHAIN (the load-bearing
// template Tasks 2-5 reuse verbatim):
//
//	accessor $def_<op>  : (result i32)                 -> mkclo(code_0, 0)   [the CGlobal thunk]
//	  code_0 (arg=v0, env={})     -> mkclo(code_1, 1); slot0 = v0            [bind a value arg]
//	  ...                                                                    [more value args]
//	  code_k (arg=world, env={..}) -> <perform effect>; return <owned value> [the world step]
//
// The world token is $rt_unit (immortal: no retain/release). ARC discipline: a code block
// receives its $arg OWNED (move it into a captured slot, or consume it) and its $env slots
// BORROWED (retain before forwarding into a child closure that will be released; never
// release the env here -- rt_free reclaims it when the closure dies). A world step that
// returns a captured/borrowed value RETAINS it first so the yielded result is an
// independent owned reference. Intermediate closures produced by rt_apply are released.
func (em *wasmEmitter) emitForeignPrimsWasm(b *strings.Builder, p Program) {
	if usesIO(p) {
		em.emitPureIOWasm(b)
		em.emitBindIOWasm(b)
	}
	if usesForeign(p, "printNat") {
		em.emitPrintNatWasm(b)
	}
	if usesForeign(p, "timeNanos") {
		em.emitTimeNanosWasm(b)
	}
}

// emitPrintNatWasm bakes `printNat : Nat -> IO Nat` -- the FIRST foreign IO op and the
// documented curried template. accessor -> closure(Nat) -> closure(world) -> effect.
// The world step renders the Nat's decimal + newline to stdout (fd 1) via $rt_show_line
// (K_BIG -> emit_big is exactly the decimal), then RETAINS + returns the Nat.
func (em *wasmEmitter) emitPrintNatWasm(b *strings.Builder) {
	vIdx := em.codeRef("printNat_v")
	wIdx := em.codeRef("printNat_w")
	// world step: env={n}. Print n, return it as an owned reference.
	b.WriteString("  (func $printNat_w (param $arg i32) (param $env i32) (result i32) (local $n i32)\n")
	b.WriteString("    (local.set $n (call $rt_env (local.get $env) (i32.const 0)))\n")
	b.WriteString("    (call $rt_show_line (local.get $n))\n")
	b.WriteString("    (call $rt_retain (local.get $n))\n") // yield an independent owned ref
	b.WriteString("    (local.get $n))\n")
	// value step: capture the (owned) Nat arg into the world step's env (MOVE).
	fmt.Fprintf(b, "  (func $printNat_v (param $arg i32) (param $env i32) (result i32) (local $c i32)\n")
	fmt.Fprintf(b, "    (local.set $c (call $rt_mkclo (i32.const %d) (i32.const 1)))\n", wIdx)
	b.WriteString("    (call $rt_clo_set (local.get $c) (i32.const 0) (local.get $arg))\n")
	b.WriteString("    (local.get $c))\n")
	// accessor thunk $def_printNat -> mkclo(printNat_v, 0).
	em.emitCachedThunk(b, "printNat", func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, vIdx)
		return "(local.get " + r + ")"
	})
}

// emitTimeNanosWasm bakes `timeNanos : IO Nat` -- the world-only arity of the template
// (accessor -> closure(world) -> effect; no value arg). The world step reads the WASI
// monotonic clock (clock_time_get, clock_id 1) into the [24,32) scratch cell and builds a
// bignum from the i64 nanosecond count. The result is fresh/owned (no retain needed).
func (em *wasmEmitter) emitTimeNanosWasm(b *strings.Builder) {
	wIdx := em.codeRef("timeNanos_w")
	b.WriteString("  (func $timeNanos_w (param $arg i32) (param $env i32) (result i32)\n")
	b.WriteString("    (drop (call $clock_time_get (i32.const 1) (i64.const 0) (i32.const 24)))\n")
	b.WriteString("    (call $rt_big_from_i64 (i64.load (i32.const 24))))\n")
	em.emitCachedThunk(b, "timeNanos", func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, wIdx)
		return "(local.get " + r + ")"
	})
}

// emitPureIOWasm bakes `pureIO A a u = a` (a constant world thunk). accessor -> closure(A)
// -> closure(a) -> closure(world) -> a. The type arg A erases to $rt_unit (immortal). The
// world step RETAINS + returns the captured value as an independent owned reference.
func (em *wasmEmitter) emitPureIOWasm(b *strings.Builder) {
	p0 := em.codeRef("io_pure0")
	p1 := em.codeRef("io_pure1")
	p2 := em.codeRef("io_pure2")
	// io_pure2: env={a}, arg=world. Return a (owned).
	b.WriteString("  (func $io_pure2 (param $arg i32) (param $env i32) (result i32) (local $a i32)\n")
	b.WriteString("    (local.set $a (call $rt_env (local.get $env) (i32.const 0)))\n")
	b.WriteString("    (call $rt_retain (local.get $a))\n")
	b.WriteString("    (local.get $a))\n")
	// io_pure1: arg=a (owned), build io_pure2 capturing a (MOVE).
	fmt.Fprintf(b, "  (func $io_pure1 (param $arg i32) (param $env i32) (result i32) (local $c i32)\n")
	fmt.Fprintf(b, "    (local.set $c (call $rt_mkclo (i32.const %d) (i32.const 1)))\n", p2)
	b.WriteString("    (call $rt_clo_set (local.get $c) (i32.const 0) (local.get $arg))\n")
	b.WriteString("    (local.get $c))\n")
	// io_pure0: arg=A (type/unit, discarded), return mkclo(io_pure1, 0).
	fmt.Fprintf(b, "  (func $io_pure0 (param $arg i32) (param $env i32) (result i32)\n")
	fmt.Fprintf(b, "    (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", p1)
	em.emitCachedThunk(b, "pureIO", func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, p0)
		return "(local.get " + r + ")"
	})
}

// emitBindIOWasm bakes `bindIO A B m k u = k (m ()) ()` -- the IO sequencing combinator.
// accessor -> A -> B -> m -> k -> world -> effect. The world step (io_bind4, env={m,k})
// runs m on the world (m borrowed from env), feeds its value to k (borrowed), runs the
// resulting action on the world, RELEASES that fresh intermediate action, and yields its
// value. io_bind3 RETAINS the forwarded m (env slot) into io_bind4 and MOVES the owned k.
func (em *wasmEmitter) emitBindIOWasm(b *strings.Builder) {
	i0 := em.codeRef("io_bind0")
	i1 := em.codeRef("io_bind1")
	i2 := em.codeRef("io_bind2")
	i3 := em.codeRef("io_bind3")
	i4 := em.codeRef("io_bind4")
	// io_bind4: env={m,k}, arg=world. k (m ()) ().
	b.WriteString("  (func $io_bind4 (param $arg i32) (param $env i32) (result i32) (local $v i32) (local $act i32) (local $r i32)\n")
	b.WriteString("    (local.set $v (call $rt_apply (call $rt_env (local.get $env) (i32.const 0)) (call $rt_unit)))\n")
	b.WriteString("    (local.set $act (call $rt_apply (call $rt_env (local.get $env) (i32.const 1)) (local.get $v)))\n")
	b.WriteString("    (local.set $r (call $rt_apply (local.get $act) (call $rt_unit)))\n")
	b.WriteString("    (call $rt_release (local.get $act))\n") // fresh action from k: reclaim
	b.WriteString("    (local.get $r))\n")
	// io_bind3: env={m}, arg=k. Build io_bind4 {m,k}: retain forwarded m, move owned k.
	fmt.Fprintf(b, "  (func $io_bind3 (param $arg i32) (param $env i32) (result i32) (local $c i32)\n")
	fmt.Fprintf(b, "    (local.set $c (call $rt_mkclo (i32.const %d) (i32.const 2)))\n", i4)
	b.WriteString("    (call $rt_retain (call $rt_env (local.get $env) (i32.const 0)))\n")
	b.WriteString("    (call $rt_clo_set (local.get $c) (i32.const 0) (call $rt_env (local.get $env) (i32.const 0)))\n")
	b.WriteString("    (call $rt_clo_set (local.get $c) (i32.const 1) (local.get $arg))\n")
	b.WriteString("    (local.get $c))\n")
	// io_bind2: arg=m (owned), build io_bind3 capturing m (MOVE).
	fmt.Fprintf(b, "  (func $io_bind2 (param $arg i32) (param $env i32) (result i32) (local $c i32)\n")
	fmt.Fprintf(b, "    (local.set $c (call $rt_mkclo (i32.const %d) (i32.const 1)))\n", i3)
	b.WriteString("    (call $rt_clo_set (local.get $c) (i32.const 0) (local.get $arg))\n")
	b.WriteString("    (local.get $c))\n")
	// io_bind1: arg=B (type/unit, discarded), return mkclo(io_bind2, 0).
	fmt.Fprintf(b, "  (func $io_bind1 (param $arg i32) (param $env i32) (result i32)\n")
	fmt.Fprintf(b, "    (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", i2)
	// io_bind0: arg=A (type/unit, discarded), return mkclo(io_bind1, 0).
	fmt.Fprintf(b, "  (func $io_bind0 (param $arg i32) (param $env i32) (result i32)\n")
	fmt.Fprintf(b, "    (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", i1)
	em.emitCachedThunk(b, "bindIO", func(f *wasmFunc, bb *strings.Builder) string {
		r := f.fresh()
		fmt.Fprintf(bb, "    (local.set %s (call $rt_mkclo (i32.const %d) (i32.const 0)))\n", r, i0)
		return "(local.get " + r + ")"
	})
}

// wasmName sanitizes a rune identifier into a WAT-symbol fragment ([A-Za-z0-9_], shared
// with the C/LLVM sanitizer so symbol schemes match).
func wasmName(n string) string { return cName(n) }

// wasmThunkName / wasmCodeName namespace the two emitted symbol kinds, matching the LLVM
// backend's scheme.
func wasmThunkName(n string) string { return "def_" + wasmName(n) }
func wasmCodeName(n string) string  { return "code_" + wasmName(n) }

// prependW pushes a new innermost local (de Bruijn 0) onto the locals stack.
func prependW(v string, locals []string) []string {
	out := make([]string, 0, len(locals)+1)
	out = append(out, v)
	out = append(out, locals...)
	return out
}

// wasmDataStr renders a Go string as a WAT data-segment string literal (each byte as
// \HH for non-printables / quote / backslash), NUL-terminated.
func wasmDataStr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '\\':
			b.WriteString("\\5c")
		case c == '"':
			b.WriteString("\\22")
		case c < 0x20 || c >= 0x7f:
			fmt.Fprintf(&b, "\\%02x", c)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteString("\\00")
	b.WriteByte('"')
	return b.String()
}
