package codegen

import (
	"fmt"
	"sort"
	"strings"
)

// EmitLibrary lowers a Rune program to a LIBRARY-mode WAT module (the export ABI, no
// `_start`) plus a generated ES module `glue.js` a browser (or any WASI-free JS host)
// can `import` directly. It shares the app-mode module core (emitModuleCore: the
// function-table type, the inline runtime, the interned string data, and every code
// block / definition thunk) with Wasm.Emit -- app-mode output stays byte-identical
// because that shared path is untouched; only the entry point differs.
//
// The export ABI (spec Decision 3, docs/superpowers/specs/2026-07-03-wasm-webrtc-shim-
// design.md): beyond the runtime's own `(export "memory" ...)`,
//
//	init                        seed $UNIT; MUST be called once before any other export
//	rt_apply(clo, arg) -> val
//	rt_retain(v)  rt_release(v)
//	rt_mkbin(len) -> bin        rt_bin_set(bin, i, byte)
//	rt_bin_len(bin) -> len      rt_bin_at(bin, i) -> byte
//	rt_live() -> n              live heap-block count (ARC balance probe, test surface)
//	rt_nat_to_u32(v) -> u32     read a builtin-Nat as a saturating host u32 (glue readNat)
//	def_<name>() -> clo         one per --export'ed definition (memoized accessor)
//
// `_start` is never emitted in library mode (no main invocation, no stdout print).
func (Wasm) EmitLibrary(p Program, spec BuildSpec) (ArtifactSet, error) {
	if len(spec.Exports) == 0 {
		return ArtifactSet{}, fmt.Errorf("wasm library build needs at least one export")
	}
	defs := map[string]DefSpec{}
	for _, d := range p.Defs {
		defs[d.Name] = d
	}
	for _, ex := range spec.Exports {
		if _, ok := defs[ex.RuneName]; !ok {
			return ArtifactSet{}, fmt.Errorf("wasm library export %q is not an emitted definition", ex.RuneName)
		}
	}
	// Reject the unsupported fragment up front, same honesty gate as app-mode Emit.
	if err := wasmCheckSupported(p); err != nil {
		return ArtifactSet{}, err
	}

	em, core := emitModuleCore(p)

	var b strings.Builder
	b.WriteString(";; Generated by rune build (wasm backend, library) - export ABI, no _start.\n")
	b.WriteString(";; Load via the sibling glue.js (WebAssembly.instantiate + WASI stubs);\n")
	b.WriteString(";; call `init` once before any other export (see the glue's ownership header).\n")
	b.WriteString("(module\n")
	b.WriteString(core.String())
	// The function table + elem: every code block by its assigned index.
	em.emitTable(&b)

	// The rt_* runtime ABI: standalone exports of already-defined runtime funcs (WAT
	// allows exporting a function by name after its definition).
	for _, fn := range []string{
		"rt_apply", "rt_retain", "rt_release",
		"rt_mkbin", "rt_bin_len", "rt_bin_set", "rt_bin_at",
		"rt_live", "rt_nat_to_u32",
	} {
		fmt.Fprintf(&b, "  (export %q (func $%s))\n", fn, fn)
	}

	// init: seed $UNIT only -- exactly the seeding instruction from app-mode _start
	// (wasm.go's emitModuleCore-era _start, unchanged: `(global.set $UNIT (call
	// $rt_mkcon (i32.const 0) (global.get $unit_name) (i32.const 0)))`).
	b.WriteString("  (func $init (export \"init\")\n")
	b.WriteString("    (global.set $UNIT (call $rt_mkcon (i32.const 0) (global.get $unit_name) (i32.const 0))))\n")

	// def_<name> per requested export: a standalone export of the memoized accessor
	// thunk emitDefs already built for every top-level definition (emitCachedThunk
	// names it wasmThunkName(name) == "def_" + wasmName(name), matching the export ABI
	// name exactly -- no wrapper function needed).
	//
	// exportManifest maps the glue-facing name (HostName if given, else RuneName) to
	// the WAT export symbol, so glue.js's call() can look it up without re-deriving
	// wasmName's sanitization rules in JS.
	exportManifest := make(map[string]string, len(spec.Exports))
	for _, ex := range spec.Exports {
		thunk := wasmThunkName(ex.RuneName)
		fmt.Fprintf(&b, "  (export %q (func $%s))\n", thunk, thunk)
		key := ex.HostName
		if key == "" {
			key = ex.RuneName
		}
		exportManifest[key] = thunk
	}
	b.WriteString(")\n")

	glue := wasmLibraryGlue(exportManifest)

	name := wasmLibraryBaseName(spec.Module)
	watPath := name + ".wat"
	gluePath := name + ".glue.js"
	return ArtifactSet{
		Target: "wasm",
		Kind:   BuildLibrary,
		Artifacts: []Artifact{
			{Path: watPath, Role: ArtifactSource, Data: []byte(b.String())},
			{Path: gluePath, Role: ArtifactSource, Data: []byte(glue)},
		},
		Link: &LinkHint{Args: []string{"wasmtime", "run", "--invoke", "init", watPath}},
	}, nil
}

// wasmLibraryBaseName derives the artifact base name from BuildSpec.Module (the last
// path segment, sanitized to a plain identifier), defaulting to "module" when Module
// is empty -- mirrors goPackageFromModule's shape for the Go backend.
func wasmLibraryBaseName(module string) string {
	if module == "" {
		return "module"
	}
	module = strings.TrimSuffix(module, "/")
	if i := strings.LastIndexAny(module, "/@"); i >= 0 {
		module = module[i+1:]
	}
	name := wasmName(module)
	if name == "" {
		return "module"
	}
	return name
}

// wasmLibraryWasiStubs are the 12 unconditional WASI preview1 imports every WASM
// module declares (wasm_runtime.go:34-66), verbatim by name. A library host (a
// browser, or any WASI-free JS runtime) never actually services file/env/argv/process
// syscalls for a pure computation module, so every stub is a harmless constant-0
// return; wasmtime's own `run` command provides real implementations of these same
// imports for the app-mode `_start` path, so the two hosts diverge only in how much
// they implement, never in the import surface a module declares.
var wasmLibraryWasiStubs = []string{
	"fd_write", "clock_time_get",
	"fd_read", "fd_close", "fd_seek", "fd_readdir", "path_open",
	"environ_sizes_get", "environ_get", "args_sizes_get", "args_get",
	"proc_exit",
}

// wasmLibraryGlue renders the generated ES module glue.js: the WASI stub object, the
// load/mkBin/readBin/readNat/call/retain/release helpers, and the ownership-contract
// header (spec Decision 3, verbatim).
func wasmLibraryGlue(exportManifest map[string]string) string {
	keys := make([]string, 0, len(exportManifest))
	for k := range exportManifest {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// glue.js - generated by `rune build` (wasm backend, library mode).\n")
	b.WriteString("//\n")
	b.WriteString("// Ownership contract (spec Decision 3): values returned to JS are owned by JS\n")
	b.WriteString("// (release when done); arguments passed to `rt_apply` are consumed (moved)\n")
	b.WriteString("// exactly as in-module; the `def_<name>` accessor result is borrowed (the\n")
	b.WriteString("// memoized cache owns it) and MUST NOT be released by JS: retain first if a\n")
	b.WriteString("// reference is kept. Bin payload bytes live at `ptr+8` for `rt_bin_len(ptr)`\n")
	b.WriteString("// bytes; this (ptr,len) window is ABI, stable per the K_BIN design.\n")
	b.WriteString("//\n")
	b.WriteString("// `init` MUST be called once (via `load`, below) before any other export.\n")
	b.WriteString("//\n")
	b.WriteString("// readNat(handle, ptr) reads a builtin-Nat result as a host u32 via the\n")
	b.WriteString("// rt_nat_to_u32 export (saturating at 2^32-1 for values that do not fit; read\n")
	b.WriteString("// the return with `>>> 0` if you need the unsigned interpretation of the\n")
	b.WriteString("// saturation sentinel).\n\n")

	b.WriteString("export const WASI_STUBS = {\n")
	b.WriteString("  wasi_snapshot_preview1: {\n")
	for _, name := range wasmLibraryWasiStubs {
		fmt.Fprintf(&b, "    %s: () => 0,\n", name)
	}
	b.WriteString("  },\n")
	b.WriteString("};\n\n")

	b.WriteString("// EXPORT_MAP: glue-facing name -> the WAT export symbol (def_<name>).\n")
	b.WriteString("export const EXPORT_MAP = {\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "  %s: %s,\n", jsIdentOrString(k), jsStringLit(exportManifest[k]))
	}
	b.WriteString("};\n\n")

	b.WriteString(`// load: instantiate the WASM bytes against the WASI-stub import object, run
// init exactly once, and return a handle exposing the raw exports + memory.
export async function load(bytes) {
  const { instance } = await WebAssembly.instantiate(bytes, WASI_STUBS);
  const exports = instance.exports;
  exports.init();
  return { exports, memory: exports.memory };
}

// mkBin: pack a Uint8Array into a fresh K_BIN and return its pointer (owned by the
// caller -- release it when done, per the ownership contract).
export function mkBin(handle, u8) {
  const ptr = handle.exports.rt_mkbin(u8.length);
  for (let i = 0; i < u8.length; i++) {
    handle.exports.rt_bin_set(ptr, i, u8[i]);
  }
  return ptr;
}

// readBin: copy a K_BIN's payload bytes out of WASM linear memory as a fresh
// Uint8Array. The payload window is (ptr+8, rt_bin_len(ptr)) bytes -- ABI per the
// K_BIN design (see the header).
export function readBin(handle, ptr) {
  const len = handle.exports.rt_bin_len(ptr);
  return new Uint8Array(handle.memory.buffer, ptr + 8, len).slice();
}

// readNat: read a builtin-Nat result as a host u32 (see the header note on
// saturation).
export function readNat(handle, ptr) {
  return handle.exports.rt_nat_to_u32(ptr) >>> 0;
}

// call(handle, name, ...args): invoke the named export's memoized accessor
// (def_<name>()), retain its borrowed result (the accessor's cache still owns the
// value the memoized thunk returns; retaining gives this call its own reference),
// then chain rt_apply over each argument. Returns the final owned value -- release it
// when done.
export function call(handle, name, ...args) {
  const exportName = EXPORT_MAP[name];
  if (!exportName) {
    throw new Error(` + "`unknown export ${name}`" + `);
  }
  let v = handle.exports[exportName]();
  handle.exports.rt_retain(v);
  for (const a of args) {
    v = handle.exports.rt_apply(v, a);
  }
  return v;
}

// retain / release: passthroughs to the rt_* ABI, for values held across calls.
export function retain(handle, v) {
  handle.exports.rt_retain(v);
}

export function release(handle, v) {
  handle.exports.rt_release(v);
}
`)
	return b.String()
}

// jsIdentOrString renders a glue-facing export key as a JS object-literal property
// key: a bare identifier when it looks like one, else a quoted string (a HostName
// could in principle contain characters that are not a valid bare JS identifier).
func jsIdentOrString(name string) string {
	if name == "" {
		return `""`
	}
	for i := 0; i < len(name); i++ {
		c := name[i]
		alnum := c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c == '_' || c == '$' || (i > 0 && c >= '0' && c <= '9')
		if !alnum {
			return jsStringLit(name)
		}
	}
	return name
}

// jsStringLit renders a Go string as a double-quoted JS string literal.
func jsStringLit(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}
