// Code generated by goplus from meta.gp. DO NOT EDIT.
//goplus:v v0.15.0

package elaborate

import (
	"fmt"
	"sort"
	"strconv"

	"goforge.dev/rune/v3/core"
)

// Metavariables (Phase 2). Metas are ELABORATION-SCOPED: created fresh per
// Elaborator run, solved by pattern unification, and eliminated by zonking
// before any term reaches the store or the hash boundary. The proof-cache layer
// never sees them — checking cached core is the deterministic, meta-free
// judgment (ref_docs/rune-proof-cache-semantics.md §0).

// metaEntry is one metavariable: its solution value and quoted solution term,
// nil/unset while unsolved.
type metaEntry struct {
	solution core.Val
	name     string // a display hint: where the meta came from
}

// metaState is the Elaborator's meta table; it satisfies core.MetaSolver so the
// shared Machine forces solved metas transparently.
type metaState struct {
	entries []metaEntry
}

// Solution implements core.MetaSolver.
func (ms *metaState) Solution(id int) (core.Val, bool) {
	if id < 0 || id >= len(ms.entries) || ms.entries[id].solution == nil {
		return nil, false
	}
	return ms.entries[id].solution, true
}

// freshMeta mints a new metavariable and returns its CONTEXTUAL term: the meta
// applied to every lambda/Pi-bound variable in scope (let-bound variables are
// definitionally transparent and excluded, keeping spines in the pattern
// fragment). The term is well-scoped in c.
func (e *Elaborator) freshMeta(c *Ctx, hint string) core.Tm {
	id := len(e.metas.entries)
	e.metas.entries = append(e.metas.entries, metaEntry{name: hint})
	var tm core.Tm = core.Meta{ID: id}
	// Apply outermost-first: walk indices from the outside in.
	for i := len(c.names) - 1; i >= 0; i-- {
		if c.bound[i] {
			tm = core.App{Fn: tm, Arg: core.Var{Idx: i}, Icit: core.Expl}
		}
	}
	return tm
}

// unsolved returns the ids of unsolved metas, sorted.
func (e *Elaborator) unsolved() []int {
	var out []int
	for i, m := range e.metas.entries {
		if m.solution == nil {
			out = append(out, i)
		}
	}
	sort.Ints(out)
	return out
}

// ErrUnsolved formats the unsolved-metas error for a definition or expression.
func (e *Elaborator) ErrUnsolved(what string) error {
	ids := e.unsolved()
	if len(ids) == 0 {
		return nil
	}
	holes := ""
	for i, id := range ids {
		if i > 0 {
			holes += ", "
		}
		holes += fmt.Sprintf("?%d", id)
		if n := e.metas.entries[id].name; n != "" {
			holes += " (" + n + ")"
		}
	}
	n := len(ids)
	thing := "one value"
	if n > 1 {
		thing = strconv.Itoa(n) + " values"
	}
	return &Diagnostic{
		Summary: "I couldn't work out every type in " + what + ".",
		Body: []string{
			"Type inference left " + thing + " undetermined: " + holes + ". These come " +
				"from a hole (`_`) or an implicit argument (`{…}`) that the surrounding code " +
				"does not pin down — there was not enough information to fill them in.",
		},
		Hints: []string{
			"Add an annotation where the type is ambiguous: give the hole an explicit type, " +
				"or pass the implicit argument directly with `{the type}`, so inference has " +
				"a value to work from.",
		},
	}
}

// Zonk replaces every solved metavariable in t by its solution, β-reducing only
// the meta-headed applications it rewrites (user redexes are left untouched, so
// plain programs keep resolution's exact core and hashes). t must be well-scoped
// at depth lvl. Unsolved metas survive zonking; callers reject them separately.
func (e *Elaborator) Zonk(lvl int, t core.Tm) core.Tm {
	switch __gp_m0 := any(t).(type) {
	case core.Var, core.Ref, core.Univ, core.Prop, core.NatLit:
		// Leaves (a compressed numeral carries no subterms and no metas).
		return t
	case core.Eq:
		ty := __gp_m0.Ty
		l := __gp_m0.L
		r := __gp_m0.R
		return core.Eq{Ty: e.Zonk(lvl, ty), L: e.Zonk(lvl, l), R: e.Zonk(lvl, r)}
	case core.Refl:
		tm := __gp_m0.Tm
		return core.Refl{Tm: e.Zonk(lvl, tm)}
	case core.Cast:
		a := __gp_m0.A
		b := __gp_m0.B
		p := __gp_m0.P
		x := __gp_m0.X
		return core.Cast{A: e.Zonk(lvl, a), B: e.Zonk(lvl, b), P: e.Zonk(lvl, p), X: e.Zonk(lvl, x)}
	case core.Subst:
		a := __gp_m0.A
		x := __gp_m0.X
		y := __gp_m0.Y
		prf := __gp_m0.Prf
		p := __gp_m0.P
		px := __gp_m0.Px
		return core.Subst{A: e.Zonk(lvl, a), X: e.Zonk(lvl, x), Y: e.Zonk(lvl, y), Prf: e.Zonk(lvl, prf), P: e.Zonk(lvl, p), Px: e.Zonk(lvl, px)}
	case core.Meta:
		id := __gp_m0.ID
		if sol, ok := e.metas.Solution(id); ok {
			return e.Zonk(lvl, e.M.Quote(lvl, sol))
		}
		return t
	case core.Pi:
		icit := __gp_m0.Icit
		qty := __gp_m0.Qty
		dom := __gp_m0.Dom
		cod := __gp_m0.Cod
		return core.Pi{Icit: icit, Qty: qty, Dom: e.Zonk(lvl, dom), Cod: core.Scope{Name: cod.Name, Body: e.Zonk(lvl+1, cod.Body)}}
	case core.Lam:
		icit := __gp_m0.Icit
		qty := __gp_m0.Qty
		body := __gp_m0.Body
		return core.Lam{Icit: icit, Qty: qty, Body: core.Scope{Name: body.Name, Body: e.Zonk(lvl+1, body.Body)}}
	case core.App:
		fn := __gp_m0.Fn
		arg := __gp_m0.Arg
		icit := __gp_m0.Icit
		// A meta-headed application whose head is solved is evaluated away as a
		// unit, not rebuilt — the artificial redex must not reach the core.
		if id, ok := metaHead(t); ok {
			if _, solved := e.metas.Solution(id); solved {
				// Evaluate the spine, force the flexible head away (Quote never
				// forces), and re-zonk the readback for metas in arguments.
				v := e.forceFlex(e.M.Eval(spineEnv(lvl), t))
				return e.Zonk(lvl, e.M.Quote(lvl, v))
			}
		}
		return core.App{Fn: e.Zonk(lvl, fn), Arg: e.Zonk(lvl, arg), Icit: icit}
	case core.Let:
		ty := __gp_m0.Ty
		val := __gp_m0.Val
		body := __gp_m0.Body
		var zty core.Tm
		if ty != nil {
			zty = e.Zonk(lvl, ty)
		}
		return core.Let{Ty: zty, Val: e.Zonk(lvl, val), Body: core.Scope{Name: body.Name, Body: e.Zonk(lvl+1, body.Body)}}
	case core.Ann:
		term := __gp_m0.Term
		ty := __gp_m0.Ty
		return core.Ann{Term: e.Zonk(lvl, term), Ty: e.Zonk(lvl, ty)}
	case core.Sig:
		qty := __gp_m0.Qty
		dom := __gp_m0.Dom
		cod := __gp_m0.Cod
		return core.Sig{Qty: qty, Dom: e.Zonk(lvl, dom), Cod: core.Scope{Name: cod.Name, Body: e.Zonk(lvl+1, cod.Body)}}
	case core.Pair:
		dom := __gp_m0.Dom
		cod := __gp_m0.Cod
		a := __gp_m0.A
		b := __gp_m0.B
		return core.Pair{Dom: e.Zonk(lvl, dom), Cod: core.Scope{Name: cod.Name, Body: e.Zonk(lvl+1, cod.Body)}, A: e.Zonk(lvl, a), B: e.Zonk(lvl, b)}
	case core.Fst:
		p := __gp_m0.P
		return core.Fst{P: e.Zonk(lvl, p)}
	case core.Snd:
		p := __gp_m0.P
		return core.Snd{P: e.Zonk(lvl, p)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// metaHead reports the meta id heading an application spine, if any.
func metaHead(t core.Tm) (int, bool) {
	for {
		switch __gp_m1 := any(t).(type) {
		case core.App:
			fn := __gp_m1.Fn
			t = fn
		case core.Meta:
			id := __gp_m1.ID
			return id, true
		default:
			return 0, false
		}
	}
}

// spineEnv is the identity environment at depth lvl: Var i ↦ the free variable
// at level lvl-1-i, so evaluating an open term and quoting back at lvl is the
// identity on everything but the reduced meta application.
func spineEnv(lvl int) core.Env {
	env := make(core.Env, lvl)
	for i := 0; i < lvl; i++ {
		env[i] = core.VVar(lvl - 1 - i)
	}
	return env
}

// MetaFree reports whether t contains no metavariables (solved or not) — the
// invariant required at the store/hash boundary.
func MetaFree(t core.Tm) bool {
	if t == nil {
		return false // matches the old walk: nil is not judged meta-free
	}
	// The derived traversal walks every subterm; one Meta anywhere sinks it.
	for sub := range core.TmUniverse(t) {
		switch any(sub).(type) {
		case core.Meta:
			return false
		default:
		}
	}
	return true
}
