// Code generated by goplus from conv.gp. DO NOT EDIT.
//goplus:v v0.15.0

package core

// Phase 1: definitional conversion over the glued Val domain. Authored in Go+
// (v3.383.0): the Val/Neutral case analyses are matches — an added variant is
// an exhaustiveness error at generation time, not a runtime panic.
//
// The glued fast path: two neutrals are compared SPINE-FIRST — syntactically, no
// unfolding, no dependency logged. Only on mismatch does conversion force the lazy
// unfoldings (δ), and forcing logs the unfolded definition into the Machine's
// dependency set. So the log records exactly the bodies the judgment consulted —
// the Frame Lemma's U — and the fast path stays free.

// Conv reports whether a and b are definitionally equal (βδη) at level lvl.
func (m *Machine) Conv(lvl int, a, b Val) bool {
	// η for functions: if either side is a lambda, compare both applied to a
	// fresh variable (Apply extends a neutral's spine, so neutral-vs-lambda
	// compares pointwise).
	if _, ok := a.(VLam); ok {
		return m.convApplied(lvl, a, b)
	}
	if _, ok := b.(VLam); ok {
		return m.convApplied(lvl, a, b)
	}
	// η for pairs: if either side is a concrete pair, compare projections
	// componentwise, so a neutral r converts to (Fst r, Snd r). Mirrors the
	// function-η entries above (the single Thompson-sensitive Σ edit).
	if _, ok := a.(VPair); ok {
		return m.convProj(lvl, a, b)
	}
	if _, ok := b.(VPair); ok {
		return m.convProj(lvl, a, b)
	}
	// η for inner paths: a CONSTANT path abstraction equals reflexivity —
	// `pabs A f ≡ preflF A x` when `f` is constantly `x`. Compares the carrier and
	// the abstraction body at a fresh interval point against the refl point. This
	// is the narrow case the J-via-comp rule (A4) needs (its line lands `pabs A
	// (λ_. x)` at i0 against `d : P x (preflF A x)`); it relates only the pabs and
	// preflF path-builtin heads, so nothing else is affected.
	if r, ok := m.convPathEta(lvl, a, b); ok {
		return r
	}
	// η for TYPE-level paths (pathU): a path of fibrant codes is determined by its
	// action `λi. pappU p i`. The pathU analogue of convPathEta — what the pathU
	// induction principle (pathUJ) needs at both ends of its transport line (i0:
	// constant `pabsU (λ_. A) ≡ ureflU A`; i1: general `pabsU (λj. pappU p j) ≡ p`).
	if r, ok := m.convPathUEta(lvl, a, b); ok {
		return r
	}
	// Guarded fixpoint unfolding (C5b): `dfix A f ≡ f (next A (dfix A f))`, a
	// single bounded step — the inner dfix that reappears is matched by spine
	// comparison, never re-unfolded, so this terminates.
	if r, ok := m.convDfix(lvl, a, b); ok {
		return r
	}
	// Guarded-recursive TYPE unfolding (C5b/clocks): `gfix k F ≡ F (gfix k F)`, a
	// single bounded step with a progress guard (it only proceeds when the operator F
	// changes the head, so an unguarded F cannot loop the checker).
	if r, ok := m.convGfix(lvl, a, b); ok {
		return r
	}
	// Indexed guarded-recursive TYPE unfolding (the Bisim former): `gfixF k D Φ d ≡
	// Φ (gfixF k D Φ) d`, a single bounded step with a progress guard.
	if r, ok := m.convGfixF(lvl, a, b); ok {
		return r
	}
	// η for the INNER Σ (sigmaF): the builtin pair `pairF A B a b` is a neutral
	// (GRolePair head), not a VPair, so the function/VPair η above does not see it.
	// When one side is a saturated pairF, compare both sides' fstF/sndF projections
	// (which compute on a pairF and stay neutral on a variable) — definitional η,
	// mirroring convProj for outer pairs. Needed to build paths in a fibre/Σ whose
	// endpoint is an abstract element w (w ≡ (w.1, w.2)).
	if r, ok := m.convSigmaEta(lvl, a, b); ok {
		return r
	}
	// η for the coinductive constructor (nuCons): a value built by `nuCons F y` is
	// determined by its observation — `nuCons F y ≡ t  ⟺  y ≡ out F t`. When exactly
	// one side is a saturated `nuCons F y`, compare `y` against `out F (other)`. This
	// is the coinductive extensionality (the dual of convSigmaEta for the final
	// coalgebra's constructor); it subsumes the eval η `nuCons F (out F s) ~> s` and
	// also bridges the inner-Σ η, so `consStr (head s)(tail s) = nuCons (pairF (fst
	// (out s))(snd (out s))) ≡ s` holds (the cons-η the E2 converse needs). Bounded:
	// a single unfold to `out F other`, then ordinary structural comparison.
	if r, ok := m.convNuConsEta(lvl, a, b); ok {
		return r
	}
	// Glue ⊤-boundary at the TYPE level: a fibrant code `Glue A ⊤ T e` IS its
	// welded fibre `T htop` on a total face. The evaluator only fires this boundary
	// under `El` (`El (Glue A ⊤ T e) ~> El (T htop)`), leaving the bare UF-level
	// `Glue` rigid so the Kan-over-Glue arms can still read its components at a line's
	// endpoints. But a `pathU`/UF comparison sees the bare code, so the boundary is
	// supplied here as a CONVERSION: when one side is a saturated `Glue` whose face is
	// ⊤, compare `T htop` against the other side. This is what lets a derived
	// univalence line `pabsU (λi. Glue B ((i=0)∨(i=1)) …)` carry the type `pathU A B`
	// (its endpoints reduce to A / B). Conversion-only, no hash impact, no eval change.
	if r, ok := m.convGlueTop(lvl, a, b); ok {
		return r
	}

	switch __gp_m0 := any(a).(type) {
	case VU:
		alvl := __gp_m0.Lvl
		if y, ok := b.(VU); ok {
			return alvl == y.Lvl
		}
	case VProp:
		if _, ok := b.(VProp); ok {
			return true
		}
	case VEq:
		ty := __gp_m0.Ty
		l := __gp_m0.L
		r := __gp_m0.R
		if y, ok := b.(VEq); ok {
			return m.Conv(lvl, ty, y.Ty) && m.Conv(lvl, l, y.L) && m.Conv(lvl, r, y.R)
		}
	case VRefl:
		// Proof irrelevance at the canonical level: any two refl proofs are
		// definitionally equal regardless of payload.
		if _, ok := b.(VRefl); ok {
			return true
		}
	case VPi:
		icit := __gp_m0.Icit
		qty := __gp_m0.Qty
		dom := __gp_m0.Dom
		cod := __gp_m0.Cod
		if y, ok := b.(VPi); ok {
			if icit != y.Icit || qty != y.Qty {
				return false
			}
			v := VVar(lvl)
			return m.Conv(lvl, dom, y.Dom) && m.Conv(lvl+1, cod(v), y.Cod(v))
		}
	case VSig:
		qty := __gp_m0.Qty
		dom := __gp_m0.Dom
		cod := __gp_m0.Cod
		if y, ok := b.(VSig); ok {
			if qty != y.Qty {
				return false
			}
			v := VVar(lvl)
			return m.Conv(lvl, dom, y.Dom) && m.Conv(lvl+1, cod(v), y.Cod(v))
		}
	case VNeu:
		spine := __gp_m0.Spine
		if y, ok := b.(VNeu); ok && m.convSpine(lvl, spine, y.Spine) {
			return true // fast path: spines agree syntactically, nothing forced
		}
	default:
	}

	// Mismatch: δ-unfold whichever sides can, and retry. If neither can, the
	// values are genuinely different.
	af, aok := m.force1(a)
	bf, bok := m.force1(b)
	if !aok && !bok {
		return false
	}
	return m.Conv(lvl, af, bf)
}

func (m *Machine) convApplied(lvl int, a, b Val) bool {
	v := VVar(lvl)
	return m.Conv(lvl+1, m.Apply(a, v), m.Apply(b, v))
}

// convPathEta is the η-law for inner paths: a path is determined by its action
// `λi. p@i`. When exactly one side forces to a path abstraction `pabs A f`, it
// compares `f@fresh` with `(other)@fresh` (built with the papp eliminator, which
// computes when the other side is itself a pabs/preflF and stays neutral on a
// path variable). Returns (_, false) when neither side is a lone pabs so the
// caller falls through. Sound: this is the standard path η (paths are functions
// out of the interval); pabs-vs-pabs is left to spine comparison, and a pabs vs a
// path value of the same type is equal iff they agree pointwise.
//
// This is what the J-via-comp rule (A4) needs at BOTH ends of its line: at i0 the
// inner path is `pabs A (λ_. x)` against `d : P x (preflF A x)` (constant η,
// `other = preflF`), and at i1 it is `pabs A (λj. p@j)` against the result type
// `P y p` (general η, `other = p`).
func (m *Machine) convPathEta(lvl int, a, b Val) (bool, bool) {
	if m.Path == nil || m.Fibrant == nil {
		return false, false
	}
	abs := func(v Val) ([]Val, bool) {
		n, ok := v.(VNeu)
		if !ok {
			return nil, false
		}
		head, as := spineParts(n.Spine)
		ref, ok := head.(NRef)
		if !ok || m.Path.PathRoleOf(ref.Hash) != PRoleAbs || len(as) != 2 {
			return nil, false
		}
		return as, true
	}
	aArgs, aAbs := abs(a)
	bArgs, bAbs := abs(b)
	if aAbs == bAbs {
		return false, false // neither, or both (both → spine comparison handles it)
	}
	absArgs, other := aArgs, b
	if bAbs {
		absArgs, other = bArgs, a
	}
	pappH, ok1 := m.Path.PathHash(PRoleApp)
	i0h, ok2 := m.Interval.IntervalHash(IRoleI0)
	i1h, ok3 := m.Interval.IntervalHash(IRoleI1)
	if !ok1 || !ok2 || !ok3 {
		return false, false
	}
	// absArgs = [A, f]; endpoints x = f i0, y = f i1.
	A, f := absArgs[0], absArgs[1]
	x := m.Apply(f, m.refVal(i0h))
	y := m.Apply(f, m.refVal(i1h))
	v := VVar(lvl)
	// papp A x y other v : the other path applied at the fresh point.
	otherAt := m.Apply(m.Apply(m.Apply(m.Apply(m.Apply(m.refVal(pappH), A), x), y), other), v)
	return m.Conv(lvl+1, m.Apply(f, v), otherAt), true
}

// convPathUEta is the η-law for TYPE-level paths (pathU): a path of fibrant codes
// is determined by its action `λi. pappU p i`. When exactly one side forces to a
// `pabsU line`, it compares `line@fresh` with `pappU A B other @fresh` (pappU
// computes when `other` is itself a pabsU/ureflU and stays neutral on a pathU
// variable). The pathU analogue of convPathEta — sound because pathU is DATA, not
// Prop, so ordinary path η applies. This is what pathUJ (path induction over a
// ua-path) needs at both ends of its transport line: at i0 the contracting line is
// `pabsU (λ_. A)` against `d : El (P A (ureflU A))` (constant η, other = ureflU A),
// and at i1 it is `pabsU (λj. pappU p j)` against the result `El (P B p)` (general η,
// other = p).
func (m *Machine) convPathUEta(lvl int, a, b Val) (bool, bool) {
	if m.PabsU == nil || m.PappU == nil || m.Interval == nil {
		return false, false
	}
	absU := func(v Val) (Val, bool) {
		n, ok := v.(VNeu)
		if !ok {
			return nil, false
		}
		head, as := spineParts(n.Spine)
		ref, ok := head.(NRef)
		if !ok || m.PabsU.PabsURoleOf(ref.Hash) != PURolePabsU || len(as) != 1 {
			return nil, false
		}
		return as[0], true
	}
	aLine, aAbs := absU(a)
	bLine, bAbs := absU(b)
	if aAbs == bAbs {
		return false, false // neither, or both (both → spine comparison handles it)
	}
	line, other := aLine, b
	if bAbs {
		line, other = bLine, a
	}
	pappH, ok1 := m.PappU.PappUHash()
	i0h, ok2 := m.Interval.IntervalHash(IRoleI0)
	i1h, ok3 := m.Interval.IntervalHash(IRoleI1)
	if !ok1 || !ok2 || !ok3 {
		return false, false
	}
	// endpoints A = line@i0, B = line@i1.
	A := m.Apply(line, m.refVal(i0h))
	B := m.Apply(line, m.refVal(i1h))
	v := VVar(lvl)
	// pappU A B other v : the other type-path applied at the fresh interval point.
	otherAt := m.Apply(m.Apply(m.Apply(m.Apply(m.refVal(pappH), A), B), other), v)
	return m.Conv(lvl+1, m.Apply(line, v), otherAt), true
}

// convDfix is the guarded-fixpoint unfolding as a BOUNDED conversion (C5b):
// `dfix A f ≡ f (next A (dfix A f))`. When exactly one side forces to a `dfix A f`,
// it is unfolded a SINGLE step and compared with the other side; the inner `dfix`
// that reappears is matched by ordinary spine comparison (both-dfix → this returns
// false → spine compares A and f), so the recursion is bounded and conversion
// terminates. Sound: this is the defining equation of the guarded fixpoint, and
// dfix heads are otherwise distinct neutrals. dfix has NO eval ι-rule (the kernel
// never diverges); its definitional content lives entirely here.
func (m *Machine) convDfix(lvl int, a, b Val) (bool, bool) {
	if m.Guard == nil {
		return false, false
	}
	dfx := func(v Val) ([]Val, bool) {
		n, ok := v.(VNeu)
		if !ok {
			return nil, false
		}
		head, as := spineParts(n.Spine)
		ref, ok := head.(NRef)
		if !ok || m.Guard.GuardRoleOf(ref.Hash) != LRoleDfix || len(as) != 3 {
			return nil, false
		}
		return as, true
	}
	aArgs, aD := dfx(a)
	bArgs, bD := dfx(b)
	if aD == bD {
		return false, false // neither, or both (both → spine comparison handles it)
	}
	args, other := aArgs, b
	if bD {
		args, other = bArgs, a
	}
	nextH, ok1 := m.Guard.GuardHash(LRoleNext)
	dfixH, ok2 := m.Guard.GuardHash(LRoleDfix)
	if !ok1 || !ok2 {
		return false, false
	}
	// args = [k, A, f]; unfold once: f (next k A (dfix k A f)).
	k, A, f := args[0], args[1], args[2]
	dfixAf := m.Apply(m.Apply(m.Apply(m.refVal(dfixH), k), A), f) // rebuilds the rigid dfix neutral
	nextV := m.Apply(m.Apply(m.Apply(m.refVal(nextH), k), A), dfixAf)
	unfolded := m.Apply(f, nextV)
	return m.Conv(lvl, unfolded, other), true
}

// convGfix is the guarded-recursive TYPE fixpoint unfolding as a bounded conversion
// (C5b/clocks): `gfix k F ≡ F (gfix k F)`. When exactly one side forces to a `gfix k F`,
// it is unfolded a single step (apply F to the rigid gfix neutral) and compared with the
// other side. A PROGRESS GUARD keeps it terminating for EVERY operator F: the step is
// taken only when the unfolded result is NOT itself gfix-headed (F made head progress, as
// a guarded operator like `λX. sigmaF A (λ_. Later k X)` does). An unguarded `F = λX. X`
// unfolds back to `gfix k F` — gfix-headed — so the step is refused and the two are equal
// only if syntactically equal (ordinary spine comparison). Sound: this is the defining
// equation of the guarded fixpoint, and gfix heads are otherwise distinct neutrals with
// no eval ι, so the kernel never diverges.
func (m *Machine) convGfix(lvl int, a, b Val) (bool, bool) {
	if m.Guard == nil {
		return false, false
	}
	gfx := func(v Val) ([]Val, bool) {
		n, ok := m.Force(v).(VNeu)
		if !ok {
			return nil, false
		}
		head, as := spineParts(n.Spine)
		ref, ok := head.(NRef)
		if !ok || m.Guard.GuardRoleOf(ref.Hash) != LRoleGfix || len(as) != 2 {
			return nil, false
		}
		return as, true
	}
	aArgs, aG := gfx(a)
	bArgs, bG := gfx(b)
	if aG == bG {
		return false, false // neither, or both (both → spine comparison handles it)
	}
	args, other := aArgs, b
	if bG {
		args, other = bArgs, a
	}
	gfixH, ok := m.Guard.GuardHash(LRoleGfix)
	if !ok {
		return false, false
	}
	// args = [k, F]; unfold once: F (gfix k F).
	k, F := args[0], args[1]
	gfixKF := m.Apply(m.Apply(m.refVal(gfixH), k), F) // rebuilds the rigid gfix neutral
	unfolded := m.Apply(F, gfixKF)
	// PROGRESS GUARD: refuse the step if F made no head progress (the result is still
	// gfix-headed), so an unguarded operator cannot loop the checker.
	if _, stuck := gfx(unfolded); stuck {
		return false, false
	}
	return m.Conv(lvl, unfolded, other), true
}

// convGfixF is the INDEXED guarded-recursive TYPE fixpoint unfolding as a bounded
// conversion (the `Bisim` former): `gfixF k D Φ d ≡ Φ (gfixF k D Φ) d`, where the
// fixpoint may recur at a DIFFERENT index. It fires on an APPLIED gfixF — a `gfixF k D Φ`
// applied to an index `d` (a 4-arg gfixF spine) — unfolding once to `Φ (gfixF k D Φ) d`.
// A PROGRESS GUARD (mirroring convGfix) refuses the step when the result is STILL an
// applied-gfixF (Φ made no head progress, e.g. Φ = λR. R), so the checker cannot loop;
// the recursive occurrence in a guarded Φ sits under `Later`, where both sides carry the
// same applied gfixF and spine comparison terminates the recursion.
func (m *Machine) convGfixF(lvl int, a, b Val) (bool, bool) {
	if m.Guard == nil {
		return false, false
	}
	// gfxF recognises a `gfixF k D Φ d` (an APPLIED indexed fixpoint: 4 args).
	gfxF := func(v Val) ([]Val, bool) {
		n, ok := m.Force(v).(VNeu)
		if !ok {
			return nil, false
		}
		head, as := spineParts(n.Spine)
		ref, ok := head.(NRef)
		if !ok || m.Guard.GuardRoleOf(ref.Hash) != LRoleGfixF || len(as) != 4 {
			return nil, false
		}
		return as, true
	}
	aArgs, aG := gfxF(a)
	bArgs, bG := gfxF(b)
	if aG == bG {
		return false, false // neither, or both (both → spine comparison handles it)
	}
	args, other := aArgs, b
	if bG {
		args, other = bArgs, a
	}
	gfixFH, ok := m.Guard.GuardHash(LRoleGfixF)
	if !ok {
		return false, false
	}
	// args = [k, D, Φ, d]; unfold once: Φ (gfixF k D Φ) d.
	k, D, Phi, d := args[0], args[1], args[2], args[3]
	gfixKDPhi := m.Apply(m.Apply(m.Apply(m.refVal(gfixFH), k), D), Phi) // rigid bare gfixF
	unfolded := m.Apply(m.Apply(Phi, gfixKDPhi), d)
	// PROGRESS GUARD: refuse if Φ made no head progress (result still applied-gfixF).
	if _, stuck := gfxF(unfolded); stuck {
		return false, false
	}
	return m.Conv(lvl, unfolded, other), true
}

// convProj compares two values of a Σ type componentwise via their projections.
// Because m.proj1/proj2 turn a neutral into an NFst/NSnd spine, this gives
// definitional η: a neutral r is equal to a pair (a, b) exactly when Fst r ≡ a
// and Snd r ≡ b.
func (m *Machine) convProj(lvl int, a, b Val) bool {
	return m.Conv(lvl, m.proj1(a), m.proj1(b)) && m.Conv(lvl, m.proj2(a), m.proj2(b))
}

// convSigmaEta is η for the inner Σ (sigmaF): a neutral r equals a pair
// `pairF A B a b` exactly when fstF r ≡ a and sndF r ≡ b. The inner pair is a
// builtin neutral (GRolePair head, 4 args) rather than a VPair, so this mirrors
// the outer-pair η (convProj) for it. Fires when at least one side is a saturated
// pairF; the fstF/sndF spines compute on a pair and stay neutral on a variable, so
// the comparison is the standard negative-Σ η. Returns (_, false) when neither side
// is a pairF, so the caller falls through.
func (m *Machine) convSigmaEta(lvl int, a, b Val) (bool, bool) {
	if m.Sigma == nil {
		return false, false
	}
	pairArgs := func(v Val) ([]Val, bool) {
		n, ok := v.(VNeu)
		if !ok {
			return nil, false
		}
		head, as := spineParts(n.Spine)
		ref, ok := head.(NRef)
		if !ok || m.Sigma.SigmaRoleOf(ref.Hash) != GRolePair || len(as) != 4 {
			return nil, false
		}
		return as, true
	}
	pa, aPair := pairArgs(a)
	pb, bPair := pairArgs(b)
	if !aPair && !bPair {
		return false, false
	}
	args := pa
	if !aPair {
		args = pb
	}
	// args = [A, fam, _, _]; the projections only need the type args A, fam.
	A, fam := args[0], args[1]
	fstH, ok1 := m.Sigma.SigmaHash(GRoleFst)
	sndH, ok2 := m.Sigma.SigmaHash(GRoleSnd)
	if !ok1 || !ok2 {
		return false, false
	}
	proj := func(h Hash, v Val) Val {
		return m.Apply(m.Apply(m.Apply(m.refVal(h), A), fam), v)
	}
	return m.Conv(lvl, proj(fstH, a), proj(fstH, b)) &&
		m.Conv(lvl, proj(sndH, a), proj(sndH, b)), true
}

// convGlueTop applies the Glue ⊤-boundary as a CONVERSION at the UF level: a
// saturated `Glue A φ T e` with φ ≡ ⊤ converts to its welded fibre `T htop`. The
// evaluator deliberately keeps the bare UF-level `Glue` rigid (only `El (Glue …)`
// fires the boundary) so the Kan-over-Glue arms can read a line's components at its
// endpoints; this supplies the missing type-level boundary where conversion needs
// it (e.g. a `pabsU (λi. Glue B ((i=0)∨(i=1)) …)` line whose endpoints must convert
// to A / B for it to inhabit `pathU A B`). Reduces whichever side is a ⊤-faced Glue
// to `T htop` and recurses; returns (_, false) when neither side is, so the caller
// falls through. Sound: on a total face the glued type genuinely is its fibre.
func (m *Machine) convGlueTop(lvl int, a, b Val) (bool, bool) {
	if m.Glue == nil || m.System == nil {
		return false, false
	}
	glueTop := func(v Val) (Val, bool) {
		n, ok := v.(VNeu)
		if !ok {
			return nil, false
		}
		head, as := spineParts(n.Spine)
		ref, ok := head.(NRef)
		if !ok || m.Glue.GlueRoleOf(ref.Hash) != URoleGlue || len(as) != 4 {
			return nil, false
		}
		if c, ok := m.faceConst(as[1]); !ok || c != CRoleTop {
			return nil, false
		}
		hth, ok := m.System.SysHash(SRoleTop)
		if !ok {
			return nil, false
		}
		return m.Apply(as[2], m.refVal(hth)), true // T htop
	}
	if r, ok := glueTop(a); ok {
		return m.Conv(lvl, r, b), true
	}
	if r, ok := glueTop(b); ok {
		return m.Conv(lvl, a, r), true
	}
	return false, false
}

// convSpine compares two neutral spines structurally. Heads must agree (same
// variable level, same definition hash); arguments are compared with full Conv,
// which may itself force inside an argument.
func (m *Machine) convSpine(lvl int, p, q Neutral) bool {
	switch __gp_m1 := any(p).(type) {
	case NVar:
		plvl := __gp_m1.Lvl
		y, ok := q.(NVar)
		return ok && plvl == y.Lvl
	case NRef:
		ph := __gp_m1.Hash
		y, ok := q.(NRef)
		return ok && ph == y.Hash
	case NMeta:
		id := __gp_m1.ID
		// Core conversion treats an unsolved meta as rigid: equal only to
		// itself. Solving-by-unification is elaborate/'s job, not conversion's.
		y, ok := q.(NMeta)
		return ok && id == y.ID
	case NCast:
		a := __gp_m1.A
		cb := __gp_m1.B
		x := __gp_m1.X
		// Casts compare on endpoints and subject; the PROOF is skipped —
		// definitional proof irrelevance at the cast site.
		y, ok := q.(NCast)
		return ok && m.Conv(lvl, a, y.A) && m.Conv(lvl, cb, y.B) && m.Conv(lvl, x, y.X)
	case NSubst:
		a := __gp_m1.A
		x := __gp_m1.X
		sy := __gp_m1.Y
		sp := __gp_m1.P
		px := __gp_m1.Px
		// Likewise: everything but the proof.
		y, ok := q.(NSubst)
		return ok && m.Conv(lvl, a, y.A) && m.Conv(lvl, x, y.X) &&
			m.Conv(lvl, sy, y.Y) && m.Conv(lvl, sp, y.P) && m.Conv(lvl, px, y.Px)
	case NApp:
		fn := __gp_m1.Fn
		arg := __gp_m1.Arg
		icit := __gp_m1.Icit
		y, ok := q.(NApp)
		return ok && icit == y.Icit && m.convSpine(lvl, fn, y.Fn) && m.Conv(lvl, arg, y.Arg)
	case NFst:
		sub := __gp_m1.P
		y, ok := q.(NFst)
		return ok && m.convSpine(lvl, sub, y.P)
	case NSnd:
		sub := __gp_m1.P
		y, ok := q.(NSnd)
		return ok && m.convSpine(lvl, sub, y.P)
	case NNatLit:
		n := __gp_m1.N
		zero := __gp_m1.Zero
		succ := __gp_m1.Succ
		// Two compressed numerals are equal iff they denote the same number of
		// the SAME nat binding — an O(1) big.Int compare, the fast path that
		// avoids peeling either chain. A literal vs a hand-written succ-chain is
		// NOT handled here (the spines differ): the main Conv loop forces (peels)
		// the literal one layer and retries, so the two inter-convert.
		y, ok := q.(NNatLit)
		return ok && zero == y.Zero && succ == y.Succ && n.Cmp(y.N) == 0
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Sub reports a <: b — definitional conversion extended with cumulativity:
// Prop <: U, and function types are covariant in their codomain (domains stay
// invariant, which is sound and keeps the relation decidable without
// antisymmetry games). Used where a Prop-valued thing is supplied at a
// U-valued expectation (e.g. Prop-valued eliminator motives).
func (m *Machine) Sub(lvl int, a, b Val) bool {
	if m.Conv(lvl, a, b) {
		return true
	}
	af, bf := m.Force(a), m.Force(b)
	if _, ok := af.(VProp); ok {
		if _, ok2 := bf.(VU); ok2 {
			return true
		}
	}
	if ua, ok := af.(VU); ok {
		if ub, ok2 := bf.(VU); ok2 && ua.Lvl <= ub.Lvl {
			return true // cumulativity
		}
	}
	pa, ok1 := af.(VPi)
	pb, ok2 := bf.(VPi)
	if ok1 && ok2 && pa.Icit == pb.Icit && pa.Qty == pb.Qty && m.Conv(lvl, pa.Dom, pb.Dom) {
		v := VVar(lvl)
		return m.Sub(lvl+1, pa.Cod(v), pb.Cod(v))
	}
	return false
}

// convNuConsEta is the η-law for the coinductive constructor `nuCons` (R-COIND):
// a value built by `nuCons F y` is determined by its single observation, so
// `nuCons F y ≡ t  ⟺  y ≡ out F t`. When exactly one side forces to a saturated
// `nuCons F y` (a NRoleNuCons-headed neutral with two args), it compares `y`
// against `out F (other)`. Sound: this is coinductive extensionality (the dual of
// convSigmaEta for the final coalgebra), and on a `nuCons F (out F s)` it recovers
// the eval η `~> s`. Bounded: a single `out` application, then ordinary structural
// comparison (which on a `pairF` argument fires convSigmaEta, bridging the inner-Σ
// η that makes `consStr (head s)(tail s) ≡ s`). nuCons-vs-nuCons is left to spine
// comparison (both saturated → handled by the VNeu fast path / structural descent).
func (m *Machine) convNuConsEta(lvl int, a, b Val) (bool, bool) {
	if m.Coind == nil {
		return false, false
	}
	consArgs := func(v Val) ([]Val, bool) {
		n, ok := v.(VNeu)
		if !ok {
			return nil, false
		}
		head, as := spineParts(n.Spine)
		ref, ok := head.(NRef)
		if !ok || m.Coind.CoindRoleOf(ref.Hash) != NRoleNuCons || len(as) != 2 {
			return nil, false
		}
		return as, true
	}
	ca, aCons := consArgs(a)
	cb, bCons := consArgs(b)
	if aCons == bCons {
		return false, false // neither, or both (both → spine comparison handles it)
	}
	consA, other := ca, b
	if bCons {
		consA, other = cb, a
	}
	outH, ok := m.Coind.CoindHash(NRoleOut)
	if !ok {
		return false, false
	}
	// consA = [F, y]; compare y against out F other.
	F, y := consA[0], consA[1]
	outOther := m.Apply(m.Apply(m.refVal(outH), F), other)
	return m.Conv(lvl, y, outOther), true
}
