// Code generated by gpp from nbe_test.gpp. DO NOT EDIT.
//gpp:v v0.14.0

package core

import "testing"

// The NbE white-box tests, authored in G++ (v3.383.0): term constructions use
// enum constructor calls — every argument explicit, no zero-value elisions.

// fakeGlobals is a minimal Globals for NbE tests: a map of definitions.
type fakeGlobals struct {
	types  map[Hash]Tm
	bodies map[Hash]Tm
}

func (g fakeGlobals) TypeOf(h Hash) (Tm, bool) { t, ok := g.types[h]; return t, ok }
func (g fakeGlobals) Unfold(h Hash) (Tm, bool) { b, ok := g.bodies[h]; return b, ok }

func emptyGlobals() fakeGlobals {
	return fakeGlobals{types: map[Hash]Tm{}, bodies: map[Hash]Tm{}}
}

// lam is shorthand for a one-binder explicit unrestricted lambda.
func lam(body Tm) Tm { return Lam{Icit: Expl, Qty: QMany, Body: Scope{Name: "x", Body: body}} }

func TestNormalizeBeta(t *testing.T) {
	m := NewMachine(emptyGlobals())
	// (λx. x) U  ~>  U
	tm := App{Fn: lam(Var{Idx: 0}), Arg: Univ{Lvl: 0}, Icit: Expl}
	if got := m.Normalize(tm); got != (Univ{}) {
		t.Fatalf("got %#v, want Univ", got)
	}
}

func TestNormalizeUnderBinder(t *testing.T) {
	m := NewMachine(emptyGlobals())
	// λy. (λx. x) y  ~>  λy. y
	tm := lam(App{Fn: lam(Var{Idx: 0}), Arg: Var{Idx: 0}, Icit: Expl})
	want := lam(Var{Idx: 0})
	if got := m.Normalize(tm); HashTerm(got) != HashTerm(want) {
		t.Fatalf("got %#v, want λ.0", got)
	}
}

func TestNormalizeLetIsTransparent(t *testing.T) {
	m := NewMachine(emptyGlobals())
	// let x = U in x  ~>  U
	tm := Let{Ty: nil, Val: Univ{Lvl: 0}, Body: Scope{Name: "x", Body: Var{Idx: 0}}}
	if got := m.Normalize(tm); got != (Univ{}) {
		t.Fatalf("got %#v, want Univ", got)
	}
}

func TestQuoteKeepsRefsFolded(t *testing.T) {
	g := emptyGlobals()
	var h Hash
	h[0] = 7
	g.bodies[h] = Univ{Lvl: 0}
	g.types[h] = Univ{Lvl: 0}
	m := NewMachine(g)
	// A bare reference normalizes (without δ) to itself, and the dependency log
	// stays empty: nothing was forced.
	if got := m.Normalize(Ref{Hash: h}); got != (Ref{Hash: h}) {
		t.Fatalf("got %#v, want Ref", got)
	}
	if len(m.Deps) != 0 {
		t.Fatalf("fast path logged deps: %v", m.DepList())
	}
	// The δ-normalizing variant unfolds it — and logs it.
	if got := m.NormalizeUnfold(Ref{Hash: h}); got != (Univ{}) {
		t.Fatalf("unfold: got %#v, want Univ", got)
	}
	if _, ok := m.Deps[h]; !ok || len(m.Deps) != 1 {
		t.Fatalf("unfold did not log exactly the forced ref: %v", m.DepList())
	}
}

func TestConvRefl(t *testing.T) {
	m := NewMachine(emptyGlobals())
	tm := Pi{Icit: Expl, Qty: QMany, Dom: Univ{Lvl: 0}, Cod: Scope{Name: "A", Body: Pi{Icit: Expl, Qty: QMany, Dom: Var{Idx: 0}, Cod: Scope{Name: "_", Body: Var{Idx: 1}}}}}
	a := m.Eval(nil, tm)
	b := m.Eval(nil, tm)
	if !m.Conv(0, a, b) {
		t.Fatal("conversion not reflexive on (A : U) -> A -> A")
	}
}

func TestConvEta(t *testing.T) {
	m := NewMachine(emptyGlobals())
	// Under a binder f : A -> A, conv must equate f and λx. f x.
	f := VVar(0)
	etaExpanded := VLam{Name: "x", Icit: Expl, Qty: QMany, Body: func(v Val) Val { return m.Apply(f, v) }}
	if !m.Conv(1, f, etaExpanded) {
		t.Fatal("η: f ≢ λx. f x")
	}
}

func TestConvDeltaFastAndSlowPaths(t *testing.T) {
	g := emptyGlobals()
	var h1, h2 Hash
	h1[0], h2[0] = 1, 2
	// Two definitions with literally different hashes but the same body U.
	g.bodies[h1], g.bodies[h2] = Univ{Lvl: 0}, Univ{Lvl: 0}
	g.types[h1], g.types[h2] = Univ{Lvl: 0}, Univ{Lvl: 0}

	// Fast path: same ref converts with NO unfolding logged.
	m := NewMachine(g)
	if !m.Conv(0, m.Eval(nil, Ref{Hash: h1}), m.Eval(nil, Ref{Hash: h1})) {
		t.Fatal("same ref not convertible")
	}
	if len(m.Deps) != 0 {
		t.Fatalf("fast path logged deps: %v", m.DepList())
	}

	// Slow path: different refs with equal bodies convert only by forcing, and
	// both unfoldings are logged.
	m2 := NewMachine(g)
	if !m2.Conv(0, m2.Eval(nil, Ref{Hash: h1}), m2.Eval(nil, Ref{Hash: h2})) {
		t.Fatal("definitionally equal refs not convertible")
	}
	if len(m2.Deps) != 2 {
		t.Fatalf("slow path should log both unfolds, got %v", m2.DepList())
	}
}

func TestConvDistinguishes(t *testing.T) {
	m := NewMachine(emptyGlobals())
	a := m.Eval(nil, Pi{Icit: Expl, Qty: QMany, Dom: Univ{Lvl: 0}, Cod: Scope{Body: Var{Idx: 0}}})
	b := m.Eval(nil, Pi{Icit: Expl, Qty: QMany, Dom: Univ{Lvl: 0}, Cod: Scope{Body: Univ{Lvl: 0}}})
	if m.Conv(0, a, b) {
		t.Fatal("(A : U) -> A and U -> U should not convert")
	}
}

func TestNormalizeIdempotent(t *testing.T) {
	m := NewMachine(emptyGlobals())
	tm := App{Fn: lam(lam(App{Fn: Var{Idx: 1}, Arg: Var{Idx: 0}, Icit: Expl})), Arg: lam(Var{Idx: 0}), Icit: Expl}
	nf1 := m.Normalize(tm)
	nf2 := m.Normalize(nf1)
	if HashTerm(nf1) != HashTerm(nf2) {
		t.Fatalf("normalize not idempotent: %#v vs %#v", nf1, nf2)
	}
}

// TestDerivedTraversalsOnTm pins the gpp-derived deep structure on the term
// enum itself: Universe walks through Scope, Transform rewrites bottom-up, and
// EqualWith's override makes a chosen field irrelevant (the same shape conv
// uses for proof irrelevance at casts).
func TestDerivedTraversalsOnTm(t *testing.T) {
	// (λx. x) ((λx. x) U)
	tm := App{Fn: lam(Var{Idx: 0}), Arg: App{Fn: lam(Var{Idx: 0}), Arg: Univ{Lvl: 0}, Icit: Expl}, Icit: Expl}
	nodes := 0
	for range TmUniverse(tm) {
		nodes++
	}
	if nodes != 7 {
		t.Fatalf("universe size: got %d, want 7", nodes)
	}
	// Rewrite every Univ 0 to Univ 9, bottom-up, through the Scopes.
	bumped := TmTransform(tm, func(u Tm) Tm {
		switch __gpp_m0 := any(u).(type) {
		case Univ:
			lvl := __gpp_m0.Lvl
			return Univ{Lvl: lvl + 9}
		default:
			return u
		}
	})
	seen := 0
	for u := range TmUniverse(bumped) {
		switch __gpp_m1 := any(u).(type) {
		case Univ:
			lvl := __gpp_m1.Lvl
			if lvl != 9 {
				t.Fatalf("transform missed a Univ: %d", lvl)
			}
			seen++
		default:
		}
	}
	if seen != 1 {
		t.Fatalf("universe found %d Univ nodes, want 1", seen)
	}
	// Structural equality, then annotation-irrelevant equality via override.
	a := Ann{Term: Var{Idx: 0}, Ty: Univ{Lvl: 0}}
	b := Ann{Term: Var{Idx: 0}, Ty: Univ{Lvl: 1}}
	if TmEqual(a, b) {
		t.Fatal("annotations differ; derived equality must see it")
	}
	tyIrrelevant := TmEqOverrides{
		Ann: func(x, y Ann) (bool, bool) {
			return TmEqual(x.Term, y.Term), true
		},
	}
	if !TmEqualWith(a, b, tyIrrelevant) {
		t.Fatal("override must make the annotation irrelevant")
	}
}
