// Code generated by goplus from val.gp. DO NOT EDIT.
//goplus:v v0.15.0

package core

import "iter"

import "math/big"

// Val is the glued NbE value domain.
//
// "Glued" (after smalltt): a neutral value carries both its un-unfolded spine
// AND a lazy unfolding. Conversion takes a fast syntactic path over spines and
// forces the lazy unfolding only on mismatch, so errors print near the source
// the user wrote.
//
// The coincidence that earns its keep (see ref_docs/rune-proof-cache-semantics.md):
// forcing a neutral's lazy unfolding is the SAME operation as store.Unfold. The
// proof-cache dependency log hooks exactly there — the fast path compares spines
// and logs nothing; forcing logs the unfolded definition's hash. The
// instrumentation rides on the machinery built for speed. This is on purpose;
// keep them coincident.
//
// Val is a goplus enum whose variants carry Go closures (VPi.Cod, VLam.Body,
// VNeu.Unfold) — closures have no structure, so Val derives NO structural
// equality (conversion is semantic and stays hand-written in conv.go) and its
// derived traversals cover only the closure-free spine.
//
//goplus:enum Val
type Val interface{ isVal() }

// VNeu is a neutral value: a variable or definition reference stuck under
// eliminators it cannot yet reduce.
//
// Spine is the un-unfolded neutral (the fast-path representative). Unfold
// is the lazy unfolding: forcing it is store.Unfold and is where the
// proof-cache dependency is logged.
//
//goplus:variant (Val) VNeu(spine Neutral, unfold func() Val)
type VNeu struct {
	Spine  Neutral
	Unfold func() Val
}

func (VNeu) isVal() {}

// VU is a universe as a value, at its level.
//
//goplus:variant (Val) VU(lvl int)
type VU struct {
	Lvl int
}

func (VU) isVal() {}

// VProp is the universe of propositions as a value (Phase 3).
//
//goplus:variant (Val) VProp
type VProp struct{}

func (VProp) isVal() {}

// VEq is a STUCK observational equality type: the stratum's EvalEq could
// not reduce it further (Ty is not a function type, and not enough
// structure is known). Values of a VEq type are proofs and are
// definitionally irrelevant.
//
//goplus:variant (Val) VEq(ty Val, l Val, r Val)
type VEq struct {
	Ty Val
	L  Val
	R  Val
}

func (VEq) isVal() {}

// VRefl is the reflexivity proof as a value. Its payload is carried for
// quotation only; conversion never inspects it (proof irrelevance).
//
//goplus:variant (Val) VRefl(v Val)
type VRefl struct {
	V Val
}

func (VRefl) isVal() {}

// VPi is a dependent function type value (x : Dom) -> Cod. Cod is a Go
// closure: the NbE meaning function. Name is a pretty-printing hint for
// the binder, like Scope.Name — never part of identity, never hashed
// (quote drops it into a Scope).
//
// NonDep, when true, records that Cod IGNORES its argument: the codomain
// term never mentions the binder (set by Eval, the strict-language
// stand-in for a lazy argument thunk). Callers that need only the result
// type of an application may then skip evaluating the argument — without
// this, checking an n-deep application chain evaluates each argument
// subterm from scratch at every node, O(n²) in the chain depth. False is
// always safe; it is never part of identity (quote and conversion ignore
// it).
//
//goplus:variant (Val) VPi(name string, icit Icit, qty Qty, nonDep bool, dom Val, cod func(Val) Val)
type VPi struct {
	Name   string
	Icit   Icit
	Qty    Qty
	NonDep bool
	Dom    Val
	Cod    func(Val) Val
}

func (VPi) isVal() {}

// VLam is a lambda value, carrying its meaning as a Go closure. Name is a
// display hint only, like VPi.Name.
//
//goplus:variant (Val) VLam(name string, icit Icit, qty Qty, body func(Val) Val)
type VLam struct {
	Name string
	Icit Icit
	Qty  Qty
	Body func(Val) Val
}

func (VLam) isVal() {}

// VSig is a dependent pair type value Σ (x : Dom), Cod. Cod is a Go
// closure (the NbE meaning function), like VPi.Cod. Name is a display
// hint only.
//
//goplus:variant (Val) VSig(name string, qty Qty, dom Val, cod func(Val) Val)
type VSig struct {
	Name string
	Qty  Qty
	Dom  Val
	Cod  func(Val) Val
}

func (VSig) isVal() {}

// VPair is a pair value (A, B) at type Σ Dom Cod. Dom/Cod are carried for
// quotation (so the type is recoverable); conversion ignores them and
// compares A, B componentwise (with η).
//
//goplus:variant (Val) VPair(name string, dom Val, cod func(Val) Val, a Val, b Val)
type VPair struct {
	Name string
	Dom  Val
	Cod  func(Val) Val
	A    Val
	B    Val
}

func (VPair) isVal() {}

// ValCases selects one handler per Val variant for ValFold.
type ValCases[R any] struct {
	VNeu  func(spine Neutral, unfold func() Val) R
	VU    func(lvl int) R
	VProp func() R
	VEq   func(ty Val, l Val, r Val) R
	VRefl func(v Val) R
	VPi   func(name string, icit Icit, qty Qty, nonDep bool, dom Val, cod func(Val) Val) R
	VLam  func(name string, icit Icit, qty Qty, body func(Val) Val) R
	VSig  func(name string, qty Qty, dom Val, cod func(Val) Val) R
	VPair func(name string, dom Val, cod func(Val) Val, a Val, b Val) R
}

// ValFold reduces Val by one-level case analysis.
func ValFold[R any](v Val, cs ValCases[R]) R {
	switch m := any(v).(type) {
	case VNeu:
		return cs.VNeu(m.Spine, m.Unfold)
	case VU:
		return cs.VU(m.Lvl)
	case VProp:
		return cs.VProp()
	case VEq:
		return cs.VEq(m.Ty, m.L, m.R)
	case VRefl:
		return cs.VRefl(m.V)
	case VPi:
		return cs.VPi(m.Name, m.Icit, m.Qty, m.NonDep, m.Dom, m.Cod)
	case VLam:
		return cs.VLam(m.Name, m.Icit, m.Qty, m.Body)
	case VSig:
		return cs.VSig(m.Name, m.Qty, m.Dom, m.Cod)
	case VPair:
		return cs.VPair(m.Name, m.Dom, m.Cod, m.A, m.B)
	default:
		panic("goplus: impossible enum value in ValFold")
	}
}

// ValChildren lists the direct Val subterms of v.
func ValChildren(v Val) []Val {
	var out []Val
	switch m := any(v).(type) {
	case VEq:
		if m.Ty != nil {
			out = append(out, m.Ty)
		}
		if m.L != nil {
			out = append(out, m.L)
		}
		if m.R != nil {
			out = append(out, m.R)
		}
	case VRefl:
		if m.V != nil {
			out = append(out, m.V)
		}
	case VPi:
		if m.Dom != nil {
			out = append(out, m.Dom)
		}
	case VSig:
		if m.Dom != nil {
			out = append(out, m.Dom)
		}
	case VPair:
		if m.Dom != nil {
			out = append(out, m.Dom)
		}
		if m.A != nil {
			out = append(out, m.A)
		}
		if m.B != nil {
			out = append(out, m.B)
		}
	}
	return out
}

// ValUniverse yields v and all transitive Val subterms, preorder.
func ValUniverse(v Val) iter.Seq[Val] {
	return func(yield func(Val) bool) {
		var walk func(Val) bool
		walk = func(cur Val) bool {
			if !yield(cur) {
				return false
			}
			for _, c := range ValChildren(cur) {
				if !walk(c) {
					return false
				}
			}
			return true
		}
		walk(v)
	}
}

// ValTransform rewrites v bottom-up: children first, then f at each node.
func ValTransform(v Val, f func(Val) Val) Val {
	switch m := any(v).(type) {
	case VEq:
		if m.Ty != nil {
			m.Ty = ValTransform(m.Ty, f)
		}
		if m.L != nil {
			m.L = ValTransform(m.L, f)
		}
		if m.R != nil {
			m.R = ValTransform(m.R, f)
		}
		return f(m)
	case VRefl:
		if m.V != nil {
			m.V = ValTransform(m.V, f)
		}
		return f(m)
	case VPi:
		if m.Dom != nil {
			m.Dom = ValTransform(m.Dom, f)
		}
		return f(m)
	case VSig:
		if m.Dom != nil {
			m.Dom = ValTransform(m.Dom, f)
		}
		return f(m)
	case VPair:
		if m.Dom != nil {
			m.Dom = ValTransform(m.Dom, f)
		}
		if m.A != nil {
			m.A = ValTransform(m.A, f)
		}
		if m.B != nil {
			m.B = ValTransform(m.B, f)
		}
		return f(m)
	}
	return f(v)
}

// Neutral is the un-unfolded spine of a stuck computation: a head (a free
// variable at a de Bruijn level, or a definition reference) under a stack of
// eliminators. Like Val it carries values (and, via VNeu, closures), so it
// derives no structural equality; conv.go's convSpine is the semantic
// comparison.
//
//goplus:enum Neutral
type Neutral interface{ isNeutral() }

// NVar is a free variable, identified by de Bruijn LEVEL (not index) so
// the head is stable as the value is reused under deeper binders.
//
//goplus:variant (Neutral) NVar(lvl int)
type NVar struct {
	Lvl int
}

func (NVar) isNeutral() {}

// NRef is a stuck reference to a top-level definition (one whose body has
// not been unfolded on the fast path).
//
//goplus:variant (Neutral) NRef(hash Hash)
type NRef struct {
	Hash Hash
}

func (NRef) isNeutral() {}

// NApp is a neutral applied to an argument value at the given plicity.
//
//goplus:variant (Neutral) NApp(fn Neutral, arg Val, icit Icit)
type NApp struct {
	Fn   Neutral
	Arg  Val
	Icit Icit
}

func (NApp) isNeutral() {}

// NMeta is a stuck metavariable head (Phase 2, elaboration-internal). A
// neutral headed by an NMeta is FLEXIBLE: solving the meta can wake it.
// The Machine's Metas solver is consulted when forcing.
//
//goplus:variant (Neutral) NMeta(ID int)
type NMeta struct {
	ID int
}

func (NMeta) isNeutral() {}

// NCast is a stuck cast: transport along an equality whose endpoint types
// are not yet concrete enough to reduce. P is carried for quotation only —
// conversion compares A, B, and X and SKIPS P (proof irrelevance).
//
//goplus:variant (Neutral) NCast(a Val, b Val, p Val, x Val)
type NCast struct {
	A Val
	B Val
	P Val
	X Val
}

func (NCast) isNeutral() {}

// NSubst is a stuck Leibniz transport: its equality's endpoints are not
// yet convertible. Prf is carried for quotation only; conversion skips it.
//
//goplus:variant (Neutral) NSubst(a Val, x Val, y Val, prf Val, p Val, px Val)
type NSubst struct {
	A   Val
	X   Val
	Y   Val
	Prf Val
	P   Val
	Px  Val
}

func (NSubst) isNeutral() {}

// NFst is a stuck first projection p.1 on a neutral pair p.
//
//goplus:variant (Neutral) NFst(p Neutral)
type NFst struct {
	P Neutral
}

func (NFst) isNeutral() {}

// NSnd is a stuck second projection p.2 on a neutral pair p.
//
//goplus:variant (Neutral) NSnd(p Neutral)
type NSnd struct {
	P Neutral
}

func (NSnd) isNeutral() {}

// NNatLit is the spine head of a compressed numeral value (C7 / R-NUM). A
// VNatLit is represented as a GLUED neutral: this spine is the fast-path
// representative (two literals compare by big.Int.Cmp without forcing),
// and the neutral's Unfold thunk peels ONE succ layer — `zero` when N=0,
// else `succ (NatLit (N-1))` — so the literal inter-converts with the
// unary succ-chain on demand (defeq preserved) and any eliminator forcing
// the scrutinee fires its ordinary constructor ι-rule. Zero/Succ are
// carried so the peel can build the session's nat constructors.
//
//goplus:variant (Neutral) NNatLit(n *big.Int, zero Hash, succ Hash)
type NNatLit struct {
	N    *big.Int
	Zero Hash
	Succ Hash
}

func (NNatLit) isNeutral() {}

// NeutralCases selects one handler per Neutral variant for NeutralFold.
type NeutralCases[R any] struct {
	NVar    func(lvl int) R
	NRef    func(hash Hash) R
	NApp    func(fn Neutral, arg Val, icit Icit) R
	NMeta   func(ID int) R
	NCast   func(a Val, b Val, p Val, x Val) R
	NSubst  func(a Val, x Val, y Val, prf Val, p Val, px Val) R
	NFst    func(p Neutral) R
	NSnd    func(p Neutral) R
	NNatLit func(n *big.Int, zero Hash, succ Hash) R
}

// NeutralFold reduces Neutral by one-level case analysis.
func NeutralFold[R any](n Neutral, cs NeutralCases[R]) R {
	switch m := any(n).(type) {
	case NVar:
		return cs.NVar(m.Lvl)
	case NRef:
		return cs.NRef(m.Hash)
	case NApp:
		return cs.NApp(m.Fn, m.Arg, m.Icit)
	case NMeta:
		return cs.NMeta(m.ID)
	case NCast:
		return cs.NCast(m.A, m.B, m.P, m.X)
	case NSubst:
		return cs.NSubst(m.A, m.X, m.Y, m.Prf, m.P, m.Px)
	case NFst:
		return cs.NFst(m.P)
	case NSnd:
		return cs.NSnd(m.P)
	case NNatLit:
		return cs.NNatLit(m.N, m.Zero, m.Succ)
	default:
		panic("goplus: impossible enum value in NeutralFold")
	}
}

// NeutralChildren lists the direct Neutral subterms of n.
func NeutralChildren(n Neutral) []Neutral {
	var out []Neutral
	switch m := any(n).(type) {
	case NApp:
		if m.Fn != nil {
			out = append(out, m.Fn)
		}
	case NFst:
		if m.P != nil {
			out = append(out, m.P)
		}
	case NSnd:
		if m.P != nil {
			out = append(out, m.P)
		}
	}
	return out
}

// NeutralUniverse yields n and all transitive Neutral subterms, preorder.
func NeutralUniverse(n Neutral) iter.Seq[Neutral] {
	return func(yield func(Neutral) bool) {
		var walk func(Neutral) bool
		walk = func(cur Neutral) bool {
			if !yield(cur) {
				return false
			}
			for _, c := range NeutralChildren(cur) {
				if !walk(c) {
					return false
				}
			}
			return true
		}
		walk(n)
	}
}

// NeutralTransform rewrites n bottom-up: children first, then f at each node.
func NeutralTransform(n Neutral, f func(Neutral) Neutral) Neutral {
	switch m := any(n).(type) {
	case NApp:
		if m.Fn != nil {
			m.Fn = NeutralTransform(m.Fn, f)
		}
		return f(m)
	case NFst:
		if m.P != nil {
			m.P = NeutralTransform(m.P, f)
		}
		return f(m)
	case NSnd:
		if m.P != nil {
			m.P = NeutralTransform(m.P, f)
		}
		return f(m)
	}
	return f(n)
}
