// Code generated by gpp from equality.gpp. DO NOT EDIT.
//gpp:v v0.11.0

package equality

import (
	"testing"

	"pgregory.net/rapid"
)

func TestObservationalLaws(t *testing.T) {
	t.Run("Stratum.CastConvertibleIsIdentity", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			host := rapid.Make[PujetTabareau]().Draw(rt, "host")
			if !Observational.LawCastConvertibleIsIdentity(host) {
				rt.Fatalf("law CastConvertibleIsIdentity violated: host=%v", host)
			}
		})
	})
	t.Run("Stratum.FunextReduces", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			host := rapid.Make[PujetTabareau]().Draw(rt, "host")
			if !Observational.LawFunextReduces(host) {
				rt.Fatalf("law FunextReduces violated: host=%v", host)
			}
		})
	})
	t.Run("Stratum.CastNeverInspectsProof", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			host := rapid.Make[PujetTabareau]().Draw(rt, "host")
			if !Observational.LawCastNeverInspectsProof(host) {
				rt.Fatalf("law CastNeverInspectsProof violated: host=%v", host)
			}
		})
	})
	t.Run("Stratum.SubstComputesAtEqualEndpoints", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			host := rapid.Make[PujetTabareau]().Draw(rt, "host")
			if !Observational.LawSubstComputesAtEqualEndpoints(host) {
				rt.Fatalf("law SubstComputesAtEqualEndpoints violated: host=%v", host)
			}
		})
	})
}
