package main

import (
	"bytes"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"goforge.dev/rune/v3/codegen"
)

const buildSmokeSrc = `
data Unit : U is unit : Unit end
main : Unit is unit end
`

func TestParseBuildArgs(t *testing.T) {
	cfg, err := parseBuildArgs([]string{
		"furnace.rune", "main",
		"--target", "go",
		"--kind", "library",
		"--module", "example.com/acme/furnacecore",
		"--export", "Furnace.parse:Parse",
		"--out", "gen",
	})
	if err != nil {
		t.Fatal(err)
	}
	if cfg.file != "furnace.rune" || cfg.main != "main" || cfg.target != "go" {
		t.Fatalf("unexpected positional/target parse: %+v", cfg)
	}
	if cfg.kind != codegen.BuildLibrary {
		t.Fatalf("kind = %q", cfg.kind)
	}
	if cfg.module != "example.com/acme/furnacecore" || cfg.outDir != "gen" {
		t.Fatalf("unexpected module/out parse: %+v", cfg)
	}
	if len(cfg.exports) != 1 || cfg.exports[0].RuneName != "Furnace.parse" || cfg.exports[0].HostName != "Parse" {
		t.Fatalf("exports = %+v", cfg.exports)
	}
}

func TestRunBuildPrintsAppArtifact(t *testing.T) {
	var out bytes.Buffer
	err := runBuild(buildSmokeSrc, buildArgs{
		target: "go",
		kind:   codegen.BuildApp,
		main:   "main",
	}, &out)
	if err != nil {
		t.Fatal(err)
	}
	got := out.String()
	for _, want := range []string{"# main.go", "package main", "func main()"} {
		if !strings.Contains(got, want) {
			t.Fatalf("build output missing %q:\n%s", want, got)
		}
	}
}

func TestRunBuildWritesOutDir(t *testing.T) {
	dir := t.TempDir()
	var out bytes.Buffer
	err := runBuild(buildSmokeSrc, buildArgs{
		target: "go",
		kind:   codegen.BuildApp,
		main:   "main",
		outDir: dir,
	}, &out)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "main.go")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if !bytes.Contains(data, []byte("package main")) {
		t.Fatalf("%s missing package main:\n%s", path, data)
	}
	if !strings.Contains(out.String(), "wrote 1 file(s)") {
		t.Fatalf("unexpected status: %q", out.String())
	}
}

func TestRunBuildGoLibraryPrintsPackageArtifact(t *testing.T) {
	var out bytes.Buffer
	err := runBuild(buildSmokeSrc, buildArgs{
		target:  "go",
		kind:    codegen.BuildLibrary,
		module:  "example.com/acme/furnacecore",
		exports: []codegen.Export{{RuneName: "main", HostName: "Main"}},
	}, &out)
	if err != nil {
		t.Fatal(err)
	}
	got := out.String()
	for _, want := range []string{"# furnacecore.go", "package furnacecore", "func Main(args ...any) any"} {
		if !strings.Contains(got, want) {
			t.Fatalf("library output missing %q:\n%s", want, got)
		}
	}
	if strings.Contains(got, "func main()") {
		t.Fatalf("library output should not include func main:\n%s", got)
	}
}

// TestRunBuildCLIWritesOutDir drives the full `rune build` dispatch path the way
// main() does: raw argv -> flag parse -> file read -> emit -> out-dir write.
func TestRunBuildCLIWritesOutDir(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "smoke.rune")
	if err := os.WriteFile(src, []byte(buildSmokeSrc), 0o644); err != nil {
		t.Fatal(err)
	}
	gen := filepath.Join(dir, "gen")
	var out bytes.Buffer
	if err := runBuildCLI([]string{src, "main", "--target", "go", "--out", gen}, &out); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(gen, "main.go"))
	if err != nil {
		t.Fatalf("read generated main.go: %v", err)
	}
	if !bytes.Contains(data, []byte("package main")) {
		t.Fatalf("generated file missing package main:\n%s", data)
	}
	if !strings.Contains(out.String(), "wrote 1 file(s)") {
		t.Fatalf("unexpected status: %q", out.String())
	}
}

// TestRunBuildCLIMissingFile surfaces a read error through the dispatch seam.
func TestRunBuildCLIMissingFile(t *testing.T) {
	err := runBuildCLI([]string{filepath.Join(t.TempDir(), "nope.rune"), "main"}, io.Discard)
	if err == nil {
		t.Fatal("expected a read error for a missing file")
	}
}

// TestRunBuildGoLibraryHeaderNamesBuild pins the cosmetic that a library artifact
// is stamped `rune build`, not `rune emit` (it is not the app shadow).
func TestRunBuildGoLibraryHeaderNamesBuild(t *testing.T) {
	var out bytes.Buffer
	err := runBuild(buildSmokeSrc, buildArgs{
		target:  "go",
		kind:    codegen.BuildLibrary,
		module:  "example.com/acme/furnacecore",
		exports: []codegen.Export{{RuneName: "main", HostName: "Main"}},
	}, &out)
	if err != nil {
		t.Fatal(err)
	}
	got := out.String()
	if !strings.Contains(got, "Generated by rune build (go backend, library)") {
		t.Fatalf("library header not stamped for build:\n%s", got)
	}
	if strings.Contains(got, "Generated by rune emit (go backend)") {
		t.Fatalf("library header still says emit:\n%s", got)
	}
}

func TestRunBuildLibraryReportsSharedUnsupportedError(t *testing.T) {
	var out bytes.Buffer
	err := runBuild(buildSmokeSrc, buildArgs{
		target:  "js",
		kind:    codegen.BuildLibrary,
		module:  "@acme/furnacecore",
		exports: []codegen.Export{{RuneName: "main", HostName: "Main"}},
	}, &out)
	if !errors.Is(err, codegen.ErrLibraryUnsupported) {
		t.Fatalf("error = %v, want ErrLibraryUnsupported", err)
	}
}

// TestRunBuildUsesPrelude verifies that runBuild (and the underlying programForSet
// path) loads the standard prelude so a source with `import Std.Float` succeeds.
// This regression-tests the fix for build bypassing the prelude (the old
// programFor path returned "import Std.Float: no definitions found for module").
func TestRunBuildUsesPrelude(t *testing.T) {
	// A minimal double.rune-style source: imports Std.Float and uses fmul/fromNat.
	src := `import Std.Float

main : IO Float is
  bindIO Float Float getFloat
    (fn (x : Float) is printFloat (fmul x (fromNat 2)) end)
end
`
	var out bytes.Buffer
	err := runBuild(src, buildArgs{
		target: "js",
		kind:   codegen.BuildApp,
		main:   "main",
	}, &out)
	if err != nil {
		t.Fatalf("runBuild with Std.Float import: %v", err)
	}
	got := out.String()
	// printFloat and getFloat come from the Std.Float prelude module;
	// their presence proves the prelude was loaded successfully.
	for _, want := range []string{"# main.js", "printFloat", "getFloat"} {
		if !strings.Contains(got, want) {
			t.Errorf("expected generated JS to contain %q", want)
		}
	}
}
