// Code generated by gpp from quantity.gpp. DO NOT EDIT.
//gpp:v v0.14.0

package quantity

import (
	"testing"

	"pgregory.net/rapid"
)

func TestZeroOneOmegaLaws(t *testing.T) {
	t.Run("Semiring.AddAssoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := GenQty.Draw(rt, "a")
			b := GenQty.Draw(rt, "b")
			c := GenQty.Draw(rt, "c")
			if !ZeroOneOmega.LawAddAssoc(a, b, c) {
				rt.Fatalf("law AddAssoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("Semiring.AddComm", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := GenQty.Draw(rt, "a")
			b := GenQty.Draw(rt, "b")
			if !ZeroOneOmega.LawAddComm(a, b) {
				rt.Fatalf("law AddComm violated: a=%v b=%v", a, b)
			}
		})
	})
	t.Run("Semiring.AddZero", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := GenQty.Draw(rt, "a")
			if !ZeroOneOmega.LawAddZero(a) {
				rt.Fatalf("law AddZero violated: a=%v", a)
			}
		})
	})
	t.Run("Semiring.MulAssoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := GenQty.Draw(rt, "a")
			b := GenQty.Draw(rt, "b")
			c := GenQty.Draw(rt, "c")
			if !ZeroOneOmega.LawMulAssoc(a, b, c) {
				rt.Fatalf("law MulAssoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("Semiring.MulOne", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := GenQty.Draw(rt, "a")
			if !ZeroOneOmega.LawMulOne(a) {
				rt.Fatalf("law MulOne violated: a=%v", a)
			}
		})
	})
	t.Run("Semiring.MulAnnihilates", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := GenQty.Draw(rt, "a")
			if !ZeroOneOmega.LawMulAnnihilates(a) {
				rt.Fatalf("law MulAnnihilates violated: a=%v", a)
			}
		})
	})
	t.Run("Semiring.Distrib", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := GenQty.Draw(rt, "a")
			b := GenQty.Draw(rt, "b")
			c := GenQty.Draw(rt, "c")
			if !ZeroOneOmega.LawDistrib(a, b, c) {
				rt.Fatalf("law Distrib violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
}
