// Code generated by goplus from quantity.gp. DO NOT EDIT.
//goplus:v v0.15.0

// Package quantity is the QUANTITY STRATUM: the usage semiring that the
// quantitative type theory threads through binders (Phase 5), kept as a
// swappable module — as of v3.383.0 a Go+ CLASS, so the semiring algebra is
// not prose: every instance gets generated rapid law tests (the stratum's
// first tests ever).
//
// The annotation DOMAIN lives in core (core.Qty: 0, 1, ω) because annotations
// are part of a term's identity and are hashed; this package supplies the
// RULES — how usages add across occurrences and multiply through nesting —
// and the compatibility judgment the elaborator's usage checker applies at
// each binder. The 0-fragment is the erasure boundary the codegen stratum
// reads.
package quantity

import (
	"reflect"

	"goforge.dev/rune/v3/core"
)

// Semiring abstracts the usage arithmetic: an additive commutative monoid
// (Zero, Add) for combining usages of distinct occurrences, and a
// multiplicative monoid (One, Mul) for composing usage through nested
// positions, with Mul annihilated by Zero and distributing over Add — the
// laws below state exactly that, and every instance is tested against them.
//
//goplus:class Semiring[Q any]
type Semiring[Q any] struct {
	Zero       func() Q
	One        func() Q
	Add        func(a, b Q) Q
	Mul        func(a, b Q) Q
	Compatible func(declared, used Q) bool
}

// Compatible reports whether an observed usage satisfies a declared
// annotation (0 requires unused; 1 requires exactly once; ω accepts any).

//goplus:law (Semiring[Q]) AddAssoc(a, b, c Q)
func (m Semiring[Q]) LawAddAssoc(a, b, c Q) bool {
	return reflect.DeepEqual(m.Add(m.Add(a, b), c), m.Add(a, m.Add(b, c)))
}

//goplus:law (Semiring[Q]) AddComm(a, b Q)
func (m Semiring[Q]) LawAddComm(a, b Q) bool {
	return reflect.DeepEqual(m.Add(a, b), m.Add(b, a))
}

//goplus:law (Semiring[Q]) AddZero(a Q)
func (m Semiring[Q]) LawAddZero(a Q) bool {
	return reflect.DeepEqual(m.Add(m.Zero(), a), a) && reflect.DeepEqual(m.Add(a, m.Zero()), a)
}

//goplus:law (Semiring[Q]) MulAssoc(a, b, c Q)
func (m Semiring[Q]) LawMulAssoc(a, b, c Q) bool {
	return reflect.DeepEqual(m.Mul(m.Mul(a, b), c), m.Mul(a, m.Mul(b, c)))
}

//goplus:law (Semiring[Q]) MulOne(a Q)
func (m Semiring[Q]) LawMulOne(a Q) bool {
	return reflect.DeepEqual(m.Mul(m.One(), a), a) && reflect.DeepEqual(m.Mul(a, m.One()), a)
}

//goplus:law (Semiring[Q]) MulAnnihilates(a Q)
func (m Semiring[Q]) LawMulAnnihilates(a Q) bool {
	return reflect.DeepEqual(m.Mul(m.Zero(), a), m.Zero()) && reflect.DeepEqual(m.Mul(a, m.Zero()), m.Zero())
}

//goplus:law (Semiring[Q]) Distrib(a, b, c Q)
func (m Semiring[Q]) LawDistrib(a, b, c Q) bool {
	return reflect.DeepEqual(m.Mul(a, m.Add(b, c)), m.Add(m.Mul(a, b), m.Mul(a, c))) &&
		reflect.DeepEqual(m.Mul(m.Add(a, b), c), m.Add(m.Mul(a, c), m.Mul(b, c)))
}

// ZeroOneOmega is the default usage semiring: Atkey's 0/1/ω lattice. Zero
// means erased, One linear, Omega unrestricted. Addition saturates: two
// nonzero usages make ω. Multiplication is annihilated by 0 and saturates to
// ω unless an operand is 1.
//
//goplus:instance ZeroOneOmega Semiring[core.Qty]
//goplus:laws gen=GenQty
var ZeroOneOmega = func() Semiring[core.Qty] {
	w := &Semiring[core.Qty]{
		Zero: func() core.Qty { return core.QZero },
		One:  func() core.Qty { return core.QOne },
		Add: func(a, b core.Qty) core.Qty {
			if a == core.QZero {
				return b
			}
			if b == core.QZero {
				return a
			}
			return core.QMany
		},
		Mul: func(a, b core.Qty) core.Qty {
			if a == core.QZero || b == core.QZero {
				return core.QZero
			}
			if a == core.QOne {
				return b
			}
			if b == core.QOne {
				return a
			}
			return core.QMany
		},
		Compatible: func(declared, used core.Qty) bool {
			switch declared {
			case core.QMany:
				return true
			case core.QZero:
				return used == core.QZero
			case core.QOne:
				return used == core.QOne
			default:
				return false
			}
		},
	}
	return *w
}()

// Default returns the 0/1/ω semiring witness, Rune v1's sole
// quantity-stratum implementation.
func Default() Semiring[core.Qty] { return ZeroOneOmega }
